Link Bitrix24 icon. RVK & Skiline Icons do not work. Why?
LawnchairLauncher/lawnicons pull request #1066
Opened 2023-02-24 14:37 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-02-24 16:10 UTC, daywalk3r666 requested changes

2023-02-24 16:10 UTC, daywalk3r666 commented on app/assets/appfilter.xml
>    <item component="ComponentInfo{cc.skiline.android/cc.skiline.android.screens.main.MainActivity}" drawable="skiline" name="Skiline"/>
<item component="ComponentInfo{cc.skiline.android/cc.skiline.android.screens.startup.StartupActivity}"

2023-02-24 16:10 UTC, daywalk3r666 commented on app/assets/appfilter.xml
>    <item component="ComponentInfo{koeln.kvb.ticket.rvkapp/com.cubic.cumo.mts.MainActivity}" drawable="rvk" name="RVK"/>
<item component="ComponentInfo{koeln.kvb.ticket.rvkapp/com.cubic.cumo.mts.SplashActivity}"

2023-02-24 16:11 UTC, daywalk3r666 commented
The two icons has the wrong activities

2023-02-25 00:59 UTC, Chefski commented
@peterge1998 try applying the suggested changes and see if they're still not working.

2023-02-26 12:40 UTC, Chefski approved these changes

2023-02-26 12:42 UTC, merged