Fixing conflicts
LawnchairLauncher/lawnicons pull request #1181
Opened 2023-04-18 01:35 UTC by KevoM

Fixing conflict

2023-04-18 11:53 UTC, Chefski requested changes

2023-04-18 11:53 UTC, Chefski commented on svgs/doctolib.svg
Quickly just going through this, icons strokes should not go into other strokes as they make the thickness bigger.

It also has a path that can be deleted. It uses 1px and theres a duplicate one with the appropriate width.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/100310118/232760871-bb6fc60a-73df-4753-869a-fe0061f822e5.png">

2023-04-18 11:53 UTC, Chefski commented on svgs/cerballiance.svg
Can you fit this to the content area?
<img width="707" alt="image" src="https://user-images.githubusercontent.com/100310118/232761489-f96c605f-a57c-4a7e-a2e3-23c62a60b98e.png">

2023-04-18 11:53 UTC, Chefski commented on svgs/impots_gouv.svg
This icon has some rough edges and end points. Could you fix the end points to be smoothly rounded and make the edges more flat

<img width="400" alt="image" src="https://user-images.githubusercontent.com/100310118/232762361-2f0cde26-2804-41c7-a17f-842de221261b.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/100310118/232762477-7367c911-7b52-4d6d-b4df-6d5a336df92e.png">

2023-04-18 11:53 UTC, Chefski commented on svgs/impotsgouv.svg
This icons seems like a duplicate of `impots_gouv.svg`. You can probably delete it. If not same changes apply as in `impots_gouv.svg` and also the colour is grey so you should make it black.

2023-04-18 11:53 UTC, Chefski commented on svgs/keepa.svg
This icon goes a little over the content area. Just decrease the `+` by a pixel. Other than that its good.

If making the `+` smaller makes the two paths touch, maybe you can reduce the stroke for the inside square to 10px?

2023-04-18 11:53 UTC, Chefski commented on svgs/la_redoute.svg
This icon is cool. Could you just adjust it to the 144x144px content area. Its a little over it

2023-04-18 11:53 UTC, Chefski commented on svgs/lunasea.svg
This icon goes outside the content area. Mind adjusting it?

2023-04-18 11:53 UTC, Chefski commented on svgs/mixcloud.svg
Mind adjusting this icon to fill the 160x160px content area?

2023-04-18 11:53 UTC, Chefski commented on svgs/monespacesant.svg
This seems like a duplicate of the already existing icon `mon_compte_sante.svg`. It can probably be deleted.

2023-04-18 11:53 UTC, Chefski commented on svgs/mon_compte_sante.svg
Can you add rounded end points to this icon please?

2023-04-18 11:53 UTC, Chefski commented on svgs/olauncher.svg
An icon like this already exists under the name `mi_fitness.svg`. To reduce the size you can use that icon as the icon for the app. If you would like, you can also rename the icon to `generic_circle.svg` and change all links from `mi_fitness.svg` to `generic_circle.svg`

2023-04-18 11:53 UTC, Chefski commented on svgs/pap.svg
Could you round all the endpoints for this please?

2023-04-18 11:53 UTC, Chefski commented on svgs/qonto.svg
Can you resize this icon to fit the content area 160x160px?

2023-04-18 11:53 UTC, Chefski commented on svgs/radiofrance.svg
This icon slightly goes out of the content area. Mind adjusting?

2023-04-18 11:53 UTC, Chefski commented on svgs/slowly.svg
Strokes cannot be smaller than 3px. You may have to improvise for this icon...

2023-04-18 11:53 UTC, Chefski commented on svgs/timepassages.svg
Can you fit this icon to the 160x160px content area?

2023-04-18 11:53 UTC, Chefski commented on svgs/trainline.svg
Can you fit this icon to the 160x160px content area. Make sure the stroke remains at 12 as I noticed it uses fill

2023-04-18 11:53 UTC, Chefski commented on svgs/vlib.svg
Could you adjust this icon to fit the 160x160px content area. Could you also center it? Understandably the original icon isn't centered however lawnicons should be centered.

2023-04-18 20:58 UTC, Chefski reviewed
Hey, I don't have time to fully review these but the guides are visible in the preview

2023-04-18 20:58 UTC, Chefski commented
Nvnm theyre gone? Maybe i was looking at old commit

2023-04-19 20:23 UTC, Chefski commented
Why is the diff so big in `app/assets/appfilter.xml`?

2023-04-19 21:47 UTC, KevoM commented
> Why is the diff so big in `app/assets/appfilter.xml`?

I don't know. I tried to fix a conflict, all the lines in the file were hightlighted... 
What I did was delete > pull the latest xml > paste the new lines > push...

2023-04-21 21:46 UTC, billy4479 commented
> Why is the diff so big in `app/assets/appfilter.xml`?

The big diff is probably due to the fact that the one committed to the repo uses CRLF line endings (windows default), while the python script uses LF line endings (*nix default) or some incompatibility of this sort.

If you're on Linux a tool like `unix2dos` or `dos2unix` would fix it.

2023-05-08 10:24 UTC, x9136 commented on svgs/pocket.svg
Hello! I've been using this app constantly for 6-7 years. Also did the icon, but since there is already a variant, I suggest to match the proportions with the original, because the tick is too small.

My version, if you're interested.

```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M36.7059 54.8C36.7059 51.4863 39.3922 48.8 42.7059 48.8H149.294C152.608 48.8 155.294 51.4863 155.294 54.8V95.7333C155.294 126.367 130.643 151.2 100.235 151.2H91.7647C61.3566 151.2 36.7059 126.367 36.7059 95.7333V54.8ZM24 42.4C24 38.8654 26.8443 36 30.3529 36H161.647C165.156 36 168 38.8654 168 42.4V95.7333C168 133.436 137.661 164 100.235 164H91.7647C54.3393 164 24 133.436 24 95.7333V42.4ZM68.9497 75.0503C66.2161 72.3166 61.7839 72.3166 59.0503 75.0503C56.3166 77.7839 56.3166 82.2161 59.0503 84.9497L91.0503 116.95C93.7839 119.683 98.2161 119.683 100.95 116.95L132.95 84.9497C135.683 82.2161 135.683 77.7839 132.95 75.0503C130.216 72.3166 125.784 72.3166 123.05 75.0503L96 102.101L68.9497 75.0503Z" fill="black"/>
</svg>
```

2023-05-19 19:22 UTC, x9136 commented
@Chefski How long do you wait if an author doesn't make changes to the request? What happens to the request afterwards?

2023-05-19 19:32 UTC, Chefski commented
> @Chefski How long do you wait if an author doesn't make changes to the request? What happens to the request afterwards?

If I'm not wrong, the PR gets a warning and stale label if there's no activity after 30 days. After that the author has 14 days to do something else the PR is closed

2023-05-20 10:45 UTC, KevoM commented
> If I'm not wrong, the PR gets a warning and stale label if there's no activity after 30 days. After that the author has 14 days to do something else the PR is closed

I've done all the changes, I don't know what's next and how

2023-05-20 14:56 UTC, SuperDragonXD commented
You can do the following to fix the conflicts in the `appfilter` file:

1. Delete the appfilter file on your local branch.
2. Copy the latest `appfilter` file from the remote (lawnicons) `develop` branch, and paste it to your local branch.
3. Apply your intended changes.
4. Commit then push.

Maybe you have merged `develop` wrong previously, so that's why there's merge conflicts.

2023-05-27 08:28 UTC, closed without merging