Add Hay Day icon
LawnchairLauncher/lawnicons pull request #1186
Opened 2023-04-19 07:53 UTC by billy4479

## Description

Adding the Hay Day icon.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* Hay Day (`com.supercell.HayDay`)

### Icons updated
None

### Icons linked
None

***

Reference:
<img src="https://img4.wikia.nocookie.net/__cb20140920172358/hayday/images/6/6a/Hay-Day-Icon.png" width=192/>

Traced icon:
![Hayday](https://user-images.githubusercontent.com/54800905/233001003-23bf4591-51db-42da-9229-8827756384f1.png)

As you can see, the reference icon cuts the crest of the chicken. I completed it by going over the 160px of the icon's content, I'm not sure what is the procedure in this case but I can resize it if needed.

Also, I've noticed that `app/assets/appfilter.xml` has CRLF line endings. If this is the intended behavior then `icontool.py` should also enforce it on every system, since I was adding this icon on Linux and got a huge diff because it converted all line endings to LF. I fixed it using `unix2dos` but I think a default should be enforced.

That said, I hope I did everything correctly, if there's any problem let me know.

2023-04-21 11:15 UTC, Chefski reviewed
I think 8px would work with this icon

2023-04-21 11:42 UTC, billy4479 commented
I'm not sure why CI is failing.. It probably doesn't like the fact that I rebased and force pushed my branch. I can open a new PR if that's a problem.

2023-04-21 14:01 UTC, SuperDragonXD commented
> I'm not sure why CI is failing.. It probably doesn't like the fact that I rebased and force pushed my branch. I can open a new PR if that's a problem.

Yes, force pushing doesn't really make sense for the checks: https://github.com/LawnchairLauncher/lawnicons/actions/runs/4744556196/jobs/8431799467#step:6:1

Could probably add a `try ... except git.GitCommandError` block so that the checks will still work

2023-04-23 12:59 UTC, Chefski requested changes

2023-04-23 12:59 UTC, Chefski commented on svgs/hay_day.svg
Could you just fix the icon to be inside the content area
<img width="400" alt="image" src="https://user-images.githubusercontent.com/100310118/233841217-dcd826e1-be60-4f1f-aeb2-b85e839170f6.png">

2023-04-23 13:03 UTC, billy4479 commented on svgs/hay_day.svg
Which should be 160x160 or 144x144?

2023-04-23 13:04 UTC, Chefski commented on svgs/hay_day.svg
160x160

2023-04-24 20:19 UTC, Chefski approved these changes
Thanks

2023-04-24 20:19 UTC, merged