add limbo, ebase, evoland2 and brotato
LawnchairLauncher/lawnicons pull request #1194
Opened 2023-04-23 18:09 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-04-24 20:32 UTC, Chefski requested changes

2023-04-24 20:32 UTC, Chefski commented on svgs/evoland2.svg
Some strokes in this have decimal points. Make sure they're whole numbers.

2023-04-24 20:32 UTC, Chefski commented on svgs/limbo.svg
The 6px stroke seems unnecessary as the icon has lots of white space. I think 10px or even 12px would be better.

2023-04-25 10:40 UTC, peterge1998 commented on svgs/evoland2.svg
done

2023-04-25 10:40 UTC, peterge1998 commented on svgs/limbo.svg
done

2023-04-25 19:51 UTC, merged