add new kleinanzeigen logo
LawnchairLauncher/lawnicons pull request #1202
Opened 2023-04-30 11:21 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-05-04 11:16 UTC, Chefski requested changes

2023-05-04 11:16 UTC, Chefski commented on svgs/bob.svg
<img width="500" alt="image" src="https://user-images.githubusercontent.com/100310118/236188598-62bbcae4-fe51-4c86-a7b3-c48e831c6798.png">

The width for the B's is too big. 14px is the maximum

2023-05-04 11:16 UTC, Chefski commented on svgs/rewe.svg
The icon is slightly bigger than 148px. Mind making it smaller?

2023-05-04 15:35 UTC, peterge1998 commented on svgs/rewe.svg
Done

2023-05-04 15:37 UTC, peterge1998 commented on svgs/bob.svg
Done

2023-05-06 12:19 UTC, Chefski approved these changes

2023-05-06 12:19 UTC, merged