Add Banglalink logo and link 2 app
LawnchairLauncher/lawnicons pull request #1218
Opened 2023-05-05 04:01 UTC by thekeyboardworrier

## Description

Added 1 icon and linked MyBL and MyBL Lite with the new icon.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:white_check_mark: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* MyBL (`com.arena.banglalinkmela.app`)

### Icons linked
* MyBL (linked `com.arena.banglalinkmela.app` to `@drawable/banglalink`)
* MyBL Lite (linked `net.banglalink.mybllite` to `@drawable/banglalink`)

2023-05-06 12:21 UTC, Chefski requested changes

2023-05-06 12:21 UTC, Chefski commented on svgs/banglalink.svg
This icon won't be suitable as it has varying widths, some looking less than 6px. Please try redesign it. Maybe a `b` can be used instead?

2023-05-08 08:58 UTC, thekeyboardworrier commented on svgs/banglalink.svg
Changed the logo. It's now a single `b`.

2023-05-10 20:28 UTC, Chefski requested changes

2023-05-10 20:28 UTC, Chefski commented on svgs/banglalink.svg
My review seems to not have sent yesterday. 

One of the rectangles has a stroke of 6.04. Could you make it 6px? I'd change the rectangles to be a line path instead though as it'll be simpler. If I remember correctly, the circle goes a bit over the line on the left. Mind moving it slightly?

2023-05-11 14:09 UTC, thekeyboardworrier commented on svgs/banglalink.svg
Changed it again. Thank you.

2023-05-13 16:49 UTC, Chefski approved these changes
Cool. Thanks :)

2023-05-13 16:49 UTC, merged