Add 2 apps
LawnchairLauncher/lawnicons pull request #1221
Opened 2023-05-08 16:15 UTC by nxmryada

## Description

Adds Türk Telekom (previously Avea OIM) app and Moovit app icons.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
Both apps were requested in the form.

### Icons added
* Moovit (`com.tranzmate`) - added from icon request form
* Türk Telekom (`com.tmob.AveaOIM`) - added from icon request form

2023-05-09 02:50 UTC, thekeyboardworrier requested changes
Would you mind centering `ttoim` logo?


![ttoim](https://user-images.githubusercontent.com/67034266/236977391-57b6c6e7-1ec9-4b4b-896f-1d35ef7e94a2.svg)

2023-05-13 16:29 UTC, Chefski requested changes

2023-05-13 16:29 UTC, Chefski commented on svgs/moovit.svg
Could you just round the bottom of the moovit icon?
<img width="366" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/08bd4ba1-0177-4d03-8026-a83a82de15e9">

2023-05-16 19:42 UTC, nxmryada commented on svgs/moovit.svg
Are you sure? The Moovit logo is stylized like that intentionally, I think rounding it would make it lose its uniqueness.

2023-05-25 20:49 UTC, Chefski approved these changes

2023-05-25 20:49 UTC, merged