15 icons
LawnchairLauncher/lawnicons pull request #1228
Opened 2023-05-11 11:05 UTC by x9136

## Description

New icons. The list below.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* App Tester (`dev.firebase.appdistribution/dev.firebase.appdistribution.main.MainActivity`)
* Edge Gestures (`com.ss.edgegestures/com.ss.edgegestures.SettingsActivity`)
* English Grammar Test (`english.grammar.test.app/english.grammar.test.app.MainActivity`)
* FotMob (`com.mobilefootie.wc2010/com.mobilefootie.fotmob.gui.v2.MainActivityWrapper`)
* I Love Hue (`com.zutgames.ilovehue/com.ansca.corona.CoronaActivity`)
* I Love Hue Too (`com.zutgames.ilovehue2/com.unity3d.player.UnityPlayerActivity`)
* IsCep (`com.pozitron.iscep/com.pozitron.iscep.features.prelogin.splash.SplashActivity`)
* MeetFrank (`com.meetfrank.android/com.meetfrank.android.MainActivity`)
* Meteoroloji (`tr.gov.mgm.meteorolojihavadurumu/tr.gov.mgm.meteorolojihavadurumu.SplashActivity`)
* Pocketbook (`com.obreey.reader/com.obreey.reader.StartActivity`)
* RocketEng (`com.edpanda.words/com.edpanda.words.screen.splash.SplashActivity`)
* Trello (`com.trello/com.trello.home.HomeActivity`)
* Turkcell (`com.ttech.android.onlineislem/com.ttech.android.onlineislem.ui.splash.SplashActivity`)
* Yandex.Translate (`ru.yandex.translate/ru.yandex.translate.ui.activities.MainActivity`)
* Yota (`ru.yota.android/ru.yota.android.splashModule.presentation.view.SplashActivity`)

2023-05-14 13:32 UTC, Chefski requested changes
Overall icons are fine, could you just change the size of some. For example, the square icons like trello and fotmob should have a content area of 144x144 rather than the current 160x160. All other icons should have 160x160. Some icons that need to be resized to 160x160 are app_tester, edge_gestures, english_grammar_test and some more

2023-05-14 14:35 UTC, x9136 commented
> Overall icons are fine, could you just change the size of some. For example, the square icons like trello and fotmob should have a content area of 144x144 rather than the current 160x160. All other icons should have 160x160. Some icons that need to be resized to 160x160 are app_tester, edge_gestures, english_grammar_test and some more

Done.

I want to clarify one thing. The manual says that the size of 144x144 is also needed for circles, at the same time there are icons, like [Amazon Alexa](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/amazon_alexa.svg). You either need to clarify in the manual that 144x144 only for squares, or redo the existing circles. Either this is a recommendation, not a requirement.

Anyway, right now the circle in the Turkcell icon is 160x160. Please clarify if it's worth redoing.

2023-05-17 21:39 UTC, Chefski approved these changes

2023-05-17 21:41 UTC, Chefski commented
Could you solve conflicts please?



> I want to clarify one thing. The manual says that the size of 144x144 is also needed for circles, at the same time there are icons, like [Amazon Alexa](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/amazon_alexa.svg). You either need to clarify in the manual that 144x144 only for squares, or redo the existing circles. Either this is a recommendation, not a requirement.

That was a mistake. I'll fix it. Thanks

2023-05-18 09:37 UTC, merged