Add 1 icon
LawnchairLauncher/lawnicons pull request #1232
Opened 2023-05-13 15:26 UTC by thekeyboardworrier

## Description
Add 1 icon and link 2 entry of Toffee app.

Don't freak out by the amount of changes in `appfilter.xml`. It's formatting and `item` entry reordering *mostly* done by `icontool.py`.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:white_check_mark: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* Toffee (`com.banglalink.toffee`)

### Icons linked
* Toffee (linked `com.banglalink.toffee` to `@drawable/toffee`)

2023-05-13 16:56 UTC, Chefski requested changes

2023-05-13 16:56 UTC, Chefski commented on svgs/toffee.svg
Hey! Could you try maybe preventing the paths from touching each other? If possible, could you also make this icon in use strokes rather than fill. It's easier to review and will make it easier edit in the future.

2023-05-13 23:03 UTC, thekeyboardworrier commented on svgs/toffee.svg
> Hey! Could you try maybe preventing the paths from touching each other? If possible, could you also make this icon in use strokes rather than fill. It's easier to review and will make it easier edit in the future.

I can use strokes, but I'm nor sure if I am able to prevent the strokes from touching each other. Because the paths in the original logo is almost touching at the top. Even 6 px strokes will touch each other. Here is the monochrome version of the logo, with 6px strokes and with 8px strokes side by side.

![toffee_monochrome](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/248d287b-f152-488a-ae1a-ab94228ec6bb) ![toffee_6px](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/b77048a9-f4ab-45f4-bfee-ea7a81138e69) ![toffee_8px](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/0b66a5df-ee61-49e1-a9e2-de6dd1a738be)

Let me know which one you prefer, 6px or 8px version. I'm using 8px one with stokes (instead of path) for now.

Thank you.

2023-05-14 13:20 UTC, Chefski commented on svgs/toffee.svg
The shapes can just be reduced in size. So instead of being on the outline of the tear drop for example, the centre of the path will be inside the shape

2023-05-15 04:58 UTC, thekeyboardworrier commented on svgs/toffee.svg
Changed it again. But this one has paths instead of strokes. It's easier to keep the shape of the logo. I can't keep the corners sharp with strokes. It gets more blobby.

2023-05-17 22:38 UTC, Chefski commented on svgs/toffee.svg
Would it not be better to just make the shapes smaller? I'm not sure in what way this one was made but the previous ones were more suitable for Lawnicons

2023-05-18 02:41 UTC, thekeyboardworrier commented on svgs/toffee.svg
Changed it again. Thank you.

2023-05-18 09:42 UTC, Chefski commented on svgs/toffee.svg
Looks good!

2023-05-18 09:42 UTC, Chefski approved these changes

2023-05-18 09:42 UTC, merged