Add 3 icons
LawnchairLauncher/lawnicons pull request #1245
Opened 2023-05-18 23:00 UTC by WHOMAN5

## Description

added icons for SimpleX , ArtStation and Microsoft Edge Dev apps 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* SimpleX (`chat.simplex.app`) - added from icon request form
* Microsoft Edge Dev (`com.microsoft.emmx.dev`) - added from icon request form
* ArtStation (`com.ballistiq.artstation`)

2023-05-19 21:33 UTC, Chefski requested changes

2023-05-19 21:33 UTC, Chefski commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.ballistiq.artstation/com.ballistiq.artstation.view.login.LoginActivity}" drawable="artstation" name="ArtStation"/>
```suggestion
  <item component="ComponentInfo{com.ballistiq.artstation/com.ballistiq.artstation.view.login.LoginActivity}" drawable="artstation" name="ArtStation" /> 
```

2023-05-19 21:33 UTC, Chefski commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{chat.simplex.app/chat.simplex.app.MainActivity_default}" drawable="simplex" name="SimpleX"/>
```suggestion
  <item component="ComponentInfo{chat.simplex.app/chat.simplex.app.MainActivity_default}" drawable="simplex" name="SimpleX" /> 
```

2023-05-19 21:33 UTC, Chefski commented on svgs/artstation.svg
The stroke is slightly over 12px. The icon is also slightly off center. Could you fix both issues?

2023-05-19 21:33 UTC, Chefski commented on svgs/simplex.svg
Could you round the endpoints on the lines and ensure the icon fits the 160x160px content area.

2023-05-20 05:23 UTC, WHOMAN5 commented on svgs/simplex.svg
yeah ofc

2023-05-22 10:49 UTC, SiMah5 commented
uh, ok so i did resize them in figma (i also re-checked their sizes in inkscape by creating a 160x160 doc and dropping them inside it) and they both look to be the correct size on my end. i dont know what im doing wrong tbh.
![image](https://github.com/LawnchairLauncher/lawnicons/assets/98214188/dca7d7c9-ad43-45bc-a1c3-e752eea2b1df)

can you tell me what software and method you're using for measuring the icons?

2023-05-22 15:46 UTC, Chefski commented
I just have guidelines for 160x160 and 144x144. If you group both paths, is the width 148?

<img width="1096" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/f117c825-0ef1-4c53-997a-20a0491f7535">

2023-05-22 17:50 UTC, SiMah5 commented
oh im so dumb, i completely misunderstood you when you said i should fit them into the 160x160 area. 
gonna fix them now, sorry.

2023-05-22 23:22 UTC, Chefski approved these changes

2023-05-22 23:24 UTC, Chefski commented
Yeah I don't like the word "fit" to use as making it just get to the edges. Its a little confusing. Thanks for making the changes though

2023-05-22 23:24 UTC, merged