Added 1 icon, changed 2
LawnchairLauncher/lawnicons pull request #1248
Opened 2023-05-19 10:49 UTC by RaduBratan

## Description
I added an icon for MIUI Hidden Settings and changed the other two settings-related icons (MicroG Settings and Android Settings) because they were asymmetrical, not properly sized, had a lot of stray paths and anchor points, some anchor points that weren't stray weren't properly connected and the shape itself was filled instead of being a path with 12px stroke. The side effect of this change is, however, that the overall shape/silhouette of the icon is slightly different.

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* Hidden Settings For MIUI (`com.ceyhan.sets`)
### Icons updated
* Settings (`com.android.settings`)
* Vanced microG Settings (`com.mgoogle.android.gms`)

2023-05-19 15:42 UTC, RaduBratan commented
The thin stroke of the second cog from hidden_settings.svg looks bad, I'll have to update it.

2023-05-19 21:41 UTC, Chefski requested changes

2023-05-19 21:41 UTC, Chefski commented on svgs/hidden_settings.svg
The icon could be increased in size slightly and centered

2023-05-20 06:18 UTC, RaduBratan commented on svgs/hidden_settings.svg
Actually, all I had to do was to move the smaller cog 1px to the right and 1 to the top. While creating the icon, that little cog used a 12px stroke, and the shape was centerd properly. Later on I changed it to 10 px because it looked too thick, but forgot to update it's position.

2023-05-22 10:10 UTC, Chefski approved these changes
Thanks

2023-05-22 10:10 UTC, merged

2023-05-22 10:10 UTC, Chefski commented on svgs/hidden_settings.svg
Ahh no problem :)