add gmm, klarmobil, pritpreise & tgtg
LawnchairLauncher/lawnicons pull request #1249
Opened 2023-05-20 10:58 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-05-20 11:04 UTC, peterge1998 commented
What do I miss? It reports too_good_to_go_foreground is missing, but icon request says this is the line I have to add:
` <item component="ComponentInfo{com.app.tgtg/com.app.tgtg.activities.login.SplashActivity}" drawable="too_good_to_go"/>`

2023-05-20 11:59 UTC, x9136 commented
@peterge1998

I think you should delete **too_good_to_go_foreground.svg** and add "o" to the svg file name, because you have a drawable in appfilter.xml that says the svg should be called **too_good_to_go**, but the svg file is called **to_good_to_go**.

2023-05-22 09:37 UTC, peterge1998 commented
> @peterge1998
> 
> I think you should delete **too_good_to_go_foreground.svg** and add "o" to tgtg svg file name, because you have a drawable in appfilter.xml that says the svg should be called **too_good_to_go**, but the svg file is called **to_good_to_go**. A typo.

fcking typo :) thx!

2023-05-22 10:03 UTC, Chefski requested changes
`too_good_to_go.svg` and `klarmobilde.svg` need to have their strokes changed to whole numbers

2023-05-22 13:19 UTC, peterge1998 commented
> `too_good_to_go.svg` and `klarmobilde.svg` need to have their strokes changed to whole numbers

Yep, you are correct. I always forget to set to whole numbers when I resize the paths at the end to 160x160.
I fixed klarmobil to 12 px.
But tgtg "needs" to stay at 7.5 for the right circle, otherwise the width does not look even compared to the left & middle circle:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/47355238/62b877ec-ef1b-4e7d-8ee9-26d4d46534e2)

2023-05-24 19:36 UTC, Chefski commented
The icon already has a bump. Either the icon will be changed to fit the guidelines or it can't be merged

<img width="316" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/baa30cc6-9951-415b-a0b5-d0abbfe04376">

2023-05-25 10:44 UTC, peterge1998 commented
> The icon already has a bump. Either the icon will be changed to fit the guidelines or it can't be merged
> <img alt="image" width="316" src="https://user-images.githubusercontent.com/100310118/240723357-baa30cc6-9951-415b-a0b5-d0abbfe04376.png">

KK, done, its all 8 px now.

2023-05-25 15:47 UTC, Chefski commented on svgs/too_good_to_go.svg
Two paths still have 8.03px as the stroke

2023-05-25 21:46 UTC, Chefski approved these changes

2023-05-25 21:46 UTC, merged