add 22 icons
LawnchairLauncher/lawnicons pull request #1255
Opened 2023-05-23 10:40 UTC by SiMah5

## Description

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* ArgoVPN (`com.filtershekanha.argovpn`)
* Atomic (`com.jlindemann.science`)
* Clipious (`com.github.lamarios.clipious`)
* Inure (`app.simple.inure`)
* Soul (`com.mycompany.app.soulbrowser`)
* Torguard (`net.torguard.openvpn.client`)
* Vendetta Manager (`dev.beefers.vendetta.manager`)
* Wifi Pro FTP Server (`com.medhaapps.wififtpserver.pro`)
* Webnovel (`com.qidian.Int.reader`)

**From icon request form**

* Castro (`com.itemstudio.castro`) 
* FlashDim (`com.cyb3rko.flashdim`) 
* Mobilism (`demigos.com.mobilism`) 
* MoeList (`com.axiel7.moelist`) 
* NetMonster (`cz.mroczis.netmonster`) 
* Pano Scrobbler (`com.arn.scrobble`) 
* Pixel Search (`rk.android.app.pixelsearch`) 
* Pixiv (`jp.pxv.android`) 
* Pluvia (`com.spicychair.weather`) 
* Shosetsu (`app.shosetsu.android.fdroid`) 
* Sound Amplifier (`com.google.android.accessibility.soundamplifier`) 
* Today Weather (`mobi.lockdown.weather`) 
* Zlib (`com.positron_it.zlib`) 

### Icons updated

### Icons linked

2023-05-23 15:37 UTC, x9136 commented
@SiMah5 

You added the following lines to the appfilter.xml file, but **arc.svg** and **soundtoggle.svg** are missing.
```
<item component="ComponentInfo{com.quadren.arc/com.quadren.arc.MainActivity}" drawable="arc" name="Arc" />
<item component="ComponentInfo{com.grmasa.soundtoggle/com.grmasa.soundtoggle.MainActivity}" drawable="soundtoggle" name="Sound Toggle" />
```

2023-05-24 00:15 UTC, jokhallouf commented
Ohio,
I see that the today Weather icon has been added (and I can find it now in the latest Lawnicons develop but the icon won't auto update after I installed dev#2260 
![Uploading Screenshot_2023-05-24-02-05-30-47_3822ac0e29cfec8970059bb21d01f05e.jpg…]()

2023-05-24 00:32 UTC, SiMah5 commented
@jokhallouf hi, yeah there was a mistake but i fixed it already, it should work now if u download the latest action build ( https://github.com/LawnchairLauncher/lawnicons/actions/runs/5062515927 )

2023-05-24 04:10 UTC, jokhallouf commented
> @jokhallouf hi, yeah there was a mistake but i fixed it already, it should work now if u download the latest action build ( https://github.com/LawnchairLauncher/lawnicons/actions/runs/5062515927 )

Yeah I installed the latest 2260 and it is still the case

2023-05-24 11:41 UTC, jokhallouf commented
> > > I double checked the files but I couldn't find any problems, I also tested it on my phone and it works . I dont have a lot of experience tho so maybe the person who will review this PR can help.
> > 
> > 
> > Thanks! It is weird that it doesn't work on my phone (OnePlus 8T) and I have the premium version of today weather but I don't think it should make a difference? (app:Today Weather package:mobi.lockdown.weather Launcher:mobi.lockdown.weather.activity.SplashActivity ) I hope the person that reviews that finds the problem. Thanks a lot
> 
> Huh...The activity name that I added had "MainActivity" at the end but yours says "SplashActivity". I added it as a new line so can u see if the [latest action build](https://github.com/LawnchairLauncher/lawnicons/actions/runs/5067644390) fixes it or not? I also checked the premium version and it has the same package/activity name as the non premium so that shouldn't be the reason.

Yep works great now thanks !

2023-05-25 20:43 UTC, Chefski requested changes

2023-05-25 20:43 UTC, Chefski commented on svgs/argovpn.svg
Could you increase the size of the icon to fit the 160x160 content area? The canvas size is also 195x192 so it needs to be changed to 192x192

2023-05-25 20:43 UTC, Chefski commented on svgs/clipious.svg
Could you increase the size of the icon to fit the 160x160 content area?

2023-05-25 20:43 UTC, Chefski commented on svgs/flashdim.svg
Could you increase the size of the icon to fit the 160x160 content area?

2023-05-25 20:43 UTC, Chefski commented on svgs/pano_scrobbler.svg
The icon is slightly off center. Could you center it? This may be because the canvas size is 195x192 so maybe changing to 192x192 will fix it.

2023-05-25 20:43 UTC, Chefski commented on svgs/torguard.svg
The canvas size for this icon is 210x198. Could you change it to 192x192?

2023-05-26 09:53 UTC, Chefski approved these changes
Thanks. Two icons were slightly outside the content area but since it was a really small change I did it :)

2023-05-26 09:56 UTC, merged