20 icons
LawnchairLauncher/lawnicons pull request #1256
Opened 2023-05-23 21:35 UTC by x9136

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons added from icon request form

* DroidCam (`com.dev47apps.droidcam/com.dev47apps.droidcam.DroidCam`)
* DroidCamX (`com.dev47apps.droidcamx/com.dev47apps.droidcamx.DroidCamX`)
* eSewa (`com.f1soft.esewa/com.f1soft.esewa.activity.SplashScreenActivity`)
* Grammarly (`com.grammarly.android.keyboard/com.grammarly.host.SplashActivity`)
* iTAX (`com.ld.itax_pro_android/com.ld.itax_pro_android.MainActivity`)
* KBC Mobile (`com.kbc.mobile.android.phone.kbc/com.kbc.mobile.android.mbk.activities.SplashScreenActivity`)
* MIFARE Classic Tool (`de.syss.MifareClassicTool/de.syss.MifareClassicTool.Activities.MainMenu`)
* Polycam (`ai.polycam/ai.polycam.MainActivity`)
* SCB EASY(`com.scb.phone/com.scb.phone.view.activity.splash.SplashActivity`)
* Siddhartha BankSmart XP (`com.f1soft.banksmart.siddhartha/com.f1soft.bankxp.android.login.splash.SplashActivity`)
* Simply Wall St (`com.simplywallst.app/com.simplywallst.app.MainActivity`)
* Sky Map (`com.google.android.stardroid/com.google.android.stardroid.activities.SplashScreenActivity`)
* Smart Switch (`com.sec.android.easyMover/com.sec.android.easyMover.DistributionActivity`)
* Smart Switch (`com.sec.android.easyMover/com.sec.android.easyMover.DistributionNoIconActivity`)
* SmartThings (`com.samsung.android.oneconnect/com.samsung.android.oneconnect.ui.SCMainActivity`)
* Stay Awake (`org.hatapps.stayawake/com.example.myapplication2.MainActivity`)
* Transit (`com.thetransitapp.droid/com.thetransitapp.droid.shared.activity.SplashActivitytorontosubwayyellow`)
* Transit (`com.thetransitapp.droid/com.thetransitapp.droid.shared.activity.SplashActivity`)
* TrueMoney (`th.co.truemoney.wallet/th.co.truemoney.wallet.activity.LoadingScreenActivity`)
* Wolt (`com.wolt.android/com.wolt.android.activities.LauncherActivity`)
* XMind (`net.xmind.doughnut/net.xmind.doughnut.MainActivity`)
* Zipmex (`com.zipmex/com.zipmex.features.splash.LauncherEntryActivity`)

2023-05-24 20:27 UTC, Chefski requested changes

2023-05-24 20:27 UTC, Chefski commented on svgs/simply_wall_st.svg
2 paths have a stroke of 11. Could you make it 10 or 12?

2023-05-24 20:27 UTC, Chefski commented on svgs/sky_map.svg
Could you make this icon have a content area of 160x160.

2023-05-24 20:27 UTC, Chefski commented on svgs/transit.svg
Could you make the content area 160x160px

2023-05-24 20:54 UTC, x9136 commented on svgs/transit.svg
The content area is 160x160px. Can you show me more specifically what's wrong?

2023-05-25 15:51 UTC, Chefski commented on svgs/transit.svg
It's not quite at the border of 160x160
<img width="702" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/d2097a62-cdcb-41b4-b1d4-f8cfcac2e99f">

2023-05-25 17:51 UTC, Chefski commented on svgs/transit.svg
I'm so stupid. I completely went autopilot here. Yeah its fine. I've gotten used to all icons being 160 on the width i forgot about the height

2023-05-25 17:51 UTC, merged