Add DKB
LawnchairLauncher/lawnicons pull request #1266
Opened 2023-05-27 14:25 UTC by sal0max

## Description
Icon based on the existing DKB companion app icon "DKB TAN2go": https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/dkb_pushtan.svg

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* DKB (`com.dkbcodefactory.banking`)

2023-05-27 20:51 UTC, Chefski requested changes

2023-05-27 20:51 UTC, Chefski commented on svgs/dkb.svg
The background should be transparent. Could you change it please?

2023-05-27 23:29 UTC, sal0max commented on svgs/dkb.svg
Sorry! Fixed it now

2023-05-28 10:33 UTC, Chefski approved these changes

2023-05-28 10:33 UTC, merged