Add C24
LawnchairLauncher/lawnicons pull request #1267
Opened 2023-05-27 14:25 UTC by sal0max

## Description

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* C24 Bank (`de.c24.bankapp`)

2023-05-27 20:52 UTC, Chefski requested changes

2023-05-27 20:52 UTC, Chefski commented on svgs/c24.svg
Could you change the background to be transparent please?

2023-05-27 23:29 UTC, sal0max commented on svgs/c24.svg
Sorry! Fixed it now

2023-05-28 10:14 UTC, Chefski approved these changes
The SVG has a lot of groups which make the size bigger. If you could ungroup them all at the end it would drastically reduce file size. I went from 5 KB to 947 bytes by ungrouping everything

2023-05-28 10:14 UTC, merged