Add 4 icons
LawnchairLauncher/lawnicons pull request #1292
Opened 2023-06-10 14:21 UTC by ElbertCode

## Description

Add 4 icons

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* Gadgetbridge (`nodomain.freeyourgadget.gadgetbridge`)
* Jami (`cx.ring`)
* Moonlight (`com.limelight`)
* Hamburger (`de.freehamburger`)

_All icons from the request form_

2023-06-10 21:20 UTC, Chefski requested changes

2023-06-10 21:20 UTC, Chefski commented on svgs/gadgetbridge.svg
Could you reduce the icon size as it slightly goes out of the 160x160 content area

2023-06-10 21:20 UTC, Chefski commented on svgs/hamburger.svg
Please resize the icon to fit the 160x160px content area

2023-06-10 21:20 UTC, Chefski commented on svgs/jami.svg
Could you reduce the icon size as it slightly goes out of the 160x160 content area

2023-06-10 21:20 UTC, Chefski commented on svgs/kodi.svg
Could you reduce the icon size as it slightly goes out of the 160x160 content area

2023-06-10 21:20 UTC, Chefski commented on svgs/moonlight.svg
Could you round the corners for this icon? It might make the icon look a little worse but the slight roundness will make the icon match all other icons

2023-06-11 22:34 UTC, Chefski approved these changes
Thanks

2023-06-11 22:34 UTC, merged

2023-06-11 22:54 UTC, x9136 commented on svgs/moonlight.svg
> Could you round the corners for this icon?

Sure.
![moonlight](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/3f3f8f56-3d2b-43b5-843d-3dde5f8f760b)

2023-06-12 08:26 UTC, ElbertCode commented on svgs/moonlight.svg
Thanks for helping out with this!