13 icons and 15 links added
LawnchairLauncher/lawnicons pull request #1297
Opened 2023-06-13 17:43 UTC by Thorodinson1

## Description

13 icons and 15 links added

## Icons addition information

### Icons added
App Name (com.twofasapp) - added from icon request form
App Name (com.wrx.wazirx)
App Name (com.onstream.android)
App Name (com.uphold.wallet)
App Name ( in.shabinder.soundbound )
App Name ( com.testbook.tbapp.rrbjeme )
App Name ( com.edurev.rrbje )
App Name ( com.pubg.imobile )
App Name ( com.duk.kerala.gst.luckybill )
App Name (com.dw.learngerman)
App Name ( com.android.lmc8 )
App Name ( com.boAt.hearables )
App Name ( com.digital.bsnl.selfcare )
App Name (com.blockchainvault)

###  Icons linked
App Name (com.uphold.wallet to Uphold)
App Name (com.onstream.android to onstream)
App Name (com.wrx.wazirx to WazirX)
App Name (com.twofasapp to 2fas_auth)
App Name ( in.shabinder.soundbound to Soundbound )
App Name ( com.testbook.tbapp.rrbjeme to RRB JE ME - Testbook )
App Name ( com.edurev.rrbje to RRB JE App )
App Name ( com.pubg.imobile to Battlegrounds India )
App Name ( com.duk.kerala.gst.luckybill to Lucky Bill )
App Name (com.dw.learngerman to DW Learn German)
App Name ( com.android.lmc8 to Camera)
App Name ( com.boAt.hearables to boAt Hearables )
App Name ( com.digital.bsnl.selfcare to BSNL Selfcare )
App Name (com.blockchainvault to Pi )

2023-06-16 21:51 UTC, Chefski requested changes

2023-06-16 21:51 UTC, Chefski commented on svgs/dw_learn_german.svg
Reduce the icon size to fit the 160x160 content area

2023-06-16 21:51 UTC, Chefski commented on svgs/onstream.svg
Could you change the icon so that the lines do not touch each other where the circle meets the bolt. Please add a gap between them

2023-06-16 21:51 UTC, Chefski commented on svgs/lucky_bill.svg
Please reduce the icon size to 160x160px and try improve the lettering.

2023-06-16 21:51 UTC, Chefski commented on svgs/pi.svg
Please reduce the icon size to 160x160px

2023-06-16 21:51 UTC, Chefski commented on svgs/rrb_je_app.svg
Although better than previous, the icon can still be improved. The icon should be inside the 144x144px content area. Some letters do not align and and the d doesn't have a straight line down. The V could be better aligned so that both points at the top are align.
<img width="280" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/b5b0c48b-5c09-4686-913b-7baf6c877204">
<img width="400" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/3c831d9c-09ae-4498-a540-4e095abf9644">

2023-06-16 21:51 UTC, Chefski commented on svgs/rrb_je_me_testbook.svg
Please reduce the icon size to fit the 144x144px content area

2023-06-16 21:51 UTC, Chefski commented on svgs/twofas_auth.svg
Please reduce the icon to fit the 160x160 content area. The shape could be improved too. Please correct the shield at the point marked in the screenshot. The lines inside could be rounded rectangles rather than manually drawn paths.
<img width="450" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/d6db298e-7014-4a0f-b4b0-0f0b2a42bfbb">

2023-06-16 21:51 UTC, Chefski commented on svgs/wazirx.svg
Please increase the icon size to 160x160px to fix the content area

2023-06-26 07:55 UTC, Thorodinson1 commented
changes done

2023-06-26 11:49 UTC, Chefski requested changes

2023-06-26 11:49 UTC, Chefski commented on svgs/rrb_je_app.svg
Can you fit the icon into the 144x144px content area. Its currently still in between 160x160 and 144x144

2023-06-26 11:49 UTC, Chefski commented on svgs/twofas_auth.svg
Please change the icon to [this version](https://github.com/LawnchairLauncher/lawnicons/files/11868346/twofas_auth.svg.zip).

2023-06-29 23:41 UTC, Chefski approved these changes
Thanks

2023-06-29 23:41 UTC, merged