add bandido & evmap
LawnchairLauncher/lawnicons pull request #1304
Opened 2023-06-18 13:28 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-06-25 19:06 UTC, Chefski requested changes

2023-06-25 19:06 UTC, Chefski commented on svgs/bandido.svg
Can you change the eye stroke to 6px or 8px?

2023-06-26 10:11 UTC, peterge1998 commented on svgs/bandido.svg
Done!

2023-06-26 11:38 UTC, Chefski approved these changes

2023-06-26 11:39 UTC, merged