39 icons
LawnchairLauncher/lawnicons pull request #1306
Opened 2023-06-18 14:47 UTC by x9136

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)
## Icons addition information
### Updated
Moonlight (`com.limelight/com.limelight.PcView`)
### Added from icon request form
Account Access (`com.adobe.ims.accountaccess/com.zoontek.rnbootsplash.RNBootSplashActivity`)
All-In-One Calculator (`all.in.one.calculator/app.calculator.ui.activities.feed.FeedActivity`)
Blackboard (`com.blackboard.android.bbstudent/com.blackboard.android.bbstudent.splash.SplashActivity`)
Canvas Student (`com.instructure.candroid/com.instructure.student.activity.LoginActivity`)
Carteira de Trabalho Digital (`br.gov.dataprev.carteiradigital/br.gov.dataprev.carteiradigital.MainActivity`)
Chegg Study (`com.chegg/com.chegg.home.HomeActivity`)
Cittamobi (`br.com.cittabus/br.com.cittati.cittamobi_flutter.MainActivity`)
Coin (`com.zerodha.coin/com.zerodha.coin.MainActivity`)
Deco (`com.tplink.tpm5/com.tplink.tpm5.component.account.welcome.view.WelcomeActivity`)
DiDi (`com.sdu.didi.psnger/com.didi.sdk.app.launch.splash.SplashActivity`)
DiDi Food (`com.xiaojukeji.didi.global.customer/com.didi.soda.customer.biz.activity.SplashActivity`)
DiDi Rider (`com.didiglobal.passenger/com.didi.sdk.app.DidiLoadDexActivity`)
Dolby On (`com.dolby.dolby234/com.dolby.sessions.Launcher`)
DreamLab (`au.com.vodafone.dreamlabapp/au.com.vodafone.dreamlabapp.presentation.launcher.LauncherScreenActivity`)
DRTV (`dk.dr.webplayer/axis.android.sdk.app.startup.ui.StartupActivity`)
DUAL (`com.Seabaa.Dual/com.Seabaa.Dual.Dual`)
Earthquake Network (`com.finazzi.distquake/com.finazzi.distquake.MainActivity`)
EatSure (`com.done.faasos/com.done.faasos.activity.SplashActivity`)
Endel (`com.endel.endel/com.endel.endel.use_cases.root.RootActivity`)
Fiszkoteka (`air.biz.krokodyl.Fiszkoteka/air.biz.krokodyl.Fiszkoteka.AppEntry`)
Headspace (`com.getsomeheadspace.android/com.getsomeheadspace.android.splash.SplashActivity`)
Japanese Dictionary Takoboto (`jp.takoboto/md57ad91dd16d2201fa70bc474fe64b7e4e.MainActivity`)
Lovense Remote (`com.lovense.wear/com.wear.main.FlashActivity`)
Lucidchart (`com.lucidchart.android.chart/com.lucidchart.android.chart.MainActivity`)
Naukri.com (`naukriApp.appModules.login/com.naukri.splash.SplashActivity`)
Nova (`com.scaleup.chatai/com.scaleup.chatai.SplashActivity`)
Olauncher (`app.olauncher/app.olauncher.MainActivity`)
Power BI (`com.microsoft.powerbim/com.microsoft.powerbi.ui.home.HomeActivity`)
Salesforce (`com.salesforce.chatter/com.salesforce.chatter.Chatter`)
Shopify Shop (`com.shopify.arrive/com.shopify.arrive.MainActivity`)
Slidebox (`co.slidebox/co.slidebox.controller.startup.WelcomeActivity`)
TARGOBANK (`com.targo_prod.bad/com.e_i.bad.controls.activities.StartActivity`)
TikTokDownloader (`com.video.downloader.no.watermark.tiktok/com.video.downloader.no.watermark.tiktok.ui.activity.SplashActivity`)
TUI (`com.thomson.mythomson/com.tui.tda.activities.LauncherActivity`)
UniFi (`com.ubnt.easyunifi/com.ubnt.unifi.network.splashscreen.SplashScreenActivity`)
Viddit (`aculix.viddit.downloader/aculix.viddit.downloader.MainActivity`)
zFont 3 (`com.htetznaing.zfont2/com.htetznaing.zfont2.ui.StartingActivity`)
Zulip (`com.zulipmobile/com.zulipmobile.MainActivity`)

2023-06-18 14:56 UTC, RaduBratan commented
It appears both you and #1305 added `dreamlab.svg` lmao

2023-06-18 15:03 UTC, x9136 commented
> It appears both you and #1305 added `dreamlab.svg` lmao

In this case, I prefer mine because it is based on ellipses, and he has a manual attempt to fit the right roundings.

2023-06-18 15:17 UTC, RaduBratan commented
> > It appears both you and #1305 added `dreamlab.svg` lmao
> 
> In this case, I prefer mine because it is based on ellipses, and he has a manual attempt to fit the right roundings.

+1 from me for the mods

2023-06-28 12:22 UTC, Grabstertv commented on svgs/canvas_student.svg
I think

2023-06-28 12:57 UTC, Grabstertv requested changes
Thank you for this PR. Most icons are perfect but some needs changes.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/canvas_student.svg
I think this one can be made into outlines instead of fills throughout. Inner circles can be kept fills.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/carteira_de_trabalho_digital.svg
This looks very unbalanced. Reduce the number of varying stroke widths so it looks visually balanced. The outmost shape (around the star) can maybe be kept at the same width stroke as the star. Smaller details can be kept as they are as they’re too small for thicker strokes.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/cibc.svg
Needs a distinguishing factor as it is exactly the same as Microsoft Launcher’s icon. Users may confuse the two

2023-06-28 12:57 UTC, Grabstertv commented on svgs/didi_rider.svg
Jump between stroke thicknesses are drastic. Instead of going from 12px to 6px, try going from 12px to 10px or 8px so the thinner stroke does not look out of place.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/earthquake_network.svg
Same issue again. Drastic thickness change.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/iitc_mobile.svg
Drastic thickness jump: part 3

2023-06-28 12:57 UTC, Grabstertv commented on svgs/katwarn.svg
Drastic thickness jump: part 4. You have the opportunity to incrementally increase thickness for each circle inside. Making it a wave. Just a suggestion

2023-06-28 12:57 UTC, Grabstertv commented on svgs/lockmypix.svg
4px is not part of the lawnicons guidelines. It is way too thin. Please refer to the guidelines to see what widths you can use.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/naukricom.svg
8px thickness for the thinner stroke looks more appealing. See if you think so too. Just a suggestion.

2023-06-28 12:57 UTC, Grabstertv commented on svgs/olauncher.svg
I understand it can be difficult to make a differentiating factor between 2 or more icons that look exactly the same when converted to outlines. In this case, Headspace is also just a circle. But making one icon thin like this is not the way to go because it will look wrong when it is applied to the home screen. It creates an imbalance alongside other icons.

Please increase the thickness for minimal icons like this according to Lawnicon guidelines. You can try adding some text or making a completely new icon by yourself. Just make sure its not too much of a difference between them so its still recognizable by users.

2023-06-28 14:19 UTC, x9136 commented
> Thank you for this PR. Most icons are perfect but some needs changes.

No problem. I hope the reviewers will be as attentive to all PRs, because there is a feeling that a lot of icons are worth redoing.

2023-06-28 15:47 UTC, Grabstertv approved these changes

2023-06-28 15:48 UTC, Grabstertv approved these changes
These look great now! Please update the rest and I’ll ask to have it merged. Thanks!

2023-06-28 19:05 UTC, x9136 commented
I did what I thought was right. I left comments on the other icons. It remains to choose which of them to delete and which to keep.

2023-06-29 07:50 UTC, lorrding commented on svgs/didi_rider.svg
I find it fine as it is, but the opacity is not right. I don't know if it'll affect the final icon, but we can see through the road lines

2023-06-29 08:15 UTC, lorrding commented on svgs/iitc_mobile.svg
The base thickness should still be 12px so you can either do 12/8 or 12/10 (12/8 should look the best)

2023-06-29 08:25 UTC, x9136 commented on svgs/iitc_mobile.svg
Ok, then I suggest we leave the last version as is or delete it.

2023-06-29 08:40 UTC, lorrding commented on svgs/iitc_mobile.svg
I don't think that deleting what's wrong is the way to go. We should still prioritise quality over quantity.

Have you tried putting the icon next to other icons? If it does not look out of place with a thickness of 10px on the outline path it's okay to keep it that way, but if not, we should change it.

2023-06-29 09:09 UTC, x9136 commented on svgs/iitc_mobile.svg
I don't plan to make any more changes, so removing the wrong ones is the way to accept the PR. If anyone wants to suggest their own versions of the remaining icons, a new PR is easy to make.

After creating any PR, I install the debug version on my phone and see how the icons look like together. Anyone can check the appearance of all the icons on the phone screen.

2023-06-29 18:16 UTC, KTibow commented on svgs/home_assistant.svg
Can you explain why you made it so the corners around the edges of the roof are filled, and made the chimney a single line? Personally I think it doesn't look good this way.

2023-06-29 21:03 UTC, x9136 commented on svgs/home_assistant.svg
@KTibow I decided to simplify the inside shape of the house, because the inside corners of the roof look crumpled because of the roundings. I ended up with a version where the inside of the house is simplified and the outside is highlighted with distinctive details: the roof corners and the chimney.

2023-06-29 21:18 UTC, x9136 commented on svgs/home_assistant.svg
I like the way the icon looks:
![IMG_20230630_001421](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/b4ddded5-4765-4c64-9209-2f81157bab8a)

But such an alternative would also be good:
![home_assistant](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/bf8ad3ce-8b0c-41b0-ba11-42821007fa4f)

2023-06-29 21:21 UTC, KTibow commented on svgs/home_assistant.svg
I would be satisfied if the existing chimney was just moved so it doesn't look like it's the same line as the side of the house.

2023-06-29 21:30 UTC, x9136 commented on svgs/home_assistant.svg
@KTibow you mean like that?
![home_assistant](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a30838d7-5814-4416-a9bf-c4e1eb8a1704)

2023-06-29 22:21 UTC, KTibow commented on svgs/home_assistant.svg
Yeah. :+1:

2023-06-29 22:34 UTC, x9136 commented
The PR is ready to merge. Thank you all for the reviews.

2023-06-29 23:36 UTC, merged