Added 6 new icons and linked 2 apps to existing ones
LawnchairLauncher/lawnicons pull request #1314
Opened 2023-06-25 11:21 UTC by Fxsch

## Description

Added power icon (I hope it's okay that I gave it a universal name since it's not an app specific icon) and linked Classic Power Menu to it. Added icons for CPU Info, LocalMonero, DeutschlandCard, Easer (also linked it to Easer (beta)) and Fallout Shelter. Linked Clock You to clock and Geometry Dash Lite to geometry_dash.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* Classic Power Menu (`com.kieronquinn.app.classicpowermenu`)
* CPU Info (`com.kgurgul.cpuinfo`)
* LocalMonero (`co.localmonero.app`)
* DeutschlandCard (`de.deutschlandcard.app`)
* Easer (`ryey.easer`)
* Fallout Shelter (`com.bethsoft.falloutshelter`)

### Icons linked
* Clock You (linked `com.bnyro.clock` to `@drawable/clock`)
* Geometry Dash Lite (linked `com.robtopx.geometryjumplite` to `@drawable/geometry_dash`)
* Easer (beta) (linked `ryey.easer.beta` to `@drawable/easer`)

2023-06-25 11:33 UTC, Fxsch commented
I only tested this out after opening the pull request and I've noticed that clips don't seem to work, so I'll need to fix that before this can be merged

2023-07-09 21:34 UTC, Fxsch commented
I've fixed the issue, all icons how they're supposed to now

2023-07-14 13:00 UTC, Chefski requested changes

2023-07-14 13:00 UTC, Chefski commented on svgs/cpu_info.svg
Icons cannot use a fill design. Please change the square in the centre

2023-07-14 14:26 UTC, Fxsch commented
Changed it

2023-07-14 14:26 UTC, Fxsch commented on svgs/cpu_info.svg
Changed it

2023-07-15 23:10 UTC, Chefski approved these changes

2023-07-15 23:11 UTC, Chefski commented
Mind just resolving conflicts and I'll merge it then

2023-08-15 01:36 UTC, KTibow commented
cc @Fxsch

2023-08-27 19:10 UTC, Fxsch commented
Conflicts should be resolved

2023-08-28 13:55 UTC, Fxsch commented
Actually, never mind. Now the `appfilter.xml` has duplicates and 2 closing tags for `resources`.

2023-08-29 18:12 UTC, Fxsch commented
I just replaced `appfilter.xml` with the newest version from this repo and added my changes back in, I hope everything's fixed now

2023-09-13 17:13 UTC, Fxsch commented
Would be nice if this could get merged soon, I'm already working on a new pull request

2023-09-13 17:26 UTC, merged