Add trakt icon
LawnchairLauncher/lawnicons pull request #1349
Opened 2023-07-14 14:22 UTC by manasch

## Description

Add trakt.tv icon

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* Trakt (`tv.trakt.trakt`)

2023-07-15 07:14 UTC, manasch commented
I've been working on some other icons, if this hasn't been accepted by the time I'm done I'll add it to this if that's fine.

2023-07-15 11:05 UTC, x9136 commented
Reviewers will definitely tell you it's worth to read [the Lawnicon guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines) and fix what's wrong.

2023-07-15 12:00 UTC, manasch commented
> Reviewers will definitely tell you it's worth to read [the Lawnicon guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines) and fix what's wrong. 

Hi, I'm sorry that the contributions upset you, I'll try to find what's wrong and fix them.

But, I am going to assume that you are not happy with the icons that have curves as they do not match the 6px round radius.
If not for that, I'll gladly fix anything else that might be pointed out.

Thanks

2023-07-15 13:02 UTC, x9136 commented
@manasch Hi, I'm not upset. I thought I'd draw your attention to the guidelines ahead of time because the moderators will ask you to do it anyway.

2023-07-15 13:42 UTC, manasch commented
@x9136 Hi, I understand sorry.
I am making the changes rn. From what I found, I made the mistake of not using base as 12px and rounded corners not having the 6px radius.

I've switched all to 12px base with the minimal ones getting 14px as well as finer details getting 6px. My only doubt would lie in the usage of the standard widths mentioned.

I will be making another commit with the fixes soon.

I hope this would resolve it.

2023-07-15 15:19 UTC, manasch commented
I have made the changes to fit the guidelines. The only one that I see to be rejected is fasthub-re (in which I will give up on that, I do not know how I can draw that better :smiling_face_with_tear:).
I used 8px as the default stroke as 12px was too thick. As for the finer details I used 6px.

I have ensured that the rest of them use the base stroke as 12px as much as possible along with 14px for the ones that are minimal.

I hope this fits to the standard.
Thanks.

2023-07-15 15:41 UTC, x9136 commented
@manasch Cool, but you forgot to round corners somehow. 🥲 There are no right angle icons in this pack.

2023-07-15 16:31 UTC, manasch commented
That is actually quite embarrassing. Sorry for the repeated work, I have changed them all to have rounded corners.
I actually failed to understand from the guidelines what rounded corners meant.

Sorry again.

2023-07-15 23:12 UTC, Chefski requested changes
Just quickly looking over the icons I see they all have a white background. Could you change it to transparent. I'll review them more later

2023-07-16 03:56 UTC, manasch commented
@Chefski Hey, before I make another commit, was just checking for any other changes to be made and noticed that the svg's I made have newlines and the color is mentioned as `black` whereas the ones already existing in the repo have no newlines (everything in oneline) and color as `#000`.

Would this be an issue and if so do I manually change it?  I've been using figma to create and export them and I don't see any export setting to get it the same way as the existing icons.

2023-07-24 09:50 UTC, Chefski requested changes
Some icons don't quite fit the content area. I fixed 3. If you could just fit them to the 160x160 content area then they will be fine :)

2023-07-24 09:50 UTC, Chefski commented on svgs/english_dictionary.svg
Change to fit 160x160 content area. Make sure the fill shape still has the acceptable line width.
<img width="500" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/83cd607b-5e50-4aa3-930d-1298028f08d6">

2023-07-24 09:50 UTC, Chefski commented on svgs/fasthub_re.svg
Fit to 160x160 content area
<img width="500" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/ab610c05-f572-474e-afe2-44bd7c5b28da">

2023-07-24 09:50 UTC, Chefski commented on svgs/flashcards.svg
Fit to 160x160 content area

2023-07-24 09:50 UTC, Chefski commented on svgs/literal.svg
Fit to 160x160 content area

2023-07-24 09:50 UTC, Chefski commented on svgs/nekome.svg
Fit to 160x160 content area

2023-07-24 09:50 UTC, Chefski commented on svgs/story_graph.svg
Fit to 160x160 content area

2023-07-24 09:50 UTC, Chefski commented on svgs/vyom.svg
Fit to 160x160 content area

2023-07-24 18:46 UTC, manasch commented on svgs/english_dictionary.svg
The fill shape is 6px, but not sure if I can accurately depict the flag, I'll commit the changes I've made but if it's not acceptable I'll remove it.

2023-08-01 15:58 UTC, Chefski approved these changes

2023-08-01 15:59 UTC, merged