add 9 icons
LawnchairLauncher/lawnicons pull request #1350
Opened 2023-07-16 12:25 UTC by SiMah5

## Description

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added from icon request form
* Pix You Cornflower Dark Icons (`com.arjunarora.pix_you_cornflower_dark_icons/com.arjunarora.pix_you_cornflower_dark_icons.MainActivity`)
* NYTimes (`com.nytimes.android/com.nytimes.android.MainActivity`)
* MPlayer (`com.mplayer.streamcast/com.mplayer.streamcast.activity.SplashScreen`)
* MoveInSync (`com.moveinsync.ets/com.moveinsync.ets.launch.LaunchActivity`)
* Gosund (`com.gosund.smart/com.gosund.smart.splash.SplashActivity`)
* Goodreads (`com.goodreads/com.goodreads.kindle.ui.activity.RoutingActivity`)
* Finch (`com.finch.finch/com.finch.finch.MainActivity`)
* Obedience (`com.obedience/com.obedience.DefaultAlias`)
* Drinkable (`com.moimob.drinkable/com.moimob.drinkable.MainActivity`)

2023-07-16 14:16 UTC, x9136 commented on svgs/gosund.svg
Why did you decide not to make a circle like in the original icon? 
![gosund](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9fc9b349-adf0-4955-87b7-df733e35f719)

2023-07-16 14:49 UTC, SiMah5 commented on svgs/gosund.svg
oh... i think i forgot to change the corner radius when i made it bigger so it turned out like that, my bad. thanks for pointing it out.

2023-07-24 10:04 UTC, Chefski requested changes

2023-07-24 10:04 UTC, Chefski commented on svgs/kafka.svg
The icon goes outside the 160x160px content area. Could you reduce it in size to fit the content area?

2023-07-24 10:04 UTC, Chefski commented on svgs/tg_monet.svg
The icon goes slightly outside the content area
<img width="500" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/5640a98d-ae27-41ac-9c31-a90622e8c7ec">

2023-07-26 20:04 UTC, Chefski approved these changes

2023-07-26 20:04 UTC, merged