1 svg added and 1 app linked
LawnchairLauncher/lawnicons pull request #1354
Opened 2023-07-19 11:06 UTC by Thorodinson1

## Description

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* BSNL FTTH Usage (`com.rrapplabs.bsnldatausage`) - added from icon request form

### Icons linked
*  BSNL FTTH Usage (linked `com.rrapplabs.bsnldatausage` to `@bsnl_ftth_usage`)

2023-07-23 01:25 UTC, Chefski requested changes

2023-07-23 01:25 UTC, Chefski commented on svgs/bsnl_ftth_usage.svg
Could you change the icon to fit the 160x160px content area
<img width="450" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/dc9e6845-0b97-4e53-a700-cc17741aeebc">

2023-07-24 04:02 UTC, Thorodinson1 commented on svgs/bsnl_ftth_usage.svg
fixed

2023-07-24 09:24 UTC, Chefski approved these changes

2023-07-24 09:24 UTC, merged