32 icons
LawnchairLauncher/lawnicons pull request #1358
Opened 2023-07-22 12:08 UTC by x9136

## Type of change
:x: Bug fix
:white_check_mark: Icon addition
:x: General change
## Icons addition information
### Requests
alif mobi (`tj.alif.mobi/tj.alif.mobi.home.HomeActivity`)
Another Widget (`com.tommasoberlose.anotherwidget/com.tommasoberlose.anotherwidget.ui.activities.MainActivity`)
AutoTagger (`com.serg.chuprin.tageditor/com.serg.chuprin.tageditor.app.main.view.MainActivity`)
ComicScreen (`com.viewer.comicscreen/com.viewer.comicscreen.ListActivity`)
Enel Energia (`it.enel/crc64d0549c3f31f5415a.SplashActivity`)
ESP (`com.ashwhale.sepush.eskom/com.ashwhale.sepush.eskom.MainActivity`)
Culture (`ru.gosuslugi.culture/ru.notamedia.pushka.pushka.MainActivity`)
KASKUS (`com.kaskus.android/com.kaskus.forum.SplashActivity`)
Lookout (`com.google.android.apps.accessibility.reveal/com.google.android.apps.accessibility.reveal.activities.ProxyActivity`)
moneycontrol (`com.divum.MoneyControl/com.moneycontrol.handheld.SplashActivity`)
Music Speed Changer (`com.smp.musicspeed/com.smp.musicspeed.MainActivity`)
MyGori (`com.goriacqua.app/it.acea.androidapp.ui.LoginActivity`)
Nat Geo TV (`com.natgeo.tv/com.disney.datg.android.abc.startup.SplashScreenActivity`)
NayaPay (`com.nayapay.app/com.nayapay.app.kotlin.SplashActivity`)
Nike Training Club (`com.nike.ntc/com.nike.ntc.onboarding.OnboardingSplashActivity`)
NMM File Manager (`in.mfile/com.nmmedit.files.ui.FileManagerActivity`)
NVIDIA SHIELD TV (`com.nvidia.shield.remote/com.nvidia.shield.remote.MainActivity`)
OPENREC.tv (`jp.co.cyber_z.openrecviewapp/jp.co.cyber_z.openrecviewapp.feature.main.ui.MainActivity`)
Pillars (`com.pillars.pillars/com.pillars.pillars.MainActivity`)
Pixel Tuner (`it.folgore95.pixeltuner/it.folgore95.pixeltuner.MainActivity`)
Poke Genie (`com.cjin.pokegenie.standard/com.canjin.pokegenie.MainActivity`)
Postepay (`posteitaliane.posteapp.apppostepay/posteitaliane.posteapp.apppostepay.ui.activity.SplashActivity`)
Setel (`com.setel.mobile/com.zapmobile.zap.splash.SplashActivity`)
Providers (`com.propel.ebenefits/com.propel.ebenefits.MainActivity`)
ShopBack (`com.shopback.app/com.shopback.app.core.ui.splash.SplashActivity`)
SideQuest Installer (`side.quest.mobile/side.quest.mobile.MainActivity`)
StoryArt (`com.ryzenrise.storyart/com.lightcone.artstory.acitivity.SplashActivity`)
TextNow (`com.enflick.android.TextNow/authorization.ui.AuthorizationActivity`)
TPBank Mobile (`com.tpb.mb.gprsandroid/com.tpb.hydrobank.views.SplashActivity`)
UnrollMe (`com.unrollme/com.unrollme.MainActivity`)
WOO (`pt.nostech.fera/pt.nostech.fera.MainActivity`)
WeRead (`com.tencent.weread/com.tencent.weread.LauncherActivity`)

2023-07-26 01:50 UTC, Rustmilian approved these changes
These are very good.

2023-07-26 02:00 UTC, Rustmilian approved these changes

2023-08-09 00:59 UTC, KTibow reviewed
overall i like this pr because it has chatgpt (because of that please merge soon), but i scrolled through it and found some stuff i feel could be better.

2023-08-09 00:59 UTC, KTibow commented on svgs/bbdaily.svg
the rounding and thickness feel a bit off here

2023-08-09 00:59 UTC, KTibow commented on svgs/central_power.svg
this icon is hard because it feels wrong but i can't suggest anything better
my best suggestion:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/f8b368a4-d4f0-423b-849d-ebc66f9e3a81)

2023-08-09 00:59 UTC, KTibow commented on svgs/dwg_fastview.svg
feels a bit off here:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/3651d026-f697-4075-aab2-d5cb8c028be8)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/f87a4eaa-97ac-4cad-8aed-919a7c4678f3)

2023-08-09 00:59 UTC, KTibow commented on svgs/ft.svg
does it look worse with consistent stroke width?

2023-08-09 00:59 UTC, KTibow commented on svgs/postepay.svg
check the alignment/size? also stroke width isn't consistent which might be fine anyway

2023-08-09 00:59 UTC, KTibow commented on svgs/radiodroid.svg
feels crowded, not sure how to improve that or if it's even allowed to make it less crowded

2023-08-09 00:59 UTC, KTibow commented on svgs/tpbank_mobile.svg
feels wrong, both because of stroke width and overlapping
some possibly decent ideas
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/30b343c9-f61f-43d5-8934-aa6cc7d5ffc5)

2023-08-09 00:59 UTC, KTibow commented on svgs/unicredit.svg
i prefer something like this - not sure what the icon rules say tho
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/6d83b8c6-00fd-40e1-878a-61b9beb87062)

2023-08-09 00:59 UTC, KTibow commented on svgs/weread.svg
don't really like this icon, although not sure what a better option is. just something that represents a book with tencent branding.

2023-08-09 00:59 UTC, KTibow commented on svgs/wo_mic.svg
surely we could reuse an existing mic icon?

2023-08-09 04:17 UTC, x9136 commented
> i scrolled through it and found some stuff i feel could be better.

Which ones?

2023-08-09 04:24 UTC, x9136 commented on svgs/bbdaily.svg
Can you elaborate on that?

2023-08-09 04:40 UTC, x9136 commented on svgs/wo_mic.svg
I don't like the idea of overusing every possible icon. That's okay if we're talking about system apps. If we're talking about apps available from the store, the same icons make it hard to distinguish between system and third-party apps.

2023-08-09 04:47 UTC, x9136 commented on svgs/ft.svg
It will look more like a blot due to the fact that the distances between elements will become small. If you try to make the distances adequate, the proportions will be lost.

2023-08-09 04:57 UTC, x9136 commented on svgs/postepay.svg
I'm not sure what you wanted to check.
<img width="386" alt="Screenshot 2023-08-09 at 07 56 43" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/758a6fda-3775-43df-bb22-5c1b71e60fa9">

2023-08-09 10:10 UTC, KTibow commented on svgs/bbdaily.svg
actually its fine

2023-08-09 10:10 UTC, KTibow commented on svgs/postepay.svg
actually its fine

2023-08-09 10:11 UTC, KTibow commented on svgs/ft.svg
ok fair

2023-08-09 10:12 UTC, KTibow commented on svgs/wo_mic.svg
ok fair

2023-08-09 10:55 UTC, x9136 commented
@Rustmilian and @KTibow politely took the time to check the icons. It seems that the PR is ready to merge.

:trollface: 🤜  🔔 @Chefski

2023-08-11 17:15 UTC, KTibow commented
@x9136 github says "This branch is out-of-date with the base branch" - can the pr still be merged or do you need to update it?

2023-08-11 19:41 UTC, x9136 commented
@KTibow I need to update it, but mods are still busy.

2023-08-12 12:14 UTC, Chefski requested changes

2023-08-13 12:12 UTC, Chefski approved these changes

2023-08-13 12:12 UTC, merged