Add 29 icons, Link 2
LawnchairLauncher/lawnicons pull request #1368
Opened 2023-07-28 15:54 UTC by Darukutsu

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark:  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* aodNotify (`com.jamworks.aod.notificationlightled/com.jamworks.aod.notificationlightled.SettingsHome`)
* Audio Recorder (`com.dimowner.audiorecorder/com.dimowner.audiorecorder.MainActivity`)
* Bunpo (`com.bunpoapp/com.bunpoapp.ui.splash.SplashActivity`)
* Casio (`jp.co.casio.CasioMusicCity/jp.co.casio.cordanaplay.lib.ChordanaPlayActivity`)
* FindMyDevice (`de.nulide.findmydevice/de.nulide.findmydevice.ui.MainActivity`)
* GameSpace (`io.chaldeaprjkt.gamespace/io.chaldeaprjkt.gamespace.settings.SettingsActivity`)
* Ideme vlakom (`sk.zssk.mobapp.android/sk.zssk.mobapp.android.ui.SplashActivity`)
* KeyMapper (`io.github.sds100.keymapper/io.github.sds100.keymapper.SplashActivity`)
* Knizka (`pk.tappdesign.knizka/pk.tappdesign.knizka.MainActivity`)
* Liturgicke citania (`sk.bouli.lc/sk.bouli.lc.MainActivity`)
* ManMan (`com.adonai.manman/com.adonai.manman.MainPagerActivity`)
* Mapy.cz (`cz.seznam.mapy/cz.seznam.mapy.MapActivity`)
* MHD Kosice (`sk.mhdapp.ke/sk.mhdapp.MainActivity`)
* MHD Presov (`com.nolimit.sk.mhdpresov/sk.mhdapp.MainActivity`)
* Mi Buds M8 (`bz.zaa.mibudsm8/bz.zaa.mibudsm8.ui.activities.MiuiHeadsetActivity`)
* Moja 4ka (`sk.stvorka.moja4ka/sk.stvorka.moja4ka.MainActivity`)
* MRepo (`com.sanmer.mrepo/com.sanmer.mrepo.ui.activity.main.MainActivity`)
* MTG Familiar (`com.gelakinetic.mtgfam/com.gelakinetic.mtgfam.FamiliarActivity`)
* OBS Blade (`com.kounex.obsBlade/com.kounex.obsBlade.MainActivity`)
* OCR (`io.github.subhamtyagi.ocr/io.github.subhamtyagi.ocr.MainActivity`)
* Packeta (`cz.zasilkovna.app/cz.zasilkovna.app.dashboard.view.MainActivity`)
* Sharik (`dev.marchello.sharik/dev.marchello.sharik.MainActivity`)
* SpyDroid (`net.majorkernelpanic.spydroid/net.majorkernelpanic.spydroid.ui.SpydroidActivity`)
* Sygic (`com.sygic.aura/com.sygic.aura.activity.NaviNativeActivity`)
* SysInfo (`com.kl3jvi.sysinfo/com.example.sysinfo.activities.SplashScreen`)
* Task (`info.tangential.task/info.tangential.task.MainActivity`)
* TetherFi (`com.pyamsoft.tetherfi/com.pyamsoft.tetherfi.main.MainActivity`)
* Tower Collector (`info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity`)
* VsZP (`sk.vszp.vszp/com.asseco.ce.vszp.patient.presentation.ui.EntryActivity`)
* XiaoFlasher (`eScooter.m365Info/eScooter.m365Info.MainActivity`)

### Icons linked
These all +
*QR & Barcode Scanner (linked `com.example.barcodescanner/com.example.barcodescanner.feature.tabs.BottomTabsActivity` to `@drawable/qr_reader`)
*Saikou (linked  `ani.saikou/ani.saikou.MainActivity` to `@drawable/saikou`)

2023-07-28 15:59 UTC, Darukutsu commented
pls tell me how to do this PRs automated, without typing it all. Some recommendation. I don't get which one are simple enough to use 14px instead of 12px. Some will need rescaling probably.

2023-07-28 17:11 UTC, x9136 commented
> pls tell me how to do this PRs automated

You can speed up some parts of the process [via icontool.py](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/icontool_guide.md).

>I don't get which one are simple enough to use 14px instead of 12px. Some will need rescaling probably.

12px is basis. You can check [the guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines) to make sure that your submissions are correct. A lot of them don't fit.

2023-07-28 17:42 UTC, Darukutsu commented
> 12px is basis. You can check [the guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines) to make sure that your submissions are correct. A lot of them don't fit.

Yeah I don't get like, if letters can be picked from any font to fit icon or reworked. Also there is said icons shouldn't be filled, but found some like `microsoft_admin_foreground` not following rule. I was learning how to use inkscape. I think I have all propotions of lines (apart from 160, 144 sizes) good. Template would be appreciated. 

>You can speed up some parts of the process [via icontool.py](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/icontool_guide.md).

Yeah I know I thought if it has some flag to output changed only/new files. Instead of copy/paste memory.

2023-07-28 18:13 UTC, x9136 commented
@Darukutsu I don't think there's a template for Inscape, only the guidelines in Figma. You probably could create it by yourself. The core rules is simple: an icon viewbox is 192×192px, the svg fit the 160×160px content area, all shapes are rounded and the base line thickness is 12px.

There are 2300+ icons, so some of them didn't fit the guidelines, but most of them are correct. Any contributor can fix wrong ones. 

I'm not entirely sure what you want to automate. If it can't be done through tables or tools that are out there, you can't do it without development.

2023-07-30 11:43 UTC, Darukutsu commented
I find that some icons didn't have appropriate stroke width. I messed my template. I refit some of square icons to 144. Please tell which icons will need what to change.

2023-08-11 07:28 UTC, x9136 commented
I only checked for size compliance with [the guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines). The result is 4 out of 29.

![x](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/164a4451-7273-4c28-a718-09ea1ceee2ba)

2023-08-11 11:47 UTC, Darukutsu commented
Resized all to fit 160x160. I didn't change `com.dimowner.audiorecorder` `pk.tappdesign.knizka` & `sk.zssk.mobapp.android` because I think they wouldn't fit original. Also added 7 new icons and 1 link. Therefore I edited first message.

2023-08-14 20:08 UTC, Chefski requested changes
Suggested some changes. I'd also like to ask to double check that all icons have the 160x160 content area (except for squares which have 144x144) and the opacity is at 100%. Please also remove the hidden layer from each icon
<img width="412" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/d6fe314e-0e67-463c-8c3a-bd1f387e56de">

2023-08-14 20:08 UTC, Chefski commented on svgs/lc.svg
The book width is too wide. Please remove some shapes, reduce the stroke width or remake the icon

2023-08-14 20:08 UTC, Chefski commented on svgs/knizka.svg
The icon does not meet the guidelines as the Alpha and Omega have varying widths

2023-08-14 20:08 UTC, Chefski commented on svgs/sysinfo.svg
The bolt uses too much of a fill style. Please try make it more outline. Alongside that ensure all shapes have 100% opacity

2023-08-15 09:30 UTC, Darukutsu commented
Well I messed up something, while trying to figure out how github ui works :smile: . How to link [pull request](https://github.com/LawnchairLauncher/lawnicons/pull/1394) to closed one? Probably not possible...

2023-08-15 14:52 UTC, KTibow commented
define "link"
you could always just reopen this one and edit the description/title, a pr just represents an input branch and an output branch

2023-08-15 17:07 UTC, Darukutsu commented
I am idiot I was looking where is the fucking reopen button. Sorry for trouble.

2023-09-13 18:57 UTC, Chefski requested changes

2023-09-13 18:57 UTC, Chefski commented on svgs/audio_recorder.svg
Not sure if I missed looking at the icon size last time but it needs to fit the 160x160px content area. Sorry about that 😅
<img width="425" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/f2d01fbe-0e1e-4457-b814-226072fc8616">

2023-09-13 18:57 UTC, Chefski commented on svgs/mtgfam.svg
Can you remove the hidden group please?
<img width="405" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/f630ac07-bbfe-4b2e-805a-66fc31127692">

2023-09-13 18:57 UTC, Chefski commented on svgs/nfc_reader.svg
Please change the opacity of the circle to 100%
<img width="410" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/d3534c09-d2c1-4c41-9bbc-1f02da114cac">

2023-09-13 18:57 UTC, Chefski commented on svgs/spydroid.svg
Please change the opacity of the almost circular shape in the center to 100%
<img width="389" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/ec0419bb-06c5-42d6-8b0a-1ef7dd389611">

2023-09-13 18:57 UTC, Chefski commented on svgs/zssk.svg
Can you fit this to the 160x160 content area?
<img width="400" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/366415fe-6075-4083-9c65-9ca2d24cf3b5">

2023-09-13 18:57 UTC, Chefski commented on svgs/mhdke.svg
Mind removing the hidden layer?
<img width="410" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/a9393ced-f552-41ab-830d-b7841c7a6f10">

2023-09-13 18:57 UTC, Chefski commented on svgs/mi_buds_m8.svg
Could you change the stroke of the ovals to 10px? (currently 10.03px)
<img width="1093" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/3e9b467c-6082-4c9d-a318-f0b7d7a8e5e2">

2023-09-13 18:57 UTC, Chefski commented on svgs/tetherfi.svg
Could you change the opacity of the circle to 100% and change it to 32x32
<img width="448" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/6ca3a496-6cb9-4269-b364-c851bcf7c9dd">

2023-09-14 09:11 UTC, Darukutsu commented on svgs/nfc_reader.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54768193/62464f28-934b-43c3-83da-73dbd687be8d)
not sure if it's inkscape problem

2023-09-14 09:11 UTC, Darukutsu commented on svgs/spydroid.svg
same as nfc_reader.svg

2023-09-14 09:15 UTC, Darukutsu commented on svgs/tetherfi.svg
same as nfc_reader.svg

2023-09-14 09:44 UTC, x9136 commented on svgs/nfc_reader.svg
> not sure if it's inkscape problem

Maybe something is going on when saving because the wrong transparency is being written to the SVG code.

2023-09-14 15:45 UTC, Darukutsu commented
ln meantime while I will search where is problem with not saving opacity properly I've added few more icons + updated original comment.

2023-09-14 15:51 UTC, Darukutsu commented on svgs/zssk.svg
l have no idea how should this be reworked because when scaling, it will lose "centerness" since no-element should exceed 160px (I mean the triangle)
![ResizedImage_2023-09-14_17-46-33_2025](https://github.com/LawnchairLauncher/lawnicons/assets/54768193/da50a8f0-792d-4b72-b451-fc285464fa28)
![shared_image(JEEjttOyjamxnGI)](https://github.com/LawnchairLauncher/lawnicons/assets/54768193/5ba8e9bd-c203-4f4c-bd03-dde8e15c9727)

2023-09-14 17:20 UTC, x9136 commented on svgs/zssk.svg
> l have no idea how should this be reworked

<img width="435" alt="Screenshot 2023-09-14 at 20 16 37" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/b5c56e9a-f844-4726-8ad3-3d49d963c4e6">

2023-09-14 22:32 UTC, KTibow reviewed
in general:
- always export as a plain svg, not an inkscape svg
- don't use so many line widths, just simplify your icons
- consider that you should use 6px rounding for corners
- maybe don't include the outside square/ring
- maybe disregard all of my comments, idk, it's not like i'm a lawnchair admin

2023-09-14 22:32 UTC, KTibow commented on svgs/gitcoach.svg
too detailed

2023-09-14 22:32 UTC, KTibow commented on svgs/xiaoflash.svg
some elements here are too crowded

2023-09-14 22:32 UTC, KTibow commented on svgs/vszp.svg
you should use single line instead of double line

2023-09-14 22:32 UTC, KTibow commented on svgs/video_transcoder.svg
too complicated, too oval-y, not rounded enough

2023-09-14 22:32 UTC, KTibow commented on svgs/tower_collector.svg
not seamless, also doesnt really look "outlined"
try this style instead
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/aeab7064-7e87-4b34-bb00-dfc298b40477)

2023-09-14 22:32 UTC, KTibow commented on svgs/thumbkey.svg
if you *want* to make it simpler, you could omit the notch :shrug:

2023-09-14 22:32 UTC, KTibow commented on svgs/tetherfi.svg
the fact that the circles are not all the same distance apart is bothering me

2023-09-14 22:32 UTC, KTibow commented on svgs/sygic.svg
i couldn't find any icons on the play store with that bottom text style

2023-09-14 22:32 UTC, KTibow commented on svgs/spydroid.svg
if you can make the eye look better (eg more centered, better line joins) do that

2023-09-14 22:32 UTC, KTibow commented on svgs/simple_wol.svg
this feels squashed compared to the original icon

2023-09-14 22:32 UTC, KTibow commented on svgs/second_screen.svg
would be cool if you could make the starting one less blobby and the last one look like an arc instead of two lines joined together

2023-09-14 22:32 UTC, KTibow commented on svgs/packeta.svg
use more consistent line widths

2023-09-14 22:32 UTC, KTibow commented on svgs/obs.svg
rename this to obs_blade

2023-09-14 22:32 UTC, KTibow commented on svgs/mi_buds_m8.svg
you're trying to convert an icon in one style to a lawnicon without reoutlining it, which makes this icon confusing (at least to me). the original icon was filled so it couldn't join the stick and pod, but since it's outlined we can do that. you may also want to simplify it further or change it another way so it's more clear it's a bud.

2023-09-14 22:32 UTC, KTibow commented on svgs/mhdke.svg
simplify and align the text, and just simplify the icon as a whole.

2023-09-14 22:32 UTC, KTibow commented on svgs/manman.svg
perhaps this could be simplified?
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/6d4ca8fd-9b16-4317-a5bc-950e52b39cc5)

2023-09-14 22:32 UTC, KTibow commented on svgs/lc.svg
you're trying to convert an icon in one style to a lawnicon without reoutlining it, which makes the book look bad (at least to me). try only drawing the current page or only drawing the book? not really sure what to recommend.

2023-09-14 22:32 UTC, KTibow commented on svgs/knizka.svg
the A and Ω are too freeform/wobbly

2023-09-14 22:32 UTC, KTibow commented on svgs/keymapper.svg
either reduce the distance between the two rows to form a grid, or reduce the number of keys in each row.

2023-09-14 22:32 UTC, KTibow commented on svgs/hj_lite.svg
too many details. just include the bamboo and some parts of the plant. also adjust the edges of the bamboo (maybe reduce the distance between), right now it looks like bones.

2023-09-14 22:32 UTC, KTibow commented on svgs/change_my_mac.svg
feels like the text isnt centered

2023-09-14 22:32 UTC, KTibow commented on svgs/android_faker.svg
too crowded/detailed - are the glasses supposed to be poking out like that? also the eyes kinda look uncentered or something idk

2023-11-14 01:18 UTC, closed without merging