add 7 icons
LawnchairLauncher/lawnicons pull request #1373
Opened 2023-08-07 20:48 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2023-08-07 21:10 UTC, peterge1998 commented
I am fcking tired...

2023-08-08 16:30 UTC, x9136 commented on svgs/chatgpt.svg
[I did that one too](https://github.com/LawnchairLauncher/lawnicons/pull/1358/files#diff-b40bd2be1640c5a6496ce8756dcc09aaff6275541396d17a7382724d927d4bff). If you plan to suggest your version, it's at least worth making sure that the icon fit the 160×160 content area.

2023-08-09 05:29 UTC, peterge1998 commented on svgs/chatgpt.svg
kk removed it

2023-08-13 12:21 UTC, Chefski requested changes
All of the icons added need to have be sized down to fit the 160x160 content area. All of them are too big. 2 icons also need changes, check the comments for them.

2023-08-13 12:21 UTC, Chefski commented on svgs/x.svg
Please remove the green fill.
<img width="236" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/14ca2d6e-252d-4c5f-90a5-aa3d3dcb92df">

2023-08-13 12:21 UTC, Chefski commented on svgs/rtl_musik.svg
The rectangle for the `R` and the `L` have their stroke adjusted to 6px.
<img width="700" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/034d5794-3957-426f-8965-d33fd21b1f40">

2023-08-14 11:32 UTC, peterge1998 commented on svgs/x.svg
Done

2023-08-14 11:32 UTC, peterge1998 commented on svgs/rtl_musik.svg
Done

2023-08-14 11:33 UTC, peterge1998 commented
> All of the icons added need to have be sized down to fit the 160x160 content area. All of them are too big. 2 icons also need changes, check the comments for them.

Is back to bed icon resized correctly? then i will do this for all icons in my pr.

2023-08-14 19:30 UTC, Chefski commented
Back to bed is good though slightly too big by 0.02px but its really small.. You can fix the rest of the icons :)
<img width="87" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/e3826cee-0a52-4a39-9e86-c4b85422460f">

2023-08-14 19:32 UTC, Chefski requested changes

2023-08-14 19:32 UTC, Chefski commented on svgs/x.svg
The bottom left line still shows the green fill. Mind double checking if the right file was imported?
<img width="599" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/5d05f287-ed38-461b-b2a1-5461fa10e5ea">

2023-08-15 07:49 UTC, peterge1998 commented on svgs/x.svg
Done

2023-08-15 09:09 UTC, peterge1998 commented
> Back to bed is good though slightly too big by 0.02px but its really small.. You can fix the rest of the icons :) <img alt="image" width="87" src="https://user-images.githubusercontent.com/100310118/260553048-e3826cee-0a52-4a39-9e86-c4b85422460f.png">

Done :)

2023-08-19 09:08 UTC, peterge1998 commented
Why does the pipeline not run? :o

2023-08-24 10:49 UTC, x9136 commented
@peterge1998 Hi. What about fixing the conflicts?

<img width="501" alt="Screenshot 2023-08-24 at 13 47 58" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/87ebdcb0-b2ef-40bb-afd7-f483d2e5fe21">

2023-08-24 10:57 UTC, peterge1998 commented
> @peterge1998 Hi. What about fixing the conflicts?
> <img alt="Screenshot 2023-08-24 at 13 47 58" width="501" src="https://user-images.githubusercontent.com/60105060/262949860-87ebdcb0-b2ef-40bb-afd7-f483d2e5fe21.png">

done

2023-08-24 10:59 UTC, peterge1998 commented
> @peterge1998 Hi. What about fixing the conflicts?
> <img alt="Screenshot 2023-08-24 at 13 47 58" width="501" src="https://user-images.githubusercontent.com/60105060/262949860-87ebdcb0-b2ef-40bb-afd7-f483d2e5fe21.png">

Done

2023-09-23 04:53 UTC, x9136 requested changes
I've left comments on the technical and style differences. Please consider it as much as possible. If you have time, I suggest spending 10-15 minutes [on Lawnicons guides](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#contributing-icons). This will help in working on icons and speed up acceptance of PRs.

2023-09-23 04:53 UTC, x9136 commented on svgs/worms4.svg
<img width="611" alt="Screenshot 2023-09-23 at 06 57 44" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a5741da5-78e8-46c1-825f-3de7a93f8804">

Could you simplify the shape in the highlights and use 8px stroke thickness?

2023-09-23 04:53 UTC, x9136 commented on svgs/sj.svg
Please make sure the canvas size is 192×192px. Right now the canvas size is equal to the icon size.

2023-09-23 04:53 UTC, x9136 commented on svgs/gold_and_goblins.svg
<img width="604" alt="Screenshot 2023-09-23 at 07 18 14" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/f05ce322-970a-4913-b78b-e2520f49f1e3">

It's worth simplifying the shape and using a stroke thickness of 8, 10 or 12px. 6px is used only for small things.

2023-09-23 04:53 UTC, x9136 commented on svgs/chefgpt.svg
<img width="422" alt="Screenshot 2023-09-23 at 07 26 56" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/8e0812ad-6553-4ead-85b0-f338408193a8">

It will be cleaner to deal with the bottom like this. Don't forget to round the corners of the rectangle by 6px.

2023-09-23 04:53 UTC, x9136 commented on svgs/back_to_bed.svg
Requires a lot of simplification because the excess of detail doesn't really fit the overall style. I would suggest concentrating on the sleepwalker and making it with fewer strokes. It's also worth using a stroke thickness of 8, 10, or 12px.

2023-11-07 01:19 UTC, closed without merging