Add 2 icons
LawnchairLauncher/lawnicons pull request #1392
Opened 2023-08-14 19:06 UTC by Reallukeisbest

## Description
Thank you for creating such an amazing project! I am excited to possibly make more icons once this request gets accepted and I am happy to contribute to such an incredible project! These are the last two icons that are needed to complete my home screen and I'm happy to have a complete home screen! 😀 

## Type of change
❌ Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
❌ General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons added
T-Mobile (`com.tmobile.pr.mytmobile`)
LA Wallet (`gov.la.omv.lawallet`)

-- Luke

2023-08-14 19:26 UTC, Chefski requested changes

2023-08-14 19:26 UTC, Chefski commented on svgs/tmobile.svg
Please round the corners

2023-08-14 20:00 UTC, x9136 commented on svgs/tmobile.svg
You can use this one, just remove the extra elements.
https://github.com/LawnchairLauncher/lawnicons/blob/d5c37a4b77c5be5c5e0b133f974839aa310da953/svgs/my_tmobile.svg

2023-08-14 20:05 UTC, KTibow commented on svgs/tmobile.svg
[the version we already have](https://play.google.com/store/apps/details?id=nl.oberon.tmobile.my)
[the version thats being added](https://play.google.com/store/apps/details?id=com.tmobile.pr.mytmobile)
i dont see why we cant just use the same icon instead of adding a new one

2023-08-14 20:13 UTC, Chefski commented on svgs/tmobile.svg
Knew we had an icon for this but my search was set to find by exact name so didn't show up when I was just searching tmobile.

@Reallukeisbest in that case, link the app to the drawable `my_tmobile` and remove the icon.

2023-08-14 20:18 UTC, Reallukeisbest commented on svgs/tmobile.svg
Hello!

I have removed the icon and have edited the appfilter accordingly. I will now work on editing the LA Wallet icon. Thank you for the notice!

-- Luke

2023-09-04 07:19 UTC, x9136 commented on svgs/la_wallet.svg
> I'm sorry, could you please elaborate?

The shape has right angles and many branches come out of it. You need to round the right corners and make it so that there are no outgrowths: simplify the shape or invent another icon.

2023-09-04 11:45 UTC, KTibow commented
Also FYI you need to resolve conflicts

2023-09-05 17:19 UTC, Reallukeisbest commented
This pull request should be ready; I've made the requested changes 🙂

2023-09-05 17:21 UTC, KTibow commented
unfortunate timing that the [dutch version of tmobile](https://play.google.com/store/apps/details?id=nl.oberon.tmobile.my) went through a rebrand before this pr could be merged
at least it should be simple to convert to an outline

2023-09-05 17:59 UTC, KTibow commented
I don't think you understand what I'm saying.
As of now, this PR will change the Odido logo to the T-Mobile logo. That's a problem. The PR needs to be updated to have a new drawable for Odido, and to make the Odido app use that drawable instead of the T-Mobile drawable.

2023-09-05 18:03 UTC, x9136 commented
> this PR will change the Odido logo to the T-Mobile logo.

`com.tmobile.pr.mytmobile` isn't dutch app.

2023-09-05 18:05 UTC, KTibow commented
Oh wait I confused the links
In that case I think this PR is good to merge as is

2023-09-10 19:45 UTC, Chefski approved these changes

2023-09-10 19:45 UTC, merged