Change tictok to tiktok, optimization icons
LawnchairLauncher/lawnicons pull request #1398
Opened 2023-08-16 02:05 UTC by KarlRaphel

## Description

Change tictok to tiktok, optimization icons in https://github.com/LawnchairLauncher/lawnicons/pull/1378/

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information

### Icons linked
* Tiktok (linked `com.ss.android.ugc.aweme/com.ss.android.ugc.aweme.splash.SplashActivity` to `@Tiktok`)

### Icons updated

* All icons in https://github.com/LawnchairLauncher/lawnicons/pull/1378/

2023-08-16 02:14 UTC, KTibow commented
fyi if you have node installed, you can run `npx svgo -f svgs -o svgs` to run the real optimization
not that it matters at the end of the day where extra stuff is removed while converting to a drawable though - this pr looks fine as is

2023-08-16 02:18 UTC, KarlRaphel commented
Thank you, I will try it next time

2023-08-17 02:02 UTC, KarlRaphel commented
# Icons linked
* Gallery (linked `com.dot.gallery` to `@gallery`)

2023-08-17 04:31 UTC, KarlRaphel commented
## Icons linked
* StatusLyricExt (linked `io.baolong24.statuslyricext` to `@yandex_music`)

## Icons added
* Wandoujia (`com.wandoujia.phoenix2/com.pp.assistant.activity.PPMainActivity`)

2023-08-19 10:22 UTC, flame-0 commented
Is this intended, `alook_browser.svg`?
![image](https://github.com/LawnchairLauncher/lawnicons/assets/40175769/5b3671d8-8a9c-4dea-a7cf-ca74dabe54d2)

2023-08-20 02:05 UTC, KTibow commented
it's still slightly off
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/ac199fc5-f71f-444b-9da1-1150b34d80a2)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/1ffff8b0-bbdb-47d7-8c38-365d9e3c91ca) ![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/8de548a2-fbab-44ba-8c24-d747b4e98353)

2023-09-12 08:32 UTC, x9136 requested changes
Hi, thanks for the icons, I've looked at them all and posted my comments.

I think @Chefski didn't have a chance to check everything carefully, or he decided to accept as is out of principle that an icon with flaws is better than when there is no icon.

In general, I was not very picky, but I noted the main points, including: wrong dimensions, wrong positioning and visual defects.

2023-09-12 08:32 UTC, x9136 commented on svgs/youku.svg
<img width="480" alt="Screenshot 2023-09-12 at 11 21 59" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/f876dee3-b2ad-482a-9d8e-64629e3e552a">

Could you connect the points on the left and increase the length on the right to correct the defects?

2023-10-28 01:14 UTC, closed without merging