Add Squawker
LawnchairLauncher/lawnicons pull request #1399
Opened 2023-08-16 11:33 UTC by thismoon

## Description

Added an icon for Squawker

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information
### Icons added
* Squawker (`org.ca.squawker/org.ca.squawker.MainActivity`)

2023-09-10 05:55 UTC, x9136 requested changes
Please fix the bird's eye and resolve conflicts.

2023-09-10 05:55 UTC, x9136 commented on svgs/squawker.svg
The eye has a fill, but you need a stroke. You can use a 6x6px circle with a stroke thickness of 6px. I would probably bring the height of the shape to 148px (currently 146.29px).

2023-09-11 14:43 UTC, thismoon commented on svgs/squawker.svg
> You can use a 6x6px circle with a stroke thickness of 6px

3x3px circle would work since the program i use have strokes in the center only and making a 6x6px one will leave space inside

> bring the height of the shape to 148px (currently 146.29px).

are you considering the stroke as a part of the shape? inkscape (and the contributing guide) does

![inkscape](https://github.com/LawnchairLauncher/lawnicons/assets/107642606/d451d31f-c133-44dc-a30d-bad941e56930)
![guide](https://github.com/LawnchairLauncher/lawnicons/assets/107642606/de6c8291-f945-4673-803e-a3128a31baaf)

i could find that number (146) when using figma (which doesn't add the stroke to the height)

![figma](https://github.com/LawnchairLauncher/lawnicons/assets/107642606/f5c53aaa-fdb6-4cda-b93e-e4aa5824f2be)

I made some changes, is [this](https://cdn.discordapp.com/attachments/842838544275734578/1150792660035059823/squawker.svg) good?

2023-09-11 16:15 UTC, x9136 commented on svgs/squawker.svg
> are you considering the stroke as a part of the shape?

If you say 148px, that means 160-12px, where 12px is the thickness of the stroke. So 148px excluding the stroke, and 160px including the stroke. Maybe I'm confusing you. In Figma, you can check the dimensions in both cases.

> I made some changes, is [this](https://cdn.discordapp.com/attachments/842838544275734578/1150792660035059823/squawker.svg) good?

Not pixel-perfect, but within the margin of error to accept the PR. The eye is ok now.
<img width="511" alt="Screenshot 2023-09-11 at 19 12 31" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/63b1fc8d-7572-4af2-873b-3b35c5208ac6">

2023-09-11 18:15 UTC, closed without merging