2 icons
LawnchairLauncher/lawnicons pull request #1400
Opened 2023-08-16 22:54 UTC by KTibow

## Description

Adds 2 icons.
Info below.
Hopefully I didn't mess anything up - I'm running the build scripts right now to test it out. Note that icontool.py ended up reordering the icons while I used it to add them.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

## Icons addition information
### Icons added
* Likewise (`com.Likewise.apps.Likewise`)
* Twilight (`com.urbandroid.lux`)

2023-09-11 11:43 UTC, x9136 requested changes

2023-09-11 11:43 UTC, x9136 commented on svgs/google_home.svg
<img width="408" alt="Screenshot 2023-09-11 at 14 16 43" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/7c64268b-0e7b-4b68-9c5b-bd5cddadd083">

A little short in height (158.12px) to 160px. Also, don't forget to round off the corners of the bottom of the small house by 6px.

2023-09-11 11:43 UTC, x9136 commented on svgs/kumo_cloud.svg
<img width="358" alt="Screenshot 2023-09-11 at 14 22 03" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/f6e8b42b-00de-48c0-ae6e-5263e6b8205d">

It's worth rounding that corner by 6px.

2023-09-11 11:43 UTC, x9136 commented on svgs/tuya.svg
Optional: use a 14px stroke on the T and move the icon slightly to the left so that it is balanced horizontally, rather than pressed to the right edge.

2023-09-11 11:43 UTC, x9136 commented on svgs/twilight.svg
The icon flies to the top edge. It will be more balanced if you move it 6-8px lower.

2023-09-11 11:43 UTC, x9136 commented on svgs/yolink.svg
The width is slightly less than 160px (159.97px). Don't forget to round the bottom by 6px.

If interested, I'd make it a bit stricter.
<img width="237" alt="Screenshot 2023-09-11 at 14 41 57" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/fe25fa0a-d422-4be9-a2bf-209f20936f24">

2023-09-11 22:11 UTC, KTibow commented on svgs/kumo_cloud.svg
i disagree, the outside is rounded already (from stroke-linejoin) which matches the original icon and guidelines

2023-09-11 22:11 UTC, KTibow commented on svgs/google_home.svg
the only change i made was moving it upwards to be centered, so this doesn't matter. did you look at the diff?

2023-09-11 22:13 UTC, KTibow commented on svgs/yolink.svg
> The width is slightly less than 160px (159.97px)

according to figma?

> Don't forget to round the bottom by 6px. If interested, I'd make it a bit stricter.

okay, i'll update it so it uses two strokes for the Y instead of one and is more rounded at the bottom soon.

2023-09-11 22:14 UTC, KTibow commented on svgs/tuya.svg
given that the `t` is the main element, it makes sense to have it closer to the center instead of considering the whole thing. this is how the official logo does it.

2023-09-11 22:16 UTC, KTibow commented on svgs/twilight.svg
i'm not planning to move it much further down as it strays from how the original icon and real sunsets look. i may move it a _tiny_ bit down in my next revision.

2023-09-12 02:53 UTC, x9136 commented on svgs/google_home.svg
> did you look at the diff?

I look at everything quite carefully. It has gotten better, but there are details that have been left out.

> so this doesn't matter.

If you don't have time to make changes, that's ok. I'm just talking about what needs to be done to make the icon look more in line with the overall style.

For example, one of the common features of icons is 6px rounding. Icons that don't have that are out of style. If you're wondering where that 6px came from — it came from [the guidelines ](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#foundation)and it's always been there.

2023-09-12 02:57 UTC, x9136 commented on svgs/kumo_cloud.svg
> which matches the original icon and guidelines

Unfortunately, this is not in line with the guidelines. According to the guideline, 90 degree corners should be rounded by 6px. [You can see for yourself.](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#foundation)

2023-09-12 02:59 UTC, x9136 commented on svgs/tuya.svg
No problem. The icon will be a bit out of the general positioning, but I think it's ok at this stage.

2023-09-12 03:01 UTC, KTibow commented on svgs/google_home.svg
I'm not trying to perfect the icon lol
My only goal was to move the icon up to be centered

2023-09-12 03:03 UTC, KTibow commented on svgs/kumo_cloud.svg
okay - i looked at the original icon and now I'm confused by how they managed to have such extreme rounding on the outside but the inside is a sharp corner. how did that happen?

2023-09-12 03:03 UTC, x9136 commented on svgs/twilight.svg
> the original icon

In the original icon, the compositional center is perfectly chosen. It's slightly above center, so it looks natural. How it will be here is up to you.

2023-09-12 03:06 UTC, x9136 commented on svgs/yolink.svg
> according to figma?

Yes. It doesn't really matter because the margin of error is small. It may be important only if you are in principle to do pixel-perfect.

2023-09-12 03:11 UTC, x9136 commented on svgs/google_home.svg
> All I did was take an existing icon and move it up by a couple pixels

I understand that, decide for yourself.

2023-09-12 03:15 UTC, x9136 commented on svgs/kumo_cloud.svg
> how did that happen?

Speaking of strokes, it's set up that way because you can't control internal rounding. If we talk about filling, you can use Boolean operations for that.

2023-09-12 14:30 UTC, x9136 commented on svgs/yolink.svg
The last version was neater because there were no defects and there was enough air around the "Y". It was enough to round the corners at the bottom by 6px.

Anyway, if you want to keep the current version, at least make sure the "Y" doesn't go outside the house.
<img width="343" alt="Screenshot 2023-09-12 at 17 29 38" src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/fd930016-a810-4dfc-851c-252fd310f19f">

2023-09-13 02:31 UTC, merged