remove duplicates, merge testbook
LawnchairLauncher/lawnicons pull request #1454
Opened 2023-09-13 13:52 UTC by KTibow

2023-09-13 19:08 UTC, Chefski requested changes

2023-09-13 19:08 UTC, Chefski commented on svgs/testbook.svg
Hey! Could you fit the icon to the 144x144px content area? (Due to its square shape)

2023-09-13 21:57 UTC, KTibow commented on svgs/testbook.svg
I didn't make the icon...
I can try though

2023-09-14 22:24 UTC, Chefski approved these changes

2023-09-14 22:24 UTC, Chefski commented
Thanks

2023-09-14 22:24 UTC, merged