Quality update 3
LawnchairLauncher/lawnicons pull request #1472
Opened 2023-09-25 16:04 UTC by x9136

I round corners, simplify shapes, correct sizes, and change the fill to stroke.

2023-09-25 23:09 UTC, KTibow commented
fyi while `among_us` doesn't need any redrawing it could easily be converted to a stroke

2023-09-26 03:51 UTC, x9136 commented
> fyi while `among_us` doesn't need any redrawing it could easily be converted to a stroke

This icon is a low priority. If I wanted to make all icons fit the guides, I'd have to redo 3 times as many icons as I plan to.

2023-09-26 13:12 UTC, KTibow commented
okay, in that case I might redraw some icons myself

2023-09-26 14:37 UTC, Pukimaa requested changes

2023-09-26 14:37 UTC, Pukimaa commented on svgs/fix_price.svg
> +<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path opacity=".9" d="M107 22v34m0 30v34m44-70V28a6 6 0 0 0-6-6H49a6 6 0 0 0-6 6v136a6 6 0 0 0 6 6h2
Same reason here. Looks too generic without the key aspects of the original icon.

2023-09-26 14:37 UTC, Pukimaa commented on svgs/intesa_sanpaolo.svg
> +<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 58h148M22 98v36m58-36v36m58-36v36M54 98v36m58-36v36m58-36v36M54 98a16 16 0 1 0-32 0m90
The original icon features the box around the main part. So I think it should be kept.

2023-09-29 10:14 UTC, Chefski approved these changes

2023-09-29 10:14 UTC, merged