Quality update 5
LawnchairLauncher/lawnicons pull request #1495
Opened 2023-10-09 22:05 UTC by x9136

I round corners, simplify shapes, correct sizes, and change the fill to stroke.

2023-10-14 13:20 UTC, Chefski requested changes

2023-10-14 13:20 UTC, Chefski commented on svgs/instaddr.svg
Triangle is missing on the bottom left arrow and also the icon seems to have some kind of transparency? Its 100% but the colours are slightly transparent???
<img width="862" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/4d6ece78-891e-4360-8c13-51aba4d143c9">

2023-10-14 13:34 UTC, x9136 commented on svgs/instaddr.svg
> Triangle is missing on the bottom left arrow

![Screenshot 2023-10-14 at 16 29 09](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/72aadbfb-7a07-4d93-b133-08c5943030ea)
It's on purpose. You think it's better with the arrow?


> Its 100% but the colours are slightly transparent???

![Screenshot 2023-10-14 at 16 33 25](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/75ffda64-0800-42e4-9620-a4a5b3a7a044)
In Figma, both the layer and the color have opacity.

2023-10-14 14:11 UTC, KTibow commented on svgs/instaddr.svg
I would personally keep the arrow but make it so the arc is smaller so it doesn't overlap with the piece of mail

2023-10-14 14:17 UTC, x9136 commented on svgs/instaddr.svg
>so it doesn't overlap with the piece of mail

I tried it this way first, but there's not enough space: either the arrow would start to merge with the line and turn into a blot, or the distance between the arrow and the letter would be too small.

2023-10-14 14:18 UTC, KTibow commented on svgs/instaddr.svg
I mean you would adjust the line and curve so that there's enough space (move the curve start to the left, and reduce the radius)

2023-10-14 14:49 UTC, Chefski commented on svgs/instaddr.svg
Oh I just realised the pass through was at 90%. It's fine now.

And about the arrow, I think it should stay. Looks incomplete without it but maybe needs to be adjusted some way.

2023-10-14 14:53 UTC, x9136 commented on svgs/instaddr.svg
> you would adjust the line and curve so that there's enough space

There will be an imbalance with the right line, so it will have to be changed. This change will break the connection with the top line. The original idea is to have these lines form an overall shape. I don't want to give up this idea in my variant, because it allows to make the icon neater.

![Screenshot 2023-10-14 at 17 45 41](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/081b46b0-15cb-42f1-92ec-81cdeba2a27b)

2023-10-14 19:37 UTC, RaduBratan commented on svgs/purple_tv.svg
Here's my two cents about this icon. [The original one](https://github.com/NyanArchive/OrangeTV/blob/main/app/models/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png) looks 3D, and the Lawnicons version is also meant to evoke a similar feeling (it no longer looks 100% 3D because it's simplified). This is why I recommend the internal square should remain slightly offset to the top right. Your current implementation looks 2D-ified.

2023-10-14 19:59 UTC, RaduBratan commented on svgs/too_good_to_go.svg
The new icon seems to have two endpoints that are misaligned, which create a weird spike. I checked and they are 0.001px apart on the Y axis (86.846px and 86.847px).

2023-10-14 20:02 UTC, x9136 commented on svgs/purple_tv.svg
![Screenshot 2023-10-14 at 23 01 40](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/013f9f85-4e0a-4e83-9d2a-1f404bc96569)
Perhaps one of these versions will be even better than your suggestion?

2023-10-14 20:09 UTC, x9136 commented on svgs/too_good_to_go.svg
I'm not sure what you're talking about. Could you be more specific, show a screenshot of what looks weird?

Also, I can't take into account 3 digits after the decimal point in Figma, because it rounds to two.

2023-10-14 20:42 UTC, RaduBratan commented on svgs/too_good_to_go.svg
Here's what I mean by "spike":
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/0846aec6-3c3e-4bb8-806b-f51a68c60ac7)

Didn't know Figma only allows 2 digits. I'll fit it myself in Illustrator, then. I noticed the same thing happened in other icons as well (such as the Play Store app).

I know it's a small difference in positions, but this is how it looks on my end:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/7a30c01c-04b3-445f-8223-0e5ebb2df5a6)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/d205bf45-79e5-402f-b22f-3f70e6c1ff6a)

2023-10-14 20:48 UTC, RaduBratan commented on svgs/purple_tv.svg
Wow, the third one looks really nice! Even closer to the original, best version imho.

2023-10-14 20:53 UTC, x9136 commented on svgs/too_good_to_go.svg
@RaduBratan I see.

![too_good_to_go](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/001fe222-5074-4619-a890-53977e5ca23a)
I manually set a slightly different value. If you don't have a spike anymore, then I'll upload that icon. If there is, then I'll delete my variant.

2023-10-14 20:57 UTC, RaduBratan commented on svgs/too_good_to_go.svg
Yep, you fixed it, now it's a single anchor point.

2023-10-14 21:12 UTC, RaduBratan commented on svgs/instaddr.svg
A middle ground could be achieved by removing the external strokes of the top and right arrow heads and adding an internal stroke for the left one, but to be honest, the original version looks just fine.

2023-10-15 23:07 UTC, Chefski commented on svgs/instaddr.svg
Would the arrow going along the triangle not look better? Instead of it going inwards

2023-10-16 04:25 UTC, x9136 commented on svgs/instaddr.svg
> Would the arrow going along the triangle not look better?

I have a feeling that either I answered above or I didn't quite understand how you imagine it. So now I'm interested in having you try it yourself and assess the situation. If you have the time, copy [a version](https://www.figma.com/file/RAXrCA2wQKRANzMGEEfJFr/Untitled?type=design&node-id=1%3A12&mode=design&t=zzxpb7Qq352Y5lQx-1) that's easier to edit.

2023-10-16 13:29 UTC, KTibow commented on svgs/instaddr.svg
Something kinda like this
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/a913e0a3-7ae9-470c-95c4-3d80a58665b3)
Except it goes out of bounds then

2023-10-16 14:09 UTC, x9136 commented on svgs/instaddr.svg
> Except it goes out of bounds then

Well, and that means the icon doesn't fit. Furthermore, the arrow turned out quite different from the others and on a small resolution on will be more like a dot.

I just wanted Chefski to try to make such an idea himself, so that he could see from his own experience if it is possible to do it properly.

2023-10-16 14:17 UTC, x9136 commented on svgs/instaddr.svg
Anyway, we've already spent too much time on this, so I suggest we either keep the current version — it's probably better than what's in the library. Or I'll remove my suggestion and it will be easier to move on.

2023-10-16 18:01 UTC, RaduBratan commented on svgs/instaddr.svg
I have 3 things to mention about this icon:
1. on my end, in Adobe Illustrator, the icon, and every one of its components, appear to be 0.001px to wide, too tall, or too much offset to the left/right (e.g. the width of the icon isn't 148px, it's 148.001 or .002; the Y coordinate of one of the lines isn't 18px, it's 18.001, etc) (see first image)
2. the envelope is still set to 90% opacity (I remember it was mentioned before, but I don't think it has been resolved; see first and second image)
3. what if we do something like in the third image? could it serve as a middle ground to the arrows problem?
<br/>

[first image]
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/e997c0b5-87f0-47b5-b4dc-d04c56f98d9e)
[second image]
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/ac8e16b5-e61e-40b7-8fbc-b72ab8bf5c96)
[third image]
![image](https://github.com/LawnchairLauncher/lawnicons/assets/54798977/65e63b84-1344-4ce9-8557-ebe876269025)

2023-10-16 18:34 UTC, x9136 commented on svgs/instaddr.svg
1. I think it's such an inconsequential difference that without numbers, no one in the world will say there is one.
2. Pay attention to make sure that the file list includes all changes:
![Screenshot 2023-10-16 at 21 29 47](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/e03c6493-e3b6-4f9b-a50e-a01072c88289)
3. It seems to me that if we vote, your version wins. If you're willing to offer it in your PR, I'll remove my version.

2023-10-16 19:23 UTC, RaduBratan commented on svgs/instaddr.svg
Sorry for 2 then, didn't realize 😅

2023-10-17 08:03 UTC, closed without merging