added an icon and modified icontool.py
LawnchairLauncher/lawnicons pull request #1496
Opened 2023-10-10 15:00 UTC by Steven52065

# Description
I attempted to add an icon, but encountered an issue while using icontool.py, so I tried to make modifications to it. I'm new to git and Python, so if there's anything I did wrong, I would appreciate some guidance. I will include the error message from icontool.py below (it works fine after the modifications).

```
PS E:\git\lawnicons> python .\icontool.py add "E:\lawniconss\u_jing.svg" com.midea.vm.washer/com.midea.vm.washer.ui.activity.SplashActivity u_jing
Traceback (most recent call last):
  File "E:\git\lawnicons\icontool.py", line 332, in <module>
    add_parser(args)
  File "E:\git\lawnicons\icontool.py", line 260, in add_parser
    parse_component(False, args.svg, args.component, args.name, args.message)
  File "E:\git\lawnicons\icontool.py", line 183, in parse_component
    xml_file = open(APPFILTER_PATH, "r").read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 519618: illegal multibyte sequence
```

## Icons addition information

### Icons added
* com.midea.vm.washer

### Icons linked
* U净 (linked `com.midea.vm.washer` to `@drawable/u_jing`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-10-11 11:04 UTC, Chefski requested changes

2023-10-11 11:04 UTC, Chefski commented on svgs/u_jing.svg
Could you change the icon to fit the 160x160px content area Could you also change the circle to be a circle shape instead of a line?

2023-10-11 13:51 UTC, Steven52065 commented on svgs/u_jing.svg
I would change his size, but the left side of the original icon is a straight line, not a curve, so I feel it would be better to keep the character of the original icon. (Of course I'll change it to a curve if that's what you want)

2023-10-11 13:54 UTC, KTibow commented on svgs/u_jing.svg
They mean this
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/b1b42ef3-9ee7-4f3c-9467-41d5cba68ea0)
(It's not a real circle)

2023-10-11 13:54 UTC, KTibow commented on svgs/u_jing.svg
Also you could improve this join
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/5aea8e3e-1b82-499a-959e-c072dc720dab)

2023-10-11 13:54 UTC, KTibow commented on svgs/u_jing.svg
Also resizing is a non-negotiable

2023-10-12 10:17 UTC, Chefski requested changes

2023-10-12 10:17 UTC, Chefski commented on svgs/u_jing.svg
The new icon seems to have some problems as when I import into Figma the circle disappears. 

Please use the ellipse to make a circle (or whatever the tool is called in Inkscape
<img width="169" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/5c651aa8-b657-4698-9791-9b5f1f53dff0">

The shape of the U was better before. I'd just like the bend to have a better curve
<img width="380" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/8057f436-fb9d-40ed-be1c-fe935aa473ca">

Please also ensure the the icon fits the 160x160px border (vertically, horizontally or both depending on the icon) and the stroke is one of the standard stroke widths (14px in this case as the icon is minimal)
<img width="500" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/5f0616f8-3e61-4439-9cc0-dfa9f2457538">
_(I just quickly scaled the icon for an example)_

<img width="204" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/62fd5fb8-852e-4640-830d-096760354827">

2023-10-12 13:02 UTC, Steven52065 commented on svgs/u_jing.svg
I switched to the software Figma and tried to draw strictly at 160px, but I feel like that's a little too big on the phone look... It feels like the previous size would have been a bit more harmonized (the fourth one is this icon I drew)
![1697115662873](https://github.com/LawnchairLauncher/lawnicons/assets/36119581/b6d508ed-bf67-4a4a-bea4-588969a0b38b)

2023-10-12 15:18 UTC, Chefski commented on svgs/u_jing.svg
If you'd like to modify the icon slightly to look better feel free, but all icons in Lawnicons are 160x160 unless they have a square shape which makes them 144x144.

2023-10-12 15:22 UTC, Chefski requested changes

2023-10-12 15:22 UTC, Chefski commented on svgs/u_jing.svg
If you could scale the icon to also reach the bottom guide line for 160x160. Please also change the stroke to 14px as the icon is minimal. This might make the icon look less empty. Try use strokes too instead of fill (for easy changes if needed in the future)

2023-10-13 14:09 UTC, Steven52065 commented on svgs/u_jing.svg
I changed the stroke to 14px and changed the fill to a stroke (I hope I didn't misunderstand QAQ)
Is there anything else that needs to be changed？

2023-10-14 13:08 UTC, Chefski approved these changes

2023-10-15 03:20 UTC, SuperDragonXD approved these changes

2023-10-17 07:34 UTC, x9136 requested changes

2023-10-17 07:34 UTC, x9136 commented on svgs/u_jing.svg
![Screenshot 2023-10-17 at 10 27 59](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/5ebf5b57-58ad-4f23-99d0-f49f7f8146b6)
@Steven52065 Hey! The only thing left to do is to enlarge the icon to 160×160px. In fact, it's missing 1px on the left and bottom.

It's strange that this PR is hanging for so long, because icontool.py should be working.

2023-10-17 07:47 UTC, x9136 commented on svgs/u_jing.svg
I did.

2023-10-17 07:50 UTC, merged

2023-10-17 09:00 UTC, x9136 commented on svgs/u_jing.svg
@Steven52065 No problem. Thanks for fixing the bug in icontool.py. That helped me.