Added 7 new icons, refined 1 existing icon
LawnchairLauncher/lawnicons pull request #1498
Opened 2023-10-12 04:28 UTC by yeyebbc

# Description

Added 7 new icons, refined 1 existing icon to better match lawnicons style guidelines.

## Icons addition information

### Icons added
* Audio Recorder (`com.dimowner.audiorecorder`)
* B612 (`com.linecorp.b612.android`)
* Clash for Android (`com.github.kr328.clash.foss`)
* TODAI Easy Japanese (`mobi.eup.jpnews`)
* FFShare (`com.caydey.ffshare`)
* Foodie (`com.linecorp.foodcam.android`)
* HUJI Cam (`kr.co.manhole.hujicam`)

### Icons updated
* KFC (`com.yek.android.kfc.activitys`)
Refined KFC icon to better match lawnicons style guidelines, also made it pixel perfect.

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-10-12 07:39 UTC, x9136 requested changes
Thank you for your careful work. If it's not too much trouble, please correct a couple of things.

2023-10-12 07:39 UTC, x9136 commented on svgs/clash_for_android.svg
![Screenshot 2023-10-12 at 10 22 06](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/0be293a8-c23a-4d0e-b5ec-1d8303b9e8dc)
The size turned out a little smaller than required by the guides. Also, if it's not much trouble, try making the eyes using a stroke.

2023-10-12 07:39 UTC, x9136 commented on svgs/audio_recorder.svg
![Screenshot 2023-10-12 at 10 28 52](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/2027084c-df80-435c-ba4a-5509c601c979)
I suggest rounding those corners [by 6px](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#foundation) to make the icon fit the overall style even better.

2023-10-12 07:39 UTC, x9136 commented on svgs/todai_easy_japanese.svg
![Screenshot 2023-10-12 at 10 34 17](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d75d4d73-d66a-4554-b464-2790cde8bc4c)
Quality-wise it's good, technically the icon should be 1px wider.

2023-10-12 08:13 UTC, yeyebbc commented on svgs/clash_for_android.svg
Thanks for the quick reply. The size is intended. For if it fully filled the 160px guide, the cat will be visually biased towards the right because of its tail. But I will try again and see if it can meet both criteria. 

Yes the eyes. I saw same issue in another PR but I forgot. Will do.

2023-10-13 09:28 UTC, yeyebbc commented
Donno if the modified cat eyes of clash_for_android.svg is correct? No idea stroke at this size can render correctly or not.

2023-10-13 09:34 UTC, x9136 commented on svgs/clash_for_android.svg
![Screenshot 2023-10-13 at 12 29 18](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d256d524-e7f6-4188-a893-b302dd33643d)
The eyes have a too thin stroke (actually 2px, which is 3 times less than the minimum). I suggest making the eyes 6×6px with 6px stroke or 8×8px with 8px stroke. It will turn out roughly as in the screenshot.

![Screenshot 2023-10-13 at 12 32 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/83928fdc-017a-4141-bdde-2942045baebc)
The whiskers on the right are out of the cat's boundaries, worth correcting.

2023-10-13 09:35 UTC, x9136 requested changes

2023-10-13 09:35 UTC, x9136 commented on svgs/clash_for_android.svg
![Screenshot 2023-10-13 at 12 29 18](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d256d524-e7f6-4188-a893-b302dd33643d)
The eyes have a too thin stroke (actually 2px, which is 3 times less than the minimum). I suggest making the eyes 6×6px with 6px stroke or 8×8px with 8px stroke. It will turn out roughly as in the screenshot.

![Screenshot 2023-10-13 at 12 32 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/83928fdc-017a-4141-bdde-2942045baebc)
The whiskers on the right are out of the cat's boundaries, worth correcting.

2023-10-13 09:39 UTC, x9136 commented
> No idea stroke at this size can render correctly or not.

In such cases, I use a stroke equal to or larger than the side of the ellipse. If you make it smaller, the stroke cuts itself off.

2023-10-13 10:08 UTC, yeyebbc commented
Yeah, thought as much, it became 2px when exported. Lemme fix it in a sec, and the whiskers.

2023-10-13 10:12 UTC, yeyebbc commented
Should be OK now.

2023-10-13 10:16 UTC, merged