Fix 4 icons, add and link 13 new icons.
LawnchairLauncher/lawnicons pull request #1525
Opened 2023-10-24 18:21 UTC by hefaestos

# Description
Replaced fill with stroke in Google Translate, Google Wallet, and AntennaPod icon. Fixed stroke width in Too Good To Go icon (was 10px, but looked noticeably thin and is a simple icon design; changed to 12px).

Added and linked: Euclidea (requested), Grindr (requested), iNaturalist, Insight Timer, Lex, OfferUp, Oscope, Patchwork, PlantNet, Scruff, Soundhound, Tuner - Pitched, and Zero.

## Icons addition information

### Icons added
* Euclidea (`com.hil_hk.euclidea/com.hil_hk.euclidea.activities.MainActivity`) - added from icon request form
* Grindr (`com.grindrapp.android/com.grindrapp.android.HomeActivityOriginal`) - added from icon request form
* iNaturalist (`org.inaturalist.android/org.inaturalist.android.ObservationListActivity.inaturalist`)
* Insight Timer (`com.spotlightsix.zentimerlite2/co.insight.timer2.LauncherActivity`)
* Lex (`us.personals/us.personals.MainActivity`)
* OfferUp (`com.offerup/com.offerup.MainActivity`)
* Oscope (`org.sbaudio.oscope/org.sbaudio.oscope.MainActivity`)
* Patchwork (`com.digidiced.pxwrelease/com.unity3d.player.UnityPlayerActivity`)
* PlantNet (`org.plantnet/org.plantnet.MainActivity`)
* Scruff (`com.appspot.scruffapp/com.appspot.scruffapp.features.splash.views.SplashActivity`)
* Soundhound (`com.melodis.midomiMusicIdentifier.freemium/com.soundhound.android.appcommon.activity.SplashScreenActivity`)
* Tuner - Pitched (`com.stonekick.tuner/com.stonekick.tuner.ui.TunerActivity tuner_pitched`)
* Zero (`com.zerofasting.zero/com.zerofasting.zero.MainActivity`)

### Icons updated
* AntennaPod
* Google Translate
* Google Wallet
* Too Good To Go

## Contributor's checklist
- [x ] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x ] I have ensured that Lawnicons builds correctly
- [x ] I am willing to make changes to my icons if someone suggests changes

2023-10-24 19:32 UTC, x9136 requested changes

2023-10-24 19:32 UTC, x9136 commented on svgs/too_good_to_go.svg
I [purposefully used a line thickness of 10px](https://github.com/LawnchairLauncher/lawnicons/pull/1513/files?short_path=9e11fc3#diff-9e11fc31d8e97aeae718a2f602682bbdebc75bb4fd313822bf3996b8a4303e02) rather than 12px, because at 12px where the lines intersect, the icon appeared too thick.

You said the icon looks noticeably thin at a stroke thickness of 10px. So the question is: does the icon look too thin on a computer screen or on a phone screen among other icons? If on a computer screen, how does it look to you on a phone screen?

2023-10-24 19:32 UTC, x9136 commented on svgs/tuner_pitched.svg
It's worth rounding the corners on the bottom left just as it turned out on the top right.

![Screenshot 2023-10-24 at 22 24 34](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d467f7dd-ca2f-4034-ac60-9b06e0098120)
If you want to simplify the icon, you can make it like this.

2023-10-24 19:32 UTC, x9136 commented on svgs/zero.svg
![Screenshot 2023-10-24 at 22 30 06](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/52de4c2a-f9d8-4126-bc8e-88995bfc1c6b)
It's worth carefully cropping the cloud as in the original.

2023-10-24 19:42 UTC, hefaestos commented on svgs/euclidea.svg
Between the perspective, the sharp corners on the constructed E, and the compass, the resulting icon is either too busy (violating the design guidelines), or totally loses the "geometrical construction" impact. The E I used is from the font used within the app.

![euclidea](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/f5cf0238-95fb-48d8-afb8-494dde59d2f9)

2023-10-24 19:51 UTC, hefaestos commented on svgs/zero.svg
The original actually does have the cloud extending beyond the sun, but uses a pretty thin transparency (see attached image, emphasized from the original). I chose to extend the cloud beyond to more clearly communicate the objects depicted (cloud in front of sun), which is less clear without the color and transparency in the original.

![zero1a](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/ebc6b001-d929-4b39-b86c-12f1ed2af3ff)

2023-10-24 19:57 UTC, x9136 commented on svgs/euclidea.svg
![Screenshot 2023-10-24 at 22 55 04](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/35104c59-d92c-4177-9240-857859e57989)
I imagined it something like this. Since your variant will be familiar to the users of the app, it should be ok.

2023-10-24 20:02 UTC, hefaestos commented on svgs/too_good_to_go.svg
It looks noticeably thin to me on my phone screen... 

10 px
![Screenshot_20231024-125844](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/a682cc8c-9a9b-473b-9f28-71177e5a1ffb)

12px
![Screenshot_20231024-104655~2](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/21f0c4b5-98fd-44f7-a6bc-fb12ec53f540)

2023-10-24 20:09 UTC, x9136 commented on svgs/zero.svg
![Screenshot 2023-10-24 at 23 05 08](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/faf8a05c-56cf-4423-a7fd-167dff30cdae)
Due to the fact that the cloud looks out a little bit, a compromise between the extremes turned out. On the phone screen, the edge of the cloud will almost merge with the edge of the circle, it will look sloppy. There are 2 options not to compromise — either as I have already suggested, or to reduce the circle so that the cloud looks out noticeably.

In any case, the icon corresponds to the guides, so it can be accepted without changes. I make suggestions in case you are interested in working on quality.

2023-10-24 20:26 UTC, x9136 commented on svgs/too_good_to_go.svg
> 10 px

In this screenshot, the stroke width is 10px. Perhaps you had an old version.

![Screenshot 2023-10-24 at 23 25 56](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d1f7c90b-6fa4-474c-8b53-812a92e53a66)
The difference between 10px and 12px is not that significant and looks like this.

2023-10-24 20:29 UTC, x9136 commented on svgs/too_good_to_go.svg
As I see, in this case the difference between 10px and 12px is insignificant. Therefore, if you leave the icon, I will accept it.

2023-10-24 20:46 UTC, hefaestos commented on svgs/zero.svg
Appreciate the guidance. I do like your 2nd version better than my original - I will make those changes.

2023-10-24 20:50 UTC, hefaestos commented on svgs/lex.svg
Just want to be clear... this looks centered to me (minus some out-of-integer slop) - (192-98)/2=47.  Are you centering on the "ex" (and omitting the height of the "L")?

![2023-10-24 13_44_41-lex svg - Inkscape](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/56284294-ff26-48aa-aef6-dcc0480d04d0)

2023-10-24 20:51 UTC, hefaestos commented on svgs/insight_timer.svg
Look correct now?

![insight_timer](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/a76e5555-135f-4c69-a45f-45d34d9324bd)

2023-10-24 21:14 UTC, x9136 commented on svgs/lex.svg
There is a geometric center and there is an optical center. The difference is that our eyes are so arranged that a figure located in the geometric center will appear lower than the center. Therefore, if the goal is to make a figure centered, it should look centered. Designers compensate for offsets when the figure has jagged edges and there is space.

![image](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/51b9b3c6-b73f-47bc-b537-1f3e51a7dd08)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/8333bdc3-daba-4f51-af38-d9dcbe111e0a)

2023-10-24 21:26 UTC, x9136 commented on svgs/insight_timer.svg
Looks fine.

2023-10-24 21:28 UTC, x9136 commented on svgs/lex.svg
In my opinion the "L" affects perception, which is why I suggested compensating for it.

2023-10-24 21:59 UTC, hefaestos commented on svgs/lex.svg
I'm familiar with the concept, but I feel like previous instances where I've offset to account for visual center, you weren't a fan, ha. Look acceptable?

![lex](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/6c7fd9c9-58ff-40e2-80e7-6073d58a624b)

2023-10-24 22:00 UTC, hefaestos commented on svgs/tuner_pitched.svg
Like this?

![tuner_pitched](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/9dfd1ea2-e605-42c2-acbf-bafc8fb77275)

2023-10-24 22:11 UTC, x9136 commented on svgs/lex.svg
Yes, looks legit.

2023-10-24 22:16 UTC, x9136 commented on svgs/tuner_pitched.svg
> Like this?

This version is ok too. The thing was that in the first version you rounded the ends only in the left part, but in the right part you didn't.

2023-10-25 22:25 UTC, hefaestos commented on svgs/tuner_pitched.svg
Ah, I see what you were talking about now... I somehow managed to upload an earlier version, so my "current" version had that fixed already. apologies!

2023-10-25 22:29 UTC, hefaestos commented on svgs/too_good_to_go.svg
You are correct - I must have had an older version when I took the screenshots, and didn't notice the incremental fix when putting together the rest of my update. 10px is sufficient to correct the visual impact, so I'm happy to revert.

2023-10-25 22:51 UTC, x9136 approved these changes

2023-10-25 22:52 UTC, merged