add 9 icons
LawnchairLauncher/lawnicons pull request #1531
Opened 2023-10-26 16:01 UTC by piecesuger

# Description

Add icons for Live2DViewerEX, CaptiveMgr, Ruler, Spectroid, Starth Bing Wallpaper, Only One, Icon Pusher, idolmaster million live theater days, QooApp, 
## Icons addition information

### Icons added
* Live2DViewerEX (`com.pavostudio.live2dviewerex`)
* CaptiveMgr (`tech.evlsoc.captivemgr`)
* Ruler (`fr.ecp.ruler.app`)
* Spectroid (`org.intoorbit.spectrum`)
* Starth Bing Wallpaper (`me.liaoheng.wallpaper`)
* Only One (`com.onlyone.onlyonestarter`)
* Icon Pusher(`dev.southpaw.iconpusher`)
* idolmaster million live theater days (`{com.bandainamcoent.imas_millionlive_theaterdays`)
* QooApp (`com.qooapp.qoohelper`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-10-26 20:29 UTC, x9136 requested changes
Thank you for contributing!

It's good that you did everything with a stroke.

All icons have wrong dimensions. There are other flaws as well: incorrect stroke widths (e.g. 9px in the `only_one.svg`), wrong rounding of right corners (`icon_pusher.svg`, `live2dviewerex.svg`, `qooapp.svg` and `ruler.svg`). If you plan on fixing this, it's worth spending 10 minutes [on the guides](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#artboard--grid). It will help and speed up the acceptance of the pull request. 

I also want to draw your attention to visual flaws: a too bold dot on the `starth.svg` icon or a clumped "e" on the `only_one.svg` icon. The `spectroid.svg` should have a slightly thicker stroke (14px) because the icon takes up very little space. I suggest to leave it for later, it is more important to make the icons fit the guides first.

2023-10-27 04:27 UTC, piecesuger commented on app/assets/appfilter.xml
I have made some modifications. By the way what do you mean wrong dimensions here? Size of whole icon?

2023-10-27 06:15 UTC, x9136 commented on app/assets/appfilter.xml
> By the way what do you mean wrong dimensions here? Size of whole icon?

Yes, the size of the icon.
![Screenshot 2023-10-27 at 09 15 12](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/872b489a-1bdc-4e67-801a-b8b90a173956)

2023-10-27 07:19 UTC, x9136 commented on app/assets/appfilter.xml
After the fixes, the sizing problem remained. Also note that you have formatted appfilter.xml differently than on the screenshot.

2023-10-27 12:42 UTC, piecesuger commented on app/assets/appfilter.xml
OK. Already resized and formatted.

2023-10-27 13:29 UTC, x9136 requested changes
All icons need a little tweaking, but some of them can be accepted as is. I have left comments on each icon separately.

2023-10-27 13:29 UTC, x9136 commented on svgs/only_one.svg
![Screenshot 2023-10-27 at 16 08 54](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/56eb3d7a-5b21-4f8f-b3b7-f175974c3bb1)
The size is a little smaller than it needs to be.

If you want to work on quality, I suggest you make the "e" differently and raise the word a bit higher so it doesn't press down.

2023-10-27 13:29 UTC, x9136 commented on svgs/qooapp.svg
![Screenshot 2023-10-27 at 16 10 37](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9d6e7752-9866-4c9b-a0a1-494e8f6615bd)
The size is a little smaller than it needs to be. It is also worth moving the icon to the left to balance the empty space (I did it on the screenshot).

2023-10-27 13:29 UTC, x9136 commented on svgs/ruler.svg
The size is a bit wrong, but it'll do for the first time.

2023-10-27 13:29 UTC, x9136 commented on svgs/spectroid.svg
![Screenshot 2023-10-27 at 16 16 11](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/36a22bcb-4184-427e-b8c5-ce0d7322b41c)
The size is a little smaller than it needs to be, but it'll do for the first time. 

If you want to work on the quality, it is worth raising the icon a bit higher to compensate for the empty space.

2023-10-27 13:29 UTC, x9136 commented on svgs/sse.svg
![Screenshot 2023-10-27 at 16 17 58](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/ae7aee99-b299-4745-bdc8-f068cd45751c)
The size is a little smaller than it needs to be, but it'll do for the first time.

If you want to work on quality, it is worth raise the icon a little higher and avoid small spacing between strokes.

2023-10-27 13:29 UTC, x9136 commented on svgs/starth.svg
![Screenshot 2023-10-27 at 16 20 51](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/ad8c2014-5258-4708-8227-5fa212700a80)
The size is a little smaller than it needs to be, but it'll do for the first time.

If you want to work on quality, it is worth raise the icon a little higher.

2023-10-27 13:29 UTC, x9136 commented on svgs/captivemgr.svg
![Screenshot 2023-10-27 at 16 24 50](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d0f5797b-1252-4e7f-a884-77dde44c9beb)
If you need to reply in a specific thread, click here first.

2023-10-27 17:21 UTC, piecesuger commented
> All icons need a little tweaking, but some of them can be accepted as is. I have left comments on each icon separately.

Done.

2023-10-27 21:15 UTC, x9136 approved these changes

2023-10-27 21:20 UTC, merged