Add 4 new icons, add 2 regional app calls, fix 25 icons
LawnchairLauncher/lawnicons pull request #1539
Opened 2023-10-30 22:52 UTC by hefaestos

# Description

Add icons for Joann, Metro Flex, USAA, Vanguard.
Add regional calls for AliExpress, Ticketmaster.
Change fills to strokes in icons for 25 misc icons

## Icons addition information

### Icons added
* Joann (`com.fifthfinger.clients.joann/com.joann.android.MainActivity`)
* Metro Flex (`ridewithvia.metroflexseattle/via.rider.features.splash.SplashActivityKt`)
* USAA (`com.usaa.mobile.android.usaa/com.usaa.mobile.android.app.MainEntryActivity`)
* Vanguard (`com.vanguard/com.vanguard.vanguard.activity.impl.MainActivity`)

### Icons updated (change fills to strokes, minimal changes as necessary)
* Actionbound
* Adobe Scan
* Amazon Prime Video
* Blockinger
* Deepl
* Deezer
* Delta Icons
* Deviant Art
* Discord
* Dislyte
* Dominos
* Duolingo
* Files
* Firefox (base, Beta, Focus, Klar, and Nightly)
* Google Chat
* Google Docs
* Google Earth
* Google One
* Mini Metro
* Steam
* Steam Chat

### Icons linked (US regional links)
* AliExpress (linked `com.alibaba.aliexpresshd/com.aliexpress.app.FirstActivity` to `aliexpress`)
* Ticketmaster (linked `com.ticketmaster.mobile.android.na/com.ticketmaster.mobile.android.library.activity.MainActivity` to `ticketmaster`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-10-30 23:01 UTC, x9136 commented on svgs/dominos.svg
Although the old icon was made with a fill, it was more in keeping with the overall style because it took into account the requirement for rounded right angles.

2023-10-30 23:03 UTC, x9136 commented on svgs/steam.svg
I recently [redrew the Steam icons](https://github.com/LawnchairLauncher/lawnicons/pull/1524/files#diff-8cea057ad6d1773405e42dd3fcb1a50a2bf0c3193eddb86abb55a334300f4425) to better match each other and the style. If they are accepted, your options will most likely become irrelevant. Pay attention.

2023-10-30 23:31 UTC, hefaestos commented on svgs/dominos.svg
I'm a bit confused... The exterior corners are the 6px rad recommended by the guideline. The current version has 12px corner rad - is that the actual preferred dimension?

2023-10-30 23:33 UTC, hefaestos commented on svgs/steam.svg
Sorry, will remove. I did try to check the icons I touched, but I missed the open pull on these.

2023-10-30 23:34 UTC, KTibow commented on svgs/dominos.svg
> The exterior corners are the 6px rad recommended by the guideline.

looks like the guidelines have a typo. if you look at the *image*, you'll see how it's supposed to look - a full corner radius.

2023-10-30 23:37 UTC, hefaestos commented on svgs/dominos.svg
appreciate the clarification. I'll correct it and other instances in the pull request.

2023-10-30 23:40 UTC, x9136 commented on svgs/dominos.svg
![Screenshot 2023-10-31 at 02 39 00](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/043bc1cd-1ed5-4d91-8232-817348b19abd)
Yeah, I think it's 6px in the original.

2023-10-30 23:59 UTC, hefaestos commented on svgs/dominos.svg
Ok actually upon further examination... the example in the guidelines has a 6px rad on the triangle and the diamond, and a 12px rad on the square. Is that intentional/as desired?

![rad question](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/27f75958-7b77-481c-a0dc-2740a81059e6)

2023-10-31 00:05 UTC, x9136 commented on svgs/dominos.svg
@hefaestos Perhaps we are talking in different units of measurement or there are other differences in the calculations of graphic editors? To make it look like the picture, you need to set it to 6px in Figma.

![Screenshot 2023-10-31 at 03 02 16](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/c29ddabc-cd86-40c4-b34c-3fe2ed78df8f)

2023-10-31 00:07 UTC, KTibow commented on svgs/dominos.svg
Seems Figma is using the term wrong
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/7ef5d309-96bf-452b-97ea-e853bfac61e4)

2023-10-31 00:08 UTC, x9136 commented on svgs/dominos.svg
But on the other hand, I would take a picture from a guide as a visual illustration rather than an accurate description. For example, if you take the thickness of the lines, it would actually be 12px wide (6px on both sides from the center).

2023-10-31 00:19 UTC, x9136 commented on svgs/dominos.svg
> Seems Figma is using the term wrong

This is strange because if you export something for development, the radius in the code will be as specified in Figma.

2023-10-31 00:51 UTC, hefaestos commented on svgs/dominos.svg
I mean, regardless of which, the point still stands that the image used is internally inconsistent. Both visually and by the written 6px, my domino matches the diamond (pink) in the demo image. The diamond does not match the square - here are identical size boxes, rotated to match orientation.

![rad q - demo](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/9ed42138-3eb2-48c2-96ff-e0e222ab4286)

So, even besides the vocabulary question, it seems like there's an open issue in the guidelines, unless it is intended that right angles with sides at 0 and 90 deg have 12px rad, and right angles in any other orientation have 6px rad.

2023-10-31 06:30 UTC, x9136 commented on svgs/dominos.svg
I see. I tend to think that the author leaving this shape unrounded is intentional. For example, to increase the difference with a square. So if you ever have a valid reason not to round at 6px and leave only the ends rounded, that's ok. Since we're having this conversation, I'll emphasize another point when it's best to avoid rounding right corners. 

![Screenshot 2023-10-31 at 09 11 39](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a55c271b-6061-41df-9510-782c23ddfad1)
For example, you make an icon that has a right angle, but the rounding will affect the meaning. This is usually due to size, overall shape, or line length. In the house icon, rounding off 6px makes the internal shape worse, and the letter "D" looks too much like an "O", especially when viewed on a phone.

2023-10-31 16:55 UTC, x9136 requested changes

2023-10-31 16:55 UTC, x9136 commented on svgs/delta_icons.svg
I'm assuming that making this icon with a 14px stroke would be a bit bold relative to the rest of the icons. I suggest using 12×12px circles with 12px stroke.

2023-10-31 16:55 UTC, x9136 commented on svgs/deviantart.svg
![Screenshot 2023-10-31 at 19 20 50](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/92b43b28-bd02-4812-8b3c-9610a2fb0291)
In addition to redrawing, it is appropriate to round the corners so that the icon better fits the overall style.

2023-10-31 16:55 UTC, x9136 commented on svgs/dislyte.svg
![Screenshot 2023-10-31 at 19 27 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9e9e3533-781f-4df5-8404-9ac3fa6b9cea)
Interestingly, the rounded version is more like the original because the end of the zipper doesn't stick into the "wall".

![Screenshot 2023-10-31 at 19 31 11](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/6c051632-27f2-495a-aa50-5aa0813ce662)
I would prefer to make it closer to the original when redrawing it, because it's more expressive that way.

2023-10-31 16:55 UTC, x9136 commented on svgs/dominos.svg
Here I suggest only correcting the rounding of the corners.

2023-10-31 16:55 UTC, x9136 commented on svgs/usaa.svg
The color should be black (#000000).

2023-10-31 16:55 UTC, x9136 commented on svgs/joann.svg
The icon is fine. I suggest in the future to pay attention to how such icons look on the phone screen.

2023-10-31 16:55 UTC, x9136 commented on svgs/google_one.svg
![Screenshot 2023-10-31 at 19 44 18](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/7826a417-fdb8-49f7-bab8-b60646650b17)
The right line should be 3px higher to cover the defect at the joint.

2023-10-31 16:55 UTC, x9136 commented on svgs/google_earth.svg
![Screenshot 2023-10-31 at 19 46 06](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/470566d3-3d66-44b8-9d23-a85e890bdf93)
Either my editor didn't handle the SVG correctly, or you didn't bring the center line to the right side enough.

2023-10-31 16:55 UTC, x9136 commented on svgs/google_docs.svg
![Screenshot 2023-10-31 at 19 49 40](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/07caa6c7-e63f-4e49-bc77-6a34527a3c2a)
It says there's a fill. It's worth removing.

2023-10-31 16:55 UTC, x9136 commented on svgs/firefox_klar.svg
![Screenshot 2023-10-31 at 19 53 14](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/0d3a97a0-2910-49eb-9060-ed0d46f00ea7)
It says there's a fill. It's worth removing.

2023-10-31 18:33 UTC, hefaestos commented on svgs/dominos.svg
Ok I think I've figured out (part) of the confusing vocabulary issue... I have been using "radius" to describe the exterior profile of the stroke. However, if you tell figma/inkscape/whatever to add a radius to a corner, it's adding the radius to the stroke path itself . So, in the image below, the "add 6px rad" makes the radius in red on the right, but then consequentially the exterior radius - the actual visible radius of the shape, indicated in the demo image by the purple arc - is 12px.

![rad vocab](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/67d26f87-bf12-4dce-a3ed-4b6fb35ddae9)

I feel like referring to the radius of the stroke path is confusing, because a) the stroke path itself is not visible -it's location has to be inferred, b) it leaves us no vocabulary to describe the difference between an exterior radius of 6px and an actually sharp exterior profile, since in both cases the stroke path is sharp, and c) almost all (all?) non-right angles (and some right angles) use the "6px rad" in the "exterior profile" sense. E.g., in the house/D image, the 3 points along the roof of the house all have (exterior) 6px rad, on both sides.

![279275148-a55c271b-6061-41df-9510-782c23ddfad1](https://github.com/LawnchairLauncher/lawnicons/assets/144565696/23c8b1b1-2997-491d-8f10-fd7ea2b97009)

So is this an accurate phrasing of guideline, as you understand it? "Right angles should have an exterior radius of 12px. Right angles may have an exterior radius of 6px if 12px makes them look distorted/unclear. Non-right angles should have an exterior radius of 6px." (also, maybe: "unless 6px makes them look distorted, in which case make them 12px"? this seems to be what your comment on the Dislyte icon is.)

2023-10-31 18:50 UTC, x9136 commented on svgs/dominos.svg
> So is this an accurate phrasing of guideline, as you understand it?

That looks right.

![Screenshot 2023-10-31 at 21 48 01](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/e26588b9-c954-4787-b503-bf34846769c2)
The only thing is, if I understood correctly "Right angles may have an exterior radius of 6px", these are called rounded caps and their radius depends on the thickness of the stroke.

2023-10-31 19:01 UTC, hefaestos commented on svgs/dominos.svg
Yes, sorry; I was using 12px as understood stroke width, in order not to further confuse the numbers/vocab. Follow-on question - since you only called out the 6px/rounded caps part in reference to non-12px stroke widths, would this be accurate? "Right angles should have an exterior radius of 12px _regardless of stroke width_. Right angles may have [default rounded cap] radius corners (eg 6px for 12px stroke, 4px for 8px stroke) if 12px exterior radius makes them look distorted/unclear." (Or, should the default right angle exterior radius be equal to the stroke width?)

It would be nice to have that more explicitly in the guidelines, since that's obviously a lot more nuance than just "rad 6px". I will go through and rework to match.

2023-10-31 19:20 UTC, x9136 commented on svgs/dominos.svg
> Right angles should have an exterior radius of 12px regardless of stroke width. Right angles may have [default rounded cap] radius corners (eg 6px for 12px stroke, 4px for 8px stroke) if 12px exterior radius makes them look distorted/unclear

For the moment, that's correct.

> Should the default right angle exterior radius be equal to the stroke width?

![Screenshot 2023-10-31 at 22 20 26](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/48942081-a556-4095-88f0-2e17f757b527)
It's about joins. If you enable rounded joins in Figma, then, as far as I understand, the radius of such rounding will be 2 times smaller than the stroke width.

2023-10-31 19:24 UTC, x9136 commented on svgs/dominos.svg
> It would be nice to have that more explicitly in the guidelines.

So far you are the only one who has asked a lot of questions. Usually everything is clear and problems arise only if a person has not read the guides. If it is important to change something, it is better to create an issue for it.

2023-10-31 22:48 UTC, KTibow commented on svgs/dominos.svg
> It's about joins. If you enable rounded joins in Figma, then, as far as I understand, the radius of such rounding will be 2 times smaller than the stroke width.

You mean `stroke-linejoin="round"`?

2023-11-01 01:25 UTC, hefaestos commented
Made requested icon changes. Don't know why the debug's not finishing... will check later tonight.

2023-11-01 02:38 UTC, KTibow commented
Also you have conflicts you need to resolve
(good luck with that if you don't know git)

2023-11-01 08:23 UTC, x9136 commented on svgs/dominos.svg
> You mean stroke-linejoin="round"?

Yeah, but I was wrong. This radius depends not only on the thickness of the stroke, but also on the angle at the joint.

2023-11-01 09:25 UTC, x9136 commented on app/assets/appfilter.xml
You removed 3 activities for new icons and 2 links for new activities. Thus the 3 new icons will not work and the other 2 apps will remain without icons. At the same time there is still 1 more conflict – the fourth new icon, which you have decided not to touch for now.

You can fix this conflict in the same way as the others. In this case I suggest to remove the new SVGs and change the PR description as well. Or you can fix everything without deletions.

2023-11-01 17:53 UTC, hefaestos commented on app/assets/appfilter.xml
Yeh, I don't know what happened there... I was trying to fix the conflicts and something went weird, so I just started clean. Should be good now - all 4 new icons re-added, made requested changes.

2023-11-01 18:10 UTC, x9136 approved these changes

2023-11-01 18:10 UTC, merged