Add 5 Icons
LawnchairLauncher/lawnicons pull request #1547
Opened 2023-11-04 03:34 UTC by KhaiCo

# Description

## Icons addition information

### Icons added
* Cashew (`com.budget.tracker_app`)
* Epic Games (`com.epicgames.portal`)
* War Thunder Mobile (`com.gaijingames.wtm`)
* Display Info (`com.drhowdydoo.displayinfo`)
* AniList  PWA (`org.chromium.webapk.a616b5911060e2ebe_v2`)

Result:
![Screenshot_2023-11-04-10-32-31-421-edit_app lawnchair](https://github.com/LawnchairLauncher/lawnicons/assets/130490107/b334a900-9422-4741-8012-44a23db1c0b9)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-11-08 19:16 UTC, x9136 requested changes
Thanks for contributing! Given the comments, I suggest reading the [guides](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#foundation) again. 

I get the feeling that most of the problems are due to the tool you are using. If you have the opportunity, I suggest trying a different vector editor or digging deeper into your current one.

I should also say that I won't be able to correct every step you take this time. Perhaps someone else can.

2023-11-08 19:16 UTC, x9136 commented on svgs/war_thunder.svg
It is very difficult to understand that the icon is an airplane and not a blot. I suggest simplifying it or taking something from the logo as a basis. 

![Screenshot 2023-11-08 at 22 07 58](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/6e87978c-dc72-46de-8628-b41dcd7dabca)
There are so many possibilities to do otherwise. I prefer this one.

2023-11-12 03:56 UTC, KhaiCo commented
Ah thanks for the review, really sorry for my late reply. my tool has indeed been a problem because of inconsistency with other editor, do you perhaps have some recommendations on editor I can use? (Perhaps free ones?)

2023-11-12 04:03 UTC, KhaiCo commented on svgs/anilist.svg
I'm really confused about this one, I've checked the stroke width in both the code and editor and can't seem to find anything wrong (I probably just suck at reading the code). And about the simplifying I think it's better to keep the outline design for faithfulness to the original design and I've tried just using lines and it looks weird in the debug build and compromise brand recognition imo

2023-11-12 04:19 UTC, KhaiCo commented on svgs/war_thunder.svg
I agree, I'll probably prefer just removing the "splash" from around the plane to make it possible to enlarge the plane and make it more visible, and I don't think that people that play this game would have trouble recognizing the plane but I'll try to make it better in the scale of an icon

2023-11-12 04:21 UTC, KhaiCo commented on svgs/display_info.svg
Which stroke is wrong exactly?, and oh yeah sorry about the pic I forgot to delete the reference pic because it was hidden 😅

2023-11-12 04:26 UTC, KhaiCo commented on app/assets/appfilter.xml
I'm really sorry but can elaborate on how to fix the conflict? I'm very unfimiliar with fixing conflicts

2023-11-12 05:47 UTC, x9136 commented on svgs/display_info.svg
> Which stroke is wrong exactly?

![Screenshot 2023-11-12 at 08 43 51](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/74c4ea18-acaa-469a-9943-23a7ed97d909)
![Screenshot 2023-11-12 at 08 44 17](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/12f77b41-70ed-4e95-94b7-e2a0090dcacb)


As I mentioned in the general comment - maybe it's the editor.

2023-11-12 06:06 UTC, x9136 commented on svgs/anilist.svg
> And about the simplifying I think it's better to keep the outline design

![Screenshot 2023-11-12 at 09 04 26](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a52b2af7-a326-4643-b4f0-da850f58a7c2)
If you want to keep this option, then it's worth making sure that there is not too little spacing between the lines (1), roughness where the lines cross (2) and excessive boldness when the lines go side by side (3).

> the actual original logo has an actual slight misaligned

Maybe you used the wrong version, because that's not what I'm seeing.
https://github.com/AniList

2023-11-12 06:13 UTC, x9136 commented on app/assets/appfilter.xml
> how to fix the conflict?

![Screenshot 2023-11-12 at 09 07 31](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/e369ced1-1e0d-4e67-b708-8db778dcc563)
Above "=======" what's in your branch. Under "=======" is what's here. In this case you should leave both lines as they are different.

![Screenshot 2023-11-12 at 09 12 42](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d362d5b6-5542-4b7c-9d0b-e4858bc3aab8)
As a result, this place should look like this.

2023-11-12 06:22 UTC, x9136 commented
> do you perhaps have some recommendations on editor I can use?

For the computer? Most of the contributors use Figma or Inkscape. Figma is easier to learn, while Inkspace has more vector capabilities and is suitable if you are constantly creating vector graphics besides Lawnicons.

If you need an editor for your phone, I don't know. Best to find out for yourself.

2024-01-20 01:21 UTC, closed without merging