Add SAQ Icon
LawnchairLauncher/lawnicons pull request #1577
Opened 2023-11-22 21:37 UTC by service-paradis

# Description

Add SAQ Icon (https://play.google.com/store/apps/details?id=com.saq.android&hl=fr&gl=US)
Inspired from the icon found in the footer of https://www.saq.com/

## Icons addition information

### Icons added
* SAQ (`com.saq.android`) 

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-11-23 14:30 UTC, Chefski requested changes

2023-11-23 14:30 UTC, Chefski commented on svgs/saq.svg
I think going we the icon square-ish shape could use a single line with 14px and bottom line could be 10px or 8px. I think it looks more consistent with other icons. What do you think?

Something like this:
<img width="450" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/c930ff2b-bf73-40f9-ab35-a1ac66e69be1">

2023-11-23 16:10 UTC, service-paradis commented on svgs/saq.svg
You're right, would probably look better. I will try to submit a proposal for it next week!

2023-11-27 14:04 UTC, service-paradis commented on svgs/saq.svg
I updated the icon with your proposal :)

2023-11-29 22:25 UTC, Chefski approved these changes

2023-11-29 22:26 UTC, merged