Added 6 icons, linked 3
LawnchairLauncher/lawnicons pull request #1593
Opened 2023-11-26 19:02 UTC by Fxsch

# Description

Added icons for Alga, NextPush, AgoraDesk, Electrum, RHVoice and Video Transcoder. Linked Mint Calculator to calculator icon, gptAssist to chatgpt icon and Nextcloud to new activity name.

## Icons addition information

### Icons added
* AgoraDesk (`com.agoradesk.app`)
* Alga (`tech.laihz.alga.arm64`)
* Electrum (`org.electrum.electrum`)
* NextPush (`org.unifiedpush.distributor.nextpush`)
* RHVoice (`com.github.olga_yakovleva.rhvoice.android`)
* Video Transcoder (`protect.videoeditor`)

### Icons linked
* gptAssist (linked `org.woheller69.gptassist` to `@drawable/chatgpt`)
* Mint Calculator (linked `bored.codebyk.mintcalc` to `@drawable/calculator`)
* Nextcloud (linked `com.nextcloud.client` to `@drawable/nextcloud`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-11-27 01:43 UTC, x9136 requested changes
Thanks for contributing! I've left you comments and I want to remind you of [the guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#foundation).

2023-11-27 01:43 UTC, x9136 commented on svgs/alga.svg
Please use black (#000000) only. Also, I'd prefer to make the brackets using 14px and make the angle a little obtuse because the icon looks small among the rest.

If it's not too much trouble, link the latest version as well.
`<item component="ComponentInfo{tech.laihz.alga/tech.laihz.alga.MainActivity}" drawable="alga" name="Alga" />`

2023-11-27 01:43 UTC, x9136 commented on svgs/electrum.svg
![Screenshot 2023-11-27 at 04 08 54](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/829c83be-8cb5-456a-bf9d-fad376993fb9)
It's worth using a stroke thickness of 10px instead of 12px to make the ovals less likely to turn into a blot. I would also prefer to simplify the shape of the bitcoin sign.

![Screenshot 2023-11-27 at 04 14 56](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/cf7b464c-59fe-4dbe-8359-650f3808c652)
Approximately this option will look better on a phone.

2023-11-27 01:43 UTC, x9136 commented on svgs/nextpush.svg
Please use black (#000000) only.

2023-11-27 01:43 UTC, x9136 commented on svgs/rhvoice.svg
Basically, I've already done [a review on the icon for this app](https://github.com/LawnchairLauncher/lawnicons/pull/1410#issuecomment-1685349202).


![test](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d986b603-84c1-444d-a83e-0d015c46b7cd)

Technically you made the right icon, but it stands out from the rest and I think there is a way to avoid this. If you do a little research, starting with [the RHVoice repository](https://github.com/RHVoice/RHVoice), you may end up at the RHVoice Lab site. This site's logo looks like a better option for an icon than the current app icon. If you agree with that, I would suggest you use it.

2023-11-27 01:43 UTC, x9136 commented on svgs/video_transcoder.svg
Right corners are worth rounding off by 6px. Also, Lawnicons style has no sharp ends, so this should be rounded as well.

![test](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d986b603-84c1-444d-a83e-0d015c46b7cd)
There are also some problems with the SVG itself. I would suggest redoing it from scratch, taking [anime_scrap.svg](https://github.com/LawnchairLauncher/lawnicons/blob/3985a9b1da412e7ba4f7b36bbf2ba68b46061261/svgs/anime_scrap.svg) as a base.

2024-01-20 01:21 UTC, closed without merging

2024-02-22 12:17 UTC, Fxsch commented on svgs/video_transcoder.svg
Yeah, the icon looks completely wrong in that image, it's not supposed to look like that. I might have exported it as an Inkscape SVG instead of plain SVG by accident.

Also, I opened this PR months ago and kinda forgot about it. I want to start contributing here again, I'm not sure if I should reopen this PR or just make a new one tho.

2024-02-22 15:45 UTC, x9136 commented on svgs/video_transcoder.svg
> Also, I opened this PR months ago and kinda forgot about it. I want to start contributing here again, I'm not sure if I should reopen this PR or just make a new one tho.

It's better to create from scratch, otherwise you'll have to fix a lot of conflicts.

2024-02-23 12:59 UTC, Fxsch commented on svgs/video_transcoder.svg
I'll do that then while keeping your comments here in mind