Add icon for La Presse
LawnchairLauncher/lawnicons pull request #1596
Opened 2023-11-28 14:09 UTC by service-paradis

# Description

Add icon for La Presse
https://play.google.com/store/apps/details?id=ca.lapresse.android.lapressemobile&hl=en_US

## Icons addition information

### Icons added
* La Presse (`ca.lapresse.android.lapressemobile`) 

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-11-29 22:39 UTC, Chefski requested changes

2023-11-29 22:39 UTC, Chefski commented on svgs/la_presse.svg
Could you try round the S's a little better? They're a bit sharp at the top and bottom and a little uneven in the middle

2023-12-01 18:39 UTC, service-paradis commented on svgs/la_presse.svg
Good catch for the favicon!
In all honesty though, I never saw them using this icon anywhere. I'm not sure if it will be as recognizable for end users.

I pushed a new commit with rounder `S`, but here is a version using LP:

![la_presse - lp](https://github.com/LawnchairLauncher/lawnicons/assets/12817388/2f65f804-3ba5-4a6e-b27e-66088f5ea035)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192"><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="6" stroke-width="14" d="M100.602 155.8V36.201h39.268c8.36 1.456 15.963 6.213 21.409 13.394 5.394 7.225 8.25 16.368 8.045 25.744-.257 9.005-3.328 17.63-8.687 24.402-5.4 6.73-12.74 11.173-20.767 12.568l-39.268.94M22.666 36.2v119.598h51.05"/></svg>
```

Let me know what you think and I will make the requested changes :)

2023-12-01 20:31 UTC, Chefski commented on svgs/la_presse.svg
I guess if it's not used anywhere else and you're happy with this one then it's good

2023-12-01 20:31 UTC, Chefski approved these changes

2023-12-01 20:32 UTC, merged