Add 6 icons
LawnchairLauncher/lawnicons pull request #1617
Opened 2023-12-03 12:47 UTC by lskmn

# Description
Added 6 new icons.

Not sure about the stroke width for "Finanzguru" & "Tado", but found quite a few icons that use "6px" only – tried a version with 12px but I feel it looks a bit odd & too far from the original.
![finanzguru2](https://github.com/LawnchairLauncher/lawnicons/assets/18117410/f80f5574-de0b-466b-8521-6d9fa40f1ed5)

## Icons addition information
### Icons added
* Finanzguru (`de.dwins.financeguru`) - added from icon request form
* Refind (`com.refind.android`)
* Deliveries (`de.orrs.deliveries`) - added from icon request form
* WeNeed (`ch.coop.android.app.shoppinglist`)
* One Jotter (`com.colanotes.android`)
* tado (`com.tado`) - added from icon request form

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-12-06 16:19 UTC, x9136 requested changes

2023-12-06 16:19 UTC, x9136 commented on svgs/refind.svg
There's no problem with your icon. I just want to suggest an alternative, considering the original. You decide what's best.

![Screenshot 2023-12-06 at 19 03 05](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/c8fe64d5-1c0d-45a6-a8b9-bc64c83ecebe)

2023-12-06 16:19 UTC, x9136 commented on svgs/tado.svg
This icon can be accepted.

<details><summary>FYI</summary><img src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/379972ff-f466-4753-bb98-6852f0341fd6"></details>
All icons of this type have one problem: they stand out too much from the rest. It takes a lot of time to solve this, so most often long work on one icon is a waste of time, not an improvement of the iconpack.

2023-12-06 16:19 UTC, x9136 commented on svgs/weneed.svg
This icon should be redone with a stroke and don't forget the rounded joins.

2023-12-09 10:39 UTC, lskmn commented
Hey @x9136, thank you very much for the feedback, I hope I'll find the time to implement the changes soon.

2024-01-09 11:29 UTC, lskmn commented on svgs/weneed.svg
Removed it for now, as I don't find the time to remake it.

2024-01-09 11:30 UTC, lskmn commented on svgs/refind.svg
Good point, thanks for the feedback. Implemented this version.

2024-01-09 11:30 UTC, lskmn commented on svgs/one_jotter.svg
Done

2024-01-09 11:30 UTC, lskmn commented on svgs/finanzguru.svg
Found the big eyes to be a bit creepy tbh, but wen't with some middle ground. :)

2024-01-09 11:31 UTC, lskmn commented on svgs/deliveries.svg
Done, thanks.

2024-01-10 03:37 UTC, x9136 commented
I've tried fixing the obvious conflicts, but it looks like there are others. Perhaps only updating your branch and recreating the PR will help here.

As for the icons.

![Screenshot 2024-01-10 at 06 32 38](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/96c675cf-f409-47b6-9a4b-28e00d0dc9aa)
Incorrect size (161px in height). Also, I'd like to check how the eyes look on the phone screen, but I can't do that while there are conflicts.

![Screenshot 2024-01-10 at 06 34 47](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/319eff86-7eaf-4e5d-803b-549b4acd5c2b)
You need to use a stroke instead of a fill.

The others are okay.

2024-01-10 10:45 UTC, closed without merging