Add 6 icons
LawnchairLauncher/lawnicons pull request #1620
Opened 2023-12-04 04:23 UTC by tduck973564

# Description
I've created 6 icons.
Egg, Inc. might not be distinctive enough, I could maybe make it more egg shaped or just use the chicken from the original icon. 

## Icons addition information

### Icons added
* WarpShare (`com.moseoridev.warpshare`)
* Seeker (`com.companyname.andriodapp1`)
* Metronome (`com.bobek.metronome`)
* PTV (`au.gov.vic.ptv`)
* Egg, Inc. (`com.auxbrain.egginc`)
* iReal Pro (`com.massimobiolcati.irealb`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-12-04 08:54 UTC, tduck973564 commented
I've just noticed that ireal pro and PTV icons aren't automatically applied when lawnicons are enabled in lawnchair launcher, and I'm not sure why. All the other icons load, and I'm sure that I have made the right entries for them both. I can use them as custom icon choices.

2023-12-04 09:12 UTC, x9136 commented
> I've just noticed that ireal pro and PTV icons aren't automatically applied when lawnicons are enabled in lawnchair launcher, and I'm not sure why.

Hey! Most likely the reason is that you made some mess in appfilter.xml.

2023-12-04 15:27 UTC, x9136 commented
> Maybe the activity from after the app is launched and the icon showing in Lawnchair differs somehow?

![IMG_20231204_182531](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/04e46840-2fec-4868-b7aa-684c3cd58cbd)
Everything works for me, so maybe it's a matter of the launcher settings.

2023-12-04 15:29 UTC, tduck973564 commented
> > Maybe the activity from after the app is launched and the icon showing in Lawnchair differs somehow?
> 
> ![IMG_20231204_182531](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/04e46840-2fec-4868-b7aa-684c3cd58cbd)
> Everything works for me, so maybe it's a matter of the launcher settings or a bug.

Which lawnchair version are you using? Do you have themed icons enabled?

2023-12-04 15:34 UTC, tduck973564 commented
That's probably it, I'm on a dev build of lawnchair 13

2023-12-06 17:04 UTC, Chefski requested changes

2023-12-06 17:04 UTC, Chefski commented on svgs/ptv.svg
Please change the icon to reach the 160x160 border and also change the stroke to 14px (currently 14.49px)

2023-12-06 17:08 UTC, Chefski commented
Also could you fix the changes made to the calendar links in `appfliter.xml`

2023-12-06 20:58 UTC, tduck973564 commented
I don't actually know what's changed or why something's happened to it

2023-12-08 02:45 UTC, x9136 commented
> I never touched them myself

https://github.com/LawnchairLauncher/lawnicons/pull/1620/commits/2931d77731cfdf0c5f02e6db4d1e1cb0d5f30a1b You can see in the "Files changed" tab how appfilter.xml has changed.

If the unnecessary changes happened unknowingly, it might be easiest to take appfilter.xml from the main repository and add the 6 lines there.

2023-12-09 03:41 UTC, tduck973564 commented
@Chefski This should all be good now.

2023-12-12 22:49 UTC, Chefski approved these changes

2023-12-12 22:49 UTC, merged