Add Mobvoi
LawnchairLauncher/lawnicons pull request #1642
Opened 2023-12-07 12:58 UTC by validcube

# Description

Add Mobvoi, I have no idea what I'm doing please help.

## Icons addition information

### Icons added
* Mobvoi (` com.mobvoi.companion.aw/com.mobvoi.companion.aw.StartEntry`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-12-10 09:37 UTC, x9136 requested changes

2023-12-10 09:37 UTC, x9136 commented on svgs/mobvoi.svg
![Screenshot 2023-12-10 at 12 29 27](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/5ef4427e-650e-42fe-8c07-2527b8348df4)
Incorrect size, it's worth enlarging the icon so that the height becomes correct.

In general, 8px stroke is good for very dense icons. In your case, the icon has very little detail and lines, so if you view it on your phone screen, it will stand out because of the 8px. Formally you did it right, but if you have the desire, it's easy to do better.

2024-01-07 10:59 UTC, validcube commented on svgs/mobvoi.svg
Should be correct now

![image](https://github.com/LawnchairLauncher/lawnicons/assets/93124920/6fe85642-3b58-412a-aff5-ab59481f2880)

2024-01-07 11:09 UTC, validcube commented on svgs/mobvoi.svg
> In general, 8px stroke is good for very dense icons. In your case, the icon has very little detail and lines, so if you view it on your phone screen, it will stand out because of the 8px. Formally you did it right, but if you have the desire, it's easy to do better.

I could do something like this, lmk what you think:

![image](https://github.com/LawnchairLauncher/lawnicons/assets/93124920/caffcd87-c937-4d33-9a6c-0bf04484b45c)

2024-01-07 11:23 UTC, x9136 commented on svgs/mobvoi.svg
![Screenshot 2024-01-07 at 14 15 17](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/1748e27a-f947-4db5-a146-85dc2f2363e8)
It feels like you moved the icon down before saving.

<details><summary>Open a screenshot</summary><img src="https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9c755ef1-4c7b-459b-b744-a03ef63af6c4"></details>
As you can see, the icon is noticeably out of style due to the fact that it's created with 8px stroke.

2024-01-07 11:33 UTC, x9136 commented on svgs/mobvoi.svg
> I could do something like this, lmk what you think:

The most important thing is to use 12px stroke. Then any of these options will look good. I already showed my option in Discord a month ago.

2024-01-07 12:35 UTC, x9136 approved these changes

2024-01-07 12:37 UTC, merged