Add icon for Pleco
LawnchairLauncher/lawnicons pull request #1657
Opened 2023-12-11 00:33 UTC by KZacharski

# Description

## Icons addition information

### Icons added
* Pleco (`com.pleco.chinesesystem`)

## Contributor's checklist

- [x ] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x ] I have ensured that Lawnicons builds correctly
- [x ] I am willing to make changes to my icons if someone suggests changes

2023-12-12 22:52 UTC, Chefski requested changes

2023-12-12 22:52 UTC, Chefski commented on svgs/pleco.svg
Hey! The icon just crosses the 160x160px content area vertically. Mind reducing the size to fit inside the content area?
<img width="450" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/bc46de16-c076-43b4-8892-479c56530465">

2023-12-13 02:32 UTC, KZacharski commented on svgs/pleco.svg
Done

<img width="574" alt="Screenshot 2023-12-13 at 03 29 25" src="https://github.com/LawnchairLauncher/lawnicons/assets/54036387/d0f826f1-ff54-4665-b1d7-b47e88fe2da4">

2023-12-13 12:50 UTC, Chefski approved these changes

2023-12-13 12:51 UTC, merged