Add icon for Benny & Co.
LawnchairLauncher/lawnicons pull request #1673
Opened 2023-12-15 13:11 UTC by service-paradis

# Description

Add icon for Benny & Co. (https://play.google.com/store/apps/details?id=com.bennyco.app&hl=fr_CA&gl=US)

## Icons addition information

### Icons added
* Benny & Co. (`com.bennyco.app`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2023-12-17 04:15 UTC, x9136 requested changes

2023-12-17 04:15 UTC, x9136 commented on app/assets/appfilter.xml
A better name would be "Benny and Co.".

2023-12-17 04:15 UTC, x9136 commented on svgs/benny_co.svg
![Screenshot 2023-12-17 at 07 10 13](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/26588b8a-1982-4a09-9c8d-dfe341466874)
The whole rooster is best made less detailed, but really the most important part is the comb. So I would try to maximize it to make it really expressive.

2023-12-19 16:25 UTC, service-paradis commented on app/assets/appfilter.xml
Since it was founded by French Canadians, I'm not sure about replacing the ampersand with "and". It still mostly used in Québec where people mostly speaks french. They recently opened a few restaurants in Ontario (where people speaks mostly english).

The ampersand is a great way to be understood by people speaking both french or english.

2023-12-19 16:46 UTC, x9136 commented on app/assets/appfilter.xml
My premise is that it's more habitual to write "Benny and" in a search query than to recall how to type an ampersand. 

If you think that most people are used to typing the ampersand in this case because the app name is heavily tied to it, then no problem.

2024-02-15 06:32 UTC, x9136 commented
Most likely, this PR will have to be recreated. If you do this, you can use this icon.
![benny_co](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/85926fdc-243b-4e25-91d6-069a4238dc42)

2024-02-17 13:09 UTC, closed without merging