add 4 icons, link 2 icons, fix 4 icons.
LawnchairLauncher/lawnicons pull request #1680
Opened 2023-12-17 13:18 UTC by Autines

# Description

## Icons addition information

### Icons added
* Appshare (`info.muge.appshare`) 
* Feizhu (`com.taobao.trip`)
* Todesk (`youqu.android.todesk`)
* Alicloud (`com.alicloud.databox`)

### Icons link fixed
* baidumap (`com.baidu.BaiduMap/com.baidu.baidumaps.WelcomeScreen.Alias0`)
* devcheck (`flar2.devcheck/flar2.devcheck.MainActivity`)
* didi (`com.sdu.didi.psnger/com.didi.sdk.app.MainActivity`)
* libchecker (`com.absinthe.libchecker/com.absinthe.libchecker.features.home.ui.MainActivity`)

### Icons linked
* legado (linked `io.legado.play.release` to `@drawable/legado`)
* netease_music (linked `com.hihonor.cloudmusic` to `@drawable/netease_music`)

## Contributor's checklist

- [ ] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [ ] I have ensured that Lawnicons builds correctly
- [ ] I am willing to make changes to my icons if someone suggests changes

2023-12-17 16:58 UTC, x9136 requested changes

2023-12-17 16:58 UTC, x9136 commented on app/assets/appfilter.xml
One app can have multiple links, so by doing a replacement you didn't fix the links, you deleted them.

Please leave the old links and add your own next to them.

2023-12-17 16:58 UTC, x9136 commented on svgs/feizhu.svg
The icon is a little hard to recognize because there is no nose. Would you mind adding it?
![Screenshot 2023-12-17 at 19 54 28](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/f2d5a9ad-3248-4849-b192-351edb98426e)

2023-12-23 10:54 UTC, Autines commented on app/assets/appfilter.xml
OK, I thought links change in new version.

2023-12-23 10:54 UTC, Autines commented on svgs/feizhu.svg
alright

2023-12-23 12:38 UTC, x9136 commented on svgs/feizhu.svg
The size became incorrect because you reduced the thickness of the stroke but did not enlarge the icon.

![Screenshot 2023-12-23 at 15 38 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/05649eb8-9fa8-4061-9bfb-0e455729e4a1)
The nose can be done neatly.

2023-12-23 12:43 UTC, x9136 commented on app/assets/appfilter.xml
> OK, I thought links change in new version.

You're right, it does happen from time to time. At the same time apps can have versions for different countries, then it is 15-20 links to one icon. Also don't forget that some people don't update applications for a long time for various reasons, so they will have old packages. There are also such cases as premium, beta or debug versions.

2024-02-07 01:14 UTC, closed without merging