Add 1 Icon
LawnchairLauncher/lawnicons pull request #1705
Opened 2023-12-24 05:20 UTC by Hamster45105

# Description

1 icon has been added.

## Icons addition information

### Added
ownCloud (`com.owncloud.android`)

## Note
ownCloud icon credit goes to @eltacogatito who originally tried to merge this icon in #1355, however couldn't due to the file not being added to the `appfilter.xml` file (https://github.com/LawnchairLauncher/lawnicons/pull/1356#issuecomment-1647553504).

I have added the icon to the `appfilter.xml` file and changed the file format from an Inkscape SVG to plain SVG.

## Contributor's checklist

- x I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- x I have ensured that Lawnicons builds correctly
- x I am willing to make changes to my icons if someone suggests changes

2023-12-30 00:31 UTC, Chefski requested changes

2023-12-30 00:31 UTC, Chefski commented on svgs/owncloud.svg
Could you change the icon to fit the content area?
<img width="504" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/35ccf9a9-1d02-43e0-8f56-45a638792c29">

2023-12-30 06:04 UTC, Hamster45105 commented on svgs/owncloud.svg
It should be good to go now. I'm new to using Inkscape, but I managed to scale the width of the object up to 160px. Let me know if any more changes need to be made!

2023-12-30 10:59 UTC, Chefski commented on svgs/owncloud.svg
The icon got scaled up but the stroke also changed to 8.11 now. A few other people had a problem with this too. Maybe you need to uncheck scaling the stroke too?

2023-12-31 01:00 UTC, Hamster45105 commented on svgs/owncloud.svg
Should be fixed now. 

The stroke width is 8.000 px and the icon width is 160.000 px.

2023-12-31 05:45 UTC, Hamster45105 commented on svgs/owncloud.svg
Should be good to go now.

Stroke width: 8px
Icon width: 160px

2024-01-06 12:39 UTC, Chefski approved these changes
Apologies for the slow approval. Thanks :)

2024-01-06 12:39 UTC, merged