Link ReVanced Manager Variant && RVX Fork
LawnchairLauncher/lawnicons pull request #1736
Opened 2024-01-07 13:41 UTC by validcube

# Description

RVX refer to [ReVanced Extended Manager](https://github.com/inotia00/revanced-manager), originally made by the ReVanced Manager Team, forked by inotia00 to bring better compatibility to his own [ReVanced Extended Patches](https://github.com/inotia00/revanced-patches).

ReVanced Manager offered three variants
* Release/Just-in-Time (app.revanced.manager.flutter)
* Debug (app.revanced.manager.flutter.debug)
* Profile (app.revanced.manager.flutter.profile)

## Icons addition information

### Linked
ReVanced Manager Debug (`app.revanced.manager.flutter.debug` → `youtube_revanced.svg`)
ReVanced Manager Profile (`app.revanced.manager.flutter.profile` → `youtube_revanced.svg`)
RVX Manager (`app.rvx.manager.flutter` → `revanced_extended.svg`)
RVX Manager Debug (`app.rvx.manager.flutter.debug` → `revanced_extended.svg`)
RVX Manager Profile (`app.rvx.manager.flutter.profile` → `revanced_extended.svg`)

### Updated
App Name (`com.package.app`)
App Name (`com.package.app`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-07 13:42 UTC, validcube commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity}" drawable="revanced_extended" name="ReVanced Manager" />
Correct ReVanced Extended Manager name; source: https://github.com/inotia00/revanced-manager/blob/main/android/app/build.gradle#L50

```suggestion
  <item component="ComponentInfo{app.rvx.manager.flutter.profile/app.revanced.manager.flutter.MainActivity}" drawable="revanced_extended" name="RVX Manager" />
  <item component="ComponentInfo{app.rvx.manager.flutter.debug/app.revanced.manager.flutter.MainActivity}" drawable="revanced_extended" name="RVX Manager" />
  <item component="ComponentInfo{app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity}" drawable="revanced_extended" name="RVX Manager" />
```

2024-01-08 00:33 UTC, x9136 requested changes

2024-01-08 00:33 UTC, x9136 commented on app/assets/appfilter.xml
Let's avoid using icons that are different from the originals. Especially since we already have [RVX Manager icon](https://github.com/LawnchairLauncher/lawnicons/blob/d68e274aec3dd1773515c40a8ea7720bbaa879e5/svgs/rvx_manager.svg).

Where can I download ReVanced Manager Profile and RVX Manager Profile? I couldn't find it on your links. Would like to learn more about them.

2024-01-08 00:39 UTC, validcube commented on app/assets/appfilter.xml
> Where can I download ReVanced Manager Profile and RVX Manager Profile? I couldn't find it on your links. Would like to learn more about them.
> 

You will have to compile it yourself, profile variant is made by using `flutter build apk --profile`.

They're basically the same as release but with access to profilers; useful for examining performance issues.

https://docs.flutter.dev/perf/ui-performance

2024-01-08 00:47 UTC, x9136 commented
If it's not too much trouble, please update the RVX Manager icon as well. I fixed the rounding.
```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M86 24.68A20 20 0 0 0 56 42m70 42.32a20.003 20.003 0 0 0 0-34.641M56 60l81.982 100.201c3.206 3.917.418 9.799-4.643 9.799H62a6 6 0 0 1-6-6V60Zm0 0V42m70 7.68-40-25m40 59.64L94 105" stroke="#000" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

2024-01-08 12:04 UTC, x9136 approved these changes

2024-01-08 12:05 UTC, merged