Added 5 icons, Linked 1 icon
LawnchairLauncher/lawnicons pull request #1747
Opened 2024-01-13 07:03 UTC by asrieldashie

# Icons addition information

### Added
Cherrygram (`uz.unnarsx.cherrygram/.CG_Icon_Cherry`) (Unlinked from regular Telegram icon)
Easy Wallet (`com.easycard.wallet/.nonfc.activity.WelcomePageActivity`)
PxPay (`com.pxmart.android/.di.mvvm.view.start.SplashActivity`)
The Wolf's Stash (`se.zepiwolf.tws.play/se.zepiwolf.tws.REGULAR`)
Yahoo! Auctions (Yahoo!拍賣) (`com.yahoo.mobile.client.android.ecauction/.activity.ECSplashScreenActivity`)

### Linked
The Wolf's Stash (APK version) (`se.zepiwolf.tws.web/se.zepiwolf.tws.REGULAR` → `the_wolfs_stash.svg`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-13 17:47 UTC, x9136 requested changes

2024-01-13 17:47 UTC, x9136 commented on app/assets/appfilter.xml
"Easy Wallet" → "悠遊付 ~~ Easy Wallet"
"Yahoo Actions" → "Yahoo Actions ~~ Yahoo!拍賣 ~~ Yahoo!オークション"
If I've got it right, it should be like this. Correct me if I'm wrong about the original names.
[Naming guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#app-name)

Make sure the Cherrygram, Easy Wallet and PxPay icons are working because they have weird `package/activity` entries.

Also, I found another link for Easy Wallet. If you want it, add it.
```
com.easycard.wallet/com.easycard.wallet.nonfc.activity.WelcomePageActivity
```

2024-01-13 17:47 UTC, x9136 commented on svgs/cherrygram.svg
![Screenshot 2024-01-13 at 20 26 59](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/74e76ecc-e93a-4f7a-9cae-1c779d023044)

Too small (148.64×152px).

2024-01-13 17:47 UTC, x9136 commented on svgs/easy_wallet.svg
The size is fine, but you need to clean up the layers that give the fill and leave only the stroke.

2024-01-13 17:47 UTC, x9136 commented on svgs/the_wolfs_stash.svg
![Screenshot 2024-01-13 at 20 32 00](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9b7729e3-4685-4c04-9251-aff463fc2e7a)
Too big (164×163.84px). Don't forget that the joints need to be rounded.

Also it might be worth working on the facial features to make them closer to the original.

2024-01-16 05:17 UTC, asrieldashie commented
Reworked on Cherrygram, Easy Wallet and Wolf's Stash
![image](https://github.com/LawnchairLauncher/lawnicons/assets/24969756/43237d92-d2ac-4074-8c3b-a66c1b0a0fbb)


Name changes
![image](https://github.com/LawnchairLauncher/lawnicons/assets/24969756/be3cf56d-8c43-4a32-89bd-82db9c52ccea)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/24969756/ee6fb816-096f-4ad2-b5c2-c23c640f80d4)
![image](https://github.com/LawnchairLauncher/lawnicons/assets/24969756/443c8ff1-3e83-41a7-adc7-81838432fbdf)

2024-01-16 05:55 UTC, x9136 requested changes

2024-01-16 05:55 UTC, x9136 commented on svgs/the_wolfs_stash.svg
![Frame 3](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/e42631be-2590-4905-b6a1-eff6002e5de0)

It's worth fixing those stroke breaks. You can also see them on your screenshot.

These line breaks can occur for 2 reasons:
1. Often because the point handles are used to select angles that create a conflict between the lines joining at the point.
2. Less frequently because the point at the joint is on a fractional coordinate.

2024-01-16 05:55 UTC, x9136 commented on app/assets/appfilter.xml
Thanks for adding the additional link.

It's worth adding a Japanese name as well, because Yahoo Auctions operates there as well.

![Screenshot 2024-01-16 at 08 53 55](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/00f47ffc-e857-4fae-a14c-e1579c3c9037)

2024-01-16 06:56 UTC, asrieldashie commented
Fixed Wolf's Stash icon

About the Y!Auctions, I only added the Chinese name since it's specifically for [TW version](https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.ecauction&hl=zh_TW&gl=US) of the app.
The [JP version](https://play.google.com/store/apps/details?id=jp.co.yahoo.android.yauction&hl=ja&gl=US) have a different icon.

2024-01-16 07:23 UTC, x9136 approved these changes

2024-01-16 07:23 UTC, merged