Add icon for Alaska
LawnchairLauncher/lawnicons pull request #1768
Opened 2024-01-19 20:42 UTC by service-paradis

# Description

Add icon for Alaska (https://play.google.com/store/apps/details?id=com.editionsalaska.ra)

## Icons addition information

### Added
Alaska (`com.editionsalaska.ra`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-20 14:05 UTC, x9136 requested changes

2024-01-20 14:05 UTC, x9136 commented on svgs/alaska.svg
It's worth it to reduce the black spot somehow.

![Screenshot 2024-01-20 at 17 02 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/c567124a-ba59-4a21-8c58-4eecd0234eb1)

We have icons with this same case: [bob_world.svg](https://github.com/LawnchairLauncher/lawnicons/blob/0911e4b183fb633f52473a66be38cc15976b776f/svgs/bob_world.svg), [zlib.svg](https://github.com/LawnchairLauncher/lawnicons/blob/0911e4b183fb633f52473a66be38cc15976b776f/svgs/zlib.svg).

2024-01-22 12:26 UTC, service-paradis commented on svgs/alaska.svg
Makes sense, thank you for the feedback. Just pushed a new version using `6px` stroke for the inner pages!

2024-01-22 12:32 UTC, x9136 approved these changes
Added 1 pixel to the center line because you didn't increase the stroke length after changing the stroke thickness.

2024-01-22 12:33 UTC, merged

2024-01-22 13:39 UTC, service-paradis commented
Oh, damn 🤦‍♂️ Thank you for the quick fix!