Update icon for Flashfood
LawnchairLauncher/lawnicons pull request #1772
Opened 2024-01-22 20:36 UTC by service-paradis

# Description

Well, there is a new icon for [Flashfood](https://www.flashfood.com/fr)

## Icons addition information

### Updated
Flashfood (`com.flashfoodapp.android`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-22 21:00 UTC, x9136 requested changes

2024-01-22 21:00 UTC, x9136 commented on svgs/flashfood.svg
![Screenshot 2024-01-22 at 23 53 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/692bd4f4-ea6f-4a46-9409-86ebf1a0ffd3)
The icon went outside the content area for some reason. The stroke is too bold for such dense icons, better to use 12px. The edges of the handle are sloppily made, though it's easy to make neat.

On the right is an example of how it could be.


It's like you were in a hurry.

2024-01-22 21:22 UTC, service-paradis commented on svgs/flashfood.svg
Hum, looks like something went wrong when I optimized the icon at the end. Just pushed a new version that should be better. Let me know if there is something else!

2024-01-23 03:37 UTC, x9136 approved these changes

2024-01-23 03:37 UTC, merged