Add 3 icons
LawnchairLauncher/lawnicons pull request #1778
Opened 2024-01-24 03:27 UTC by Hamster45105

# Description

Added 3 icons (floccus, Qantas and what3words)

## Icons addition information

### Added
floccus (`org.handmadeideas.floccus`)
Qantas (`au.com.qantas.qantas`)
what3words (`com.what3words.android`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-24 14:51 UTC, x9136 requested changes
Hey! I've left a few comments.

By the way, [Lawnicons guideline](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#contributing-icons) was updated recently — if you have time, take a look. The changes mainly concern square icons, which are not in this PR.

2024-01-24 14:51 UTC, x9136 commented on svgs/floccus.svg
![Screenshot 2024-01-24 at 17 22 55](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/cb6d31d1-b56e-4eaa-bc85-eba4a946e590)
In cases when the thickness of the initial shape is close to the base stroke thickness, it is better to do with a single line instead of outlining the shape. This way it is easier to make an icon and it will look neater.


Also, try to avoid too small distances between lines, because they stick to the phone screen.

2024-01-24 14:51 UTC, x9136 commented on svgs/qantas.svg
The icon is thin. If you use a stroke thickness of 8px, it will stand out a lot among other icons. It's worth increasing the stroke width to 10px (don't forget to correct the size afterward).

2024-01-24 14:51 UTC, x9136 commented on svgs/what3words.svg
12.06px stroke doesn't fit. Also, you made double lines, so actually your stroke became ~24px.

![Screenshot 2024-01-24 at 17 39 47](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/63c87dbe-7f56-4bdc-81df-49c8fc75e90f)
14px stroke would be fine for this icon.

2024-01-24 23:38 UTC, Hamster45105 commented
The icons should be fixed now!

2024-01-25 04:12 UTC, x9136 requested changes

2024-01-25 04:12 UTC, x9136 commented on svgs/what3words.svg
12px stroke is not enough for this icon, as there are few shapes in it.

If interested, read about the reasons in [the Maintaining Visual Balance](https://github.com/LawnchairLauncher/lawnicons/blob/develop/docs/images/creating-icons-4-maintaining-visual-balance.png).

2024-01-25 04:12 UTC, x9136 commented on svgs/floccus.svg
For some reason you decided to use a fill instead of a stroke, that option won't fit. Also, we don't make icons that have lines with square ends. Even if you find such icons, they should be redesigned.

[About stroke and rounded ends](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#foundation)

2024-01-25 05:39 UTC, Hamster45105 commented on svgs/floccus.svg
Sorry about that! Both icons should be fixed now and ready to go.

2024-01-25 05:40 UTC, Hamster45105 commented
I fixed both icons, so they should be ready to go now!

2024-01-25 05:42 UTC, Hamster45105 commented on svgs/what3words.svg
Sorry about that, I forgot to increase the stroke width. It should be all good now.

2024-01-25 07:13 UTC, x9136 approved these changes
Floccus icon turned out to be unbalanced because of the difference in stroke thicknesses of the cloud and tick, as well as because of too small distances between them. But it can be accepted.

I'll wait until tomorrow before merging the PR in case you want to make changes.

2024-01-25 21:42 UTC, Hamster45105 commented
Thanks, I'm happy, for everything to be merged now.

2024-01-26 05:53 UTC, merged