Add 5 Icons, Link 1
LawnchairLauncher/lawnicons pull request #1788
Opened 2024-01-27 04:16 UTC by Hamster45105

# Description

Added 5 icons, linked 1.

## Icons addition information

### Added
Australia Post (`au.com.auspost.android`) - Round
BOM Weather (`au.gov.bom.metview`) - Round
Camera Assistant (`com.samsung.android.app.cameraassistant`) - Square
FlightStats (`com.conducivetech.android.traveler`) - Rectangle
PlaneFinder (`com.pinkfroot.planefinderfree`) - Square

### Linked
Fossify Phone (`org.fossify.phone` → `dialer.svg`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-27 07:49 UTC, x9136 requested changes
Some of the icons are made without taking into account [Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#lawnicons-contributing-guide), and the other part can be significantly improved in quality.

2024-01-27 07:49 UTC, x9136 commented on svgs/aus_post.svg
![Screenshot 2024-01-27 at 10 08 07](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/2e033b80-370a-48c2-882c-59e4bd85865d)

Overall, the case is the same as last time.

> In cases when the thickness of the initial shape is close to the base stroke thickness, it is better to do with a single line instead of outlining the shape. This way it is easier to make an icon and it will look neater.
> 
> Also, try to avoid too small distances between lines, because they stick together on the phone screen.
>

2024-01-27 07:49 UTC, x9136 commented on svgs/camera_assistant.svg
![Screenshot 2024-01-27 at 10 16 00](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d7aef31f-e406-4162-90c3-37bd452637ef)
Incorrect size (152×152px). This icon can be considered square, so the size will be 154×154px.

It's too thin, so the icon stands out in style even in this PR. It's worth using at least 10px, although it's possible to make a high-quality icon with the base thickness in this case. I recommend simplifying the details.

2024-01-27 07:49 UTC, x9136 commented on app/assets/appfilter.xml
`aus_post.svg` → `australia_post.svg`

[Naming guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#naming)

2024-01-27 07:49 UTC, x9136 commented on svgs/flightstats.svg
![Screenshot 2024-01-27 at 10 34 13](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/0374c028-a18f-4c97-92b2-ab2b844e2ee1)
It's too bold in the center and left. Also lacks simplification of the shape. And it's worth compensating the emptiness at the bottom by raising the icon a bit higher, because of the shape it is now pressed to the bottom.

2024-01-27 07:49 UTC, x9136 commented on svgs/plane_finder.svg
Incorrect size (150.3×150.25).
[Canvas & Sizes](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes)

There are no sharp corners in Lawnicons.
[Lawnicons foundation](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#foundation)

This icon looks good without simplification, so what's left is to make it Lawnicons style.

2024-01-28 07:44 UTC, Hamster45105 commented
Thanks for all the feedback and help with these!

I hope they look a bit better now.

2024-01-28 09:40 UTC, x9136 commented on svgs/camera_assistant.svg
That's a good one. I'd keep it.

![Screenshot 2024-01-28 at 12 32 55](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/027cd87c-d279-41b7-a544-7faba95318fc)
If you're curious, I would do it this way, since it seems like sliders are a metaphor for camera settings.

2024-01-28 09:40 UTC, x9136 commented on svgs/flightstats.svg
The icon is very thin, you need the 14px stroke here.

2024-01-28 09:41 UTC, x9136 requested changes
Only FlightStats left.

2024-01-29 00:39 UTC, Hamster45105 commented on svgs/camera_assistant.svg
Thanks for the tips, I'll keep that in mind for next time.

2024-01-29 04:13 UTC, x9136 approved these changes

2024-01-29 04:13 UTC, merged