Add BorrowBox
LawnchairLauncher/lawnicons pull request #1799
Opened 2024-01-30 02:06 UTC by Hamster45105

# Description

Added 5 icons

## Icons addition information

### Added
BorrowBox (`com.bolindadigital.BorrowBoxLibrary`)
Caffeine (`moe.zhs.caffeine`)
Emergency Plus (`com.threesixtyentertainment.nesn`)
RadarBox (`com.airnav.radarbox`)
triple j (`au.net.abc.triplej`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

2024-01-30 02:43 UTC, KTibow commented on svgs/borrowbox.svg
bottom left needs more rounding

2024-01-30 02:43 UTC, KTibow commented on svgs/caffeine.svg
corners need more rounding

2024-01-30 02:43 UTC, KTibow commented on svgs/radarbox.svg
i personally prefer consistent stroke width, but that's up to you

2024-01-30 02:43 UTC, KTibow commented on svgs/triplej.svg
these edges could be improved
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/03748cbb-a4fe-4605-bd16-39b870d013aa)

2024-01-30 03:13 UTC, Hamster45105 commented on svgs/borrowbox.svg
I've made the bottom more curved, is that enough?

2024-01-30 03:13 UTC, Hamster45105 commented on svgs/caffeine.svg
For this, I've rounded the corner at the bottom of the handle. Is that god enough?

2024-01-30 03:45 UTC, KTibow commented
@Hamster45105 i think you misunderstood the rounding guidelines. instead of having the 6px corner radius currently used, your lines should have a 12px corner radius, like this:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/e351edcc-8377-474f-a522-d65feb121303)

2024-01-30 06:04 UTC, x9136 commented
> your lines should have a 12px corner radius, like this:

It's 6px in Figma. Maybe other graphic editors count differently. In any case, everyone can overlay the corners on the examples and see what value is needed.
![Screenshot 2024-01-30 at 09 00 53](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a1c0fe3c-3387-4503-9648-5600b6f87b25)

2024-01-30 11:17 UTC, x9136 requested changes

2024-01-30 11:17 UTC, x9136 commented on svgs/borrowbox.svg
![Screenshot 2024-01-30 at 14 00 09](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/5e9f00a5-9fd7-4c8d-8259-1c6ab901e656)
You could consider this icon square, although I wouldn't because of the void at the bottom. However, if you leave the size 154×154px, the icon needs to be raised 2px higher because it's offset.

Also, don't forget to round the selected corner by at least 6px.

2024-01-30 11:17 UTC, x9136 commented on svgs/caffeine.svg
![Screenshot 2024-01-30 at 14 03 19](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/67d8dacd-33ba-4229-9722-39b7e6683201)
This icon is not square, so the long side should be 160px. Remember to round the selected corner by at least 6px.

2024-01-30 11:17 UTC, x9136 commented on svgs/triplej.svg
It's gotten better, although it's a bit sloppy. It won't be noticeable to users, but in the future, when you need to make 2+ lines parallel, it helps to set opacity, zoom the workspace and manual input of points and handles coordinates.

2024-01-31 07:08 UTC, x9136 commented on svgs/emergency_plus.svg
![Screenshot 2024-01-31 at 10 00 41](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/179ae2d1-0306-4ebe-9a51-394cb2785100)
How about a better take on the features of the original?

This icon is very good for figuring out how to combine 2 curves so that there are no unnecessary protrusions at the junction. It also requires the ability to trim the shape with a line.

2024-01-31 07:15 UTC, x9136 commented on svgs/emergency_plus.svg
If you don't have the desire or time, here's my version. The original is interesting enough to try to keep it.

```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M96 48v48M46 72c0 38 50 98 50 98M72 72h74m-50 98s8.172-9.806 17.908-24" stroke="#000" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><path d="M146 72a50 50 0 1 0-6.699 25" stroke="#000" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

2024-02-01 05:59 UTC, merged

2024-02-01 06:01 UTC, Hamster45105 commented on svgs/triplej.svg
Thanks, I'll keep that in mind for next time.