+5 Icons
LawnchairLauncher/lawnicons pull request #1829
Opened 2024-02-14 14:17 UTC by airon-main

# Description

I've been trying lawnchair and then lawnicons. i was amazed by how simple yet incredible the apps are. so i tried making so much icons, turns out the guideline is outdated. so i remake some of the icons and make a new one

## Icons addition information

### Added
Get Current Wallpaper (`dk.appdictive.getcurrentwallpaper`)
PC Remote (`com.monect.portable`)
Quizizz (`com.quizizz_mobile`)
Milk Choco (`com.gameparadiso.milkchoco`)
Screen Dimmer (`com.github.ericytsang.screenfilter.app.android`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-02-14 14:27 UTC, airon-main commented
This is my first time contributing. What are the checks not successful about?. I've run the app and it runs completely fine

2024-02-14 14:40 UTC, x9136 requested changes

2024-02-14 14:40 UTC, x9136 commented on app/assets/appfilter.xml
>  What are the checks not successful about?

It's worth to add a space between `"` and `/>` everywhere.

2024-02-14 14:40 UTC, x9136 commented on svgs/pc_remote.svg
Wrong size (`158`×109px).

2024-02-14 14:40 UTC, x9136 commented on svgs/screen_dimmer.svg
![Screenshot 2024-02-14 at 17 36 29](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a96ae2eb-c3cf-44dd-9651-e82d3192acfe)
![Screenshot 2024-02-14 at 17 37 40](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d10fa02f-3ee6-4769-92c5-34b21019c7ae)

2024-02-15 04:34 UTC, airon-main commented on svgs/pc_remote.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/892164ef-9423-4536-a60e-2303a7c1262d)
Too large maybe?

2024-02-15 04:39 UTC, airon-main commented on app/assets/appfilter.xml
just committed 👍

2024-02-15 04:40 UTC, airon-main commented on svgs/screen_dimmer.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/132d7e58-cda2-4ba0-81ff-0ba688d410a8)

like this?

2024-02-15 04:41 UTC, airon-main commented on svgs/screen_dimmer.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/6d99435c-63fb-4335-b5ca-95ae5d7836e2)

like this?

2024-02-15 04:43 UTC, airon-main commented on svgs/screen_dimmer.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/008c32b8-6968-4289-9e89-277482856534)

2024-02-15 04:53 UTC, airon-main commented on svgs/pc_remote.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/8dafb43f-a109-4cbb-a9f4-58b545ecedb0)

maybe you mean like this

2024-02-15 06:26 UTC, x9136 requested changes

2024-02-15 06:26 UTC, x9136 commented on svgs/pc_remote.svg
Yes, the long side should be 160px.

2024-02-15 06:26 UTC, x9136 commented on svgs/screen_dimmer.svg
![Screenshot 2024-02-15 at 09 25 51](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/019233b9-b5ec-4565-b01d-62204ea76759)
If you want to round all corners, then don't forget to resize the shape after that.

![image](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d23ecd5f-82e5-4436-8816-e06e8c88e9fc)
It's enough to round the selected corners by 6px, though.

2024-02-17 04:39 UTC, airon-main commented
done commit on the screen dimmer :))

2024-02-17 04:42 UTC, airon-main commented on svgs/screen_dimmer.svg
Done commit 👍

2024-02-17 04:42 UTC, airon-main commented on svgs/screen_dimmer.svg
Sorry i had some school projects

2024-02-17 05:46 UTC, merged