+13 Icons
LawnchairLauncher/lawnicons pull request #1852
Opened 2024-02-22 08:50 UTC by airon-main

# Description

Second time contributing. there's a change i made on the gradle. i'll change it back if requested.
there are also some apps that i haven't found the activity, also some that i haven't filter which activity works and not. i'll get to them tomorrow, I'm real tired today

## Icons addition information

### Added
NeoBank (`com.bnc.finance`)
XArena (`com.transsion.smartpanel`)
Blynk (`cloud.blynk`)
Prayer Times (`com.reworewo.prayertimes`)
Modern Strike Online (`com.gamedevltd.modernstrike`)
Palm Store (haven't found the activity yet) (`com.transsnet.store`)
Zen Flip Clock (`com.mad.zenflipclock`)
Charge Meter (`dev.km.android.chargemeter`)
Noti Progress Bar (`com.gustavoas.noti`)
Touch the Notch (`com.notch.touch`)
DeskDock (`com.floriandraschbacher.deskdock.free`)
ClickUp (haven't found the activity yet) (`com.mangotechnologies.clickup`)
APK Info (`com.wt.apkinfo`)

## Contributor's checklist

- [ ] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-02-23 10:38 UTC, Chefski requested changes

2024-02-23 10:38 UTC, Chefski commented on svgs/noti_progress_bar.svg
The `n` got converted to a fill shape. Could you change it to a stroke?
<img width="378" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/8961f9ef-45f4-4381-8a3a-85be44553f9a">

2024-02-23 10:38 UTC, Chefski commented on svgs/xarena.svg
The icon is a bit bugged on the Github preview. If you can download the debug and check if it's fine in app would be good. The icons are sometimes bugged like on Github
<img width="203" alt="image" src="https://github.com/LawnchairLauncher/lawnicons/assets/100310118/74f3c218-4fb2-4d77-9dcd-c320aeaf7016">

2024-02-23 13:03 UTC, airon-main commented on svgs/noti_progress_bar.svg
yea sure

2024-02-23 13:19 UTC, airon-main commented on svgs/xarena.svg
I have retraced the old vector and still get the same result 😭😭

2024-02-23 13:26 UTC, airon-main commented on svgs/xarena.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/5c806086-6408-497d-b5c7-9f954e9ee5c5)
i've had enough

2024-02-23 13:30 UTC, airon-main commented
I'm just wondering. You know the activities of the app some time have a lot that even the one that has .MainActivity doesn't even work. Is it okay for me to just put all the activity that looks working, or do I need to filter down the non-working ones?

2024-02-23 22:22 UTC, airon-main commented
Alr all set. ready to merge

2024-02-24 00:06 UTC, airon-main commented
Oh wait. It's not ready, I've deleted the correct activity
 ![Screenshot_20240224-070554.jpg](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/5ac88a80-b394-405b-9cf3-44c5e3552937)

2024-02-24 03:53 UTC, airon-main commented
Aight, now it's all done

2024-02-25 12:41 UTC, airon-main commented
No merge?
![images (8).jpeg](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/60a11285-c051-419e-aeb0-3157d6c9f3d4)

2024-02-28 09:26 UTC, Chefski approved these changes

2024-02-28 09:26 UTC, merged