+13 icons
LawnchairLauncher/lawnicons pull request #1860
Opened 2024-02-28 12:01 UTC by airon-main

# Description

## Icons addition information

another 13 icons to contribute :). most of them are racing games and requested icons. gonna change some if requested
### Added
Asphalt 8 (`com.gameloft.android.ANMP.GloftA8HM`)
Awaker (`com.gilapps.screenon`)
Dhikr and Du'a (`com.alifewithallah.app`)
Dynasty Legends 2 (`com.newtypegames.dl2hmt`)
FR Legends (`com.fengiiley.frlegends`)
Hot Lap League (`com.ultimatestudio.hotlapleague.premium`)
Lemmy Redirect (`dev.zwander.lemmyredirect`)
Need for Speed: No Limits (`com.ea.game.nfs14_row`)
Privy (`com.privygate.privyid`)
Rush Rally 3 Demo (`brownmonster.app.game.rushrally3demo`)
Rush Rally Origin Demo (`brownmonster.app.game.rushrallyremastereddemo`)
Turnip Boy Commits Tax Evasion (`com.pid.turnipboy`)
Warden (`com.aurora.warden`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-02-29 09:29 UTC, x9136 requested changes

2024-02-29 09:29 UTC, x9136 commented on svgs/rush_rally_3_demo.svg
There's a lot of sloppiness in the number and letters on the Rush Rally icons, but it's hard and time-consuming to fix, so ok.

Basically, we need to find a way to neatly label that this is a demo and keep the "RO" and "R3" more geometrically correct.

2024-02-29 09:29 UTC, x9136 commented on svgs/turnip_boy_commits_tax_evasion.svg
![Screenshot 2024-02-29 at 12 04 36](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/715c2450-c778-4bc8-97de-2b652cc70aa5)
The crown is too dense, this is an easy fix. It is unlikely to save wrinkles without losing the quality of the icon.

2024-02-29 09:29 UTC, x9136 commented on svgs/warden.svg
It's a little big. Also, I'd move the cloak lines away from the person more so they don't stick together at small sizes.

Overall, it's hard to make this icon better, while there are plenty of comments that could be written. Limitations of Lawnicons style.

2024-02-29 09:29 UTC, x9136 commented on app/assets/appfilter.xml
The ampersand is written in Unicode.
```
name="Dhikr And Du'a" → name="Dhikr &amp; Dua"
```

It's also worth adding this line because Lemmy Redirect and Mastodon Redirect have the same icon.
```
<item component="ComponentInfo{dev.zwander.mastodonredirect/dev.zwander.mastodonredirect.MainActivity}" drawable="lemmy_redirect" name="Mastodon Redirect" />

```

2024-02-29 10:58 UTC, airon-main commented on svgs/awaker.svg
yea i just took the icon from the material icon from google and turn it into outlined.
gotta rework that

2024-02-29 10:58 UTC, airon-main commented on svgs/dynasty_legends_2.svg
you're not wrong 😭😭

2024-02-29 10:59 UTC, airon-main commented on svgs/fr_legends.svg
tried to make it more accurate.
see what i can do with it

2024-02-29 10:59 UTC, airon-main commented on svgs/privy.svg
noted

2024-02-29 11:00 UTC, airon-main commented on svgs/turnip_boy_commits_tax_evasion.svg
i don't think that's wrinkles.

2024-02-29 11:01 UTC, airon-main commented on svgs/warden.svg
perhaps i'll try making the head only/ or cloak only variation

2024-02-29 11:02 UTC, airon-main commented on app/assets/appfilter.xml
aight

2024-02-29 11:02 UTC, airon-main commented
got some things to do. i'll get to them in a moment

2024-02-29 11:35 UTC, airon-main commented on svgs/turnip_boy_commits_tax_evasion.svg
i kinda wanna keep the blush.
i also don't think there's alternative

2024-02-29 11:52 UTC, airon-main commented on svgs/dynasty_legends_2.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/62e0d56c-e156-41c2-93e0-4a39a6d8f9d7)
what do you think?

2024-02-29 12:09 UTC, airon-main commented on svgs/asphalt_8.svg
also how did you screenshot while holding down alt?

2024-02-29 13:56 UTC, x9136 commented on svgs/asphalt_8.svg
> also how did you screenshot while holding down alt?

Shift+Alt+4 on MacOS.

2024-02-29 13:56 UTC, x9136 commented on svgs/dynasty_legends_2.svg
> what do you think?

I think the mustache is too close to the muzzle, so it will clump together on the phone screen. There are very few icons where you have to sacrifice quality in favor of meaning, but in the rest it's easy to control spacing.

2024-02-29 13:56 UTC, x9136 commented on svgs/fr_legends.svg
I'd add as much space as possible, but that way you can spend a month reviewing. So okay.

2024-02-29 13:56 UTC, x9136 commented on svgs/turnip_boy_commits_tax_evasion.svg
It's up to you. I prefer quality.

> i also don't think there's alternative

That game has many characters.

2024-03-01 00:39 UTC, airon-main commented on svgs/asphalt_8.svg
man i use windows

2024-03-01 00:42 UTC, airon-main commented on svgs/hot_lap_league.svg
i also wanna make it as accurate as the original. does 3px radius allowed?

2024-03-01 00:46 UTC, airon-main commented on svgs/turnip_boy_commits_tax_evasion.svg
> That game has many characters.
i meant to replace the blush. 

circle wouldn't work. it's either there or none

2024-03-01 00:54 UTC, x9136 commented on svgs/hot_lap_league.svg
> does 3px radius allowed?

You'll find the exact answer if you read the Lawnicons guidelines.

2024-03-01 01:37 UTC, airon-main commented on svgs/turnip_boy_commits_tax_evasion.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/0c900d09-7ed7-4bb0-9008-4bb713c80bce)
also those are leaves. not crown

2024-03-01 03:06 UTC, airon-main commented on svgs/dynasty_legends_2.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/7cd4ec9c-ecc8-4f8f-97b1-5b08ce077da0)
like this?

2024-03-01 03:46 UTC, airon-main commented on svgs/warden.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/1937917f-eb24-4236-a829-2c29f2eca9f8)
both are good options imo.

2024-03-01 03:52 UTC, airon-main commented on svgs/warden.svg
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/6c26bf3b-ef38-4c43-9190-27486fdb89cf)
better i guess

2024-03-01 06:50 UTC, x9136 commented on svgs/warden.svg
It's hard to make this icon better than the first option. The new options have lost too much meaning and will be poorly recognizable.

2024-03-01 08:00 UTC, airon-main commented on svgs/warden.svg
i agree. it is difficult

2024-03-03 00:47 UTC, airon-main commented on svgs/warden.svg
any suggestion?

2024-03-03 00:56 UTC, x9136 commented on svgs/warden.svg
That was my only suggestion.
> I'd move the cloak lines away from the person more so they don't stick together at small sizes.

2024-03-03 01:19 UTC, x9136 commented on svgs/privy.svg
A little small now.

![Screenshot 2024-03-03 at 04 11 34](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9da64b2e-7275-4574-adf1-8656f2360b4a)

2024-03-03 01:19 UTC, x9136 commented on svgs/hot_lap_league.svg
90° angles should have been rounded by 6px, but we spent too much time on this icon, so I accept it as it is.

2024-03-04 00:14 UTC, airon-main commented on svgs/privy.svg
There's a border radius if you notice.

.5 pixel really matter
You really like quality. I respect that.

Aight sure

2024-03-04 07:33 UTC, x9136 commented on svgs/privy.svg
> .5 pixel really matter

If all icons are allowed such a size error, it will worsen the visual consistency of Lawnicons. Some icons will have a width of 159.5px, others with a height of 160.5px and so on. There is nothing difficult about keeping the size within 159.99—160.01px.

2024-03-04 07:35 UTC, merged