Added +2 icons and +2 links
LawnchairLauncher/lawnicons pull request #1871
Opened 2024-03-03 12:57 UTC by sujoybyte

# Description

## Icons addition information

### Added
Mini Mini Farm (`jp.coffeebreakin.app.minifarm`)
Haak (`com.blingame.haaktestb`)

### Linked
Mini Mini Farm (`jp.coffeebreakin.app.minifarm` → `mini_mini_farm.svg`)
Haak (`com.blingame.haaktestb` → `haak.svg`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-03 13:02 UTC, sujoybyte commented
Note: Haak's icon is inspired by it's earlier logo design as it was less detailed

2024-03-08 07:15 UTC, x9136 requested changes

2024-03-08 07:15 UTC, x9136 commented on svgs/haak.svg
![Screenshot 2024-03-08 at 09 54 28](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/385edb87-71bd-4b1e-a6d7-9a28e3493036)

I suggest working on the eyes to make the icon balanced. In the current version, the imbalance is caused by the difference between the stroke widths and the unnecessarily small distance between the shapes.

When you make a stroke inside the shape of the original image (for example, inside the face like here), the stroke width "eats up" the size of the shape (the face), so it's worth compensating for this, rather than making the contents of the shape as in the original.

2024-03-08 07:15 UTC, x9136 commented on svgs/mini_mini_farm.svg
![Screenshot 2024-03-08 at 10 13 06](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/0e124964-d72d-444f-888c-0002d3259734)
The 6px stroke is only used for small details. Otherwise, it is worth working on the balance by choosing closer stroke widths and increasing the distances between the shapes.

2024-03-08 23:40 UTC, x9136 commented on svgs/haak.svg
> I thought filled shapes will not be accepted.

You're right. It's all done with a stroke.

2024-03-09 12:53 UTC, sujoybyte commented on svgs/haak.svg
@x9136 have a look if its proper now.

2024-03-09 13:46 UTC, x9136 commented on svgs/haak.svg
It is better not to use a fill when almost the same thing can be done with a stroke.

![Screenshot 2024-03-09 at 16 46 02](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d4837c7a-7427-497e-a71f-ee7d57781611)

2024-03-09 18:19 UTC, sujoybyte commented on svgs/haak.svg
I did it exactly like you said.

2024-03-09 18:26 UTC, merged