+11 Icons, +1 link
LawnchairLauncher/lawnicons pull request #1875
Opened 2024-03-05 23:55 UTC by airon-main

# Description

MOOOREEE (btw sorry if i pr-ed too much. i'm a little addicted to it). Also, I'm going to commit some linked. it's night time in here so i'll commit tomorrow

## Icons addition information

### Added
TheFor (`xyz.thefor.habits.habits`)
Home Workout (`homeworkout.homeworkouts.noequipment`)
Pako Highway (`com.treemengames.pakohighway`)
Godot Editor 4 (`org.godotengine.editor.v4`)
Recharge RC (`com.HonduneGames.ReCharge`)
Polytopia (`air.com.midjiwan.polytopia`)
CarX Street (`com.carxtech.sr`)
Rebel Racing (`com.hutchgames.rebelracing`)
System UI Tuner (`com.bryancandi.android.uituner`)
R.A.C.E. (`com.smokoko.race`)
Power Marathon (`com.transsion.batterylab.icon`)

### Linked
Ruler (`org.nixgame.ruler` → `ruler`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-08 08:05 UTC, x9136 requested changes

2024-03-08 08:05 UTC, x9136 commented on svgs/power_marathon_icon.svg
There is a feeling that this app is now called BatteryLab. I hope you found and installed the apk to make sure that the app exists and is called Power Marathon.

In any case, all the icons that I found are far from your option. First of all, I suggest confirming the existence of the app through installation on the phone.

2024-03-08 08:05 UTC, x9136 commented on svgs/recharge_rc.svg
It is worth moving 1-2 px up.

2024-03-08 08:05 UTC, x9136 commented on svgs/system_ui_tuner.svg
![Screenshot 2024-03-08 at 11 04 08](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/cfe7a29d-4d2d-47bd-82ef-95e8da57ef7c)

2024-03-09 00:32 UTC, airon-main commented on svgs/power_marathon_icon.svg
![Screenshot_20240309-073103.jpg](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/1923ced4-bfb9-4b97-8760-1d48311c016c)

It does exist

2024-03-09 00:32 UTC, airon-main commented on svgs/recharge_rc.svg
Aight

2024-03-09 00:33 UTC, airon-main commented on app/assets/appfilter.xml
Got it

2024-03-09 00:33 UTC, airon-main commented on svgs/carx.svg
Sure

2024-03-09 00:36 UTC, airon-main commented on svgs/godot.svg
Noted

2024-03-09 00:36 UTC, airon-main commented on svgs/system_ui_tuner.svg
Yea. I usually forgot about that

2024-03-11 02:32 UTC, airon-main commented on app/assets/appfilter.xml
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/ceb525b9-e7da-432c-84af-9bc0aa04403a)

2024-03-11 09:14 UTC, x9136 commented on app/assets/appfilter.xml
As far as I can see, you need an explanation regarding the issue with appfilter.xml.

I do not know why you did not pay attention to the screenshot in the first comment, but even so, I cannot merge the PR until you are sure that Lawnicons builds correctly.

If the info in the screenshot does not help to figure out the issue, then the point is simple: the names of the icons should be the same as the drawables.

2024-03-12 04:45 UTC, airon-main commented on app/assets/appfilter.xml
oh...

the color is gray for the first screenshot

yea sorry about that

2024-03-12 04:53 UTC, airon-main commented on svgs/pako_highway.svg
figma export do get a bit quirky

2024-03-29 00:12 UTC, airon-main commented on app/assets/appfilter.xml
> ![Screenshot 2024-03-08 at 10 16 22](https://private-user-images.githubusercontent.com/60105060/311148680-361b30e6-ce23-4684-9683-1b5ec8731f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NzEyOTEsIm5iZiI6MTcxMTY3MDk5MSwicGF0aCI6Ii82MDEwNTA2MC8zMTExNDg2ODAtMzYxYjMwZTYtY2UyMy00Njg0LTk2ODMtMWI1ZWM4NzMxZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAwMDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMmMyNjQ4ODFhY2VmMzU3ODVlNTRhNzQyM2Q5OWI0NzQ0MDI5OTk5ZmU1NDg1MjdlNTA4YzJkZTMzMzg2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtttM2kjYiQVOno0jMXlLbwo4BgVwHOHsal8eLZFJTY)

![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/3c6682a9-f81d-466e-933c-956cfa21919d)

2024-03-29 00:12 UTC, airon-main commented on app/assets/appfilter.xml
it built fine in my device

2024-03-29 04:13 UTC, airon-main commented on app/assets/appfilter.xml
![image](https://github.com/LawnchairLauncher/lawnicons/assets/122789671/c819b6a7-0efa-4a6e-ad8d-df3bd7a72d9f)

2024-03-29 09:43 UTC, merged