Add 4, Link 1
LawnchairLauncher/lawnicons pull request #1912
Opened 2024-03-22 09:49 UTC by Hamster45105

# Description

Added 4 new icons, linked 1 and updated 1

## Icons addition information

### Added
Install with Options (`com.zwander.installwithoptions`)
AutoWeb (`com.joaomgcd.autoweb`)
Flowit! (`com.bytehamster.flowitgame`)
Kobo Books (`com.kobobooks.android`)

### Linked
aShell You (`in.hridayan.ashell` → `ladb.svg`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-22 13:54 UTC, x9136 requested changes

2024-03-22 13:54 UTC, x9136 commented on svgs/flowit.svg
It's a bit far from the original, although if you look at the game itself, the icon fits. I suggest 2 options:
1. Leave it as it is, but you need to raise the arrow a little so that it is in the center, not at the bottom.
2. Make the version closer to the original.

![Screenshot 2024-03-22 at 16 31 19](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/97d75173-7bc7-4d28-84c9-ae6fba389655)

2024-03-22 13:54 UTC, x9136 commented on svgs/install_with_options.svg
The size is too small, especially for a circle. I suggest trying to make a perfect circle and increase the distance between the lines, slightly simplifying the shape.
![Screenshot 2024-03-22 at 16 36 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/c19d4ca8-f19a-4dda-b047-ea82e70e1fa2)

2024-03-22 13:54 UTC, x9136 commented on svgs/kobo_books.svg
Although you forgot to round the right corners, I would suggest simplifying everything and using a 14px stroke.

The width of the lines in the original is too close to the base stroke width, so it is better to use 3 lines for the "K". Also, because of the 10px stroke, the icon would stand out from the rest.

![Screenshot 2024-03-22 at 16 52 55](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/555023a9-82c9-4a73-bc63-98259d184b67)

2024-03-23 06:20 UTC, x9136 commented on svgs/flowit.svg
1. 13px stroke width isn't allowed.
2. Corner radius for 90° angles is 6—32px.
3. It's not worth using 8px stroke in such an icon, because the difference between 12px and 8px breaks the balance, and you can make the icon look neat by limiting the strokes to 12px and 10px.

[The Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#tldr)

2024-03-23 06:38 UTC, Hamster45105 commented on svgs/flowit.svg
> Corner radius for 90° angles is 6—32px.

I've made it 6px, are there any specific requirements on this, or just whatever looks good?

2024-03-23 06:54 UTC, Hamster45105 commented on svgs/flowit.svg
> Corner radius for 90° angles is 6—32px.

Yeah sorry I forgot about that.

I've made it 6px, are there any specific requirements on this, or just whatever looks good?

2024-03-23 11:06 UTC, x9136 commented on svgs/flowit.svg
> I've made it 6px, are there any specific requirements on this, or just whatever looks good?

I do it depending on the original. If the original is not rounded at all, then 6px, and if the rounding is larger, then I do it as close as possible to the original.

2024-03-23 11:07 UTC, merged