Add +11 icons
LawnchairLauncher/lawnicons pull request #1916
Opened 2024-03-23 20:25 UTC by ScaredPenguinXXL

# Description

## Icons addition information
### Added 11 icons:
Add Text (`com.nand.addtext`)
Chroma Lab (`com.ilixa.chroma`)
Circle Cutter (`com.gohn.shapecutter`)
Infinite Design (`com.brakefield.idfree`)
Infinite Painter (`com.brakefield.painter`)
Pi (`ai.inflection.pi`)
Isybank (`com.intesasanpaolo.isybank.mobile`)
Lexis Audio Editor (`com.pamsys.lexisaudioeditor`)
Lose It! (`com.fitnow.loseit`)
Pixel Brush (`com.jaween.paint`)
Wave Lines Live Wallpaper (`de.markusfisch.android.wavelines`)

## Contributor's checklist
- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-23 21:57 UTC, x9136 requested changes
Hey! Thanks for contributing, I left a few comments.

2024-03-23 21:57 UTC, x9136 commented on app/assets/appfilter.xml
A lot of duplicates and spaces have been added, it is worth removing the excess.

2024-03-23 21:57 UTC, x9136 commented on svgs/infinite_design.svg
The width is a little big, it's worth making it 160px.

![Screenshot 2024-03-24 at 00 32 40](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/b43ed5e5-7943-48ce-a613-a14e935cba62)
Apart from the size, no changes are needed, but I'll show you what the alternative could be.

2024-03-23 21:57 UTC, x9136 commented on svgs/infinite_painter.svg
![Screenshot 2024-03-24 at 00 39 56](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/0e639d98-3217-4da6-80c7-a0398f2632cd)
It is worth slightly reducing the width, as well as connecting the points so that the strokes go smoothly.


![Screenshot 2024-03-24 at 00 36 57](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/f9933a23-0c52-40e8-a2ed-b9607b02a451)
Possible alternative.

2024-03-23 21:57 UTC, x9136 commented on svgs/isybank.svg
This icon is abstract in shape, so the size should be 160×160px.

2024-03-23 21:57 UTC, x9136 commented on svgs/pixel_brush.svg
![Screenshot 2024-03-24 at 00 49 03](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/6f65148d-1c14-4d68-9f63-b9afbe81bf29)
It's worth changing 12.05px to 12px, refining the height and moving the icon horizontally to the center.

2024-03-26 20:36 UTC, ScaredPenguinXXL reviewed
I have redone the Infinite Design and Infinite Painting Icons, deleted the duplicate calendar components and removed the extra white spaces. Style checks may now pass. I have also fixed stroke and sizing issues with the Pi, Pixel Brush and Isybank icons.

2024-03-26 20:53 UTC, x9136 commented on svgs/isybank.svg
![Screenshot 2024-03-26 at 23 46 47](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/3a64c387-31c3-4acf-a153-c4bd9feca367)
While minimal error is sometimes acceptable in the sizes, the stroke widths must be exact.

2024-03-26 20:53 UTC, x9136 commented on svgs/infinite_design.svg
Would you mind making the ellipse using a stroke (6×6px with 6px stroke width)?

2024-03-26 20:55 UTC, x9136 commented
There are important little things left.

2024-03-26 21:51 UTC, ScaredPenguinXXL commented on svgs/isybank.svg
My bad. I don't know why but Inkscape keeps changing values for no apparent reason. (Might be an issue with [Scour](https://github.com/scour-project/scour))
[Screencast from 2024-03-26 22-42-52.webm](https://github.com/LawnchairLauncher/lawnicons/assets/89851117/e94b9db9-a07b-4ed6-9339-3b0da5a239b9)

2024-03-26 22:20 UTC, x9136 commented on svgs/isybank.svg
> I don't know why but Inkscape keeps changing values for no apparent reason.


If you want to check if it's Scour or not, you can compare the stroke widths from the SVG codes. The strange values in the code are most likely due to the transform.

```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M70.284 170c0-54.896 44.505-99.296 99.296-99.296M22 170C22 88.233 88.233 22 170 22m-49.333 148c0-26.871 21.832-48.704 48.703-48.704" stroke="#000" stroke-width="12" stroke-linecap="round"/></svg>
```
If you're curious, it's the optimized `isybank.svg` from Figma. For some reason, it is more readable than from Scour.

I haven't worked in Inkscape, but I got the impression from dozens of reviews that there are difficulties with specifying exact sizes. The Google search also shows that people have issues with this. Although some contributors have found how to deal with it (I didn't ask, but I can see from the results).

2024-03-26 22:41 UTC, x9136 approved these changes

2024-03-26 22:42 UTC, merged