Add 2
LawnchairLauncher/lawnicons pull request #1920
Opened 2024-03-24 19:34 UTC by mwchiao

# Description
Adding 2 bird icons

## Icons addition information
### Added
* Audubon (`com.audubon.mobile.android/com.audubon.mobile.android.MainActivity`)
* whoBIRD (`org.woheller69.whobird/org.tensorflow.lite.examples.soundclassifier.MainActivity`)

## Contributor's checklist
- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-25 16:14 UTC, x9136 requested changes

2024-03-25 16:14 UTC, x9136 commented on svgs/audubon.svg
The smallest possible circle is 6×6px with 6px stroke. It's worth considering this and then probably move the edges of the bird around the eye a bit.

2024-03-25 16:14 UTC, x9136 commented on svgs/whobird.svg
The eye is better done with a stroke. Visually, the result will be the same. It is worth moving the ear a little farther away from the edge so that the gap is larger (keeping the gap between the eye and the ear almost the same as it is now).

2024-03-26 22:48 UTC, mwchiao commented on svgs/audubon.svg
I've shrunk the eye to a 6px stroke and widened the head by the eye a bit.

2024-03-26 22:48 UTC, mwchiao commented on svgs/whobird.svg
Replaced the circle with with a stroke and moved the eye + "ear" some pixels to the left

2024-03-26 22:59 UTC, x9136 commented on svgs/whobird.svg
It's hard to check this code, but visually it seems ok. If anything, we'll fix it later.

2024-03-26 23:04 UTC, x9136 commented on svgs/audubon.svg
I may not have been able to explain properly what is required, so keep the SVG to see without words.

```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 158s56-1.374 70-34-7-48-20-44c-11.47 3.529-12-19 0-20 19.93-1.66 26.61 11.269 31.611 16.269 8 8 17.579 12.77 17.579 12.77" stroke="#000" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><path d="M22 102c9 6 9.802 8.748 16.056 10 23.627 4.729 22.434-10.973 12.506-18-11.385-8.058-18.029-36.258 1.265-51.44 3.767-2.963 10.382-6.882 18.685-8.322 10.118-1.754 21.471-1.427 31.47.31 11.637 2.023 25.881 6.102 31.91 24.59" stroke="#000" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><path d="m172 136-40.863-38.325 5.092-5.595-.844-18.59L172 136Z" stroke="#000" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><circle cx="117" cy="63" r="3" stroke="#000" stroke-width="6"/></svg>
```

2024-03-26 23:29 UTC, mwchiao commented on svgs/audubon.svg
Oh so you want me to make the eye a circle instead of a stroke/dot? I totally misread your comment if that is what you meant, apologies.

2024-03-27 08:24 UTC, x9136 commented on svgs/audubon.svg
> Oh so you want me to make the eye a circle instead of a stroke/dot?

I only suggested the quickest way to create the eye, considering the Lawnicons guidelines.

2024-03-29 08:27 UTC, x9136 approved these changes

2024-03-29 08:27 UTC, merged