+4 Icons
LawnchairLauncher/lawnicons pull request #1931
Opened 2024-03-29 00:15 UTC by Hamster45105

# Description

## Icons addition information

### Added
Samsung Studio (`com.sec.android.app.vepreload`)
SqueezePlayer (`de.bluegaspode.squeezeplayer`)
Microsoft Translator (`com.microsoft.translator`)
SunSmart (`au.org.cancervic.globaluv`)

## Contributor's checklist

- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-03-29 09:20 UTC, x9136 requested changes

2024-03-29 09:20 UTC, x9136 commented on svgs/samsung_studio.svg
![Screenshot 2024-03-29 at 12 00 15](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/39bf3f99-e2a4-4883-90eb-d4ddd2a4c3fe)
It is worth rounding the corners of the pencil, taking into account the Lawnicons guidelines, and then adjust the size of the icon.

2024-03-29 09:20 UTC, x9136 commented on svgs/squeezeplayer.svg
The fill should be removed. The circles are too tiny, it won't work that way in the Lawnicons guidelines. The margins between them and the large circles are also too small. Also, the arrow is not centered.

![Screenshot 2024-03-29 at 12 17 07](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/2e19e18e-dce1-4305-820d-4fe52b3d1d9b)
If you reduce the stroke width of large circles to 10px, align the arrow and correct the size of small circles, you will get something like this.

![Screenshot 2024-03-29 at 12 15 09](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/7c4735aa-f617-4377-a803-fd3798bc1ee5)
If you leave 12px stroke width only at the outer circle, align the arrow and correct the size of the small circles, then it will turn out something like this.

2024-03-29 09:20 UTC, x9136 commented on svgs/sunsmart.svg
It is worth using 14px stroke width, because the icon has very few elements.

2024-03-29 09:23 UTC, x9136 commented on app/assets/appfilter.xml
> com.printeron.android.printplugin

name="PrinterOn" → name="PrinterOn Print Service"

2024-03-29 22:46 UTC, Hamster45105 commented on svgs/squeezeplayer.svg
I have fixed the circle sizes and centered the arrow.

Removing the fill results in a donut like shape, so is it OK to leave the fill in this case?

2024-03-30 02:19 UTC, Hamster45105 commented
Everything is fixed now.

It appears some of the stroke width/shape sizes problems had to do with me optimising the SVGs. Before they were optimised, everything was fine. However after I optimised them some stroke widths and sizes of some of the shapes changed.

2024-03-30 04:45 UTC, x9136 commented on svgs/microsoft_translator.svg
![Screenshot 2024-03-30 at 07 26 54](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/dfc48a3f-3729-44e9-8177-32639453c66e)

Right now, the icon is pressed to the left edge (visually), and the distance between the Chinese character elements is too small. I suggest at least reducing the stroke width of the Chinese character to 10px.

It may take a lot of time to carefully align such abstract shapes, so if something else can be corrected, it's good, but another time it will be better to redesign this icon, taking as a basis only the meaning and position of elements, not the original shapes.

2024-03-30 04:45 UTC, x9136 commented on svgs/squeezeplayer.svg
After reducing the width of the stroke, you forgot to increase the main circle, as a result the icon became too small.

![Screenshot 2024-03-30 at 07 41 03](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/ae908e01-de60-4f39-a029-dd86f7caa70d)
As for the small circles, in the examples I suggested, they are all made as 6×6px ellipses with 6px stroke width. Your options for small circles are not yet in line with Lawnicons guideline.

2024-03-30 05:17 UTC, Hamster45105 commented on svgs/microsoft_translator.svg
Looking better now

2024-03-30 06:05 UTC, x9136 commented on svgs/squeezeplayer.svg
> The circles are too tiny, it won't work that way in the Lawnicons guidelines. The margins between them and the large circles are also too small.

![Screenshot 2024-03-30 at 09 00 11](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/7d22bd21-5631-4766-9f64-3ebda4a70e67)
If you make the distances between the elements too small, then the elements will stick together on the phone screen, because the icons there are usually much smaller than on the computer screen. That's why I initially drew attention to this issue.

2024-03-30 06:24 UTC, x9136 approved these changes

2024-03-30 06:24 UTC, x9136 commented
Cool, thanks.

2024-03-30 06:24 UTC, merged

2024-03-30 06:25 UTC, Hamster45105 commented
No problem, thanks for the help!