Added 4 icons, linked 2
LawnchairLauncher/lawnicons pull request #1952
Opened 2024-04-01 20:36 UTC by Fxsch

# Description

Added icons for Alga, NextPush, AgoraDesk and Video Transcoder. Linked Mint Calculator to calculator icon and gptAssist to chatgpt icon.

## Icons addition information

### Added
AgoraDesk (`com.agoradesk.app`)
Alga (`tech.laihz.alga.arm64`)
NextPush (`org.unifiedpush.distributor.nextpush`)
Video Transcoder (`protect.videoeditor`)

### Linked
gptAssist (`org.woheller69.gptassist` → `chatgpt.svg`)
Mint Calculator (`bored.codebyk.mintcalc` → `calculator.svg`)

## Contributor's checklist

- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-04-01 20:55 UTC, x9136 requested changes

2024-04-01 20:55 UTC, x9136 commented on svgs/video_transcoder.svg
The fill should be replaced with a stroke, and the icon should be moved 2px down to compensate for the void.

2024-04-01 20:55 UTC, x9136 commented on app/assets/appfilter.xml
> gptAssist

I realize it's just a shell, but its icon is too different from ChatGPT. This will be a problem if both apps are installed. It's worth removing the link or adding a unique icon.

2024-04-03 23:35 UTC, Fxsch commented on svgs/video_transcoder.svg
Done

2024-04-04 00:09 UTC, Fxsch commented on app/assets/appfilter.xml
I made a unique icon for the app

2024-04-04 06:58 UTC, x9136 commented on svgs/gptassist.svg
It's worth to replace the fill with a stroke.

2024-04-04 15:59 UTC, x9136 commented on svgs/gptassist.svg
The eyes have become creepy, and the distance between them is too small.

![Screenshot 2024-04-04 at 18 52 14](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/373d5f22-c281-4def-a7f0-120b36ed2c4a)
It was enough to replace the fill with a stroke, preserving the look.

2024-04-04 15:59 UTC, x9136 approved these changes

2024-04-04 16:01 UTC, merged

2024-04-04 16:09 UTC, Fxsch commented on svgs/gptassist.svg
Yeah, I thought so too but I made the commit to see what it looks like in practice. But what's the advantage of making it an outline instead of a fill?

2024-04-04 17:14 UTC, Fxsch commented
Thanks for the explanation, I will keep that in mind for future icons I make