Add 3 Icons
LawnchairLauncher/lawnicons pull request #1972
Opened 2024-04-06 22:14 UTC by Hamster45105

# Description

Added 3 icons

## Icons addition information

### Added
Bonza Word Puzzle (`air.au.com.minimega.bonza`)*
Bin Reminder (`com.retfunsoft.binreminder`)
DAIKIN Mobile Controller (`ao.daikin.remoapp`)

\* 90° angles not curved because it spoils the shape. Additionally, an alternative is to have this without the dots, they symbolise the letters that are in the original icon.

## Contributor's checklist

- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-04-06 22:39 UTC, x9136 requested changes

2024-04-06 22:39 UTC, x9136 commented on svgs/bonza_word_puzzle.svg
![Screenshot 2024-04-07 at 01 36 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/6f414666-9426-4f5a-b2f5-056251020386)
It is better to connect these shapes to avoid artifacts at the intersection and an unnecessarily thick line.

2024-04-06 22:39 UTC, x9136 commented on svgs/daikin_mobile_controller.svg
![Screenshot 2024-04-07 at 01 34 55](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/a439d5f4-0f06-4845-b861-35be360d732d)
It is worth connecting such points so that the lines do not fall out of each other.

2024-04-07 08:07 UTC, x9136 requested changes

2024-04-07 08:07 UTC, x9136 commented on svgs/sony_auto_play.svg
![Screenshot 2024-04-07 at 11 05 45](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/07ec23eb-37f9-4e9a-97ff-57d600ec86e4)
The height is too small, and the legs are of different widths for some reason. I don't know why the circle is squared on the sides, and the legs are rounded, but I suggest doing the opposite — as in the original.

2024-04-07 09:26 UTC, x9136 commented
It is surprising that pixel-perfect is difficult in Inkscape. Almost all the icons that were made there have fractional numbers.

2024-04-07 09:26 UTC, merged

2024-04-08 01:07 UTC, Hamster45105 commented
> It is surprising that pixel-perfect is difficult in Inkscape. Almost all the icons that were made there have fractional numbers.

Yes, it's quite annoying

2024-04-08 06:42 UTC, x9136 commented
> Yes, it's quite annoying

If it doesn't matter to you where to create icons, then I suggest you try Figma. There is not such a wide range of work with vectors, but it may be more comfortable and faster.