Add more icons
LawnchairLauncher/lawnicons pull request #199
Opened 2021-12-09 09:40 UTC by prayag17

2021-12-11 16:50 UTC, arun54321 commented
CPU-Z doesn't resemble original icon. Could you make it similar to official icon?

2021-12-12 09:52 UTC, prayag17 commented
I have fixed the cpu_z icon

2021-12-22 18:29 UTC, patrykmichalik requested changes
Thanks for your interest in contributing! Here are some tweaks I’d suggest. Additionally, because there’s already an icon for Tidal in Lawnicons, I’d suggest removing the one from this pull request to avoid creating a duplicate.

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/amazon_alexa.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M12,2C6.4866,2 2,6.4864 2,12 2,16.9918 5.7262,21.2537 10.6967,21.9146 10.7831,21.9237 11.5571,22 12,22 17.5143,22 22,17.5137 22,12 22,6.4864 17.5143,2 12,2ZM18.292,13.0337c-0.7168,4.7254 -6.3274,7.3046 -6.965,7.5827l-1.2733,0.5564 -0.0018,-2.96c0,-0.0556 -0.0328,-0.1046 -0.0801,-0.12C7.3115,17.1982 5.5689,14.7109 5.6353,11.9037 5.7171,8.4064 8.5057,5.69 11.9972,5.69c0.0228,0 0.0456,0 0.0673,0 3.4752,0.0364 6.302,2.8909 6.302,6.3672 0,0.3256 -0.0246,0.6537 -0.0746,0.9764z"
      android:strokeWidth="1.11111"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/google_classroom.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m3,5v14a1,1 45,0 0,1 1h16a1,1 135,0 0,1 -1V5A1,1 45,0 0,20 4H4A1,1 135,0 0,3 5Z"
      android:strokeLineJoin="miter"
      android:strokeWidth="2"
      android:fillColor="#00000000"
      android:strokeColor="#000000"
      android:strokeLineCap="butt"/>
  <path
      android:pathData="M14,18h4v2h-4z"
      android:strokeWidth="2"
      android:fillColor="#000000"
      android:strokeColor="#00000000"/>
  <path
      android:pathData="m12,12c0.8288,0 1.5,-0.6712 1.5,-1.5 0,-0.8288 -0.6712,-1.5 -1.5,-1.5 -0.8288,0 -1.5,0.6712 -1.5,1.5 0,0.8288 0.6712,1.5 1.5,1.5zM12,12.75c-1.0013,0 -3,0.5025 -3,1.5L9,15h6v-0.75c0,-0.9975 -1.9987,-1.5 -3,-1.5z"
      android:strokeWidth="0.375"
      android:fillColor="#000000"/>
  <path
      android:pathData="M15.75,10.5C15.1284,10.5 14.625,11.0034 14.625,11.625C14.625,12.2466 15.1284,12.75 15.75,12.75C16.3716,12.75 16.875,12.2466 16.875,11.625C16.875,11.0034 16.3716,10.5 15.75,10.5zM15.75,13.3125C15.5794,13.3125 15.3699,13.3323 15.1484,13.3711C15.3508,13.6064 15.5,13.9079 15.5,14.25L15.5,15L18,15L18,14.4375C18,13.6894 16.5009,13.3125 15.75,13.3125zM14.0195,13.748C13.7132,13.9243 13.5,14.1551 13.5,14.4375L13.5,14.5L14.5,14.5L14.5,14.25C14.5,14.1676 14.4679,14.0883 14.332,13.9629C14.2558,13.8925 14.1469,13.8191 14.0195,13.748z"
      android:strokeWidth="0.28125"
      android:fillColor="#000000"/>
  <path
      android:pathData="M8.25,10.5C7.6284,10.5 7.125,11.0034 7.125,11.625C7.125,12.2466 7.6284,12.75 8.25,12.75C8.8716,12.75 9.375,12.2466 9.375,11.625C9.375,11.0034 8.8716,10.5 8.25,10.5zM8.25,13.3125C7.4991,13.3125 6,13.6894 6,14.4375L6,15L8.5,15L8.5,14.25C8.5,13.9079 8.6492,13.6064 8.8516,13.3711C8.6301,13.3323 8.4206,13.3125 8.25,13.3125zM9.9805,13.748C9.8531,13.8191 9.7442,13.8925 9.668,13.9629C9.5321,14.0883 9.5,14.1676 9.5,14.25L9.5,14.5L10.5,14.5L10.5,14.4375C10.5,14.1551 10.2868,13.9243 9.9805,13.748z"
      android:strokeWidth="0.28125"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/jellyfin.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m12.0012,9.6628c-0.8768,0 -3.7047,5.1272 -3.2749,5.9911 0.4298,0.8638 6.1242,0.8552 6.5496,0 0.4254,-0.8553 -2.3938,-5.9911 -3.2748,-5.9911z"
      android:fillColor="#000000"/>
  <path
      android:pathData="M12.0011,2C9.3538,2 0.8358,17.446 2.1337,20.0548c1.2979,2.6087 18.4499,2.5785 19.7349,0C23.1536,17.4761 14.6486,2 12.0011,2ZM18.4692,17.7941c-0.8423,1.689 -12.0808,1.7105 -12.9317,0C4.6865,16.0836 10.2692,5.9625 12.0011,5.9625c1.732,0 7.3104,10.1383 6.4681,11.8316z"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/mega.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M12,2C6.4767,2 2,6.4767 2,12 2,17.5233 6.4767,22 12,22 17.5233,22 22,17.5233 22,12 22,6.4767 17.5233,2 12,2ZM17.1917,15.5376c0,0.1708 -0.1383,0.3091 -0.3092,0.3091 -0.0008,0 -0.0008,0 -0.0016,0L15.575,15.8467 15.5741,15.8467c-0.1708,0 -0.3091,-0.1383 -0.3091,-0.3091v-0.0009,-4.0233c0,-0.0333 -0.0383,-0.05 -0.0667,-0.0274l-2.7667,2.7667c-0.1117,0.11 -0.265,0.1782 -0.435,0.1782 -0.17,0 -0.3233,-0.0682 -0.435,-0.1782L8.795,11.4859c-0.0225,-0.0226 -0.0667,-0.0059 -0.0667,0.0274v4.0233,0.0009c0,0.1708 -0.1383,0.3091 -0.3092,0.3091L8.4183,15.8467 7.1125,15.8467 7.1117,15.8467C6.9408,15.8467 6.8025,15.7083 6.8025,15.5376v-0.0009,-7.0725c0,-0.1717 0.1383,-0.31 0.31,-0.31L8.0092,8.1542C8.18,8.1558 8.335,8.225 8.4467,8.3375l3.4417,3.4416c0.0276,0.0283 0.0659,0.0459 0.1083,0.0459 0.0426,0 0.0809,-0.0176 0.1083,-0.0459L15.5467,8.3375C15.6633,8.2208 15.8176,8.1542 15.9842,8.1542L16.88,8.1542c0.1717,0 0.31,0.1383 0.31,0.31l0.0017,7.0725v0.0009z"
      android:strokeWidth="1.11111"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/mi_files.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m11.2716,4.2 l0.4566,0.6393v0.0002c0.1752,0.2452 0.2423,0.3261 0.2777,0.3539 0.05,0.0392 0.1069,0.0686 0.168,0.0865C12.2172,5.2926 12.3218,5.3 12.6233,5.3h6.7766c0.0676,0 0.1235,-0.0001 0.1854,-0.0004 -0.0012,-0.0025 -0.0021,-0.0052 -0.0033,-0.0076 -0.1917,-0.3763 -0.4977,-0.6823 -0.874,-0.874 -0.4278,-0.218 -0.9879,-0.218 -2.108,-0.218z"
      android:strokeWidth="0.1"
      android:fillColor="#000000"/>
  <path
      android:pathData="M7.8008,3C6.1206,3 5.2804,2.9992 4.6387,3.3262C4.0742,3.6138 3.6138,4.0742 3.3262,4.6387C2.9992,5.2804 3,6.1206 3,7.8008L3,16.1992C3,17.8794 2.9992,18.7195 3.3262,19.3613C3.6138,19.9258 4.0742,20.3862 4.6387,20.6738C5.2804,21.0008 6.1206,21 7.8008,21L16.1992,21C17.8794,21 18.7195,21.0008 19.3613,20.6738C19.9258,20.3862 20.3862,19.9258 20.6738,19.3613C21.0008,18.7195 21,17.8794 21,16.1992L21,7.4004C21,6.8403 20.9996,6.5596 20.8906,6.3457C20.7947,6.1575 20.6413,6.0041 20.4531,5.9082C20.2392,5.7992 19.9605,5.8008 19.4004,5.8008L12.623,5.8008C12.3215,5.8008 12.171,5.8001 12.0332,5.7598C11.9112,5.724 11.7973,5.6644 11.6973,5.5859C11.5843,5.4973 11.4975,5.3762 11.3223,5.1309L10.2793,3.6699C10.104,3.4245 10.0153,3.3015 9.9023,3.2129C9.8023,3.1344 9.6884,3.0768 9.5664,3.041C9.4286,3.0006 9.2781,3 8.9766,3L7.8008,3zM5.3887,13.8008L9.2656,13.8008C9.6398,13.8008 9.9749,13.8614 10.3418,14.2207C10.6925,14.5647 10.7246,14.9546 10.7246,15.2266L10.7246,18.5234C10.7246,18.5657 10.6898,18.5996 10.6465,18.5996L9.6289,18.5996C9.5853,18.5996 9.5488,18.5657 9.5488,18.5234L9.5488,15.5762C9.5488,15.2713 9.3746,14.8008 8.7578,14.8008L6.5645,14.8008C6.5209,14.8008 6.4844,14.8348 6.4844,14.877L6.4844,18.5234C6.4844,18.5657 6.4496,18.5996 6.4063,18.5996L5.3887,18.5996C5.3451,18.5996 5.3086,18.5657 5.3086,18.5234L5.3086,13.877C5.3086,13.8343 5.3451,13.8008 5.3887,13.8008zM11.7246,13.8008L12.7422,13.8008C12.7854,13.8008 12.8203,13.8343 12.8203,13.877L12.8203,18.5234C12.8203,18.5657 12.7854,18.5996 12.7422,18.5996L11.7246,18.5996C11.681,18.5996 11.6445,18.5657 11.6445,18.5234L11.6445,13.877C11.6445,13.8343 11.681,13.8008 11.7246,13.8008zM7.4824,15.6504L8.5527,15.6504C8.596,15.6504 8.6309,15.6841 8.6309,15.7266L8.6309,18.5234C8.6309,18.5656 8.596,18.5996 8.5527,18.5996L7.4824,18.5996C7.4388,18.5996 7.4043,18.5656 7.4043,18.5234L7.4043,15.7266C7.4043,15.6841 7.4388,15.6504 7.4824,15.6504z"
      android:strokeWidth="0.1"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/amazon_alexa.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg4"
   sodipodi:docname="amazon_alexa.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <sodipodi:namedview
     id="namedview6"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="17.354167"
     inkscape:cx="2.3913565"
     inkscape:cy="12.331333"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4" />
  <path
     d="M 12,2 C 6.4865889,2 2,6.4863667 2,12 2,16.991778 5.7262444,21.253667 10.696667,21.914556 10.783111,21.923667 11.557111,22 12,22 17.514333,22 22,17.513667 22,12 22,6.4863667 17.514333,2 12,2 Z m 6.292,11.033667 c -0.716778,4.725444 -6.327444,7.304555 -6.965,7.582666 l -1.273333,0.556445 -0.0018,-2.96 c 0,-0.05556 -0.03278,-0.104556 -0.08011,-0.12 C 7.3115,17.198222 5.5688889,14.710889 5.6352889,11.903667 5.7171444,8.4063667 8.5056889,5.69 11.997222,5.69 c 0.02278,0 0.04556,0 0.06733,0 3.475222,0.036367 6.302,2.8909111 6.302,6.367222 0,0.325556 -0.02456,0.653667 -0.07456,0.976445 z"
     fill="#000000"
     id="path2"
     style="stroke-width:1.11111" />
</svg>
```

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/google_classroom.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg4"
   sodipodi:docname="google_classroom.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8">
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect2616"
       is_visible="true"
       lpeversion="1"
       satellites_param="F,0,0,1,0,1,0,1 @ F,0,0,1,0,1,0,1 @ F,0,0,1,0,1,0,1 @ F,0,0,1,0,1,0,1"
       unit="px"
       method="auto"
       mode="F"
       radius="1"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="false"
       hide_knots="false" />
  </defs>
  <sodipodi:namedview
     id="namedview6"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="true"
     inkscape:snap-grids="true"
     inkscape:zoom="45.254834"
     inkscape:cx="11.788796"
     inkscape:cy="17.346213"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4">
    <inkscape:grid
       type="xygrid"
       id="grid849"
       empspacing="1" />
  </sodipodi:namedview>
  <path
     style="opacity:1;fill:none;stroke:#000000;stroke-width:2;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
     d="m 3,5 v 14 a 1,1 45 0 0 1,1 h 16 a 1,1 135 0 0 1,-1 V 5 A 1,1 45 0 0 20,4 H 4 A 1,1 135 0 0 3,5 Z"
     id="path884"
     sodipodi:nodetypes="ccccc"
     inkscape:path-effect="#path-effect2616"
     inkscape:original-d="M 3,4 V 20 H 21 V 4 Z" />
  <rect
     style="opacity:1;fill:#000000;fill-opacity:1;stroke:none;stroke-width:2;stroke-miterlimit:4;stroke-dasharray:none"
     id="rect1729"
     width="4"
     height="2"
     x="14"
     y="18" />
  <path
     d="m 12,12 c 0.82875,0 1.5,-0.67125 1.5,-1.5 0,-0.8287501 -0.67125,-1.5000001 -1.5,-1.5000001 -0.82875,0 -1.5,0.67125 -1.5,1.5000001 0,0.82875 0.67125,1.5 1.5,1.5 z m 0,0.75 c -1.00125,0 -3,0.5025 -3,1.5 V 15 h 6 v -0.75 c 0,-0.9975 -1.99875,-1.5 -3,-1.5 z"
     id="path1857"
     style="fill:#000000;stroke-width:0.375" />
  <path
     id="path2058"
     style="fill:#000000;stroke-width:0.28125"
     d="M 15.75 10.5 C 15.128438 10.5 14.625 11.003438 14.625 11.625 C 14.625 12.246563 15.128438 12.75 15.75 12.75 C 16.371562 12.75 16.875 12.246563 16.875 11.625 C 16.875 11.003438 16.371562 10.5 15.75 10.5 z M 15.75 13.3125 C 15.579437 13.3125 15.36986 13.332274 15.148438 13.371094 C 15.350818 13.606445 15.5 13.907929 15.5 14.25 L 15.5 15 L 18 15 L 18 14.4375 C 18 13.689375 16.500937 13.3125 15.75 13.3125 z M 14.019531 13.748047 C 13.713223 13.924343 13.5 14.155113 13.5 14.4375 L 13.5 14.5 L 14.5 14.5 L 14.5 14.25 C 14.5 14.167605 14.46786 14.088253 14.332031 13.962891 C 14.255774 13.892509 14.146922 13.819095 14.019531 13.748047 z " />
  <path
     id="path2142"
     style="fill:#000000;stroke-width:0.28125"
     d="M 8.25 10.5 C 7.6284375 10.5 7.125 11.003438 7.125 11.625 C 7.125 12.246563 7.6284375 12.75 8.25 12.75 C 8.8715625 12.75 9.375 12.246563 9.375 11.625 C 9.375 11.003438 8.8715625 10.5 8.25 10.5 z M 8.25 13.3125 C 7.4990625 13.3125 6 13.689375 6 14.4375 L 6 15 L 8.5 15 L 8.5 14.25 C 8.5 13.907929 8.6491818 13.606445 8.8515625 13.371094 C 8.6301403 13.332274 8.4205632 13.3125 8.25 13.3125 z M 9.9804688 13.748047 C 9.8530774 13.819095 9.7442256 13.892509 9.6679688 13.962891 C 9.5321399 14.088253 9.5 14.1676 9.5 14.25 L 9.5 14.5 L 10.5 14.5 L 10.5 14.4375 C 10.5 14.155113 10.286777 13.924343 9.9804688 13.748047 z " />
</svg>
```

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/hotstar.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg376"
   sodipodi:docname="hotstar.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs380" />
  <sodipodi:namedview
     id="namedview378"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="31.56"
     inkscape:cx="9.9968314"
     inkscape:cy="10.329531"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg376" />
  <g
     id="g1384"
     transform="matrix(1.1428713,0,0,1.1428713,0.57107494,0.57141048)">
    <path
       d="m 12.7429,11.9225 -0.2579,0.005 v 0.0021 l 0.2579,-0.005 z"
       fill="#000000"
       id="path2" />
    <path
       d="m 12.6963,9.81667 -0.2146,0.00416 v 0.0025 l 0.2146,-0.00416 z"
       fill="#000000"
       id="path4" />
    <path
       d="m 12.5483,3.12708 c 0,-0.02125 -0.0179,-0.03833 -0.0383,-0.03833 -0.0229,0 -0.0392,0.0175 -0.0392,0.03917 l 0.0063,3.8825 0.1571,-0.00292 z"
       fill="#000000"
       id="path6" />
    <path
       d="m 12.6496,7.71 -0.1713,0.00333 v 8.4e-4 l 0.1713,-0.00334 z"
       fill="#000000"
       id="path8" />
    <path
       d="M 12.665,8.41333 12.4792,8.41667 V 8.41792 L 12.665,8.41417 Z"
       fill="#000000"
       id="path10" />
    <path
       d="m 12.4921,16.39 v 0.0042 c 8e-4,0.0966 0.0829,0.1733 0.1779,0.1708 0.0971,-0.0017 0.1742,-0.0817 0.1717,-0.1788 l -0.0834,-3.7591 -0.2725,0.005 z"
       fill="#000000"
       id="path12" />
    <path
       d="m 12.7583,12.6271 -0.0154,-0.7025 -0.2579,0.005 8e-4,0.7025 z"
       fill="#000000"
       id="path14" />
    <path
       d="m 12.7271,11.2204 -0.2434,0.0046 0.0013,0.7025 0.2579,-0.005 z"
       fill="#000000"
       id="path16" />
    <path
       d="m 12.7117,10.5217 -0.2292,0.0041 0.0013,0.6992 0.2433,-0.0046 z"
       fill="#000000"
       id="path18" />
    <path
       d="m 12.4837,11.225 0.2434,-0.0046 z"
       fill="#000000"
       id="path20" />
    <path
       d="m 12.7117,10.5179 -0.0154,-0.69873 -0.2146,0.00416 8e-4,0.69917 z"
       fill="#000000"
       id="path22" />
    <path
       d="m 12.7117,10.5179 -0.2292,0.0046 v 0.0033 l 0.2292,-0.0041 z"
       fill="#000000"
       id="path24" />
    <path
       d="m 12.6808,9.11667 -0.2004,0.00375 0.0013,0.70041 0.2146,-0.00416 z"
       fill="#000000"
       id="path26" />
    <path
       d="M 12.6808,9.11458 12.665,8.41417 12.4792,8.41792 12.4804,9.11833 Z"
       fill="#000000"
       id="path28" />
    <path
       d="M 12.4804,9.11833 V 9.12042 L 12.6808,9.11667 V 9.11458 Z"
       fill="#000000"
       id="path30" />
    <path
       d="m 12.6496,7.71083 -0.1713,0.00334 9e-4,0.7025 0.1858,-0.00334 z"
       fill="#000000"
       id="path32" />
    <path
       d="M 12.6342,7.0075 12.4771,7.01042 12.4783,7.71333 12.6496,7.71 Z"
       fill="#000000"
       id="path34" />
    <path
       d="m 13.5092,13.4329 -0.4242,0.0254 v 0.0025 l 0.4242,-0.0254 z"
       fill="#000000"
       id="path36" />
    <path
       d="m 13.1979,9.50167 -0.2991,0.01791 v 8.4e-4 L 13.1979,9.5025 Z"
       fill="#000000"
       id="path38" />
    <path
       d="M 12.6558,2.64792 C 12.6542,2.62625 12.6358,2.61 12.6146,2.61 c -4e-4,0 -8e-4,0 -0.0013,0 -0.0233,8.3e-4 -0.04,0.02042 -0.0383,0.04292 l 0.2496,5.28833 0.2491,-0.015 z"
       fill="#000000"
       id="path40" />
    <path
       d="m 13.3225,11.0738 -0.3492,0.0212 v 0.0025 l 0.3492,-0.0208 z"
       fill="#000000"
       id="path42" />
    <path
       d="M 13.1358,8.71375 12.8617,8.73 v 0.00125 l 0.2741,-0.01667 z"
       fill="#000000"
       id="path44" />
    <path
       d="m 13.3217,18.4733 c 0.0012,0.0025 0.0012,0.0067 0.0012,0.0096 0.0138,0.16 0.1554,0.2796 0.3159,0.2658 0.1612,-0.0141 0.2799,-0.1554 0.2658,-0.317 l -0.3334,-4.21 -0.4495,0.027 z"
       fill="#000000"
       id="path46" />
    <path
       d="m 13.5717,14.2221 -0.0625,-0.7867 -0.4242,0.0254 0.0371,0.7884 z"
       fill="#000000"
       id="path48" />
    <path
       d="m 13.4471,12.6463 -0.3996,0.0241 0.0375,0.7879 0.4242,-0.0254 z"
       fill="#000000"
       id="path50" />
    <path
       d="m 13.385,11.8633 -0.3746,0.0225 0.0371,0.7842 0.3996,-0.0237 z"
       fill="#000000"
       id="path52" />
    <path
       d="m 13.0475,12.67 v 4e-4 l 0.3996,-0.0241 z"
       fill="#000000"
       id="path54" />
    <path
       d="m 13.3846,11.8596 -0.0621,-0.7829 -0.3492,0.0208 0.0371,0.7846 z"
       fill="#000000"
       id="path56" />
    <path
       d="m 13.3846,11.8596 -0.3742,0.0225 v 0.0037 l 0.3746,-0.0225 z"
       fill="#000000"
       id="path58" />
    <path
       d="m 13.2604,10.2896 -0.3242,0.0191 0.0371,0.7863 0.3492,-0.0213 z"
       fill="#000000"
       id="path60" />
    <path
       d="m 13.2604,10.2871 -0.0625,-0.7846 -0.2991,0.01792 0.037,0.78628 z"
       fill="#000000"
       id="path62" />
    <path
       d="m 12.9358,10.3067 5e-4,0.0021 0.3241,-0.0192 v -0.0025 z"
       fill="#000000"
       id="path64" />
    <path
       d="m 13.1358,8.71458 -0.2741,0.01667 0.0371,0.78833 0.2991,-0.01791 z"
       fill="#000000"
       id="path66" />
    <path
       d="M 13.0733,7.92667 12.8246,7.94167 12.8617,8.73 13.1358,8.71375 Z"
       fill="#000000"
       id="path68" />
    <path
       d="M 7.26208,6.84583 7.15167,7.19667 7.15458,7.1975 7.265,6.84667 Z"
       fill="#000000"
       id="path70" />
    <path
       d="m 17.3258,10.5692 c 0.0117,0.0046 0.0259,0.0083 0.0363,0.0112 0.3008,0.0771 0.6062,-0.1046 0.6833,-0.4046 C 18.1204,9.87709 17.9404,9.57167 17.64,9.495 L 14.7629,8.76083 14.4892,9.62917 Z"
       fill="#000000"
       id="path72" />
    <path
       d="M 3.26083,5.82458 C 3.25833,5.82375 3.255,5.82375 3.25167,5.82375 3.23583,5.82375 3.22,5.83458 3.215,5.85125 3.20833,5.87042 3.21958,5.89292 3.24,5.89958 L 6.10083,6.84792 6.18792,6.57167 Z"
       fill="#000000"
       id="path74" />
    <path
       d="m 13.445,9.2825 1.0438,0.34625 0.2741,-0.86833 -1.0675,-0.2725 z"
       fill="#000000"
       id="path76" />
    <path
       d="m 12.6283,8.21542 -0.2275,0.72125 1.0371,0.34375 0.2509,-0.79417 z"
       fill="#000000"
       id="path78" />
    <path
       d="M 13.6888,8.48625 13.4379,9.28042 13.445,9.2825 13.6954,8.48792 Z"
       fill="#000000"
       id="path80" />
    <path
       d="m 11.5558,7.94208 -0.2037,0.64667 1.0421,0.34542 0.2271,-0.72042 z"
       fill="#000000"
       id="path82" />
    <path
       d="m 12.6213,8.21375 -0.2271,0.72042 0.0066,0.0025 0.2275,-0.72125 z"
       fill="#000000"
       id="path84" />
    <path
       d="M 10.4837,7.66833 10.3029,8.24125 11.35,8.58833 11.5542,7.94125 Z"
       fill="#000000"
       id="path86" />
    <path
       d="M 11.5542,7.94125 11.35,8.58833 11.3521,8.58875 11.5558,7.94208 Z"
       fill="#000000"
       id="path88" />
    <path
       d="M 9.41125,7.39458 9.25417,7.89333 10.3013,8.24042 10.4817,7.66792 Z"
       fill="#000000"
       id="path90" />
    <path
       d="m 10.4817,7.66792 -0.1804,0.5725 0.0016,8.3e-4 0.1809,-0.57292 z"
       fill="#000000"
       id="path92" />
    <path
       d="M 8.33917,7.12083 8.205,7.54583 9.25208,7.89292 9.40958,7.39417 Z"
       fill="#000000"
       id="path94" />
    <path
       d="M 9.40958,7.39417 9.25208,7.89292 9.25417,7.89333 9.41125,7.39458 Z"
       fill="#000000"
       id="path96" />
    <path
       d="M 8.33708,7.12042 7.265,6.84667 7.15458,7.1975 8.20333,7.545 Z"
       fill="#000000"
       id="pa [...]

2021-12-22 18:29 UTC, patrykmichalik commented on app/src/main/res/drawable/hotstar.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M8.0612,16.1749 L7.1921,16.5197 7.3388,16.8921 8.3183,16.5864 8.5497,16.5145 8.3678,16.0535ZM9.545,15.5863 L9.7617,16.1359 9.7636,16.1354 9.5474,15.5854zM9.4293,16.2397 L9.7617,16.1359 9.545,15.5863 9.1093,15.7593 8.7326,15.9087 8.3712,16.0521 8.5531,16.5131 9.035,16.3626ZM10.7188,15.1206 L10.9703,15.7588 10.9722,15.7582L10.7212,15.1202ZM9.5474,15.5854 L9.7636,16.1354 10.9703,15.7588 10.7188,15.1206zM11.8926,14.6554 L12.1789,15.3817 12.1812,15.3806 11.8946,14.6544zM11.7584,14.7087 L10.7212,15.1202 10.9722,15.7582 12.1393,15.394 12.1789,15.3817 11.8926,14.6554zM13.0664,14.1896 L13.3875,15.0045 13.3897,15.0035 13.0684,14.1887zM12.7555,14.313 L11.8946,14.6544 12.1812,15.3806 13.1765,15.0701 13.3875,15.0044 13.0664,14.1896zM14.235,13.7263 L14.5903,14.6287 14.5983,14.6263 14.2422,13.723zM13.4875,14.0225 L13.0684,14.1887 13.3899,15.0035 13.8983,14.845 14.5903,14.6287 14.235,13.7263zM15.7937,14.2535 L15.8012,14.2507 15.4108,13.2597 15.4031,13.2625zM14.2422,13.723 L14.5984,14.6263 15.7937,14.2535 15.4031,13.2625zM15.4108,13.2597 L15.8012,14.2507 17.0041,13.8753 16.5794,12.7964zM21.0089,11.8149C20.8975,11.5315 20.6261,11.3592 20.3403,11.3592c-0.0886,0 -0.1785,0.0157 -0.2657,0.0509l-3.4952,1.3862 0.4253,1.079 3.5495,-1.108c0.0186,-0.0057 0.0352,-0.011 0.051,-0.0182 0.3695,-0.1466 0.5519,-0.5657 0.4038,-0.9343zM2.8002,18.2616c-0.011,0.0048 -0.0171,0.0158 -0.0129,0.0277 0.0033,0.0119 0.0162,0.0181 0.0271,0.0152L7.3393,16.8921 7.1926,16.5197ZM8.3678,16.0535 L8.5497,16.5145 8.5531,16.5131 8.3712,16.0521ZM5.6097,16.963 L5.6421,17.0336 6.3588,16.7307 6.3192,16.6435zM6.3202,16.643 L6.3597,16.7302 7.0769,16.4274 7.0292,16.3239zM7.7926,16.125 L7.7945,16.1244 7.7393,16.0039 7.7374,16.005zM7.7374,16.005 L7.0302,16.3235 7.0778,16.4268 7.7926,16.125zM7.7393,16.0039 L7.7945,16.1245 8.5093,15.8226 8.4464,15.6859zM9.1545,15.3668 L9.225,15.5202 9.2283,15.5188 9.1583,15.3654ZM9.1545,15.3668 L8.4488,15.685 8.5117,15.8217L9.225,15.5202ZM9.9417,15.2173 L9.864,15.0478L9.8636,15.0478ZM9.1583,15.3654 L9.2283,15.5188 9.9417,15.2173 9.8636,15.0478ZM9.864,15.0478 L9.9417,15.2173 10.6583,14.9149 10.5731,14.7283zM11.3774,14.6111 L11.2841,14.4083 10.575,14.7272 10.6607,14.914zM3.4625,17.9297c-0.0052,0.0019 -0.0091,0.0086 -0.0052,0.0149 0.0019,0.0051 0.0076,0.008 0.0152,0.0051L5.6416,17.0336 5.6092,16.963ZM8.4464,15.6859 L8.5093,15.8226 8.5117,15.8217 8.4488,15.685zM7.0292,16.3239 L7.0769,16.4273 7.0778,16.4268 7.0302,16.3235zM10.575,14.7274 L10.5731,14.7283 10.6583,14.9149 10.6607,14.914zM6.3192,16.6435 L6.3588,16.7307 6.3597,16.7301 6.3202,16.643zM13.1217,13.8744c0,-0.0009 0.0018,-0.0009 0.0038,-0.0024 0.0662,-0.0299 0.0967,-0.1086 0.0662,-0.1757 -0.0224,-0.0501 -0.0705,-0.0786 -0.1214,-0.0786 -0.0186,0 -0.0377,0.0033 -0.0553,0.0114l-1.7305,0.7791 0.0929,0.2029zM11.5817,16.1402 L11.035,15.4188 10.7312,15.6116 11.3041,16.3159ZM10.4874,14.6964 L10.1579,14.9059 10.7307,15.6102 11.0341,15.4178ZM9.584,14.2002 L9.586,14.2021 9.9417,13.9764 9.9398,13.9744ZM9.9417,13.9764 L9.586,14.2021 10.1569,14.905 10.4864,14.6954zM9.9398,13.9744 L9.395,13.2553 9.0131,13.4977 9.584,14.2002ZM8.4383,12.7906 L8.4412,12.794 8.8488,12.5353 8.8464,12.5316ZM8.8488,12.5353 L8.4412,12.794 9.0112,13.4953 9.3931,13.2529ZM8.3021,11.8139 L7.8683,12.0892l0,0.0005l0.4343,-0.2757zM8.3026,11.8139 L7.8683,12.0896 8.4383,12.7906 8.8464,12.5316zM8.3021,11.8139L7.7559,11.093 7.2959,11.3849 7.8683,12.0892ZM7.2074,10.3696 L6.7212,10.6782 7.294,11.383 7.754,11.0906ZM9.3931,13.2529 L9.0112,13.4953 9.0131,13.4977 9.395,13.2553zM15.2574,21.1793c0.0209,0.0238 0.0558,0.0281 0.08,0.009 0.0253,-0.0186 0.029,-0.0543 0.011,-0.0795L11.5812,16.1393 11.3041,16.3154ZM4.5692,6.8896C4.5673,6.8858 4.563,6.882 4.5611,6.8796 4.4906,6.7915 4.3868,6.7463 4.2821,6.7463 4.2025,6.7463 4.1216,6.7724 4.0559,6.8272 3.9006,6.952 3.8768,7.1786 4.0025,7.3344l2.7186,3.3443 0.4862,-0.3086zM11.0341,15.4178 L10.7307,15.6102 10.7312,15.6116 11.035,15.4188ZM10.4864,14.6954 L10.1569,14.905 10.1579,14.9059 10.4874,14.6964zM7.754,11.0906 L7.294,11.383 7.2959,11.3849 7.7559,11.093ZM11.3703,16.8787 L10.7993,16.1787 10.606,16.3206 11.1907,17.0101ZM10.2279,15.4778 L10.0207,15.6297 10.6055,16.3193 10.7983,16.1778ZM9.4355,14.9392 L9.4369,14.9411 9.6579,14.7792 9.6564,14.7768ZM9.6579,14.7792 L9.4369,14.9411 10.0198,15.6287 10.2269,15.4769zM9.6564,14.7768 L9.0874,14.0792 8.8526,14.2516l0.5829,0.6877zM8.2659,13.5592 L8.2688,13.5625 8.5174,13.3801 8.515,13.3768zM8.5174,13.3801 L8.2688,13.5625 8.8507,14.2492L9.0855,14.0768ZM7.9469,12.6806 L7.6845,12.873ZM7.9469,12.6806 L7.6845,12.8729 8.2659,13.5592 8.515,13.3768zM7.9469,12.6806L7.3764,11.9806 7.0997,12.1834 7.6845,12.873ZM6.804,11.2787L6.5135,11.4915 7.0983,12.1815 7.3745,11.9787ZM5.4402,9.6063c0,0 -0.0019,-0.0019 -0.0019,-0.0029C5.3988,9.5572 5.3426,9.5329 5.2859,9.5329 5.2392,9.5329 5.193,9.5487 5.1554,9.5815 5.0711,9.6515 5.0611,9.7787 5.1335,9.863L6.514,11.4915 6.8045,11.2787ZM9.0855,14.0768 L8.8507,14.2492 8.8526,14.2516 9.0874,14.0792ZM14.1936,20.553c0.0238,0.0277 0.0647,0.0314 0.0923,0.0086 0.0301,-0.0238 0.0347,-0.0662 0.0105,-0.0943l-2.9262,-3.5886 -0.1795,0.1314zM10.2269,15.4769 L10.0198,15.6287l0.0009,0.0009 0.2071,-0.1519zM7.3745,11.9787 L7.0983,12.1816 7.0997,12.1834 7.3764,11.9806ZM10.7983,16.1778 L10.6055,16.3193 10.606,16.3206 10.7993,16.1788ZM7.4664,12.2397 L7.2921,12.1221 6.7197,12.9015 6.8731,13.0054ZM8.0607,11.473 L7.8655,11.3411 7.2931,12.1206 7.4674,12.2386ZM8.4383,10.5596 L8.4369,10.562 8.6536,10.7082 8.655,10.7063ZM8.6536,10.7082L8.4369,10.562 7.8659,11.3396 8.0616,11.472ZM8.655,10.7063 L9.2469,9.9425 9.0093,9.782 8.4383,10.5596ZM9.5836,8.9996 L9.5807,9.0034 9.8393,9.1782 9.8421,9.1744ZM9.8393,9.1782 L9.5807,9.0034 9.0112,9.7796 9.2488,9.9401ZM10.4326,8.4125 L10.1531,8.2234l0,0.0005zM10.4326,8.4125 L10.1531,8.2239 9.5836,8.9996 9.8421,9.1744zM10.4326,8.4125 L11.026,7.6467L10.7255,7.4439 10.1531,8.2234ZM11.6212,6.8786 L11.2998,6.662 10.7274,7.4415 11.0279,7.6444ZM7.4674,12.2388 L7.2931,12.1206 7.2921,12.1221 7.4664,12.2397zM15.0708,2.4276 L15.0746,2.4219C15.1603,2.301 15.1317,2.1343 15.0108,2.0491 14.9636,2.0162 14.9098,2 14.8561,2c-0.0834,0 -0.1657,0.0391 -0.2176,0.1129l-3.3387,4.5491 0.3214,0.2171zM11.0279,7.6444 L10.7274,7.4415 10.7255,7.4439 11.026,7.6467ZM9.2488,9.9401 L9.0112,9.7796 9.0093,9.782 9.2469,9.9425ZM8.0616,11.472 L7.8659,11.3396 7.8655,11.3411 8.0607,11.473ZM6.7197,12.9016 L3.5592,17.2074c-0.0076,0.0099 -0.0043,0.0242 0.0052,0.0309 0.0105,0.0072 0.0243,0.0048 0.0319,-0.0047l3.2772,-4.2286zM6.5511,13.5821 L6.6369,13.6478 7.2192,12.9577 7.115,12.8777zM7.1154,12.8768 L7.2202,12.9568L7.8026,12.2668 7.6793,12.1725ZM8.3845,11.5777 L8.3859,11.5758 8.244,11.4673 8.2426,11.4696ZM8.2426,11.4696 L7.6802,12.1716 7.8035,12.2658 8.3845,11.5777ZM8.244,11.4673 L8.3859,11.5758 8.9669,10.8877 8.8059,10.7653ZM9.3693,10.062 L9.5483,10.1987 9.5512,10.1953 9.3717,10.0587ZM9.3693,10.062L8.8078,10.763 8.9688,10.8853 9.5483,10.1987ZM10.1307,9.5091L10.1307,9.5087L9.9331,9.3577 9.9326,9.3582ZM9.3717,10.0587 L9.5512,10.1953 10.1307,9.5091 9.9326,9.3582ZM9.9331,9.3577 L10.1307,9.5087 10.7131,8.8191 10.4964,8.6539ZM11.0622,7.9477 L10.4983,8.652 10.7145,8.8167 11.2969,8.1267ZM7.6793,12.1725 L7.8026,12.2668 7.8035,12.2658L7.6802,12.1716ZM13.9088,5.0324C13.9098,5.0315 13.9103,5.0296 13.9103,5.0286 13.9807,4.9424 13.966,4.8162 13.8794,4.7472 13.8427,4.7177 13.7983,4.7034 13.755,4.7034c-0.0585,0 -0.1171,0.0252 -0.1557,0.0752L11.0622,7.9477 11.2974,8.1272ZM4.7521,15.8292c-0.0048,0.0077 -0.0048,0.0176 0.0024,0.0243 0.0081,0.0051 0.0171,0.0047 0.0233,-0.0029L6.6373,13.6478 6.5511,13.5821ZM7.115,12.8777 L7.2192,12.9577 7.2202,12.9568 7.1154,12.8768zM8.8059,10.7653 L8.9669,10.8877 8.9688,10.8853 8.8078,10.763ZM10.4964,8.6539 L10.7131,8.8191 10.7145,8.8167 10.4983,8.652ZM7.1278,12.1696 L7.0331,12.1034 6.52 [...]

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/jellyfin.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg6"
   sodipodi:docname="jellyfin.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs10" />
  <sodipodi:namedview
     id="namedview8"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="17.354167"
     inkscape:cx="4.9843938"
     inkscape:cy="13.080432"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg6" />
  <g
     id="g928"
     transform="matrix(1.1111048,0,0,1.1111048,-1.3332452,-1.3333144)">
    <path
       d="m 12.0011,9.8966 c -0.7891,0 -3.33421,4.6145 -2.94741,5.392 0.38679,0.7774 5.51181,0.7697 5.89471,0 0.3829,-0.7698 -2.1544,-5.392 -2.9473,-5.392 z"
       fill="#000000"
       id="path2" />
    <path
       d="M 12.001,3 C 9.6184,3 1.95217,16.9015 3.12028,19.2494 c 1.16812,2.3478 16.60502,2.3207 17.76152,0 C 22.0383,16.9286 14.3837,3 12.001,3 Z m 5.8213,14.2148 c -0.7581,1.5201 -10.87277,1.5395 -11.63862,0 C 5.41783,15.6753 10.4423,6.56627 12.001,6.56627 c 1.5588,0 6.5794,9.12453 5.8213,10.64853 z"
       fill="#000000"
       id="path4" />
  </g>
</svg>
```

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/mega.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg4"
   sodipodi:docname="mega.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <sodipodi:namedview
     id="namedview6"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="34.708333"
     inkscape:cx="12"
     inkscape:cy="11.985594"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4" />
  <path
     d="M 12,2 C 6.4766667,2 2,6.4766667 2,12 2,17.523333 6.4766667,22 12,22 17.523333,22 22,17.523333 22,12 22,6.4766667 17.523333,2 12,2 Z m 5.191667,13.537556 c 0,0.170777 -0.138334,0.309111 -0.309223,0.309111 -7.77e-4,0 -7.77e-4,0 -0.0016,0 H 15.575 15.574111 c -0.170778,0 -0.309111,-0.138334 -0.309111,-0.309111 v -8.89e-4 -4.023334 c 0,-0.03333 -0.03833,-0.05 -0.06667,-0.02744 l -2.766666,2.766667 c -0.111667,0.11 -0.265,0.178222 -0.435,0.178222 -0.17,0 -0.323334,-0.06822 -0.435,-0.178222 L 8.795,11.485889 c -0.0225,-0.02256 -0.066667,-0.0059 -0.066667,0.02744 v 4.023334 8.89e-4 c 0,0.170777 -0.1383333,0.309111 -0.3091666,0.309111 H 8.4183333 7.1125 7.1116667 C 6.9408333,15.846667 6.8025,15.708333 6.8025,15.537556 v -8.89e-4 -7.0725003 c 0,-0.1716667 0.1383333,-0.31 0.31,-0.31 H 8.0091667 C 8.18,8.1558333 8.335,8.225 8.4466667,8.3375 l 3.4416663,3.441611 c 0.02756,0.02833 0.06589,0.04589 0.108334,0.04589 0.04256,0 0.08089,-0.01756 0.108333,-0.04589 L 15.546667,8.3375 C 15.663333,8.2208333 15.817556,8.1541667 15.984222,8.1541667 H 16.88 c 0.171667,0 0.31,0.1383333 0.31,0.31 l 0.0017,7.0725003 v 8.89e-4 z"
     fill="#000000"
     id="path2"
     style="stroke-width:1.11111" />
</svg>
```

2021-12-22 18:29 UTC, patrykmichalik commented on svgs/mi_files.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg8"
   sodipodi:docname="mi_files.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs12" />
  <sodipodi:namedview
     id="namedview10"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:lockguides="true"
     inkscape:zoom="17.354167"
     inkscape:cx="-15.356543"
     inkscape:cy="15.788715"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg8"
     inkscape:snap-smooth-nodes="true"
     inkscape:snap-midpoints="true"
     inkscape:snap-intersection-paths="true"
     inkscape:object-paths="true" />
  <path
     id="path2532"
     d="m 11.271584,4.199996 0.45664,0.639258 v 2e-4 c 0.175151,0.245189 0.242289,0.32609 0.277735,0.353906 0.04999,0.039234 0.106939,0.068628 0.167968,0.086523 C 12.217184,5.29256 12.321792,5.3 12.623341,5.3 h 6.776563 c 0.06756,0 0.123508,-6.6e-5 0.185351,-4e-4 -0.0012,-0.00245 -0.0021,-0.00518 -0.0033,-0.00762 -0.1917,-0.37633 -0.497723,-0.682284 -0.874023,-0.874024 -0.4278,-0.21799 -0.987908,-0.217969 -2.108008,-0.217969 z"
     style="fill:#000000;stroke-width:0.1"
     sodipodi:nodetypes="cccccssccccc" />
  <path
     id="path2534"
     style="fill:#000000;fill-opacity:1;stroke-width:0.1"
     d="M 7.8007812 3 C 6.1206222 3 5.2804019 2.9991919 4.6386719 3.3261719 C 4.0741818 3.6137929 3.6137929 4.0741819 3.3261719 4.6386719 C 2.9991919 5.2804019 3 6.1206212 3 7.8007812 L 3 16.199219 C 3 17.879418 2.9991919 18.719528 3.3261719 19.361328 C 3.6137929 19.925828 4.0741818 20.386228 4.6386719 20.673828 C 5.2804019 21.000828 6.1206222 21 7.8007812 21 L 16.199219 21 C 17.879419 21 18.719528 21.000828 19.361328 20.673828 C 19.925829 20.386228 20.386227 19.925828 20.673828 19.361328 C 21.000828 18.719528 21 17.879418 21 16.199219 L 21 7.4003906 C 21 6.8403406 20.999625 6.5596131 20.890625 6.3457031 C 20.794725 6.1575431 20.641325 6.0040831 20.453125 5.9082031 C 20.239224 5.7992131 19.960491 5.8007813 19.400391 5.8007812 L 12.623047 5.8007812 C 12.321497 5.8007812 12.170963 5.8001456 12.033203 5.7597656 C 11.911213 5.7239956 11.797266 5.6644175 11.697266 5.5859375 C 11.584326 5.4973075 11.497546 5.3762394 11.322266 5.1308594 L 10.279297 3.6699219 C 10.104017 3.4245399 10.015284 3.3015166 9.9023438 3.2128906 C 9.8023438 3.1344106 9.6883963 3.0767766 9.5664062 3.0410156 C 9.4286463 3.0006306 9.2781125 3 8.9765625 3 L 7.8007812 3 z M 5.3886719 13.800781 L 9.265625 13.800781 C 9.6398472 13.800781 9.9748647 13.861419 10.341797 14.220703 C 10.692503 14.564703 10.724609 14.954562 10.724609 15.226562 L 10.724609 18.523438 C 10.724609 18.565748 10.689824 18.599609 10.646484 18.599609 L 9.6289062 18.599609 C 9.5853152 18.599609 9.5488281 18.565748 9.5488281 18.523438 L 9.5488281 15.576172 C 9.5488281 15.271283 9.3746481 14.800781 8.7578125 14.800781 L 6.5644531 14.800781 C 6.5208621 14.800781 6.484375 14.834823 6.484375 14.876953 L 6.484375 18.523438 C 6.484375 18.565747 6.449592 18.599609 6.40625 18.599609 L 5.3886719 18.599609 C 5.3450809 18.599609 5.3085938 18.565748 5.3085938 18.523438 L 5.3085938 13.876953 C 5.3085938 13.834293 5.3450809 13.800781 5.3886719 13.800781 z M 11.724609 13.800781 L 12.742188 13.800781 C 12.785407 13.800781 12.820312 13.834283 12.820312 13.876953 L 12.820312 18.523438 C 12.820313 18.565747 12.785407 18.599609 12.742188 18.599609 L 11.724609 18.599609 C 11.681019 18.599609 11.644531 18.565748 11.644531 18.523438 L 11.644531 13.876953 C 11.644531 13.834293 11.681019 13.800781 11.724609 13.800781 z M 7.4824219 15.650391 L 8.5527344 15.650391 C 8.5959704 15.650391 8.6308594 15.684072 8.6308594 15.726562 L 8.6308594 18.523438 C 8.6308594 18.565568 8.5959694 18.599609 8.5527344 18.599609 L 7.4824219 18.599609 C 7.4388309 18.599609 7.4042969 18.565568 7.4042969 18.523438 L 7.4042969 15.726562 C 7.4042969 15.684072 7.4388309 15.650391 7.4824219 15.650391 z " />
</svg>
```

2021-12-24 04:14 UTC, prayag17 commented
I have changed the files and removed tidal music files that I added

2022-01-05 16:05 UTC, patrykmichalik requested changes
Thanks, @prayag17! As a final request, I’d suggest updating the Hotstar icon to use the latest logo.

2022-01-05 16:05 UTC, patrykmichalik commented on svgs/hotstar.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   fill="none"
   version="1.1"
   viewBox="0 0 24 24"
   id="svg4"
   sodipodi:docname="hotstar.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <sodipodi:namedview
     id="namedview6"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="34.708333"
     inkscape:cx="12"
     inkscape:cy="11.985594"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4" />
  <path
     d="m 18.984832,10.462479 c 0.604283,0 1.111702,0.224232 1.432798,0.69415 h 0.01485 v -0.582022 h 0.776171 V 14.70896 H 20.43248 v -0.642203 h -0.01485 c -0.291012,0.492576 -0.813683,0.746495 -1.403158,0.746495 -1.208517,0 -2.193716,-0.910546 -2.193716,-2.104317 0,-1.320718 0.947651,-2.246516 2.164076,-2.246516 z m -12.3383795,0 c 1.1417981,0 2.2160367,0.895713 2.2011566,2.208956 -0.014847,1.126127 -0.9764986,2.182197 -2.3387963,2.140557 -1.1549863,-0.03544 -2.1368366,-1.028027 -2.1232766,-2.183397 0.014424,-1.246919 1.0016503,-2.166116 2.2609163,-2.166116 z m 6.2535505,0 c 0.686723,0 1.246439,0.478151 1.268759,1.208997 h -0.776171 c -0.0371,-0.298439 -0.208572,-0.500003 -0.52968,-0.500003 -0.298439,0 -0.485159,0.201984 -0.485159,0.44064 0,0.350375 0.358619,0.455062 0.768754,0.582023 0.582024,0.178896 1.119118,0.529679 1.119118,1.298398 0,0.798431 -0.582023,1.320718 -1.387918,1.320718 -0.746087,0 -1.462438,-0.50742 -1.462438,-1.462439 h 0.776171 c 0.0371,0.500005 0.291012,0.753503 0.701159,0.753503 0.358608,0 0.597275,-0.231239 0.597275,-0.56719 0,-0.283596 -0.216407,-0.469907 -0.701567,-0.626543 -1.014838,-0.321108 -1.186726,-0.761339 -1.186726,-1.231678 0,-0.731242 0.619535,-1.215959 1.298398,-1.215959 z M 2.325e-5,9.1867605 c 0.4286873,0 0.7761707,0.3474834 0.7761707,0.776171 v 1.0519425 h 0.014844 C 1.0375297,10.649247 1.4328329,10.462526 1.947668,10.462526 c 0.9851625,0 1.7237974,0.626951 1.7237974,1.761357 V 14.7086 H 2.8952946 v -2.246038 c 0,-0.887878 -0.3433674,-1.290597 -1.0296824,-1.290597 -0.6788989,0 -1.08944225,0.492167 -1.08944225,1.298397 v 2.238237 H -7.5e-7 Z m 10.50454275,0 v 1.3879175 h 0.6789 v 0.708983 h -0.6789 v 3.425395 c -0.428686,0 -0.7761703,-0.347892 -0.7761703,-0.776171 v -2.649236 h -0.320688 v -0.708983 h 0.320688 V 9.1867485 Z m 5.391112,0 v 1.3879175 h 0.678898 v 0.708983 h -0.678898 v 3.425395 c -0.428688,0 -0.776171,-0.347892 -0.776171,-0.776171 v -2.649236 h -0.320686 v -0.708983 h 0.320686 V 9.1867485 Z m 8.104306,1.2761985 v 0.79843 c -0.671891,0.02227 -1.014839,0.432816 -1.014839,1.126547 v 1.544877 c 0,0.428688 -0.347481,0.775763 -0.77617,0.775763 v -4.134354 h 0.723826 v 0.373453 h 0.01485 c 0.186732,-0.27618 0.507828,-0.455064 1.05235,-0.484753 z m -4.992112,0.708983 c -0.819454,0 -1.481037,0.739894 -1.404837,1.614117 0.06265,0.720527 0.652103,1.303438 1.375077,1.317838 0.820283,0.01648 1.469518,-0.661583 1.469518,-1.455118 0,-0.805439 -0.582023,-1.476957 -1.439758,-1.476957 z m -12.3995794,0 c -0.8899426,0 -1.6426773,0.863146 -1.4023177,1.825197 0.1628157,0.652511 0.7576188,1.12531 1.4299177,1.106757 0.7938947,-0.02185 1.4353177,-0.655811 1.4353177,-1.477318 0,-0.805847 -0.649631,-1.455116 -1.4629177,-1.455116 z"
     fill="#000000"
     stroke-width="0.374727"
     id="path2" />
</svg>
```

2022-01-05 16:55 UTC, prayag17 commented
I have changed that too

2022-01-07 17:21 UTC, patrykmichalik approved these changes

2022-01-07 17:24 UTC, merged

2022-01-07 17:24 UTC, patrykmichalik commented
Thank you, @prayag17 and @arun54321!