Added icons for multiple apps (closes #158,#181,#189,#197) (#182,#177)
LawnchairLauncher/lawnicons pull request #200
Opened 2021-12-09 19:30 UTC by hardeik

2021-12-22 19:42 UTC, patrykmichalik requested changes
Thanks for your interest in contributing! Here are some changes I’d suggest. Additionally, because ES File Explorer has been found to be insecure and has been removed from the Play Store for committing click fraud, I’m afraid we won’t be able to add an icon for it. This is to avoid adding icons for disreputable apps.

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/alexa.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m20.4136,15.095c-0.2603,-0.3338 -1.727,-0.1577 -2.3854,-0.0796 -0.2006,0.0245 -0.2312,-0.15 -0.0505,-0.2756 1.1682,-0.8222 3.0851,-0.5849 3.3086,-0.3093 0.2235,0.2771 -0.0582,2.1986 -1.156,3.1157 -0.1684,0.1409 -0.3292,0.0658 -0.2542,-0.121 0.2465,-0.6155 0.7992,-1.995 0.5374,-2.3303"
      android:strokeWidth="0.03517312"
      android:fillColor="#000000"
      android:strokeColor="#00000000"
      android:fillType="evenOdd"/>
  <path
      android:pathData="m19.5835,16.0653c-2.0523,1.5127 -5.027,2.3198 -7.5881,2.3198 -3.5911,0 -6.8241,-1.3282 -9.27,-3.5373 -0.1922,-0.1737 -0.02,-0.4105 0.2106,-0.2752 2.6396,1.5358 5.9033,2.4597 9.2746,2.4597 2.2737,0 4.7749,-0.4704 7.0747,-1.4466 0.3474,-0.1476 0.638,0.2275 0.2982,0.4796"
      android:fillColor="#000000"
      android:strokeColor="#00000000"
      android:fillType="evenOdd"/>
  <path
      android:pathData="m20.0556,10.5309c-0.8939,-0 -1.3409,0.3451 -1.3409,1.0349 0,0.6006 0.3162,0.9008 0.9483,0.9008 0.2425,-0 0.5043,-0.0478 0.7854,-0.1438 0.281,-0.0957 0.5651,-0.2362 0.8526,-0.4216l0,-1.1979c-0.4343,-0.115 -0.8494,-0.1725 -1.2453,-0.1725zM20.1898,7.8956c1.1046,-0 1.6568,0.4761 1.6568,1.428l0,3.3922c0,0.0959 -0.0479,0.1438 -0.1436,0.1438l-0.2011,-0c-0.0959,-0 -0.147,-0.0479 -0.1533,-0.1438l-0.0383,-0.412c-0.5493,0.4407 -1.1239,0.6613 -1.724,0.6613 -0.4408,-0 -0.7903,-0.1262 -1.0489,-0.3786 -0.2588,-0.2522 -0.388,-0.5893 -0.388,-1.011 0,-0.4662 0.1583,-0.8337 0.4742,-1.1019 0.3161,-0.2685 0.7519,-0.4024 1.3075,-0.4024 0.2042,-0 0.4277,0.0191 0.6704,0.0573 0.2425,0.0383 0.4757,0.0926 0.6993,0.163L21.3009,9.4865c0,-0.3898 -0.0927,-0.6693 -0.2779,-0.8386 -0.1853,-0.1692 -0.4917,-0.254 -0.9195,-0.254 -0.3959,-0 -0.8141,0.0639 -1.2547,0.1917 -0.0703,0.0192 -0.1262,0.0367 -0.1676,0.0528 -0.0418,0.016 -0.0751,0.0238 -0.1005,0.0238 -0.0768,-0 -0.1151,-0.0415 -0.1151,-0.1245l0,-0.1533c0,-0.0959 0.0414,-0.1596 0.1247,-0.1916 0.2425,-0.096 0.5028,-0.1693 0.7805,-0.2204 0.2778,-0.0512 0.5507,-0.0768 0.819,-0.0768zM15.5378,10.7322 L14.1489,12.754c-0.0511,0.0705 -0.1181,0.1055 -0.2011,0.1055l-0.2681,-0c-0.0832,-0 -0.1246,-0.035 -0.1246,-0.1055 0,-0.0253 0.0222,-0.067 0.067,-0.1244L15.26,10.3489 13.7658,8.2598c-0.0383,-0.0575 -0.0574,-0.0957 -0.0574,-0.1149 0,-0.0704 0.0414,-0.1055 0.1244,-0.1055l0.297,-0c0.083,-0 0.15,0.0352 0.2012,0.1055l1.2548,1.7824 1.2546,-1.7824c0.0509,-0.0704 0.115,-0.1055 0.1916,-0.1055l0.2585,-0c0.083,-0 0.1246,0.0352 0.1246,0.1055 0,0.0256 -0.0191,0.067 -0.0574,0.1245L15.8825,10.3106 17.5205,12.6296c0.0383,0.0574 0.0574,0.0991 0.0574,0.1244 0,0.0705 -0.0417,0.1055 -0.1247,0.1055l-0.2967,-0c-0.0767,-0 -0.1406,-0.035 -0.1916,-0.1055zM11.1144,8.3844c-0.4788,-0 -0.8573,0.1405 -1.1349,0.4216 -0.2778,0.2812 -0.4454,0.6932 -0.5028,1.2361 0.2489,0.0641 0.4965,0.112 0.7422,0.1438 0.2456,0.032 0.4932,0.0479 0.7421,0.0479 0.479,-0 0.8301,-0.0701 1.0537,-0.2107 0.2234,-0.1405 0.3352,-0.3642 0.3352,-0.6707 0,-0.6453 -0.4119,-0.9678 -1.2356,-0.9678zM12.3308,12.342c0.083,-0.0254 0.1437,-0.0461 0.182,-0.0623 0.0383,-0.0158 0.0734,-0.0238 0.1053,-0.0238 0.0767,-0 0.1149,0.0416 0.1149,0.1246l0,0.134c0,0.1024 -0.0351,0.1694 -0.1053,0.2012 -0.4599,0.1916 -0.9482,0.2876 -1.4655,0.2876 -0.7342,-0 -1.2947,-0.2124 -1.6809,-0.6373 -0.3864,-0.4247 -0.5793,-1.046 -0.5793,-1.8637 0,-0.4025 0.051,-0.7652 0.153,-1.0876 0.1021,-0.3226 0.2505,-0.5974 0.4454,-0.8243 0.1947,-0.2266 0.4326,-0.3991 0.7135,-0.5173 0.2811,-0.1182 0.5971,-0.1774 0.9483,-0.1774 0.5555,-0 0.9849,0.1279 1.2882,0.3833 0.3033,0.2558 0.455,0.6133 0.455,1.0734 0,0.4537 -0.1613,0.7874 -0.4836,1.0014 -0.3225,0.2139 -0.8223,0.321 -1.499,0.321 -0.2428,-0 -0.4871,-0.0145 -0.7326,-0.0432 -0.2459,-0.0287 -0.4902,-0.0782 -0.7329,-0.1485 0,0.6898 0.1453,1.1993 0.4359,1.5283 0.2906,0.3293 0.7264,0.4936 1.3074,0.4936 0.3768,-0 0.7534,-0.0542 1.1302,-0.1629zM7.1148,5.912c0,-0.0957 0.0478,-0.1437 0.1437,-0.1437l0.2585,-0c0.0957,-0 0.1436,0.048 0.1436,0.1437L7.6607,12.0258c0,0.1405 0.0271,0.2396 0.0815,0.297 0.0541,0.0577 0.1516,0.0864 0.2921,0.0864 0.0382,-0 0.0814,-0.0032 0.1293,-0.0096 0.0478,-0.0065 0.0877,-0.0096 0.1197,-0.0096 0.0893,-0 0.1342,0.0447 0.1342,0.1341l0,0.182c0,0.0767 -0.0416,0.1247 -0.1246,0.1437 -0.0383,0.0128 -0.0943,0.0223 -0.1676,0.0287 -0.0737,0.0062 -0.139,0.0096 -0.1965,0.0096 -0.2554,-0 -0.455,-0.075 -0.5986,-0.2254 -0.1436,-0.1498 -0.2154,-0.3592 -0.2154,-0.6274zM4.0594,10.5309c-0.8939,-0 -1.3409,0.3451 -1.3409,1.0349 0,0.6006 0.3162,0.9008 0.9483,0.9008 0.2425,-0 0.5044,-0.0478 0.7853,-0.1438 0.2811,-0.0957 0.5651,-0.2362 0.8526,-0.4216l0,-1.1979c-0.4342,-0.115 -0.8494,-0.1725 -1.2452,-0.1725zM4.1935,7.8956c1.1047,-0 1.6568,0.4761 1.6568,1.428l0,3.3922c0,0.0959 -0.0478,0.1438 -0.1434,0.1438l-0.2012,-0c-0.0958,-0 -0.147,-0.0479 -0.1533,-0.1438l-0.0382,-0.412c-0.5494,0.4407 -1.124,0.6613 -1.724,0.6613 -0.4407,-0 -0.7903,-0.1262 -1.0488,-0.3786 -0.2587,-0.2522 -0.3879,-0.5893 -0.3879,-1.011 0,-0.4662 0.1581,-0.8337 0.4741,-1.1019 0.3162,-0.2685 0.752,-0.4024 1.3075,-0.4024 0.2042,-0 0.4276,0.0191 0.6704,0.0573 0.2425,0.0383 0.4756,0.0926 0.6992,0.163L5.3046,9.4865c0,-0.3898 -0.0927,-0.6693 -0.2779,-0.8386 -0.1852,-0.1692 -0.4917,-0.254 -0.9195,-0.254 -0.3957,-0 -0.814,0.0639 -1.2545,0.1917 -0.0704,0.0192 -0.1262,0.0367 -0.1675,0.0528 -0.0419,0.016 -0.0753,0.0238 -0.1007,0.0238 -0.0767,-0 -0.115,-0.0415 -0.115,-0.1245l0,-0.1533c0,-0.0959 0.0414,-0.1596 0.1246,-0.1916 0.2425,-0.096 0.5028,-0.1693 0.7805,-0.2204 0.2778,-0.0512 0.5506,-0.0768 0.8189,-0.0768"
      android:strokeWidth="0.30680346"
      android:fillColor="#000000"
      android:strokeColor="#000000"
      android:fillType="evenOdd"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/disneyplus.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m11.0798,13.9311c0.0111,0.0015 0.0135,0.002 0.0242,0.0034 0.1801,0.0245 0.3571,0.0569 0.4926,0.1175 0.1256,0.0554 0.1992,0.1256 0.2664,0.2507 0.1022,0.1896 0.1088,0.4553 0.0165,0.6564 -0.069,0.1496 -0.2204,0.2751 -0.3586,0.3416 -0.1436,0.0696 -0.285,0.1027 -0.4472,0.1213 -0.2837,0.0312 -0.5901,-0.0275 -0.8454,-0.151 -0.151,-0.0738 -0.3355,-0.2008 -0.4285,-0.3644 -0.0684,-0.1199 -0.0662,-0.2759 0.017,-0.3898 0.1327,-0.1816 0.4169,-0.2216 0.6309,-0.214 0.1632,0.0063 0.457,0.0568 0.6119,0.1119 0.0429,0.0155 0.2013,0.0772 0.229,0.1055 0.0195,0.0197 0.0321,0.0483 0.0233,0.0747 -0.0354,0.1083 -0.2985,0.1654 -0.3745,0.1768 -0.2034,0.0312 -0.3089,-0.0458 -0.5402,-0.1371 -0.0574,-0.0225 -0.1339,-0.0474 -0.1923,-0.0528 -0.105,-0.01 -0.2318,0.0194 -0.2518,0.134 -0.01,0.0591 0.0593,0.1143 0.1121,0.1375 0.124,0.0533 0.2249,0.0724 0.347,0.0741 0.3606,0.0059 0.7659,-0.0534 1.0609,-0.2624 0.0404,-0.0288 0.08,-0.071 0.0805,-0.1242 0.0013,-0.1074 -0.187,-0.173 -0.187,-0.173 -0.1987,-0.0828 -0.5658,-0.1232 -0.755,-0.1387 -0.1985,-0.0172 -0.5108,-0.0429 -0.5858,-0.0539 -0.0772,-0.011 -0.1611,-0.0266 -0.2279,-0.0566 -0.0672,-0.0303 -0.1329,-0.0982 -0.1524,-0.1734 -0.0346,-0.1354 0.0095,-0.3016 0.0847,-0.4098 0.1971,-0.2834 0.6588,-0.391 1.0037,-0.4337 0.3338,-0.0415 0.8735,-0.0411 1.2014,0.1331 0.0506,0.0271 0.0765,0.0524 0.0659,0.1065 -0.0214,0.1016 -0.0977,0.1671 -0.1903,0.1958 -0.0971,0.0309 -0.298,0.0429 -0.3862,0.0485 -0.3953,0.0222 -0.873,0.0105 -1.2496,0.1132 -0.0295,0.0084 -0.0805,0.0222 -0.097,0.0407 -0.0589,0.064 0.1094,0.0823 0.1455,0.0896 0.0107,0.0026 0.0128,0.0029 0.024,0.0041l0.8322,0.0981M8.728,12.1684c0,0 0.0643,-0.0964 0.1182,-0.1696 0.0981,-0.1332 0.2756,-0.318 0.4093,-0.4324 0.0409,-0.0349 0.0891,-0.0745 0.0891,-0.0745 0,0 -0.0754,0.0078 -0.1182,0.0165 -0.1014,0.0197 -0.2502,0.1186 -0.3245,0.1825 -0.1226,0.105 -0.2575,0.2756 -0.1965,0.4273 0.0089,0.0214 0.0225,0.0502 0.0225,0.0502m0.6818,0.1824c0.1937,-0.0134 0.3752,-0.0691 0.5442,-0.1629 0.1657,-0.0927 0.4094,-0.2735 0.3841,-0.4861 -0.0077,-0.0688 -0.0527,-0.1207 -0.1096,-0.145 -0.0739,-0.032 -0.1124,-0.0269 -0.2068,0.0012 -0.0686,0.0201 -0.0995,0.0322 -0.1642,0.0693 -0.1901,0.1104 -0.4595,0.3467 -0.6058,0.5353 -0.0338,0.0445 -0.068,0.0942 -0.0947,0.1283 -0.0169,0.021 -0.03,0.0403 -0.0284,0.0455 0.0058,0.0214 0.2056,0.0194 0.2813,0.0143m-0.4933,0.3623c-0.02,0.0211 -0.0411,0.0721 -0.063,0.109 -0.0117,0.0197 -0.0334,0.0452 -0.0478,0.0554 -0.0504,0.0371 -0.0931,0.0388 -0.1418,-0.004 -0.0683,-0.0604 -0.1077,-0.1538 -0.1105,-0.2446 -0.0015,-0.0396 0.0053,-0.0835 -0.0022,-0.1169 -0.0124,-0.0564 -0.0689,-0.1145 -0.0993,-0.1685 -0.0357,-0.0635 -0.0647,-0.1743 -0.0683,-0.2459 -0.0123,-0.2231 0.1053,-0.4285 0.2581,-0.5906 0.1538,-0.1639 0.3551,-0.3001 0.5739,-0.3928 0.2069,-0.0871 0.51,-0.1465 0.7372,-0.0679 0.074,0.0253 0.177,0.0883 0.2288,0.1542 0.011,0.0137 0.02,0.0285 0.0312,0.0357 0.0101,0.0064 0.0365,0.009 0.0575,0.0128 0.0725,0.0126 0.1768,0.0674 0.2194,0.104 0.0856,0.0739 0.1325,0.1445 0.1542,0.2469 0.0435,0.2062 -0.0752,0.4323 -0.2104,0.57 -0.2315,0.2369 -0.4602,0.4035 -0.7564,0.5195 -0.1301,0.0508 -0.3327,0.0983 -0.4803,0.085 -0.0458,-0.0038 -0.0929,-0.0159 -0.1376,-0.0188 -0.0228,-0.002 -0.1061,-0.0234 -0.115,-0.0295 -0.011,-0.0085 -0.0253,-0.0159 -0.0278,-0.013m0.2645,0.4571c0.009,0.0015 0.0229,0.0056 0.0349,0.0102 0.1038,0.0395 0.1466,0.1356 0.1721,0.2412 0.0593,0.2451 0.0846,0.7874 0.0944,0.9997 0.0072,0.1593 0.0112,0.3161 0.0179,0.4735 0.0057,0.1334 0.0163,0.3107 -0.0115,0.4356 -0.0101,0.0449 -0.0402,0.0972 -0.0832,0.124 -0.0493,0.0316 -0.1615,0.034 -0.2232,0.0212 -0.152,-0.0314 -0.2014,-0.1292 -0.2231,-0.2796 -0.0516,-0.3588 -0.0267,-1.0629 0.0037,-1.36 0.0101,-0.0981 0.0471,-0.4126 0.0983,-0.5444 0.0175,-0.0445 0.0548,-0.134 0.1197,-0.1213m-4.6253,0.5969c0,0 -0.2263,0.016 -0.382,0.0333 -0.1981,0.0213 -0.5704,0.0856 -0.7853,0.1624 -0.0645,0.0231 -0.1954,0.0779 -0.2068,0.1442 -0.012,0.0687 0.0307,0.1224 0.0781,0.178 0.0274,0.0323 0.1826,0.1816 0.2261,0.2179 0.1824,0.1523 0.5523,0.3872 0.8248,0.5012 0.0936,0.0387 0.2484,0.0942 0.2484,0.0942 0,0 -0.0115,-0.4409 -0.0094,-0.8752 0.0012,-0.2291 0.0061,-0.4559 0.0061,-0.4559m4.1491,0.1755c0.013,0.1184 -0.0175,0.3424 -0.0228,0.3719 -0.0096,0.0681 -0.061,0.2251 -0.0695,0.2443 -0.0414,0.0954 -0.0823,0.1736 -0.1256,0.2516 -0.0742,0.1335 -0.2506,0.3452 -0.3554,0.4358 -0.3895,0.3367 -0.9925,0.5283 -1.5097,0.5915 -0.351,0.0424 -0.7543,0.0362 -1.1262,-0.0326 -0.128,-0.0233 -0.3185,-0.0672 -0.3185,-0.0672 0,0 0.0006,0.0762 -0.0055,0.1297 -0.003,0.0244 -0.0214,0.0888 -0.0317,0.1096 -0.027,0.0559 -0.0714,0.0847 -0.136,0.0971 -0.0779,0.0145 -0.1606,0.0193 -0.2326,-0.0115 -0.1182,-0.0497 -0.1607,-0.1603 -0.1813,-0.2879 -0.0167,-0.102 -0.0341,-0.2794 -0.0341,-0.2794 0,0 -0.0884,-0.0419 -0.1622,-0.0787C4.1674,15.3053 3.9522,15.1701 3.764,15.0311 3.7119,14.9921 3.4879,14.8045 3.4385,14.758 3.2998,14.6263 3.1751,14.4954 3.0802,14.3274c-0.0738,-0.1313 -0.095,-0.2478 -0.0389,-0.3868 0.0774,-0.1939 0.3553,-0.3398 0.5455,-0.423 0.1396,-0.0616 0.5738,-0.2034 0.7541,-0.2297 0.0852,-0.0122 0.2173,-0.0358 0.2254,-0.0411 0.0033,-0.0025 0.0056,-0.0047 0.008,-0.0074 0.0042,-0.0059 0.0112,-0.1978 0.0098,-0.268 -0.0018,-0.069 0.0511,-0.5223 0.0681,-0.6182 0.0089,-0.0518 0.0481,-0.2514 0.0882,-0.3038 0.0262,-0.0354 0.0726,-0.0325 0.1104,-0.0093 0.2068,0.1286 0.2697,0.5747 0.2851,0.8016 0.0092,0.1383 0.0138,0.3463 0.0138,0.3463 0,0 0.2373,-0.007 0.3832,-0.0029 0.1418,0.0033 0.2982,0.0257 0.4454,0.0491 0.1885,0.0302 0.5559,0.1104 0.7666,0.2172 0.1735,0.088 0.3359,0.2362 0.3885,0.393 0.0489,0.1438 0.0416,0.2433 -0.0329,0.373 -0.0837,0.1465 -0.2421,0.2554 -0.4026,0.2645 -0.0478,0.0028 -0.2276,-0.0211 -0.283,-0.064 -0.0217,-0.0171 -0.0206,-0.0479 -0.0049,-0.0688 0.0059,-0.0073 0.09,-0.052 0.1396,-0.0781 0.0249,-0.0135 0.0455,-0.0281 0.0649,-0.0458 0.0412,-0.0363 0.0783,-0.0763 0.0742,-0.1231 -0.0057,-0.0608 -0.07,-0.0983 -0.1314,-0.1224 -0.2877,-0.1143 -0.8622,-0.2092 -1.1398,-0.2256 -0.1087,-0.0064 -0.2632,-0.0118 -0.2632,-0.0118l0.0327,1.5329c0,0 0.1278,0.0243 0.2285,0.0407 0.0578,0.0088 0.3026,0.0308 0.3677,0.0324 0.4954,0.0131 1.0482,-0.0313 1.5028,-0.2458 0.1996,-0.0939 0.3827,-0.2109 0.5213,-0.3692 0.1827,-0.2095 0.2784,-0.4961 0.2531,-0.7955 -0.0278,-0.327 -0.2579,-0.7152 -0.4417,-0.9515 -0.4856,-0.6245 -1.3179,-1.1381 -2.0502,-1.4393 -0.7476,-0.3073 -1.4865,-0.484 -2.2799,-0.5136 -0.2045,-0.0076 -0.6505,0.0027 -0.876,0.0651 -0.0322,0.0091 -0.0647,0.0199 -0.0946,0.0266 -0.0236,0.0058 -0.0608,0.0214 -0.0711,0.0297 -0.0057,0.0046 -0.0113,0.0109 -0.0113,0.0109 0,0 0.0139,0.0077 0.0272,0.0133 0.0239,0.0104 0.1244,0.0167 0.1764,0.0262 0.0465,0.0088 0.095,0.0332 0.1142,0.0673 0.0182,0.0324 0.0205,0.058 -0.0013,0.085 -0.0511,0.0621 -0.2433,0.0516 -0.328,0.0382 -0.088,-0.014 -0.1975,-0.0409 -0.2176,-0.1175 -0.0233,-0.0902 0.0195,-0.1787 0.0658,-0.2604 0.093,-0.1636 0.2263,-0.2487 0.4214,-0.3019 0.2771,-0.0763 0.6271,-0.1296 0.8888,-0.1396 0.5923,-0.0224 1.1529,0.0812 1.7268,0.2554 0.3285,0.0993 0.7585,0.266 1.0733,0.4176 0.2259,0.1089 0.5818,0.3092 0.7818,0.4401 0.0631,0.0416 0.4321,0.3128 0.4894,0.3604 0.1196,0.0978 0.276,0.2383 0.3892,0.3507 0.2191,0.2171 0.4917,0.55 0.6241,0.8142 0.0319,0.0633 0.0565,0.1255 0.0976,0.1988 0.0141,0.0251 0.0746,0.1754 0.0847,0.2188 0.01,0.0429 0.0246,0.1061 0.0266,0.1086 0.0029,0.0231 0.031,0.1521 0.0288,0.2019m7.4464,-0.3389c-0.2774,0.064 -1.0068,0.0995 -1.0068,0.0995l-0.092,0.2881c0,0 0.3645,-0.0311 0.6297,-0.0034 0,0 0.0859,-0.01 0.096,0.0975 0.0034,0.1003 -0.0085,0.2079 -0.0085,0.2079 0,0 -0.0055,0.0651 -0.0978,0.0817 -0.1,0.0167 -0.7857,0.0432 -0.7857,0.0432l-0.111,0.3756c0,0 -0.0413,0.0868 0.0512,0.062 0.0859,-0.023 0.8044,-0.1578 0.898,-0.1384 0.1003,0.0249 0.2113,0.1586 0. [...]

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/picsart.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M12,2C8.1726,2.0071 5.0384,5.0853 4.9113,8.962h-0.012v0.1693c-0.0018,0.0234 -0.0034,0.0466 -0.0049,0.07 0.0014,0.0232 0.0031,0.0465 0.0049,0.0697L4.8993,21.9652L7.8055,22v-7.0616c1.2355,0.9656 2.6343,1.4575 4.1945,1.464 3.9242,-0 7.1055,-3.224 7.1056,-7.201 0,-3.9771 -3.1813,-7.2013 -7.1056,-7.2013zM11.9778,4.7522c2.3627,0 4.278,1.9767 4.2781,4.415 0.0002,2.4384 -1.9152,4.4153 -4.2781,4.4153C9.615,13.5825 7.6996,11.6056 7.6997,9.1672 7.6998,6.7289 9.6151,4.7523 11.9778,4.7522Z"
      android:strokeWidth="0.175629"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/protonvpn.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m18.7097,2.2301a2.2001,2.2001 0,0 0,-2.2598 2.1403v0.0597L7.0822,7.4167A2.2598,2.2598 0,0 0,5.2903 6.5705,2.2001 2.2001,0 0,0 3.0404,8.7307v0a2.1901,2.1901 0,0 0,2.2499 2.1403v0a2.2897,2.2897 0,0 0,0.6371 -0.0896l6.1921,7.8645a2.0707,2.0707 0,0 0,-0.1891 0.876,2.2499 2.2499,0 0,0 4.4997,0v0A2.1005,2.1005 0,0 0,15.7033 17.9293L19.0383,6.5008A2.1901,2.1901 0,0 0,20.9596 4.3704,2.1901 2.1901,0 0,0 18.7097,2.2301ZM17.1368,5.9134a1.9014,1.9014 0,0 0,0.3186 0.2389L14.1702,17.3718a2.2996,2.2996 0,0 0,-0.8561 0.1692L7.2315,9.8258A2.1702,2.1702 0,0 0,7.5302 8.9597Z"
      android:strokeAlpha="0"
      android:strokeWidth="0.46"
      android:fillColor="#040404"
      android:strokeColor="#000"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/roku.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m15.6145,10.2231 l-1.8777,1.8774v-1.8836h-1.6297v4.7872h1.6297v-1.9419l1.9604,1.9419h2.0513l-2.4911,-2.4914 2.0634,-2.0626v2.841c0,0.9433 0.5673,1.8137 1.9957,1.8137 0.6782,0 1.3005,-0.3846 1.603,-0.7326l0.7328,0.632L22,15.0041v-4.781h-1.6297v2.4908,0.6046c-0.1835,0.3203 -0.4392,0.5217 -0.8345,0.5217 -0.401,0 -0.585,-0.2377 -0.585,-0.998v-0.2006,-2.4185zM9.2803,11.3036c-0.4305,0 -0.7966,0.5851 -0.7966,1.3094 0,0.7243 0.3662,1.3102 0.7966,1.3102 0.4405,0 0.806,-0.5859 0.806,-1.3102 0,-0.7243 -0.3656,-1.3094 -0.806,-1.3094m2.509,1.3094c0,1.3837 -1.1253,2.4918 -2.509,2.4918 -1.3833,0 -2.5002,-1.108 -2.5002,-2.4918 0,-1.3827 1.117,-2.4913 2.5002,-2.4913 1.3837,0 2.509,1.1086 2.509,2.4913m-6.6393,-1.676c0,-0.5682 -0.4571,-1.0257 -1.016,-1.0257L3.63,9.9113v2.0424L4.1339,11.9536c0.5589,0 1.016,-0.4579 1.016,-1.0166m2.292,4.0715L5.5924,15.0085L4.1239,12.9707L3.63,12.9707v2.0334L2,15.0042v-6.1089h2.3351c1.3462,0 2.445,0.9154 2.445,2.0418 0,0.6869 -0.4212,1.3005 -1.0623,1.6759l1.7242,2.3957"
      android:strokeWidth="0.151308"
      android:fillColor="#000000"
      android:strokeColor="#00000000"
      android:fillType="nonZero"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/schoolplanner.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M4.7778,3.3889C4.7778,2.6218 5.3996,2 6.1667,2l0.9722,0L7.1389,22L6.1667,22C5.3996,22 4.7778,21.3782 4.7778,20.6111ZM8.1111,22L8.1111,2l5.2778,0l0,4.1667l1.8056,-1.25 1.8056,1.25L17,2l0.8333,0c0.7671,0 1.3889,0.6218 1.3889,1.3889l0,17.2222c0,0.7671 -0.6218,1.3889 -1.3889,1.3889zM10.3333,12.6944L17,12.6944L17,14.0833L10.3333,14.0833ZM15.3333,15.4722L10.3333,15.4722l0,1.3889l5,0z"
      android:fillColor="#000000"
      android:fillType="evenOdd"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/stremio.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="M12,2 L1.9999,11.9999 12,22 22.0001,11.9999ZM10.453,8.2663 L12.9473,10.1554 15.4419,12.0448 12.9473,13.9339 10.453,15.8232v-3.7785z"
      android:strokeWidth="0.0958784"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/viber.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m12.7433,13.4551c0,0 0.3556,0.03 0.5471,-0.2059L13.6638,12.7796c0.1801,-0.2329 0.6147,-0.3815 1.0402,-0.1444a11.0047,11.0047 0,0 1,0.9277 0.5924c0.2824,0.2077 0.8608,0.6903 0.8626,0.6903 0.2755,0.2326 0.3391,0.5741 0.1516,0.9343 0,0.0021 -0.0015,0.0057 -0.0015,0.0075a3.8959,3.8959 0,0 1,-0.777 0.9568c-0.0036,0.0018 -0.0036,0.0036 -0.0069,0.0054q-0.4016,0.3355 -0.789,0.3815a0.5219,0.5219 0,0 1,-0.1152 0.0072,1.0504 1.0504,0 0,1 -0.3355,-0.0516l-0.0084,-0.0123C14.2142,16.0344 13.5498,15.7535 12.4432,15.143A12.9171,12.9171 0,0 1,10.6208 13.9392,9.5533 9.5533,0 0,1 9.8012,13.2123l-0.0276,-0.0276 -0.0276,-0.0276v0L9.7184,13.1295c-0.0093,-0.009 -0.0183,-0.0183 -0.0276,-0.0276A9.5533,9.5533 0,0 1,8.9638 12.2822,12.9303 12.9303,0 0,1 7.76,10.4602C7.1496,9.3533 6.8687,8.6894 6.7564,8.2909l-0.0123,-0.0084A1.0504,1.0504 0,0 1,6.6928 7.9469,0.5063 0.5063,0 0,1 6.6997,7.8317Q6.748,7.4448 7.0817,7.0421c0.0018,-0.0033 0.0036,-0.0033 0.0054,-0.0069A3.8875,3.8875 0,0 1,8.044 6.2584c0.0018,0 0.0054,-0.0018 0.0075,-0.0018 0.3602,-0.1876 0.7017,-0.124 0.934,0.1501 0.0018,0.0018 0.4835,0.5801 0.6903,0.8626a11.0047,11.0047 0,0 1,0.5924 0.9286C10.5053,8.6231 10.3567,9.0586 10.1238,9.2381L9.6541,9.6114c-0.2371,0.1915 -0.2059,0.5471 -0.2059,0.5471 0,0 0.6957,2.633 3.2951,3.2966zM11.8652,5.5801a0.253,0.253 0,0 0,-0.2559 0.252,0.253 0.253,0 0,0 0.252,0.2539c1.3527,0.0094 2.4536,0.447 3.3555,1.3262 0.8943,0.8718 1.3515,2.0566 1.3633,3.6113a0.253,0.253 0,0 0,0.2539 0.252,0.253 0.253,0 0,0 0.252,-0.2559C17.0734,9.3661 16.5688,8.0241 15.5703,7.0508 14.5793,6.0847 13.3277,5.5903 11.8652,5.5801ZM12.3281,6.8926a0.253,0.253 0,0 0,-0.2715 0.2344,0.253 0.253,0 0,0 0.2344,0.2715c0.9658,0.0707 1.6821,0.3862 2.2051,0.957 0.5244,0.573 0.7728,1.2692 0.7539,2.1406a0.253,0.253 0,0 0,0.248 0.2578,0.253 0.253,0 0,0 0.2578,-0.2461C15.777,9.5305 15.48,8.6812 14.8691,8.0137 14.2516,7.3396 13.3881,6.9702 12.3281,6.8926ZM12.707,8.25a0.253,0.253 0,0 0,-0.2656 0.2402,0.253 0.253,0 0,0 0.2383,0.2656c0.4361,0.0227 0.7306,0.1457 0.9297,0.3516 0.1991,0.2058 0.3211,0.5151 0.3438,0.9707a0.253,0.253 0,0 0,0.2637 0.2402,0.253 0.253,0 0,0 0.2402,-0.2637C14.4304,9.5181 14.2776,9.0711 13.9727,8.7559 13.6677,8.4406 13.2298,8.2773 12.707,8.25ZM19.3428,3.9508C18.8458,3.4922 16.8373,2.0342 12.3637,2.0144c0,0 -5.2756,-0.3181 -7.8474,2.0409 -1.4316,1.4319 -1.9352,3.5271 -1.9883,6.1247 -0.0531,2.5976 -0.1219,7.4656 4.5706,8.7856h0.0045l-0.003,2.0141c0,0 -0.03,0.8154 0.5069,0.9817 0.6495,0.2017 1.0306,-0.4181 1.6507,-1.0862 0.3403,-0.3668 0.8103,-0.9055 1.1645,-1.3173 3.2092,0.2701 5.6775,-0.3472 5.9578,-0.4385 0.648,-0.2101 4.3146,-0.6801 4.911,-5.5475C21.9064,8.5547 20.9932,5.3812 19.3428,3.9508ZM19.8866,13.212c-0.5033,4.0643 -3.4773,4.3197 -4.0256,4.4956 -0.2332,0.075 -2.401,0.6144 -5.127,0.4364 0,0 -2.0312,2.4505 -2.6657,3.0877 -0.099,0.0996 -0.2155,0.1399 -0.2932,0.12 -0.1092,-0.0267 -0.1393,-0.1561 -0.1381,-0.3451 0.0018,-0.2701 0.0174,-3.347 0.0174,-3.347 0,0 -0.0024,0 0,0C3.6849,16.5575 3.9163,12.4143 3.9613,10.2447 4.0064,8.0751 4.4139,6.2977 5.6246,5.1023 7.8,3.132 12.2811,3.4264 12.2811,3.4264c3.7843,0.0165 5.5976,1.1561 6.0181,1.5378 1.3962,1.1954 2.1075,4.0559 1.5874,8.2465z"
      android:strokeWidth="0.0300125"
      android:fillColor="#000000"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on app/src/main/res/drawable/ytstudio.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="m11.9742,2c-0.5139,-0.0032 -0.9671,0.2983 -0.9671,0.2983 0,0 -4.3698,2.506 -6.7288,3.9198 -0.191,0.1145 -0.6671,0.4177 -0.8998,0.7245 -0.31,0.4088 -0.3036,1.3058 -0.3042,1.5208 -0.0101,2.994 0.0015,5.2585 0.0175,7.8311 0.0011,0.1875 0.0326,0.3858 0.2622,0.7283 0.1983,0.2957 0.3758,0.4478 0.5424,0.5445 2.788,1.6178 4.8886,2.8536 7.2779,4.2196 0.1755,0.1003 0.5406,0.2094 0.8243,0.213 0.2651,0.0033 0.5575,-0.0539 0.7748,-0.1797 2.5964,-1.5036 4.9513,-2.8708 7.4878,-4.3531 0.2722,-0.1591 0.411,-0.3686 0.5021,-0.5662 0.0803,-0.1742 0.167,-0.5261 0.1661,-0.7323 -0.0115,-2.6883 -0.0267,-5.2204 -0.0302,-8.0812 -0.0009,-0.763 -0.143,-0.9974 -0.3124,-1.236 -0.2216,-0.312 -0.514,-0.4553 -1.0579,-0.7656 -2.3756,-1.3552 -6.3764,-3.6863 -6.3764,-3.6863 0,0 -0.6474,-0.3962 -1.1784,-0.3995zM11.9741,5.8778c0.3247,0.0021 0.7207,0.2443 0.7207,0.2443 0,0 2.4463,1.4254 3.8989,2.2541 0.3326,0.1897 0.5114,0.2773 0.6469,0.4681 0.1036,0.1459 0.1905,0.2892 0.1911,0.7558 0.0021,1.7493 0.0116,3.2976 0.0185,4.9414 0.0005,0.1261 -0.0525,0.3413 -0.1016,0.4478 -0.0557,0.1208 -0.1405,0.2489 -0.307,0.3462 -1.551,0.9064 -2.991,1.7424 -4.5786,2.6618 -0.1329,0.077 -0.3117,0.1119 -0.4738,0.1099 -0.1735,-0.0021 -0.3968,-0.069 -0.5041,-0.1303 -1.461,-0.8353 -2.7454,-1.5908 -4.4502,-2.58 -0.1019,-0.0591 -0.2105,-0.1522 -0.3317,-0.333 -0.1404,-0.2094 -0.1596,-0.3306 -0.1603,-0.4453 -0.0098,-1.573 -0.0168,-2.9578 -0.0107,-4.7885 0.0003,-0.1315 -0.0036,-0.68 0.186,-0.9299 0.1423,-0.1876 0.4335,-0.373 0.5503,-0.443 1.4425,-0.8645 4.1144,-2.3969 4.1144,-2.3969 0,0 0.2771,-0.1843 0.5913,-0.1823z"
      android:strokeLineJoin="miter"
      android:strokeWidth="0.264583"
      android:fillColor="#000000"
      android:strokeColor="#00000000"
      android:strokeLineCap="butt"/>
  <path
      android:pathData="m11.9924,6.3819c-0.2893,-0.0025 -0.5448,0.1677 -0.5448,0.1677 0,0 -2.4633,1.4146 -3.7932,2.2129 -0.1077,0.0646 -0.376,0.2358 -0.5074,0.4094 -0.1751,0.2313 -0.1726,0.7397 -0.1733,0.8615 -0.0095,1.6968 -0.0058,2.9802 0,4.4382 0.0004,0.1063 0.018,0.2188 0.1468,0.4131 0.1112,0.1678 0.211,0.2542 0.3047,0.3093 1.5676,0.9204 2.7486,1.6235 4.092,2.4007 0.0987,0.0571 0.304,0.1193 0.4638,0.1218 0.1493,0.0022 0.3139,-0.0299 0.4364,-0.1009 1.4636,-0.8488 2.7912,-1.6205 4.221,-2.4574 0.1535,-0.0898 0.2318,-0.2084 0.2834,-0.3203 0.0454,-0.0986 0.0948,-0.2979 0.0945,-0.4148 -0.003,-1.5236 -0.0085,-2.9587 -0.0069,-4.58 0.0004,-0.4324 -0.0793,-0.5655 -0.1744,-0.7009 -0.1244,-0.1771 -0.2888,-0.2586 -0.5946,-0.4352 -1.3357,-0.7711 -3.5851,-2.0973 -3.5851,-2.0973 0,0 -0.364,-0.2252 -0.663,-0.2278zM10.1016,9.0924 L12.625,10.5528 15.1484,12.0133 12.6225,13.4697 10.0966,14.9259 10.0991,12.0092z"
      android:strokeLineJoin="miter"
      android:strokeWidth="0.564858"
      android:fillColor="#000000"
      android:strokeColor="#00000000"
      android:strokeLineCap="butt"/>
</vector>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/alexa.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   sodipodi:docname="alexa.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview7"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="1"
     inkscape:pageshadow="2"
     inkscape:pageopacity="1"
     inkscape:pagecheckerboard="0"
     inkscape:document-units="px"
     showgrid="false"
     inkscape:object-nodes="false"
     inkscape:showpageshadow="false"
     inkscape:snap-page="true"
     units="px"
     inkscape:zoom="21.949773"
     inkscape:cx="10.501248"
     inkscape:cy="13.89536"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5" />
  <defs
     id="defs2" />
  <g
     id="g26520"
     transform="matrix(0.30680299,0,0,0.30680299,-20.214314,-29.281163)">
    <g
       id="g26511"
       transform="translate(1.6867562,0.16741769)">
      <path
         d="m 130.73667,144.47322 c -0.84838,-1.08791 -5.62917,-0.51401 -7.77504,-0.2595 -0.65375,0.0799 -0.75355,-0.48906 -0.1647,-0.89827 3.80768,-2.67986 10.05566,-1.90634 10.78428,-1.00807 0.72857,0.90327 -0.18965,7.16622 -3.76777,10.15547 -0.54893,0.45912 -1.07294,0.21458 -0.82839,-0.39425 0.80344,-2.00614 2.60497,-6.50249 1.75162,-7.59538"
         id="path10"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.114644"
         inkscape:connector-curvature="0" />
      <g
         transform="matrix(0.01534819,0,0,-0.01534819,-0.22276628,119.96966)"
         id="g12">
        <g
           id="g24152"
           transform="matrix(7.4999995,0,0,-7.4999995,3135.5291,4930.5817)">
          <path
             d="m 696.1013,897.75335 c -58.11169,42.83292 -142.34105,65.68583 -214.86092,65.68583 -101.68461,0 -193.22683,-37.60937 -262.48206,-100.16107 -5.44116,-4.91885 -0.5659,-11.62235 5.96353,-7.79179 74.7399,43.48586 167.15276,69.64701 262.61265,69.64701 64.37988,0 135.20216,-13.32001 200.32209,-40.96113 9.83763,-4.17885 18.06468,6.44234 8.44471,13.58115"
             id="path8"
             style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:none"
             inkscape:connector-curvature="0" />
        </g>
      </g>
    </g>
    <g
       transform="matrix(0.03527778,0,0,-0.03527778,-158.54755,131.45959)"
       id="g12-7">
      <path
         id="path86"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:28.3465;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
         d="m 8214.9176,48.057953 c -82.5935,0 -123.8938,-31.88283 -123.8938,-95.61797 0,-55.489293 29.215,-83.228613 87.6166,-83.228613 22.4015,0 46.5933,4.41565 72.5613,13.28529 25.961,8.8391 52.2134,21.825283 78.7712,38.948583 v 110.67449 c -40.128,10.62951 -78.4797,15.93822 -115.0553,15.93822 z m 12.3979,243.481187 c 102.0605,0 153.0802,-43.98589 153.0802,-131.93279 v -313.411 c 0,-8.86397 -4.4263,-13.28529 -13.2647,-13.28529 h -18.5791 c -8.8597,0 -13.5843,4.42132 -14.1599,13.28529 l -3.5381,38.06615 c -50.7497,-40.72194 -103.8439,-61.09855 -159.2828,-61.09855 -40.7248,0 -73.0162,11.65901 -96.9097,34.98269 -23.9076,23.2988 -35.8508,54.443443 -35.8508,93.406243 0,43.0729198 14.6216,77.02611 43.8083,101.806972 29.2078,24.805739 69.4707,37.180899 120.803,37.180899 18.8704,0 39.5171,-1.76484 61.9399,-5.29806 22.4084,-3.54103 43.9503,-8.559162 64.6111,-15.058646 V 144.5477 c 0,36.01216 -8.5685,61.84241 -25.6768,77.48152 -17.1227,15.63272 -45.4282,23.46507 -84.9522,23.46507 -36.5756,0 -75.2187,-5.90339 -115.9223,-17.70946 -6.4936,-1.77336 -11.6589,-3.39112 -15.4813,-4.87603 -3.8649,-1.47637 -6.9413,-2.20107 -9.286,-2.20107 -7.0977,0 -10.6359,3.83305 -10.6359,11.50411 v 14.16203 c 0,8.86467 3.8295,14.74815 11.517,17.70661 22.4086,8.86963 46.4583,15.63911 72.1138,20.36522 25.6697,4.72613 50.8775,7.09344 75.6663,7.09344 z M 7797.5027,29.460413 7669.1827,-157.34001 c -4.7246,-6.51654 -10.913,-9.74993 -18.579,-9.74993 h -24.7745 c -7.6875,0 -11.5098,3.23339 -11.5098,9.74993 0,2.34174 2.0532,6.19398 6.1883,11.49487 L 7771.8402,64.876468 7633.7866,257.89147 c -3.5382,5.30943 -5.3074,8.84194 -5.3074,10.6153 0,6.50019 3.8296,9.74994 11.4957,9.74994 h 27.4388 c 7.666,0 13.8614,-3.24975 18.5861,-9.74994 l 115.9363,-164.68173 115.9151,164.68173 c 4.7033,6.50019 10.6288,9.74994 17.698,9.74994 h 23.8865 c 7.6731,0 11.5097,-3.24975 11.5097,-9.74994 0,-2.36945 -1.762,-6.18615 -5.3073,-11.50056 L 7829.3536,68.415372 7980.6932,-145.84514 c 3.5382,-5.30089 5.3002,-9.15313 5.3002,-11.49487 0,-6.51654 -3.8507,-9.74993 -11.5169,-9.74993 h -27.4104 c -7.0906,0 -12.9947,3.23339 -17.7052,9.74993 z M 7388.8126,246.37387 c -44.2344,0 -79.2044,-12.97695 -104.8598,-38.94859 -25.6698,-25.97732 -41.1511,-64.04916 -46.4513,-114.207006 22.9982,-5.91973 45.8687,-10.34674 68.5757,-13.28529 22.6927,-2.959149 45.5702,-4.42132 68.5685,-4.42132 44.2558,0 76.6964,6.4803 97.3573,19.47144 20.6394,12.985476 30.9698,33.647696 30.9698,61.970316 0,59.625 -38.0534,89.42045 -114.1602,89.42045 z m 112.3911,-365.65056 c 7.6661,2.34743 13.2789,4.26289 16.8171,5.75844 3.5382,1.46288 6.7779,2.20107 9.7336,2.20107 7.0834,0 10.6145,-3.84653 10.6145,-11.51476 v -12.38368 c 0,-9.45793 -3.2397,-15.64693 -9.7265,-18.58903 -42.4938,-17.70377 -87.6094,-26.57058 -135.4035,-26.57058 -67.8368,0 -119.6237,19.6242 -155.3039,58.88397 -35.7018,39.239873 -53.5278,96.638933 -53.5278,172.19718 0,37.189434 4.7105,70.69572 14.1386,100.49118 9.4352,29.80397 23.1474,55.19301 41.1511,76.15504 17.9893,20.93931 39.9716,36.87825 65.9255,47.79622 25.9681,10.9208 55.1689,16.39078 87.6165,16.39078 51.3253,0 90.9984,-11.81955 119.0198,-35.41251 28.0215,-23.63202 42.0392,-56.66372 42.0392,-99.17321 0,-41.91555 -14.8987,-72.749736 -44.6821,-92.526688 -29.7976,-19.759909 -75.9717,-29.659739 -138.5012,-29.659739 -22.4299,0 -45.0019,1.34067 -67.6876,3.98793 -22.7212,2.65364 -45.2931,7.22417 -67.7159,13.724355 0,-63.735125 13.4209,-110.810195 40.2701,-141.208135 26.849,-30.422793 67.112,-45.601503 120.7959,-45.601503 34.8137,0 69.613,5.00391 104.4266,15.05367 z m -481.9265,594.08584 c 0,8.84549 4.4191,13.27893 13.2789,13.27893 h 23.8864 c 8.8383,0 13.2718,-4.43344 13.2718,-13.27893 V -90.063847 c 0,-12.985463 2.5009,-22.132893 7.531,-27.439493 5.0018,-5.3286 14.0036,-7.98437 26.9913,-7.98437 3.531,0 7.5238,0.2991 11.9431,0.88809 4.4192,0.59609 8.0995,0.8881 11.0551,0.8881 8.2486,0 12.3979,-4.13287 12.3979,-12.39221 v -16.81851 c 0,-7.09059 -3.8437,-11.51761 -11.5098,-13.2796 -3.5382,-1.1794 -8.7104,-2.05969 -15.4814,-2.65579 -6.8064,-0.57477 -12.8383,-0.88809 -18.1527,-0.88809 -23.5952,0 -42.0393,6.93216 -55.3109,20.82278 -13.2648,13.84373 -19.9007,33.18444 -19.9007,57.970993 z M 6736.9817,48.057953 c -82.5934,0 -123.8937,-31.88283 -123.8937,-95.61797 0,-55.489293 29.215,-83.228613 87.6165,-83.228613 22.4015,0 46.6005,4.41565 72.5543,13.28529 25.9682,8.8391 52.2134,21.825283 78.7711,38.948583 v 110.67449 c -40.1209,10.62951 -78.4797,15.93822 -115.0482,15.93822 z m 12.3908,243.481187 c 102.0677,0 153.0802,-43.98589 153.0802,-131.93279 v -313.411 c 0,-8.86397 -4.412,-13.28529 -13.2503,-13.28529 h -18.5934 c -8.8526,0 -13.5774,4.42132 -14.1598,13.28529 l -3.5312,38.06615 c -50.7567,-40.72194 -103.851,-61.09855 -159.2899,-61.09855 -40.7176,0 -73.0161,11.65901 -96.9025,34.98269 -23.9006,23.2988 -35.8438,54.443443 -35.8438,93.406243 0,43.0729198 14.6075,77.02611 43.8012,101.806972 29.215,24.805739 69.4779,37.180899 120.8031,37.180899 18.8705,0 39.5098,-1.76484 61.9397,-5.29806 22.4086,-3.54103 43.9434,-8.559162 64.6041,-15.058646 V 144.5477 c [...]

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/disneyplus.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   sodipodi:docname="disneyplus.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview16"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="31.041667"
     inkscape:cx="12.032215"
     inkscape:cy="12.016107"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="g1375" />
  <defs
     id="defs2" />
  <g
     id="g1375"
     transform="matrix(0.14702583,0,0,0.14702583,-3.4377122,-7.2429965)">
    <g
       id="g898"
       transform="matrix(0.1360302,0,0,0.1360302,27.859435,96.336834)">
      <linearGradient
         id="SVGID_1_"
         gradientUnits="userSpaceOnUse"
         x1="930.50293"
         y1="184.4834"
         x2="189.4962"
         y2="84.295403">
        <stop
           offset="0"
           style="stop-color:#101C50"
           id="stop885" />
        <stop
           offset="0.236"
           style="stop-color:#0D267A"
           id="stop887" />
        <stop
           offset="0.4973"
           style="stop-color:#085AA4"
           id="stop889" />
        <stop
           offset="0.6549"
           style="stop-color:#058BBF"
           id="stop891" />
        <stop
           offset="1"
           style="stop-color:#B1FFFF"
           id="stop893" />
      </linearGradient>
      <g
         id="g1260"
         transform="translate(67.084307,-26.833723)">
        <path
           fill="#101c50"
           d="m 453.988,377.341 c 0.553,0.076 0.673,0.098 1.212,0.168 9.006,1.224 17.856,2.847 24.63,5.875 6.278,2.772 9.958,6.28 13.318,12.533 5.109,9.482 5.442,22.766 0.825,32.82 -3.449,7.481 -11.02,13.754 -17.932,17.079 -7.178,3.48 -14.25,5.137 -22.361,6.063 -14.186,1.562 -29.507,-1.377 -42.272,-7.551 -7.552,-3.688 -16.774,-10.039 -21.426,-18.221 -3.421,-5.994 -3.312,-13.793 0.85,-19.49 6.634,-9.08 20.843,-11.079 31.545,-10.7 8.159,0.316 22.85,2.838 30.597,5.594 2.147,0.776 10.066,3.861 11.448,5.276 0.973,0.984 1.604,2.414 1.167,3.736 -1.77,5.414 -14.926,8.268 -18.725,8.841 -10.17,1.558 -15.447,-2.291 -27.009,-6.856 -2.87,-1.124 -6.695,-2.371 -9.617,-2.641 -5.249,-0.5 -11.589,0.97 -12.591,6.7 -0.498,2.953 2.965,5.715 5.606,6.876 6.202,2.664 11.244,3.622 17.348,3.704 18.032,0.297 38.297,-2.672 53.046,-13.122 2.019,-1.441 4.002,-3.55 4.023,-6.209 0.064,-5.369 -9.349,-8.652 -9.349,-8.652 -9.935,-4.142 -28.292,-6.158 -37.749,-6.937 -9.924,-0.859 -25.539,-2.144 -29.288,-2.696 -3.86,-0.551 -8.053,-1.33 -11.396,-2.828 -3.358,-1.517 -6.643,-4.912 -7.618,-8.668 -1.729,-6.771 0.477,-15.079 4.237,-20.488 9.855,-14.168 32.94,-19.549 50.186,-21.686 16.692,-2.077 43.677,-2.056 60.072,6.656 2.531,1.357 3.824,2.619 3.295,5.325 -1.068,5.08 -4.886,8.354 -9.514,9.789 -4.855,1.545 -14.898,2.147 -19.309,2.425 -19.766,1.108 -43.652,0.527 -62.479,5.661 -1.475,0.421 -4.023,1.108 -4.851,2.033 -2.947,3.199 5.47,4.113 7.273,4.479 0.536,0.128 0.64,0.146 1.199,0.207 l 41.609,4.905 M 336.399,289.204 c 0,0 3.215,-4.822 5.909,-8.48 4.905,-6.662 13.782,-15.901 20.467,-21.621 2.045,-1.747 4.456,-3.726 4.456,-3.726 0,0 -3.771,0.39 -5.908,0.827 -5.072,0.987 -12.509,5.93 -16.225,9.124 -6.132,5.249 -12.875,13.782 -9.824,21.364 0.443,1.071 1.125,2.512 1.125,2.512 m 34.088,9.122 c 9.687,-0.668 18.761,-3.457 27.209,-8.143 8.285,-4.636 20.471,-13.676 19.207,-24.303 -0.384,-3.44 -2.636,-6.037 -5.479,-7.249 -3.695,-1.601 -5.622,-1.343 -10.342,0.06 -3.429,1.003 -4.974,1.612 -8.212,3.465 -9.503,5.521 -22.977,17.337 -30.292,26.767 -1.688,2.224 -3.398,4.711 -4.736,6.416 -0.844,1.051 -1.5,2.016 -1.418,2.273 0.292,1.069 10.28,0.971 14.063,0.714 m -24.664,18.116 c -0.999,1.057 -2.056,3.605 -3.152,5.45 -0.586,0.987 -1.671,2.258 -2.389,2.768 -2.521,1.854 -4.657,1.94 -7.091,-0.202 -3.413,-3.019 -5.387,-7.688 -5.527,-12.23 -0.073,-1.982 0.267,-4.175 -0.108,-5.846 -0.621,-2.821 -3.444,-5.727 -4.966,-8.424 -1.787,-3.177 -3.233,-8.717 -3.413,-12.294 -0.613,-11.153 5.266,-21.427 12.903,-29.53 7.691,-8.194 17.753,-15.004 28.696,-19.64 10.344,-4.357 25.502,-7.327 36.861,-3.393 3.698,1.267 8.85,4.414 11.439,7.711 0.55,0.684 0.998,1.424 1.562,1.786 0.505,0.322 1.826,0.449 2.877,0.642 3.623,0.628 8.839,3.371 10.97,5.198 4.281,3.693 6.626,7.223 7.711,12.346 2.176,10.308 -3.76,21.617 -10.521,28.5 -11.577,11.846 -23.01,20.175 -37.82,25.973 -6.505,2.541 -16.636,4.915 -24.016,4.251 -2.292,-0.19 -4.646,-0.794 -6.878,-0.942 -1.139,-0.098 -5.303,-1.172 -5.748,-1.475 -0.552,-0.424 -1.265,-0.793 -1.39,-0.649 m 13.227,22.854 c 0.451,0.076 1.146,0.278 1.744,0.508 5.192,1.975 7.328,6.78 8.607,12.058 2.964,12.256 4.229,39.37 4.722,49.983 0.362,7.966 0.561,15.803 0.895,23.677 0.283,6.668 0.815,15.533 -0.575,21.78 -0.505,2.247 -2.008,4.86 -4.16,6.198 -2.465,1.578 -8.076,1.698 -11.16,1.062 -7.602,-1.572 -10.072,-6.46 -11.157,-13.978 -2.579,-17.939 -1.337,-53.146 0.185,-68.002 0.506,-4.907 2.354,-20.629 4.916,-27.221 0.875,-2.223 2.738,-6.7 5.983,-6.065 m -231.264,29.847 c 0,0 -11.314,0.801 -19.101,1.665 -9.907,1.067 -28.522,4.281 -39.267,8.118 -3.223,1.154 -9.77,3.894 -10.339,7.208 -0.598,3.435 1.534,6.121 3.905,8.9 1.371,1.614 9.131,9.079 11.307,10.893 9.121,7.615 27.616,19.359 41.238,25.062 4.68,1.936 12.422,4.708 12.422,4.708 0,0 -0.575,-22.044 -0.472,-43.758 0.06,-11.455 0.307,-22.796 0.307,-22.796 m 207.454,8.773 c 0.648,5.922 -0.874,17.119 -1.138,18.596 -0.482,3.404 -3.049,11.256 -3.475,12.214 -2.072,4.772 -4.115,8.682 -6.28,12.582 -3.71,6.677 -12.532,17.262 -17.769,21.792 -19.475,16.833 -49.623,26.417 -75.487,29.574 -17.55,2.12 -37.716,1.809 -56.312,-1.632 -6.4,-1.164 -15.924,-3.359 -15.924,-3.359 0,0 0.031,3.808 -0.274,6.486 -0.148,1.222 -1.068,4.438 -1.584,5.48 -1.352,2.793 -3.572,4.234 -6.8,4.854 -3.896,0.723 -8.028,0.964 -11.628,-0.575 -5.911,-2.487 -8.033,-8.017 -9.063,-14.395 -0.833,-5.101 -1.705,-13.968 -1.705,-13.968 0,0 -4.422,-2.094 -8.109,-3.934 C 108.367,446.051 97.611,439.29 88.201,432.337 85.594,430.391 74.394,421.011 71.922,418.682 64.99,412.101 58.754,405.554 54.01,397.153 c -3.688,-6.563 -4.75,-12.388 -1.945,-19.342 3.868,-9.693 17.765,-16.991 27.276,-21.15 6.981,-3.082 28.688,-10.17 37.705,-11.484 4.259,-0.609 10.865,-1.792 11.271,-2.056 0.166,-0.127 0.281,-0.235 0.401,-0.372 0.208,-0.293 0.559,-9.888 0.491,-13.398 -0.088,-3.451 2.554,-26.117 3.403,-30.91 0.443,-2.592 2.406,-12.57 4.41,-15.189 1.311,-1.77 3.629,-1.627 5.519,-0.465 10.342,6.431 13.484,28.734 14.253,40.082 0.46,6.914 0.689,17.314 0.689,17.314 0,0 11.864,-0.351 19.162,-0.144 7.092,0.165 14.909,1.284 22.27,2.457 9.424,1.511 27.793,5.518 38.328,10.859 8.675,4.398 16.795,11.808 19.426,19.65 2.444,7.189 2.078,12.164 -1.645,18.652 -4.186,7.326 -12.104,12.771 -20.132,13.226 -2.389,0.138 -11.381,-1.057 -14.148,-3.199 -1.085,-0.854 -1.029,-2.395 -0.246,-3.44 0.297,-0.367 4.5,-2.602 6.981,-3.906 1.244,-0.676 2.273,-1.405 3.244,-2.29 2.061,-1.815 3.916,-3.813 3.709,-6.155 -0.285,-3.04 -3.502,-4.915 -6.568,-6.121 -14.386,-5.715 -43.109,-10.459 -56.989,-11.28 -5.433,-0.319 -13.161,-0.592 -13.161,-0.592 l 1.634,76.646 c 0,0 6.389,1.217 11.424,2.033 2.889,0.438 15.13,1.54 18.383,1.62 24.768,0.654 52.412,-1.564 75.142,-12.29 9.979,-4.696 19.134,-10.543 26.065,-18.458 9.135,-10.473 13.919,-24.806 12.653,-39.777 -1.388,-16.35 -12.895,-35.759 -22.084,-47.577 -24.279,-31.223 -65.896,-56.907 -102.51,-71.965 -37.38,-15.363 -74.324,-24.201 -113.995,-25.681 -10.227,-0.379 -32.526,0.137 -43.798,3.255 -1.61,0.454 -3.233 [...]

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/picsart.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   sodipodi:docname="picsart.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview7"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="1"
     inkscape:pageshadow="2"
     inkscape:pageopacity="1"
     inkscape:pagecheckerboard="0"
     inkscape:document-units="px"
     showgrid="false"
     inkscape:object-nodes="false"
     inkscape:showpageshadow="false"
     inkscape:snap-page="true"
     units="px"
     inkscape:zoom="22.715805"
     inkscape:cx="7.5057873"
     inkscape:cy="7.7479094"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5" />
  <defs
     id="defs2" />
  <path
     id="path871"
     style="display:inline;fill:#000000;stroke-width:0.175629"
     d="M 11.999983,2.0000003 C 8.1725623,2.0071114 5.0383953,5.0852795 4.9112554,8.9620397 h -0.011967 v 0.1692631 c -0.00178,0.02336 -0.00344,0.04664 -0.00489,0.07003 0.00144,0.02322 0.00311,0.04645 0.00489,0.06968 V 21.9652 L 7.8054557,22 v -7.06163 c 1.2354942,0.965633 2.6343133,1.457535 4.1945263,1.463975 3.924232,-4.8e-5 7.105468,-3.223979 7.105619,-7.2009852 3.9e-5,-3.9771425 -3.181254,-7.2012863 -7.105619,-7.2013339 z m -0.02218,2.7522282 c 2.362709,4.78e-5 4.278047,1.9766751 4.278082,4.4149673 1.58e-4,2.4384372 -1.915236,4.4152822 -4.278082,4.4153302 C 9.6149593,13.582478 7.6995649,11.605633 7.6997227,9.1671958 7.6997582,6.7289036 9.6150953,4.7522763 11.977803,4.7522285 Z"
     sodipodi:nodetypes="ccccccccccccccccc" />
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/protonvpn.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   id="svg4818"
   viewBox="0 0 24 24"
   version="1.1"
   sodipodi:docname="protonvpn.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview9"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     width="24px"
     inkscape:zoom="18.643644"
     inkscape:cx="13.75804"
     inkscape:cy="14.589423"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4818" />
  <defs
     id="defs4">
    <style
       id="style2">.cls-1{fill:#040404;stroke:#000;stroke-miterlimit:15.12;stroke-opacity:0;stroke-width:0.46px;}</style>
  </defs>
  <path
     id="path2097"
     class="cls-1"
     d="m 18.709744,2.2300569 a 2.2000802,2.2000802 0 0 0 -2.259811,2.1403495 v 0.059731 L 7.0821711,7.4166714 A 2.2598109,2.2598109 0 0 0 5.2902505,6.5704867 2.2000802,2.2000802 0 0 0 3.0403948,8.7307465 v 0 a 2.1901252,2.1901252 0 0 0 2.2498557,2.1403495 v 0 a 2.2896763,2.2896763 0 0 0 0.6371273,-0.08959 l 6.1920802,7.86454 a 2.0706638,2.0706638 0 0 0 -0.189146,0.87605 2.2498558,2.2498558 0 0 0 4.499711,0 v 0 A 2.1005291,2.1005291 0 0 0 15.7033,17.929272 L 19.038263,6.5008009 A 2.1901252,2.1901252 0 0 0 20.9596,4.3704064 2.1901252,2.1901252 0 0 0 18.709744,2.2300569 Z m -1.572908,3.6833922 a 1.9014268,1.9014268 0 0 0 0.318563,0.2389227 L 14.170212,17.371786 a 2.2996313,2.2996313 0 0 0 -0.85614,0.169237 L 7.2314978,9.8258086 A 2.1702149,2.1702149 0 0 0 7.5301512,8.959714 Z" />
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/roku.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   sodipodi:docname="roku.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview7"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="1"
     inkscape:pageshadow="2"
     inkscape:pageopacity="1"
     inkscape:pagecheckerboard="0"
     inkscape:document-units="px"
     showgrid="false"
     inkscape:object-nodes="false"
     inkscape:showpageshadow="false"
     inkscape:snap-page="true"
     units="px"
     inkscape:zoom="31.041667"
     inkscape:cx="5.6214764"
     inkscape:cy="13.240268"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5" />
  <defs
     id="defs2" />
  <path
     id="path3031"
     style="fill:#000000;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:0.151308"
     d="m 15.61448,10.223055 -1.87773,1.87744 v -1.88364 h -1.62974 v 4.78724 h 1.62974 v -1.94189 l 1.96035,1.94189 h 2.05129 l -2.49114,-2.49144 2.06339,-2.06264 v 2.84097 c 0,0.94326 0.56725,1.81373 1.99575,1.81373 0.67817,0 1.3005,-0.38462 1.60297,-0.73263 l 0.73278,0.63201 H 22 v -4.78104 h -1.62974 v 2.49084 0.60463 c -0.18354,0.32032 -0.43925,0.52171 -0.83447,0.52171 -0.40097,0 -0.58496,-0.23771 -0.58496,-0.99803 v -0.20064 -2.41851 z m -6.3342,1.08054 c -0.43047,0 -0.79664,0.58511 -0.79664,1.30942 0,0.72432 0.36617,1.31018 0.79664,1.31018 0.44046,0 0.80602,-0.58586 0.80602,-1.31018 0,-0.72431 -0.36556,-1.30942 -0.80602,-1.30942 m 2.50899,1.30942 c 0,1.38372 -1.12528,2.49175 -2.50899,2.49175 -1.38326,0 -2.50022,-1.10803 -2.50022,-2.49175 0,-1.38265 1.11696,-2.49129 2.50022,-2.49129 1.38371,0 2.50899,1.10864 2.50899,2.49129 m -6.63933,-1.67602 c 0,-0.56817 -0.4571,-1.02572 -1.01604,-1.02572 H 3.63005 v 2.04236 H 4.1339 c 0.55894,0 1.01604,-0.45786 1.01604,-1.01664 m 2.29202,4.07155 H 5.59236 L 4.12392,12.970725 H 3.63005 v 2.03343 H 2 v -6.10892 h 2.33514 c 1.34619,0 2.44499,0.91542 2.44499,2.04176 0,0.68694 -0.42124,1.30049 -1.06233,1.67589 l 1.72416,2.39566" />
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/schoolplanner.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   id="svg5"
   viewBox="0 0 24 24"
   version="1.1"
   sodipodi:docname="schoolplanner.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs837" />
  <sodipodi:namedview
     id="namedview835"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="true"
     inkscape:zoom="15.520834"
     inkscape:cx="10.534228"
     inkscape:cy="16.3651"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5">
    <inkscape:grid
       type="xygrid"
       id="grid823"
       empspacing="1" />
  </sodipodi:namedview>
  <g
     style="fill:none"
     id="g934"
     transform="matrix(0.13888889,0,0,0.13888889,4.7777777,1.9999999)">
    <path
       fill-rule="evenodd"
       clip-rule="evenodd"
       d="M 0,10 C 0,4.47705 4.47705,0 10,0 h 7 V 144 H 10 C 4.47705,144 0,139.523 0,134 Z M 24,144 V 0 h 38 v 30 l 13,-9 13,9 V 0 h 6 c 5.5229,0 10,4.47705 10,10 v 124 c 0,5.523 -4.4771,10 -10,10 z M 40,77 H 88 V 87 H 40 Z M 76,97 H 40 v 10 h 36 z"
       fill="#000000"
       id="path925" />
  </g>
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/stremio.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   sodipodi:docname="stremio.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview7"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="1"
     inkscape:pageshadow="2"
     inkscape:pageopacity="1"
     inkscape:pagecheckerboard="0"
     inkscape:document-units="px"
     showgrid="false"
     inkscape:object-nodes="false"
     inkscape:showpageshadow="false"
     inkscape:snap-page="true"
     units="px"
     inkscape:zoom="16.0625"
     inkscape:cx="10.054475"
     inkscape:cy="6.4124514"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5" />
  <defs
     id="defs2" />
  <path
     id="rect847"
     style="display:inline;fill:#000000;stroke-width:0.0958784"
     d="M 12,2 1.999908,11.999907 12,22 22.000092,11.999907 Z m -1.546974,6.2662999 2.494324,1.8891391 2.494509,1.889324 -2.494509,1.889139 -2.494324,1.889324 v -3.778463 z" />
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/viber.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   viewBox="0 0 24 24"
   fill="none"
   version="1.1"
   id="svg4"
   sodipodi:docname="viber_new.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8">
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect2405"
       is_visible="true"
       lpeversion="1"
       satellites_param="F,0,0,1,0,4,0,1 @ F,0,0,1,0,4,0,1 @ F,0,1,1,0,0,0,1 @ F,0,1,1,0,0,0,1 | F,0,1,1,0,0,0,1 @ F,0,1,1,0,0,0,1 @ F,0,1,1,0,0,0,1 @ F,0,1,1,0,0,0,1"
       unit="px"
       method="auto"
       mode="F"
       radius="0"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="true"
       hide_knots="false" />
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect2224"
       is_visible="true"
       lpeversion="1"
       satellites_param="F,0,0,1,0,0,0,1 @ F,0,1,1,0,0,0,1 @ F,0,0,1,0,4,0,1 @ F,0,0,1,0,0,0,1 | F,0,0,1,0,0,0,1 @ F,0,0,1,0,0,0,1 @ F,0,0,1,0,0,0,1"
       unit="px"
       method="auto"
       mode="F"
       radius="0"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="true"
       hide_knots="false" />
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect2066"
       is_visible="true"
       lpeversion="1"
       satellites_param="F,0,1,1,0,8,0,1 @ F,0,1,1,0,8,0,1 @ F,0,0,1,0,4,0,1 @ F,0,0,1,0,0,0,1"
       unit="px"
       method="auto"
       mode="F"
       radius="8"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="true"
       hide_knots="false" />
  </defs>
  <sodipodi:namedview
     id="namedview6"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="true"
     inkscape:zoom="11.446291"
     inkscape:cx="-18.302872"
     inkscape:cy="12.231036"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg4">
    <inkscape:grid
       type="xygrid"
       id="grid901"
       empspacing="1" />
  </sodipodi:namedview>
  <g
     id="g828">
    <path
       id="path920"
       style="fill:#000000;stroke-width:0.0300125"
       class="cls-1"
       d="m 12.743316,13.455136 c 0,0 0.355648,0.03001 0.547128,-0.205886 L 13.6638,12.779554 c 0.180076,-0.232898 0.614657,-0.38146 1.040235,-0.144361 a 11.004698,11.004698 0 0 1 0.927688,0.592448 c 0.282418,0.207687 0.860759,0.690288 0.86256,0.690288 0.275515,0.232598 0.339142,0.57414 0.151563,0.934291 0,0.0021 -0.0015,0.0057 -0.0015,0.0075 a 3.8959278,3.8959278 0 0 1 -0.777025,0.9568 c -0.0036,0.0018 -0.0036,0.0036 -0.0069,0.0054 q -0.401568,0.33554 -0.789029,0.381459 a 0.52191807,0.52191807 0 0 1 -0.115249,0.0072 1.0504389,1.0504389 0 0 1 -0.33554,-0.05162 l -0.0084,-0.0123 C 14.21423,16.034414 13.549753,15.753496 12.44319,15.143041 A 12.917097,12.917097 0 0 1 10.620829,13.939238 9.5532916,9.5532916 0 0 1 9.8011865,13.212335 l -0.027612,-0.02761 -0.027611,-0.02761 v 0 L 9.7183519,13.1295 c -0.0093,-0.009 -0.018308,-0.01831 -0.027612,-0.02761 A 9.5532916,9.5532916 0 0 1 8.9638367,12.282246 12.930303,12.930303 0 0 1 7.7600337,10.460185 C 7.1495786,9.3533221 6.8686613,8.6894447 6.7564144,8.2908782 l -0.012305,-0.0084 A 1.0504389,1.0504389 0 0 1 6.6927884,7.946938 0.50631155,0.50631155 0 0 1 6.6996884,7.8316898 Q 6.7480084,7.4448282 7.081748,7.0420599 c 0.0018,-0.0033 0.0036,-0.0033 0.0054,-0.0069 A 3.8875243,3.8875243 0 0 1 8.0439523,6.258429 c 0.0018,0 0.0054,-0.0018 0.0075,-0.0018 0.3601504,-0.1875783 0.7016931,-0.1239517 0.9339902,0.1500627 0.0018,0.0018 0.483502,0.5801424 0.6902884,0.8625604 a 11.004698,11.004698 0 0 1 0.5924481,0.928588 C 10.505281,8.623117 10.356719,9.058599 10.123821,9.238074 L 9.6541251,9.61143 c -0.2370991,0.19148 -0.205886,0.547129 -0.205886,0.547129 0,0 0.6956909,2.633 3.2950769,3.296577 z M 11.865234,5.5800781 a 0.25300571,0.25300571 0 0 0 -0.255859,0.2519531 0.25300571,0.25300571 0 0 0 0.251953,0.2539063 c 1.352709,0.00942 2.453648,0.4470392 3.355469,1.3261719 0.894303,0.8718034 1.351452,2.0566437 1.363281,3.6113286 a 0.25300571,0.25300571 0 0 0 0.253906,0.251953 0.25300571,0.25300571 0 0 0 0.251953,-0.25586 C 17.073357,9.3660786 16.568799,8.024147 15.570313,7.0507812 14.579345,6.0847449 13.327698,5.5902644 11.865234,5.5800781 Z m 0.462891,1.3125 a 0.25300571,0.25300571 0 0 0 -0.271484,0.234375 0.25300571,0.25300571 0 0 0 0.234375,0.2714844 c 0.965847,0.070686 1.682147,0.3862102 2.205078,0.9570313 0.524376,0.572988 0.772768,1.2692149 0.753906,2.1406252 a 0.25300571,0.25300571 0 0 0 0.248047,0.257812 0.25300571,0.25300571 0 0 0 0.257812,-0.246093 C 15.777015,9.5304519 15.480038,8.681201 14.869141,8.0136719 14.251597,7.3395739 13.388122,6.9701541 12.328125,6.8925781 Z M 12.707031,8.25 a 0.25300571,0.25300571 0 0 0 -0.265625,0.2402344 0.25300571,0.25300571 0 0 0 0.238282,0.265625 c 0.436052,0.022749 0.730606,0.1457246 0.929687,0.3515625 0.199081,0.2058378 0.321148,0.5150889 0.34375,0.9707031 a 0.25300571,0.25300571 0 0 0 0.263672,0.240234 0.25300571,0.25300571 0 0 0 0.240234,-0.263671 C 14.430412,9.5180882 14.277586,9.0711387 13.972656,8.7558594 13.667727,8.4405801 13.229778,8.2772718 12.707031,8.25 Z M 19.342773,3.9507648 C 18.845766,3.4921732 16.837326,2.034164 12.363657,2.0143557 c 0,0 -5.2756041,-0.3181329 -7.8473786,2.0408527 -1.4315982,1.4318983 -1.9352086,3.5270737 -1.9883308,6.1246586 -0.053122,2.597586 -0.1218509,7.46562 4.5706097,8.785571 h 0.0045 l -0.003,2.014142 c 0,0 -0.030013,0.815441 0.5069118,0.98171 0.6494714,0.201684 1.0306307,-0.418075 1.6506897,-1.086154 0.3403422,-0.366753 0.8103382,-0.905478 1.1644862,-1.31725 3.209241,0.270113 5.677472,-0.347245 5.957789,-0.438483 0.647971,-0.210088 4.314603,-0.680085 4.910952,-5.547518 C 21.906444,8.5546884 20.993163,5.3811625 19.342773,3.9507648 Z M 19.8866,13.212034 c -0.50331,4.064299 -3.477252,4.319705 -4.025582,4.495579 -0.233197,0.07503 -2.401003,0.614356 -5.127042,0.436382 0,0 -2.0312484,2.450524 -2.6657135,3.08769 -0.099041,0.09964 -0.2154901,0.139859 -0.2932225,0.12005 -0.1092457,-0.02671 -0.1392582,-0.156065 -0.1380577,-0.345144 0.0018,-0.270113 0.017407,-3.346998 0.017407,-3.346998 0,0 -0.0024,0 0,0 C 3.684931,16.557532 3.9163277,12.414301 3.9613465,10.244695 4.0063653,8.075088 4.4139356,6.2977454 5.6246415,5.102346 7.7999504,3.1320227 12.281123,3.4264457 12.281123,3.4264457 c 3.784281,0.016507 5.597639,1.1560831 6.018114,1.5378426 1.396184,1.1953994 2.107481,4.0558946 1.587363,8.2465457 z" />
  </g>
</svg>
```

2021-12-22 19:42 UTC, patrykmichalik commented on svgs/ytstudio.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   viewBox="0 0 24 24"
   version="1.1"
   id="svg5"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   sodipodi:docname="ytstudio.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview7"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="1"
     inkscape:pageshadow="2"
     inkscape:pageopacity="1"
     inkscape:pagecheckerboard="0"
     inkscape:document-units="px"
     showgrid="false"
     inkscape:object-nodes="false"
     inkscape:showpageshadow="false"
     inkscape:snap-page="true"
     units="px"
     fit-margin-top="0"
     fit-margin-left="0"
     fit-margin-right="0"
     fit-margin-bottom="0"
     inkscape:zoom="31.041667"
     inkscape:cx="4.7194631"
     inkscape:cy="12.467114"
     inkscape:window-width="2560"
     inkscape:window-height="1011"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg5" />
  <defs
     id="defs2" />
  <g
     id="g891"
     style="display:inline"
     transform="matrix(0.23728973,0,0,0.23728973,-15.106615,-22.005003)">
    <path
       id="path871"
       style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 114.12532,101.16337 c -2.16573,-0.0136 -4.0757,1.25705 -4.0757,1.25705 0,0 -18.415306,10.5609 -28.356829,16.51912 -0.805032,0.48247 -2.811323,1.76029 -3.791992,3.0533 -1.306307,1.72264 -1.279291,5.50279 -1.281901,6.4091 -0.04251,12.61731 0.0063,22.16071 0.07383,33.00207 0.0048,0.79009 0.137388,1.62604 1.10496,3.06909 0.835559,1.24612 1.583823,1.88725 2.285981,2.29468 11.749501,6.81785 20.601631,12.02571 30.671051,17.78251 0.73948,0.42277 2.27805,0.88263 3.47397,0.89755 1.11722,0.0139 2.34939,-0.22703 3.26522,-0.7574 10.94171,-6.33637 20.86615,-12.09824 31.55551,-18.34494 1.14728,-0.67046 1.73214,-1.55336 2.11603,-2.38609 0.3385,-0.7343 0.70374,-2.217 0.70004,-3.08617 -0.0484,-11.32932 -0.11266,-22.00022 -0.12741,-34.05608 -0.004,-3.21554 -0.60249,-4.20346 -1.31657,-5.20874 -0.9339,-1.31473 -2.16611,-1.91892 -4.45834,-3.22656 -10.01144,-5.71123 -26.87164,-15.53482 -26.87164,-15.53482 0,0 -2.7282,-1.66964 -4.96624,-1.68367 z m -3.7e-4,16.34176 c 1.36851,0.009 3.03728,1.02941 3.03728,1.02941 0,0 10.30928,6.00699 16.43102,9.49926 1.40164,0.79961 2.15506,1.16873 2.72609,1.97265 0.43667,0.61471 0.80275,1.21871 0.80516,3.18493 0.009,7.37185 0.049,13.89682 0.0779,20.82442 0.002,0.53148 -0.22106,1.43828 -0.42807,1.88729 -0.23472,0.5092 -0.59215,1.04906 -1.29369,1.45903 -6.53627,3.81969 -12.60492,7.34277 -19.2955,11.2173 -0.56,0.32429 -1.31347,0.47176 -1.99661,0.46326 -0.73129,-0.009 -1.67223,-0.29062 -2.12442,-0.54913 -6.15719,-3.52014 -11.56987,-6.70399 -18.754384,-10.87294 -0.429348,-0.24913 -0.887019,-0.64148 -1.397938,-1.40347 -0.591651,-0.88238 -0.672707,-1.39331 -0.675716,-1.87644 -0.04128,-6.62923 -0.07098,-12.46497 -0.04499,-20.18014 0.0014,-0.55418 -0.0152,-2.86565 0.783749,-3.91901 0.599657,-0.79063 1.826735,-1.57194 2.31899,-1.86696 6.078979,-3.6433 17.339069,-10.10101 17.339059,-10.10101 0,0 1.16779,-0.77677 2.49208,-0.76845 z" />
    <path
       id="path871-1"
       style="display:inline;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.564858px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 431.63086,452.14453 c -4.60834,-0.0396 -8.67774,2.67188 -8.67774,2.67188 0,0 -39.23566,22.53168 -60.41796,35.24609 -1.71526,1.02958 -5.9892,3.75653 -8.08204,6.52148 -2.78818,3.68353 -2.74956,11.78134 -2.75976,13.72266 -0.15052,27.02608 -0.0921,47.46886 0,70.69141 0.007,1.69236 0.28592,3.48445 2.33789,6.58007 1.77197,2.67326 3.3614,4.04958 4.85352,4.92579 24.96851,14.66056 43.77918,25.85851 65.17773,38.23828 1.57149,0.90913 4.84204,1.89977 7.38672,1.93945 2.37728,0.0352 4.99995,-0.47587 6.95117,-1.60742 23.31228,-13.51964 44.45752,-25.81186 67.23242,-39.14063 2.44441,-1.43051 3.69284,-3.31974 4.51367,-5.10156 0.72378,-1.57126 1.50919,-4.7457 1.50586,-6.60742 -0.0476,-24.2677 -0.13583,-47.12556 -0.10937,-72.94922 0.007,-6.88773 -1.26266,-9.00731 -2.77735,-11.16406 -1.98081,-2.82066 -4.59945,-4.11952 -9.4707,-6.93164 -21.27549,-12.2818 -57.10351,-33.40625 -57.10351,-33.40625 0,0 -5.7985,-3.58696 -10.56055,-3.62891 z m -30.11719,43.17188 40.19336,23.26171 40.19141,23.26172 -40.23242,23.19727 -40.23243,23.19531 0.041,-46.45703 z"
       transform="scale(0.26458333)" />
  </g>
</svg>
```

2021-12-23 06:04 UTC, hardeik commented
@patrykmichalik Done! Kindly check if it is okay and I have also removed the es file explorer icon.

2022-01-03 11:10 UTC, patrykmichalik commented
Thanks, @hardeik! It would appear that you haven’t made the requested changes to the following files. Would you be able to do so?

- `alexa.svg`
- `disneyplus.svg`
- `picsart.svg`
- `protonvpn.svg`

2022-01-07 18:30 UTC, hardeik commented
@patrykmichalik On my side it seems to be updated. I had cut and pasted your code for these svgs before simply selecting commit suggestion for the other ones so that might be why those ones don't appear updated. Kindly check.

2022-01-09 10:16 UTC, patrykmichalik commented
Perhaps you’ve forgotten to push some of your changes, @hardeik? The revision history for the files I’ve listed shows that they haven’t been updated. Please see [here](https://github.com/hardeik/lawnicons/commits/Alexa%2C-Deezer%2C-Disney-Plus-etc/svgs/picsart.svg) for an example.

2022-01-09 12:11 UTC, hardeik commented
@patrykmichalik Sorry, I was mistaken and had not updated those icons. It should be in order now. Thank you!

2022-01-10 17:21 UTC, patrykmichalik approved these changes

2022-01-10 17:25 UTC, merged

2022-01-10 17:26 UTC, patrykmichalik commented
No worries, @hardeik! Everything looks good now, so Iʼve merged the pull request. Thanks for contributing!