Add LOFTER Andpods and NextTransfer logos
LawnchairLauncher/lawnicons pull request #2063
Opened 2024-05-02 15:51 UTC by AetherNo2332

# Description

Add icons for the LOFTER AndPods Honkai:Star Rail cloud and NextTransfer
Linked WearOS icon for the China market version 
## Icons addition information

lofter.svg (com.lofter.android)
honkai_star_rail_cloud.svg (com.miHoYo.cloudgames.hkrpg)
and_pods.svg (cn.xiaolongonly.andpodsop)
next_transfer.svg (com.next.transfer)
### Added

LOFTER (com.lofter.android)
Hongkai:Star rail · Cloud (com.miHoYo.cloudgames.hkrpg)
AndPods (cn.xiaolongonly.andpodsop)
Next Transfer (com.next.transfer)
### Linked

WearOS (linked com.google.android.wearable.app.cn to @drawable/wear_os)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-05-03 08:29 UTC, x9136 requested changes
Hey! Not bad for your first time. Something needs to be fixed.

Also, could you remove these updates from the PR?
![Screenshot 2024-05-03 at 11 22 27](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/88c6d517-ba5a-409c-9287-b86b88e53f8d)

2024-05-03 08:29 UTC, x9136 commented on svgs/next_transfer.svg
![Screenshot 2024-05-03 at 11 15 11](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/1126cb04-9aa1-488b-b04a-fa05d1c9587b)
If this is the original, then the icon turned out to be too different.

![Screenshot 2024-05-03 at 11 20 48](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9a5161aa-4830-431b-bc9d-f3c15aa1926b)
It should be something like this.

2024-05-03 19:11 UTC, AetherNo2332 commented
The workflow will fail if the SVG-process folder is deleted.  Is this okay?

2024-05-03 21:56 UTC, x9136 commented
> The workflow will fail if the SVG-process folder is deleted. Is this okay?

It doesn't need to be updated or deleted. PRs for adding icons should only include appfilter.xml and icons.

2024-05-04 08:41 UTC, x9136 requested changes

2024-05-04 08:41 UTC, x9136 commented on svgs/and_pods.svg
I don't know why you decided to replace the icon, but now its size is incorrect.

2024-05-04 08:41 UTC, x9136 commented on svgs/honkai_cloud.svg
The icon size has also decreased slightly and now does not fit.

2024-05-04 08:41 UTC, x9136 commented on svgs/lofter.svg
The icon has become too small. You also didn't take into account the alignment of the icon I mentioned last time.

2024-05-04 08:41 UTC, x9136 commented on svgs/next_transfer.svg
The icon is too small. The distances between the lines in the left "sheet" are also too small (last time I showed an example of what they should be in order for the icon to look good on the phone).

2024-05-04 08:41 UTC, x9136 commented on app/assets/appfilter.xml
drawable="honkai_cloud" name="云·星穹铁道 ~~ Honkai:Star rail · Cloud"
↓
drawable="honkai_star_rail_cloud" name="云·星穹铁道 ~~ Honkai: Star Rail · Cloud"

honkai_cloud.svg → honkai_star_rail_cloud.svg

2024-05-04 15:01 UTC, AetherNo2332 commented on svgs/and_pods.svg
sorry，
I used the wrong unit (pt) instead of the correct unit (px) when aligning the template, which resulted in abnormal graphics sizes. I will try my best to fix it

2024-05-04 18:18 UTC, x9136 requested changes
There's something else left (appfilter.xml, lofter.svg)

2024-05-05 16:23 UTC, merged