+15 icons, linked 2, modified 2 app names
LawnchairLauncher/lawnicons pull request #2084
Opened 2024-05-09 14:25 UTC by Ahmed-Khalifa

# Description
+15 icons, linked 2, modified 2 app names

### Added
Absher (`sa.gov.moi/com.elm.android.individual.RoutingActivity`)
Crypto Bubbles (`net.cryptobubbles/net.cryptobubbles.MainActivity`)
Alfagih Hospital (`com.dmfh.dmfh/com.dmfh.dmfh.ui.SplashScreen`)
ExpertOption (`com.expertoption/com.expertoption.MainActivity`)
Jarir (`com.jarirbookstore.JBMarketingApp/com.yaqut.jarirapp.activities.onboarding.SplashScreen`)
M2 (`com.m2.exchange/com.m2.exchange.MainActivity`)
Mobily (`com.mobily.activity/com.mobily.activity.core.navigation.RouteActivity`)
NAFATH (`sa.gov.nic.myid/sa.gov.nic.myid.MainActivity`)
Nahdi (`com.nahdi.main/com.nahdi.main.presentation.ui.activity.splash.SplashActivity`)
noon (`com.noon.buyerapp/com.noon.buyerapp.MainActivity`)
Phantom (`app.phantom/app.phantom.MainActivity`)
RedotPay (`com.redotpay/com.redotpay.MainActivity`)
Sehhaty (`com.lean.sehhaty/com.lean.sehhaty.ui.splash.SplashActivity`)
Tawakkalna Emergency (`sa.gov.nic.tawakkalna/com.store.android.ui.SplashActivity`)
Wafeer (`com.app.wafeer/com.app.wafeer.MainActivity`)

### Linked
ANB Telemoney (`telemoneyapp.anb.keystore/telemoneyapp.anb.keystore.launcher_2cfa478945145ffc9dff49d2d860c62dfd80892e28877b2ed1434c45f77637c8 `-> `anb_telemoney`
Tamara (`co.tamara.user/co.tamara.user.LaunchActivity` -> `tamara.svg`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-05-10 08:10 UTC, x9136 requested changes

2024-05-10 08:10 UTC, x9136 commented on app/assets/appfilter.xml
drawable="dr_alfagih" name="مستشفى محمد الفقيه ~~ Mohammad Alfagih Hospital" />
↓
drawable="dr_mohammad_alfagih_hospital" name="مستشفى محمد الفقيه ~~ Dr. Mohammad Alfagih Hospital" />
dr_alfagih.svg → dr_mohammad_alfagih_hospital.svg

2024-05-10 08:10 UTC, x9136 commented on svg-processor/bin/main/app/lawnchair/lawnicons/helper/Application.kt
![Screenshot 2024-05-10 at 11 09 53](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/35915d79-cb28-4a71-8cda-9c3b68ab4faf)
It is better to leave these files without updating.

2024-05-11 13:37 UTC, Ahmed-Khalifa commented on svgs/m2.svg
I reduced the stroke width to 10px.

2024-05-11 14:33 UTC, Ahmed-Khalifa commented on svgs/nafath.svg
I raised the icon up by 6px, changed the stroke width to 10px, the color to be 000000ff.

2024-05-11 14:46 UTC, Ahmed-Khalifa commented on svgs/phantom.svg
Changed the stroke width to 8px.

2024-05-11 15:24 UTC, Ahmed-Khalifa commented on svgs/redotpay.svg
Simplified the icon.

2024-05-11 16:01 UTC, Ahmed-Khalifa commented on svgs/sehhaty.svg
I increased the distance between lines.

2024-05-11 17:40 UTC, Ahmed-Khalifa commented on svgs/wafeer.svg
I did what you suggested.

2024-05-11 17:40 UTC, Ahmed-Khalifa commented on app/assets/appfilter.xml
Done

2024-05-11 17:47 UTC, Ahmed-Khalifa commented on svgs/dr_alfagih.svg
Done

2024-05-11 18:03 UTC, Ahmed-Khalifa commented on svgs/crypto_bubbles.svg
I reworked the icon again.

2024-05-11 18:04 UTC, Ahmed-Khalifa commented on svgs/wafeer.svg
I increased the spaces between lines.

2024-05-11 18:06 UTC, Ahmed-Khalifa commented on svg-processor/bin/main/app/lawnchair/lawnicons/helper/Application.kt
I did not touch these files.
they're created without my intervention.

2024-05-11 18:50 UTC, x9136 requested changes

2024-05-11 18:50 UTC, x9136 commented on svgs/crypto_bubbles.svg
![Screenshot 2024-05-11 at 21 17 05](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/98a5374e-675e-4042-8e18-591dc7888d1b)
The stroke width is incorrect.

2024-05-11 18:50 UTC, x9136 commented on svgs/m2.svg
> I reduced the stroke width to 10px.

I don't know why you did it, I think it was better with 12px stroke width.

Anyway:

![Screenshot 2024-05-11 at 21 20 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/9ca2f51a-4679-4095-960d-a32c92a2dd77)
The width is still too big.

![Screenshot 2024-05-11 at 21 21 35](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/8bf39b84-6198-4e6f-a92b-be1b65b1f21a)
The opacity should be 100%.

![Screenshot 2024-05-11 at 21 22 22](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/70857eb6-42ef-4945-9837-26611b06bca5)
The color is incorrect.

2024-05-11 18:50 UTC, x9136 commented on svgs/nafath.svg
> ... changed the stroke width to 10px

![Group 2](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/7dfd0652-29a3-41f6-937b-2c2292f53190)
The incorrect stroke width in the previous version.

![Screenshot 2024-05-11 at 21 32 00](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/11326d88-0499-4ebd-9eba-5f2535e80ab0)
Possible stroke widths depending on the shapes of the icons.


Anyway, let's go back to the current version.

![Screenshot 2024-05-11 at 21 31 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/ad033995-1adb-48c2-804a-986a11e1914d)
The width is too small.

2024-05-11 18:50 UTC, x9136 commented on svgs/sehhaty.svg
![Screenshot 2024-05-11 at 21 37 12](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/87e5ef37-ab05-4099-8964-a24172e403c6)
The width has changed a bit and is now too big.

2024-05-11 18:50 UTC, x9136 commented on svg-processor/bin/main/app/lawnchair/lawnicons/helper/Application.kt
> I did not touch these files.
they're created without my intervention.

Even so, they should not be added or updated. They were moved to another folder. https://github.com/LawnchairLauncher/lawnicons/tree/develop/svg-processor

Most likely, your branch is a little outdated in this regard. I suggest either figuring out how to keep the branch up-to-date, or how to ignore files so that they are not added to the request.

2024-05-11 18:58 UTC, x9136 commented
I suggest simplifying the process to save your time if you leave comments for me and not for yourself as a mark.

There is no point in telling me what and how you have changed, because I can see it when I do a review. But if, for example, you have a question or a suggestion to do something different from what I suggested, then it makes sense to discuss it.

2024-05-12 10:37 UTC, x9136 approved these changes

2024-05-12 10:38 UTC, x9136 commented
Thanks!

2024-05-12 10:38 UTC, merged

2024-05-12 10:40 UTC, x9136 commented
If you would like to get rid of the long commit history, then read how `git reset --hard` works.