Link aliucord (com.aliucord) to discord and link other countries' sho…
LawnchairLauncher/lawnicons pull request #209
Opened 2021-12-19 01:26 UTC by uuunwired

…pee apps

2021-12-22 21:03 UTC, patrykmichalik requested changes
Thanks for your interest in contributing! For the CapCut icon, I’d suggest making the logo a bit larger. For the Infinity for Reddit icon, how about separating the UFO from its driver? These suggestions are reflected below.

2021-12-23 15:58 UTC, uuunwired commented on app/src/main/res/drawable/infinity_for_reddit.xml
> +</vector>
Added the suggested changes to my repo. Thanks.

2021-12-27 12:21 UTC, uuunwired commented
**Update 12/27**

**added:**
* AliExpress (com.alibaba.aliexpresshd)
* Lazada (com.lazada.android)
* Citra Emulator (org.citra.citra_emu)
* Dolphin Emulator (org.dolphinemu.dolphinemu)
* DraStic DS Emulator (com.dsemu.drastic)
* Pokemon GO (com.nianticlabs.pokemongo)
* Viber (com.viber.voip)

2021-12-28 17:06 UTC, uuunwired commented
**Update 12/29**

**added:**

* 3DMark (com.futuremark.dmandroid.application)
* AIDA64 (com.finalwire.aida64)
* AndroBench (com.andromeda.androbench2)
* AppChecker (com.kroegerama.appchecker)
* Canva (com.canva.editor)
* Device care (Samsung) (com.samsung.android.lool)
* Device Info HW (ru.andr7e.deviceinfohw)
* DiskInfo (me.kuder.diskinfo)
* Geekbench (com.primatelabs.geekbench, com.primatelabs.geekbench5)
* Geometric Weather (wangdaye.com.geometricweather)
* Goodreads (com.goodreads)
* GSam Battery Monitor (com.gsamlabs.bbm)
* Network Cell Info (Lite) (com.wilysis.cellinfo, com.wilysis.cellinfolite)
* Phone Info SAM (org.vndnguyen.phoneinfo)
* QuickSwitch (xyz.paphonb.quickstepswitcher)
* Screen Recorder (Kimcy929) (com.kimcy929.screenrecorder)
* Shizuku (moe.shizuku.privileged.api)
* YASNAC (rikka.safetynetchecker)
* YouTube Studio (com.google.android.apps.youtube.creator)
* Zoom (us.zoom.videomeetings)

2022-01-16 11:30 UTC, patrykmichalik requested changes
Iʼd suggest some minor sizing tweaks: [suggestions.zip](https://github.com/LawnchairLauncher/lawnicons/files/7876850/suggestions.zip).

2022-01-24 19:32 UTC, ZhmieXD commented
Oh wow turns out some of the icons I'm currently doing are currently in this pull request, Mind if I resolve the issue?

2022-01-24 19:45 UTC, uuunwired commented
> Oh wow turns out some of the icons I'm currently doing are currently in this pull request, Mind if I resolve the issue?

Sure go ahead!

2022-01-24 19:50 UTC, ZhmieXD commented
After a rest ^^;

2022-01-25 09:22 UTC, ZhmieXD commented
Alright, so, can the suggestions be a bit more specific? @patrykmichalik

2022-01-25 09:34 UTC, ZhmieXD commented
![diskinfo](https://user-images.githubusercontent.com/32131554/150950290-f8774851-1919-4a41-ade9-94dd5e09545a.svg)
![drastic_ds_emulator](https://user-images.githubusercontent.com/32131554/150950296-733f7d25-bc78-4393-9c9d-28747ea51a92.svg)

Here, I uploaded the tweaked svg files requested in the suggestions. hope this is enough ^^;

2022-01-31 21:39 UTC, patrykmichalik commented
Just to clarify, my comment above includes a ZIP file with some minor tweaks that I’d suggest. These changes would have to be applied by @uuunwired.

2022-02-02 12:28 UTC, ZhmieXD commented
> Just to clarify, my comment above includes a ZIP file with some minor tweaks that I’d suggest. These changes would have to be applied by @uuunwired.

I know, it's all on him to apply it.
But does that means you already put your modified version of it? Alright then 👍

2022-10-04 23:25 UTC, Chefski commented
Thanks for all these additions. Unfortunately I'll be closing this as the icons are outdated.

2022-10-04 23:25 UTC, closed without merging