Added 8, Linked 1, Modified 1
LawnchairLauncher/lawnicons pull request #2099
Opened 2024-05-15 19:53 UTC by Ahmed-Khalifa

### Added
stc pay (`sa.com.stcpay`)
Salatuk (`com.masarat.salati`)
SAB Mobile (`com.sabb.mobilebanking`)
ANB - Arab National Bank (`com.anb.mobile.prod`)
Bupa Arabia (`com.buparabia.mobileapp.outsystems`)
Cobone (`com.cobone.coboneapp`)
Mobily Pay (`com.es.mobily`)
Najm (`com.najm.najm`)

### Linked
Exchange (`com.blockchain.exchange` → `blockchain.svg`)

### Updated
Rabby Wallet (`com.debank.rabbymobile`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-05-15 20:40 UTC, Ahmed-Khalifa commented
I do not understand what this error is: "Comment icon checklist / comment (pull_request)

2024-05-15 20:42 UTC, Ahmed-Khalifa reviewed
Kindly review my pull request.

2024-05-15 22:49 UTC, x9136 requested changes

2024-05-15 22:49 UTC, x9136 commented on svgs/najm.svg
![Screenshot 2024-05-16 at 01 00 57](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/026ac17b-3cf2-4712-b2b9-d567900fc250)
The highlighted corners should be rounded in accordance with the guidelines.

![Screenshot 2024-05-16 at 01 04 01](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/99d1de37-73d5-44bf-bc91-cd39b13425d9)
The fill should be replaced with strokes.

![Screenshot 2024-05-16 at 01 07 02](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/4b995aa6-733e-4d46-ac73-9756c5da9ac8)
The shapes are too close in this area.


The icon is pressed to the bottom because of the emptiness at the top.

2024-05-15 22:49 UTC, x9136 commented on svgs/mobily_pay.svg
It is worth trying to reduce the density of "a" and better position it relative to other letters.

2024-05-15 22:49 UTC, x9136 commented on svgs/bupa_arabia.svg
![Screenshot 2024-05-16 at 01 24 50](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/d0f262b3-f396-4400-ba61-bd4108763711)
It is worth reducing the density in these areas.

It is worth reducing the density of strokes in the word "Bupa".

It is also worth increasing the distance between the "بوبا" and "Bupa"

2024-05-15 22:49 UTC, x9136 commented on svgs/anb.svg
The density is too high where the strokes are close. Also, the icon is still pressed to the bottom due to the emptiness at the top.

2024-05-15 22:49 UTC, x9136 commented on svgs/salatuk.svg
The icon goes out of the content area due to the fact that it is located closer to the left edge.

2024-05-15 22:49 UTC, x9136 commented on svgs/simply_fi.svg
The density is too high and the icon is slightly pressed to the bottom due to the emptiness at the top.

2024-05-15 22:49 UTC, x9136 commented on svgs/sab_mobile.svg
https://github.com/LawnchairLauncher/lawnicons/blob/ad928fa5a08b2194b5ea14a4c52aeb22a93963ca/svgs/hsbc.svg

2024-05-15 22:56 UTC, x9136 commented
> I do not understand what this error is: "Comment icon checklist / comment (pull_request)

You can ignore it. We are testing a self-review checklist.

2024-05-16 07:37 UTC, Ahmed-Khalifa commented on svgs/urpay.svg
Is it better to use 12px stroke width or 14px, because the icon is simple in my opinion.

2024-05-16 08:27 UTC, x9136 commented on svgs/urpay.svg
Any of them.

2024-05-16 11:30 UTC, Ahmed-Khalifa commented on svgs/bupa_arabia.svg
I have other suggestions for this icon as shown below.
![image](https://github.com/LawnchairLauncher/lawnicons/assets/8474394/067a6352-62d1-4997-b2e0-2fe71601a090)

the box in blue is the original, which one is better?
as for the refinements, it'll be done once the icon chosen.

2024-05-16 11:53 UTC, x9136 commented on svgs/bupa_arabia.svg
> the box in blue is the original, which one is better?

There is no significant difference, so it's up to you.

I mostly read from left to right, so the option 1 seems neat to me, but if I was used to reading the other way around, then the option 2 could be neat.

2024-05-17 23:39 UTC, Ahmed-Khalifa reviewed
Updated icons as requested.

2024-05-18 08:07 UTC, x9136 requested changes

2024-05-18 08:07 UTC, x9136 commented on svgs/najm.svg
I have removed irrelevant items from the first comment.

In addition to the remaining items, I suggest to align the upper point relative to the vertical line.

2024-05-18 08:07 UTC, x9136 commented on svgs/urpay.svg
You used the incorrect stroke width.

2024-05-18 08:07 UTC, x9136 commented on svgs/rabby_wallet.svg
You used the incorrect stroke width.

2024-05-19 21:14 UTC, merged