+ 2 icons: Banxo, RATP
LawnchairLauncher/lawnicons pull request #2144
Opened 2024-06-09 19:50 UTC by Ender-events

# Description
Add 2 icons (Caisse d'epargne banxo, ratp)

## Icons addition information
### Added
Banxo (`com.caisseepargne.android.mobilebanking`)
Bonjour RATP (`com.fabernovel.ratp`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-06-12 21:57 UTC, x9136 requested changes

2024-06-12 21:57 UTC, x9136 commented on svgs/caisseepargne_banxo.svg
- the icon size is too small;
- try to remove the fill by making 6x6px ellipse with 6px stroke width. The result is likely to be comparable to what was expected, so the fill can be avoided.

2024-06-12 21:57 UTC, x9136 commented on svgs/hello_ratp.svg
- the icon size is too small;
- replace the fill with 12px stroke.

2024-06-12 21:57 UTC, x9136 commented on app/assets/appfilter.xml
drawable="caisseepargne_banxo" → drawable="banxo" 
caisseepargne_banxo.svg → banxo.svgs

drawable="hello_ratp" → drawable="bonjour_ratp"
hello_ratp.svg → bonjour_ratp.svgs

2024-06-14 20:35 UTC, Ender-events commented
If #2159 is accepted, you can close this PR

2024-06-26 21:04 UTC, x9136 commented
#2174

2024-06-26 21:04 UTC, closed without merging