+5 icons
LawnchairLauncher/lawnicons pull request #2174
Opened 2024-06-22 00:11 UTC by I21b

# Description

Add 5 icons to Lawnicons.

## Icons addition information

### Added

Banxo (`com.caisseepargne.android.mobilebanking`) [↗︎](https://github.com/LawnchairLauncher/lawnicons/pull/2144)
Bonjour RATP (`com.fabernovel.ratp`) [↗︎](https://github.com/LawnchairLauncher/lawnicons/pull/2144)
Fandango (`air.com.vudu.air.DownloaderTablet`) [↗︎](https://github.com/LawnchairLauncher/lawnicons/pull/2133)
Fandango (`com.fandango`)
Rizline (`com.PigeonGames.Rizline`)
律动轨迹 ~~ Rizline (`com.leiting.ldgj`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-06-22 03:18 UTC, I21b reviewed
This is my first time making icons, so point out any mistakes!

2024-06-22 17:06 UTC, x9136 requested changes

2024-06-22 17:06 UTC, x9136 commented on svgs/aircade.svg
I doubt this app exists or is called Aircade because I haven't found it.

Can you give a link or take a screenshot of the app info screen?

2024-06-22 17:13 UTC, I21b commented on svgs/aircade.svg
[apk](https://25.s-ul.eu/apk/QqUiK9LU)
[official](https://arcadelink.github.io/Document/overview.html)

2024-06-22 17:17 UTC, I21b commented on app/assets/appfilter.xml
![originalname](https://github.com/LawnchairLauncher/lawnicons/assets/169070113/edaef772-1f4e-4509-a756-799ce357f253)🤔

2024-06-22 17:22 UTC, x9136 commented on app/assets/appfilter.xml
Ok. In English the TV remote is more often called "remote".

2024-06-22 17:55 UTC, I21b commented on svgs/maimai_data.svg
Is it okay to use 6px for all?

2024-06-22 18:41 UTC, x9136 commented on svgs/maimai_data.svg
No, this way the icon will be too different from the others.

2024-06-22 18:45 UTC, I21b commented on svgs/maimai_data.svg
> No, this way the icon will be too different from the others.

What should I do now?
<img width="400" alt="1" src="https://github.com/LawnchairLauncher/lawnicons/assets/169070113/4ede04c1-a9cb-4a1e-9f82-7682410c99fc">

2024-06-22 19:06 UTC, x9136 commented on svgs/maimai_data.svg
Simplify the details while maintaining recognition and quality. I would start by using the 10px stroke width, take a few steps and then see what I got. What would I try:

1. Delete the dash on the bottom right.
2. Remove the bottom line at the ears.
3. For the line in the outer ellipse, I would use the 8px stroke width.
4. Most likely, I would have reduced the glasses, and therefore the inner circle.
5. I would have made a sufficient indentation between the glasses and the nose.
6. If after that I would have lost a lot in quality and recognition, then I would have reduced the main stroke width to 8px.

and so on.

2024-06-22 19:29 UTC, I21b commented on svgs/maimai_data.svg
8px looks fine, 10px is a bit thicker
<img width="423" alt="full8px" src="https://github.com/LawnchairLauncher/lawnicons/assets/169070113/2cd5659c-8355-43c6-87fd-37cc32b140e6">

2024-06-22 19:36 UTC, x9136 commented on svgs/maimai_data.svg
Yeah, sort of.

2024-06-22 22:18 UTC, I21b commented
Why it shows request changes not resolved? 🙇‍♂️@x9136

2024-06-23 03:59 UTC, x9136 requested changes

2024-06-23 03:59 UTC, x9136 commented on svgs/pipepipe.svg
Although the old version is of poor quality — the new version is not suitable in style for Lawnicons. The base stroke width is 12px, not 18px.

2024-06-23 03:59 UTC, x9136 commented on svgs/fandango.svg
The width is a little too wide. You can also align the "F" better.

2024-06-23 03:59 UTC, x9136 commented on svgs/tagwriter.svg
The height of the icon is too small.

2024-06-23 03:59 UTC, x9136 commented on svgs/taginfo.svg
The height of the icon is too small.

2024-06-26 15:34 UTC, x9136 requested changes

2024-06-26 15:34 UTC, x9136 commented on svgs/fandango.svg
![Screenshot 2024-06-26 at 18 29 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/00e6e24f-7d3a-472c-a2d0-1aaf20162410)

The width is noticeably smaller than 160px.

2024-06-26 15:34 UTC, x9136 commented on svgs/taginfo.svg
The height of the icon has become even smaller than last time. The height should be 160px or as close to it as possible (160.01px for example).

The same for `tagwriter.svg`.

2024-06-26 20:55 UTC, x9136 approved these changes

2024-06-26 20:59 UTC, merged