+1 icon +1 link
LawnchairLauncher/lawnicons pull request #2181
Opened 2024-06-26 23:28 UTC by Alex123098c

# Description

## Icons addition information

### Added

Shortcuts Widget (`com.light.shortcutswidget`)

### Linked

WingOS Camera (`com.wingos.wingcamera` → `camera.svg`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-06-30 10:25 UTC, x9136 requested changes

2024-06-30 10:25 UTC, x9136 commented on svgs/shortcuts_widget.svg
The canvas size is incorrect. The icon itself is a little smaller than it needs to be. The wrong stroke width was also used. Due to the fact that the lines at the bottom of the icon are not connected and have different stroke widths, there is a bulge at the junction.

**Lawnicons guidelines**
The canvas size is 192×192px.
The icon size is 160×160px.
The stroke width is 12px.

2024-07-10 16:40 UTC, Alex123098c commented on svgs/shortcuts_widget.svg
I fixed the icon (hopefully)

2024-07-10 20:00 UTC, x9136 requested changes

2024-07-12 21:48 UTC, Alex123098c commented on svgs/shortcuts_widget.svg
i made it pixels instead of milimeters

2024-07-12 22:05 UTC, x9136 approved these changes

2024-07-12 22:14 UTC, merged