+9 icons, +1 link
LawnchairLauncher/lawnicons pull request #2183
Opened 2024-06-29 06:30 UTC by Autines

# Description

## Icons addition information
### Linked
PiliPala (com.guozhigq.pilipala → pilipala.svg)

### Added
VVEX (com.guozhigq.vvex)
爱奇艺 (com.qiyi.video)
飞书 (com.ss.android.lark)
雅迪智行 (com.yadea.smartmoto)
华住会 (com.htinns)
天猫 (com.tmall.wireless)
凯迪仕 (com.kaidishi.lock)
it之家 (com.ruanmei.ithome)
云日历 (com.ruanmei.yunrili)

## Contributor's checklist

- [x]  I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-06-30 11:14 UTC, x9136 requested changes

2024-06-30 11:14 UTC, x9136 commented on svgs/tmall.svg
The icon size is too big. It's also very dense. It will be difficult to make a high-quality icon from the app name, so I suggest using their cat.

2024-06-30 11:14 UTC, x9136 commented on svgs/vvex.svg
The icon size is too big.

2024-06-30 11:14 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.guozhigq.vvex/com.guozhigq.vvex.MainActivity}" drawable="vvex" name="Vvex" />
Vvex → [VVEX](https://github.com/guozhigq/flutter_v2ex)

2024-06-30 11:14 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.yadea.smartmoto/com.yadea.smartmoto.main.view.normal_icon}" drawable="yadi" name="雅迪智行 ~~ Yadi" />
雅迪智行 ~~ Yadi → [雅迪](https://zh.wikipedia.org/wiki/%E9%9B%85%E8%BF%AA) ~~ [Yadea](https://play.google.com/store/apps/details?id=com.yadea.smartmotoen&hl=en)

2024-06-30 11:14 UTC, x9136 commented on svgs/yadi.svg
The icon size is too big.

2024-06-30 11:14 UTC, x9136 commented on svgs/yunrili.svg
I suggest raising the icon 1px up so that it feels centered. It is also better to round off (6px) the check mark so that it is as in the original.

2024-06-30 14:13 UTC, Autines commented on svgs/feishu.svg
Could you please take a look this one? if it's ok, then I know how to fix others. Thanks!
![feishu](https://github.com/LawnchairLauncher/lawnicons/assets/16075324/0fd29a18-d762-40d8-a4cc-8cc41a037c30)

2024-06-30 14:33 UTC, x9136 commented on svgs/feishu.svg
The icon size is correct. I would also move the icon down by 1px to compensate for the emptiness at the bottom.

2024-07-02 13:34 UTC, Autines commented on svgs/tmall.svg
I delete the icon. I will push when I make it better.

2024-07-02 14:43 UTC, x9136 requested changes

2024-07-02 14:43 UTC, x9136 commented on svgs/yadea.svg
![Screenshot 2024-07-02 at 17 07 20](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/299464bf-1e84-42d5-a25e-c85e0614312d)
You need to increase the distance between the lines in the selected areas so that the lines do not stick together at small sizes.

2024-07-02 14:43 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.qiyi.video/com.qiyi.video.WelcomeActivity}" drawable="iqiyi" name="爱奇艺 ~~ iQiyi" />
iQiyi → [iQIYI](https://play.google.com/store/apps/details?id=com.iqiyi.i18n&hl=en)

2024-07-02 14:43 UTC, x9136 commented on svgs/kaadas.svg
![Screenshot 2024-07-02 at 17 19 00](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/532fc91f-f305-4eb9-9c91-d1fc05d40322)
The icon is shifted.

![Screenshot 2024-07-02 at 17 20 50](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/33addb8a-5704-443b-94c3-1ff4c6190404)
You also didn't round the corners.

2024-07-02 14:43 UTC, x9136 commented on svgs/ithome.svg
> Also, don't forget to move the icon down a little to compensate for the emptiness at the bottom. Now it looks pinned to the top.

The geometric center ≠ the visual center. If you place icons of an abstract shape in the geometric center, then some of them will be displaced. On the phone, this will be noticeable among the other icons that look centered. At the same time, you need to stay within the content area, so some icons will still be shifted. When it can be avoided, it's worth doing it.

To avoid this, you need to take into account the shape of the icon and shift it slightly in the direction where there is more emptiness. For example, a triangle pointing to the right is shifted ~10 px to the right of the geometric center to look visually centered rather than shifted to the left.

![image](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/adae800e-a31a-4e41-8887-f86d5fcc2b8d)

2024-07-02 14:43 UTC, x9136 commented on svgs/yunrili.svg
> I suggest raising the icon 1px up so that it feels centered.

The geometric center ≠ the visual center.
![image](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/adae800e-a31a-4e41-8887-f86d5fcc2b8d)

2024-07-02 14:43 UTC, x9136 commented on svgs/iqiyi.svg
On phones, the icon will be 3-4 times smaller than here. Due to the fact that the letters are too close to each other, the lines in the icon will stick together. As a result, it will look and read worse.

To avoid this, you need  to increase the distance between the lines. For example, reduce the size of the letters and reduce the stroke width to 10px.

2024-07-11 03:12 UTC, Autines commented on svgs/yadea.svg
Is there a standard? Or just increase the distance will be OK.

2024-07-27 02:55 UTC, Autines commented on svgs/iqiyi.svg
now icon already letters, I cannot reduce the wide size of the letters. I just reduce the stroke width to 10px. Is that will be ok?

2024-07-27 16:34 UTC, x9136 commented on svgs/iqiyi.svg
> Is that will be ok?

Yes, but I completed the PR for you, so it's no longer relevant.

2024-07-27 16:35 UTC, merged