+1 icon
LawnchairLauncher/lawnicons pull request #2203
Opened 2024-07-17 16:20 UTC by Alex123098c

# Description

## Icons addition information

### Added

PowerAudio Plus (`power.amp.musicplayer.pi.audioplayer`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-07-17 17:09 UTC, thismoon commented
It would be better to link it to `[generic_player.svg](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs%2Fgeneric_player.svg)` instead of creating a new icon in this case

2024-07-18 19:53 UTC, x9136 requested changes

2024-07-18 19:53 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{power.amp.musicplayer.pi.audioplayer/xsoftstudio.musicplayer.ActivityMain}" drawable="poweraudio_plus" name="PowerAudio Plus"/>
`"/>` → `" />`

Need a space here.

2024-07-18 19:53 UTC, x9136 commented on svgs/poweraudio_plus.svg
The easiest way is to remove the icon and make the link the way **thismoon** suggested.

If you want to keep the icon, then consider the following:
1. The icon size is incorrect.
2. The icon looks shifted to the left due to the emptiness on the right.
3. The stroke width of such minimalistic icons increases to 14px.

2024-07-27 16:53 UTC, x9136 commented
#2229

2024-07-27 16:53 UTC, closed without merging