update 1 icon
LawnchairLauncher/lawnicons pull request #2219
Opened 2024-07-22 23:47 UTC by thismoon

# Description
this pr updates the aves gallery icon

## Icons addition information

### Updated

Aves Gallery/Aves Libre (`deckers.thibault.aves`/`deckers.thibault.aves.libre`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-07-24 14:52 UTC, x9136 requested changes

2024-07-24 14:52 UTC, x9136 commented on svgs/aves_gallery.svg
The icon size is slightly incorrect.


![Screenshot 2024-07-24 at 17 44 44](https://github.com/user-attachments/assets/4b66dbc5-da9c-4689-aa2e-ed0856cadc12)
The strokes in the highlighted area are too close to each other. It is better to make the eye without the hole.

![Screenshot 2024-07-24 at 17 47 02](https://github.com/user-attachments/assets/dd8e7e77-6b51-4856-9a27-0d18b6d4373b)
The selected corners should be rounded to 6px.

![Screenshot 2024-07-24 at 17 48 32](https://github.com/user-attachments/assets/34a5b776-57be-4fdf-83bd-b18d4b371ac4)
These lines should be an extension of the wing. Now they are growing from a random place.

![Screenshot 2024-07-24 at 17 51 22](https://github.com/user-attachments/assets/b8912579-4822-41b1-a44a-5761e8027671)
Expected result.

2024-07-25 19:27 UTC, x9136 approved these changes

2024-07-25 19:30 UTC, merged

2024-07-25 19:51 UTC, thismoon commented
@x9136 i don't remember reading anything about the "visual center" in the guidelines. neither does the google results show much about it. there's [this website](https://javier.xyz/visual-center) (which doesn't give the same result as yours, see the image below) and [this figma plugin](https://www.figma.com/community/plugin/1011367955824608832/visual-center). i was wondering if it is possible to add a method (or even a script to automate it) that contributors have to follow to apply the visual center to their contributions. or maybe would that will complicate the contribution process

![image](https://github.com/user-attachments/assets/dcd1a08c-e77a-4bcc-976a-86f132bb4007)

2024-07-25 20:19 UTC, x9136 commented
> there's [this website](https://javier.xyz/visual-center)

![Screenshot 2024-07-25 at 22 58 32](https://github.com/user-attachments/assets/000a14cc-d7ca-46f6-9e93-feae6e8ad6d4)
This site considers some other visual center, or it is not suitable for all possible shapes. I mean the visual center, which is physiologically seen by the human eye.  For example, the triangle on the left is below the visual center I'm talking about, and on the right is above. That is, at least the triangle is considered incorrect.

> i was wondering if it is possible to add a method (or even a script to automate it) that contributors have to follow to apply the visual center to their contributions

If this is possible, then the development will take a lot of time.

Practice is needed, for example, make 100 icons and pay attention to the visual center in each one. After that, you sort of see when and how much the icon is shifted, if geometrically it is centered.

https://crazybitsstudios.com/another-way-of-aligning-elements-when-creating-icons
This article is better suited to mathematical calculations, but the correct method depends on what the eyes see.