+5 icons and -1 typo
LawnchairLauncher/lawnicons pull request #2239
Opened 2024-08-01 14:58 UTC by 5h3r10k

# Description

Added 5 icons and fixed a typo
- Marcus
- NJ Transit
- Parkmobile
- Snackpass
- YI Home

## Icons addition information

### Added

Marcus (com.marcus.android)
NJ Transit (com.njtransit.njtapp)
Parkmobile (net.sharewire.parkmobilev2)
Snackpass (com.snackpassapp)
YI Home (com.ants360.yicamera.international)

## Contributor's checklist
- [X] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

2024-08-02 18:32 UTC, 5h3r10k commented
Everything looks good to me now

2024-08-03 10:43 UTC, x9136 requested changes

2024-08-03 10:43 UTC, x9136 commented on svgs/marcus.svg
![Screenshot 2024-08-03 at 13 06 17](https://github.com/user-attachments/assets/13a8d20a-6167-4db3-b284-99595a2e6b8c)
The icon size is too small.

![Screenshot 2024-08-03 at 13 05 42](https://github.com/user-attachments/assets/241003c9-cf8e-4220-ac5d-2e672e6ae5ae)
The color should be black (#ffffff).

![Screenshot 2024-08-03 at 13 04 13](https://github.com/user-attachments/assets/3cbfec1b-5e11-45f0-8231-f917edc91383)
There is a defect here.

![Screenshot 2024-08-03 at 13 04 55](https://github.com/user-attachments/assets/b96eefb4-cdd9-4a56-a7aa-4de16195322f)
The corners are rounded in a different way.

It is better to make the icon with lines, rather than tracing the shape.

Considering everything:
![Screenshot 2024-08-03 at 13 16 12](https://github.com/user-attachments/assets/9ff7370e-248c-478f-990b-93ea12270089)

2024-08-03 10:43 UTC, x9136 commented on svgs/nj_transit.svg
The icon size is too small. It needs to be done with a stroke.

The result is something like this.
![Screenshot 2024-08-03 at 13 35 43](https://github.com/user-attachments/assets/0d667065-c19a-4892-8768-7b073b3d8959)

2024-08-03 10:43 UTC, x9136 commented on svgs/parkmobile.svg
The icon size is too small. The color should be black (#ffffff).

2024-08-03 10:43 UTC, x9136 commented on svgs/snackpass.svg
The icon size is too small. The color should be black (#ffffff).

It is possible to make the icon using the base stroke width. This way it will look more appropriate.
![Screenshot 2024-08-03 at 13 42 32](https://github.com/user-attachments/assets/4685d00b-25bc-4bde-89c3-262e46cbd6d4)

2024-08-03 10:43 UTC, x9136 commented on svgs/yi_home.svg
The icon size is too small. The color should be black (#ffffff).

2024-08-04 13:22 UTC, x9136 requested changes
You have all the information to make Lawnicons-style icons: the comment from **github-actions** and the review. In this regard, it is impossible to give you more.

Good luck if you plan to do everything as required. If there is an update, I will come here in the foreseeable future, but in silence.

2024-08-04 13:22 UTC, x9136 commented on svgs/snackpass.svg
The previous comments remain valid. Also, all parts should be done with a stroke.

2024-08-04 13:22 UTC, x9136 commented on svgs/yi_home.svg
The icon size is too small. The icon needs to be done with a stroke.

2024-08-11 18:42 UTC, x9136 requested changes
Some of the issues have been resolved.

2024-08-15 16:37 UTC, x9136 commented
The last 2 icons still don't fit.

I suggest removing them, fixing the conflicts in the branch and then everything will be fine.

2024-08-16 13:44 UTC, 5h3r10k commented
I'm unsure why they don't fit, as I have kept both their sizes fitting 160x160 px.

<img width="1056" alt="Screenshot 2024-08-16 at 09 40 08" src="https://github.com/user-attachments/assets/2884b24b-2e84-4434-97bd-3cd3f1c9c9e1">
<img width="1153" alt="Screenshot 2024-08-16 at 09 42 08" src="https://github.com/user-attachments/assets/fe2e7fea-cdcd-4600-8941-d415c3886823">

Should I discard the PR and create a new one?

2024-08-16 14:17 UTC, x9136 commented
> I'm unsure why they don't fit

Because icons should be made with a stroke.

2024-08-16 15:16 UTC, 5h3r10k commented
I haven't ignored the message about the stroke; as is visible on the right side of the images, the fill is transparent and the stroke is black and 12px. However, I now believe that illustrator's "stroke inside" (where the stroke is entirely on the inside of the path, not on the center of the path) is causing compatibility issues. I can attempt to rework the icons in question. I will remove these 2 icons and add them in another PR.

Would you be able to show me what the icon looks like on your end? So I can troubleshoot the stroke issue.

2024-08-16 15:32 UTC, 5h3r10k commented
I removed the icons in question, the rest should be good to go

2024-08-16 23:31 UTC, merged

2024-08-16 23:31 UTC, x9136 commented
> Would you be able to show me what the icon looks like on your end? 

![Screenshot 2024-08-17 at 02 31 06](https://github.com/user-attachments/assets/585e63f6-d7e0-438f-87e7-011ca6e63fa5)

2024-08-16 23:46 UTC, 5h3r10k commented
My screenshots were to show you that there is no fill being applied to any of the selected paths, as is visible on the right panel. Illustrator has an option to have the stroke lie on one side of the path (not 50/50 along the path), which was used in these designs. This way, the path is actually on the edge of the shape, which makes it easy to size exactly to 160px width.

In the first screenshot, I have selected the outline guide, not the paths. Here is a better picture.

<img width="488" alt="Screenshot 2024-08-16 at 19 45 56" src="https://github.com/user-attachments/assets/27b22aae-31d4-4c0e-8a9d-156f07a4b75b">


I am unsure if the SVG is converted to a fill in other applications. I was asking if it was showing as a fill when viewed by you in your application, not from my screenshot.

2024-08-17 00:03 UTC, x9136 commented
In short, the screenshot was supposed to show the following:
1. The lines where the path goes in the middle are made with the stroke.
2. The lines where there is no path in the middle are made with the fill.

2024-08-17 01:04 UTC, 5h3r10k commented
So I am still waiting on my answer, does the svg show a fill when I do it this way? So I know to stick to middle stroke in future? Because when I test the APK the icon looks fine. Not opposing what you said, just trying to find a solution. Is the definition of a stroke for lawnicons where the path cannot be on the outside? If so, this should be highlighted in the guidelines.