Pixel Wallpapers app icon added.
LawnchairLauncher/lawnicons pull request #224
Opened 2021-12-29 14:26 UTC by LimeWools

Here's the link to the app: https://github.com/wacko1805/Pixel-Wallpaper-app

2022-01-14 16:01 UTC, patrykmichalik requested changes
Iʼd suggest making the app logo in the icon slightly larger: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7871631/suggestions.zip).

2022-01-14 16:13 UTC, LimeWools commented
> Iʼd suggest making the app logo in the icon slightly larger: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7871631/suggestions.zip).

I updated the SVG and XML files.

2022-01-15 11:34 UTC, patrykmichalik approved these changes

2022-01-15 11:34 UTC, merged

2022-01-15 11:34 UTC, patrykmichalik commented
Thanks, @LimeWools!