+6 icons
LawnchairLauncher/lawnicons pull request #2298
Opened 2024-09-04 11:13 UTC by McIntoshEuan

# Description
Added a few icons for common Japanese apps, hope to keep adding more in the future.
## Icons addition information
### Added
ICOCA ( jp.co.westjr.android.icocaapp/crc64fa0dbc8111ab4fb7.MainActivity )
JOYFIT ( jp.joyfit.joyfitappandroid/jp.joyfit.joyfitappandroid.MainActivity )
Mynaportal ( jp.go.cas.mpa/jp.go.cas.mpa.presentation.view.eventcontrol.EventControlActivity )
くら寿司 ( jp.co.kura_corpo/jp.co.kura_corpo.SplashActivity_ ) 
モンベル ( jp.montbell.montbellofficialapp/jp.montbell.montbellofficialapp.SplashActivity )
ヤマレコ ( com.yamareco.memo/com.yamareco.memo.ui )

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.+

2024-09-04 11:16 UTC, McIntoshEuan commented
Build debug APK / check-style (pull_request) wasn't successful. Looking into this.

2024-09-05 07:43 UTC, x9136 requested changes
Let's fix the canvas size for all icons first.

2024-09-07 16:01 UTC, McIntoshEuan commented
Fixed all canvases to 192x192. Also adjusted the naming of some of the apps in the appfilter.xml. (Had the Japanese and English backwards)

2024-09-08 15:40 UTC, x9136 requested changes

2024-09-08 15:40 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{jp.montbell.montbellofficialapp/jp.montbell.montbellofficialapp.SplashActivity}" drawable="montbell" name="モンベル公式アプリ ~~ mont-bell" />
> 公式アプリ

This is an optional part. It is better to leave only the application name.

2024-09-08 15:40 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{[jp.co.westjr.android.icocaapp/crc64fa0dbc8111ab4fb7.MainActivity}" drawable="icoca" name="モバイルICOCA ~~ ICOCA" />
> モバイル

This is an optional part. It is better to leave only the application name.

2024-09-08 15:40 UTC, x9136 commented on svgs/icoca.svg
![Screenshot 2024-09-08 at 18 05 52](https://github.com/user-attachments/assets/8a4a3fe6-435d-46ad-adac-9ceb1b7ef334)
The eyes are too close to the beak. The nostrils are too close to the borders of the beak. Icons on the phone screen are 3-4 times smaller, so everything will stick together in the highlighted area.

2024-09-08 15:40 UTC, x9136 commented on svgs/joyfit.svg
1. The left area of the icon is empty, so you should move it slightly to the left so that it does not look shifted to the right.

2. ![Screenshot 2024-09-08 at 18 14 06](https://github.com/user-attachments/assets/f39a5baa-4985-41a1-a21f-aa57b89d40ef)

2024-09-08 15:40 UTC, x9136 commented on svgs/kurasushi.svg
![Screenshot 2024-09-08 at 18 19 04](https://github.com/user-attachments/assets/d6bb3bab-b8c2-40ca-810d-f897f2aafc1e)
The density between the parts of the icon is too high. It's worth simplifying.

2024-09-08 15:40 UTC, x9136 commented on svgs/mynaportal.svg
1. The icon is shifted up.
2. The ears should be slightly moved away from each other.
3. The icon will stand out from the rest due to the choice of stroke width. Wider strokes will help to avoid this, but the icon will be more difficult to make.

2024-09-08 15:40 UTC, x9136 commented on svgs/yamareco.svg
![Screenshot 2024-09-08 at 18 39 52](https://github.com/user-attachments/assets/e464efe6-5beb-42db-bf23-218bdc0a6200)
1. The icon size is too small.
2. It is better to connect the mountains.

2024-09-23 12:52 UTC, closed without merging