+ 2 icons
LawnchairLauncher/lawnicons pull request #2299
Opened 2024-09-04 23:34 UTC by McIntoshEuan

# Description
Added a couple icons for the new Pixel 9 series applications.

![Screenshot 2024-09-05 083249](https://github.com/user-attachments/assets/4965ff86-70f5-4ff8-a04d-68bccd502cd5)

## Icons addition information
### Added
Pixel Screenshots (com.google.android.apps.pixel.agent/com.google.android.apps.pixel.agent.app.ui.browser.BrowserActivity)
Pixel Studio (com.google.android.apps.pixel.creativeassistant/com.google.android.apps.pixel.merlin.tiktok.app.BlockAppActivity)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.+

2024-09-05 07:43 UTC, x9136 requested changes
Let's fix the drawing size for all icons first.

2024-09-07 15:38 UTC, McIntoshEuan commented
Fixed canvas sizes. Apologies for the mistake there, still quite new to Figma.

2024-09-08 15:48 UTC, x9136 requested changes

2024-09-08 15:48 UTC, x9136 commented on svgs/pixelscreenshots.svg
It is worth moving the icon slightly to the right to compensate for the emptiness on the right.

2024-09-08 15:48 UTC, x9136 commented on svgs/pixelstudio.svg
1. The icon size should be slightly larger.
2. If desired, it is better to make smooth lines from a minimum number of points, rather than broken lines from hundreds of points. This improves the quality of the icon.

2024-09-08 15:48 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.google.android.apps.pixel.agent/com.google.android.apps.pixel.agent.app.ui.browser.BrowserActivity}" drawable="pixelscreenshots" name="Pixel Screenshots" />
drawable="pixelscreenshots" → drawable="pixel_screenshots" 
pixelscreenshots.svg → pixel_screenshots.svg

2024-09-08 15:48 UTC, x9136 commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.google.android.apps.pixel.creativeassistant/com.google.android.apps.pixel.merlin.tiktok.app.BlockAppActivity}" drawable="pixelstudio" name="Pixel Studio" />
drawable="pixelstudio" → drawable="pixel_studio"
pixelstudio.svg → pixel_studio.svg

2024-09-23 07:36 UTC, McIntoshEuan commented
Changes made as requested. Thank you!

2024-09-23 07:51 UTC, x9136 commented
It remains to resolve conflicts between branches.

2024-09-23 08:35 UTC, McIntoshEuan commented
> It remains to resolve conflicts between branches.

Redid the appfilter.xml from prod and commited it. Did that sort it?

2024-09-23 08:38 UTC, x9136 commented
> Did that sort it?

![Screenshot 2024-09-23 at 11 38 27](https://github.com/user-attachments/assets/441ff43b-432c-4d5a-bc4d-5475ba22dd5c)
You can see for yourself.

2024-09-23 13:02 UTC, McIntoshEuan commented
Closing, will redo PR.

2024-09-23 13:02 UTC, closed without merging