+7 icons, Updated 3, Linked 1
LawnchairLauncher/lawnicons pull request #2340
Opened 2024-09-16 06:22 UTC by Ahmed-Khalifa

### Added
150X Duplicate Remover Pro (`com.nutuvamapp.onefivexduplicatexapp/com.nutuvamapp.onefivexduplicatexapp.activity.SplashActivity`)
AlDawaa Pharmacies (`com.kr.aldawaa/com.kr.aldawaa.view.SplashActivity`)
مطاعم الرومانسية (`com.tech_world.romansia/com.tech_world.romansia.ui.splash.SplashActivity`)
AlinmaPay E Wallet (`com.alinma.pay.consumer/com.alinma.pay.consumer.MainActivity`)
barq (`sa.com.barraq/com.globalfinancingsolutions.ui.splash.SplashActivity`)
BCare (`com.app.bcare/com.nqdi.app.MainActivity`)
Core | Crypto Wallet and NFTs (`com.avaxwallet/com.avaxwallet.MainActivity`)

### Linked
ClicFlyer (`main.ClicFlyer` → `clicflyer.svg`)

### Updated
Almanea (`com.almanea.android`)
Hungerstation (`com.hungerstation.android.web`)
Mada Pay (`com.mada.madapay`)

2024-09-16 12:24 UTC, x9136 requested changes

2024-09-16 12:24 UTC, x9136 commented on svgs/alinma_pay.svg
![Screenshot 2024-09-16 at 15 01 45](https://github.com/user-attachments/assets/990e6f3a-094c-4d79-9aff-138f3e05537e)
It is better and easier to make the icon without labels.

2024-09-16 12:24 UTC, x9136 commented on svgs/bcare.svg
The icon looks shifted to the right due to the emptiness on the left.

2024-09-16 12:24 UTC, x9136 commented on svgs/core.svg
![Screenshot 2024-09-16 at 15 23 23](https://github.com/user-attachments/assets/18af6f3d-12d1-49a4-85bb-091fc38b820a)
It is better to do so in order to correct excessive density and improve the overall quality.

2024-09-16 13:17 UTC, Ahmed-Khalifa commented on app/assets/appfilter.xml
> +  <item component="ComponentInfo{com.app.bcare/com.nqdi.app.MainActivity}" drawable="bcare" name="بي كير للتأمين ~~ BCare" />
you're right, the last bit means "Insurance", it's the function of the app.

2024-09-16 14:02 UTC, Ahmed-Khalifa commented on svgs/alinma_pay.svg
I can do that, using the icon only but it'll be the same icon as alinma.svg, in my opinion there should be a difference between the two icons, so that is what I suggested an icon with text.
What's your opinion on the matter.

2024-09-16 14:20 UTC, x9136 commented on svgs/alinma_pay.svg
Then you need to somehow adapt the label or its meaning to the icon. There are many options. One of them is:
![Screenshot 2024-09-16 at 17 18 06](https://github.com/user-attachments/assets/03c3d9c9-e793-461e-86cf-cfce9c9fe750)

2024-09-17 06:03 UTC, Ahmed-Khalifa commented on svgs/core.svg
What should I do for this one?
should I reduce the stroke of the eyes?

2024-09-17 06:28 UTC, Ahmed-Khalifa commented on svgs/alinma_pay.svg
Here is a suggestion.
![alinmapay](https://github.com/user-attachments/assets/0e9ad257-12c4-4669-aed7-462f4ba0ac5c)

2024-09-17 09:21 UTC, Ahmed-Khalifa commented on svgs/alinma_pay.svg
I chose a 10px stroke width.

2024-09-17 19:50 UTC, x9136 commented on svgs/bcare.svg
You moved the icon to the left too much.

2024-09-17 19:55 UTC, x9136 commented on svgs/core.svg
> What should I do for this one?

I suggest you compare our options and figure out for yourself what was done differently and why.

2024-09-17 22:29 UTC, Ahmed-Khalifa reviewed
Kindly check again.

2024-09-18 06:43 UTC, merged