Link Aliucord to Discord
LawnchairLauncher/lawnicons pull request #339
Opened 2022-02-05 02:48 UTC by Randomblock1

Fixes #334 
Just links Aliucord to the Discord icon.
Note: Both entries are named Discord so they won't appear as duplicates in the app. I don't know if this is the correct way to do it, but it's the way I did it.

2022-02-07 07:27 UTC, patrykmichalik requested changes
I’d suggest changing the value of the `name` attribute to `"Aliucord"`. This is so that the right icon is shown after you type “Aliucord” into the search bar. I’ll most likely add some code that filters out duplicate icons from the home screen based on the value of the `drawable` attribute.

2022-02-07 07:27 UTC, patrykmichalik commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/discord" package="com.aliucord" name="Discord" />
```suggestion
    <icon drawable="@drawable/discord" package="com.aliucord" name="Aliucord" />
```

2022-02-07 22:30 UTC, Randomblock1 commented
OK, fixed it.

2022-02-08 16:44 UTC, merged

2022-02-08 16:44 UTC, patrykmichalik commented
Thanks, @Randomblock1!