Remove Duplicates (Ungoogled Chromium & Telegram X)
LawnchairLauncher/lawnicons pull request #356
Opened 2022-02-06 10:26 UTC by IAmRuMaks

2022-02-10 21:25 UTC, patrykmichalik requested changes
Please correct me if I’m wrong, but I believe the name ungoogled-chromium is written in lowercase letters and hyphenated. An example: https://en.wikipedia.org/wiki/Ungoogled-chromium.

2022-02-10 21:29 UTC, patrykmichalik requested changes
It looks like I didn’t include an interactive change request in my previous review. Sorry! Here it is.

2022-02-10 21:29 UTC, patrykmichalik commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/google_chrome" package="org.ungoogled.chromium.stable" name="Ungoogled Chromium" />
```suggestion
    <icon drawable="@drawable/google_chrome" package="org.ungoogled.chromium.stable" name="ungoogled-chromium" />
```

2022-02-11 06:19 UTC, IAmRuMaks commented
No, it's called "Ungoogled Chromium":
![Screenshotl](https://user-images.githubusercontent.com/62820070/153545720-4d33ec3a-a8cc-4f48-b646-64b6c80dfcef.png)

2022-02-11 15:12 UTC, merged