Update Retro Music
LawnchairLauncher/lawnicons pull request #560
Opened 2022-06-13 22:27 UTC by gr-e

Update Retro Music icon

![preview](https://user-images.githubusercontent.com/16453792/173457625-1d585ae9-045a-4785-b08e-923c7dbd7cfb.png)

2022-06-13 22:46 UTC, Chefski approved these changes

2022-07-04 17:28 UTC, Bnyro approved these changes

2022-07-14 15:16 UTC, patrykmichalik requested changes
Thanks for your interest in contributing! Iʼd suggest these minor geometric tweaks: [`retro_music.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9113010/retro_music.zip).

2022-07-14 16:37 UTC, gr-e commented
> Thanks for your interest in contributing! Iʼd suggest these minor geometric tweaks: [`retro_music.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9113010/retro_music.zip).

Looks good. Updated

2022-07-14 18:56 UTC, patrykmichalik approved these changes

2022-07-14 18:56 UTC, merged

2022-07-14 18:56 UTC, patrykmichalik commented
Thanks, @gr-e!