Samsung internet
LawnchairLauncher/lawnicons pull request #60
Opened 2021-11-12 10:08 UTC by arun54321

2021-11-12 10:26 UTC, paphonb approved these changes

2021-11-12 22:04 UTC, meistr91 commented
Can you link please samsung interneta beta too

2021-11-13 15:02 UTC, rodrigoswz commented
> Can you link please samsung interneta beta too

Samsung Browser Beta should have its own icon since that it has a badge just like Chrome and Firefox

2021-11-14 09:35 UTC, meistr91 commented
> > Can you link please samsung interneta beta too
> 
> Samsung Browser Beta should have its own icon since that it has a badge just like Chrome and Firefox

I know it ahould have. But i think it will never happen, so im just asking to link together 😂

2021-11-14 20:56 UTC, patrykmichalik requested changes

2021-11-14 20:56 UTC, patrykmichalik commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/sbrowser" package="com.sec.android.app.sbrowser" name="Browser" />
The app is listed on Google Play under the name Samsung Internet Browser, so I’d suggest updating the value of the `name` attribute accordingly.

```suggestion
    <icon drawable="@drawable/sbrowser" package="com.sec.android.app.sbrowser" name="Samsung Internet Browser" />
```

2021-11-15 13:15 UTC, patrykmichalik approved these changes

2021-11-15 13:18 UTC, merged

2021-11-15 13:19 UTC, patrykmichalik commented
Cheers, @arun54321!