Add Catogram, MX Player/Pro, Snapseed, Solid Explorer, DriveDroid
LawnchairLauncher/lawnicons pull request #62
Opened 2021-11-12 14:37 UTC by ninopiamonte

You're welcome and no worries @patrykmichalik. Btw, I still don't know how to properly align the drawable icons I just convert them online so if you see any errors, please correct/optimize them and I'll just happily apply/commit changes. Thanks!

#42 #14 #20

2021-11-12 16:07 UTC, ninopiamonte commented
@patrykmichalik should I update? I've attached the Solid Explorer outline version if you want to modify it. current & suggestion:

<img width="439" alt="Screen Shot 2021-11-13 at 12 00 54 AM" src="https://user-images.githubusercontent.com/88925766/141496915-d495e578-49af-45b6-9a4c-973e6e4cae94.png">

[solid_explorer_outline.zip](https://github.com/LawnchairLauncher/lawnicons/files/7528877/solid_explorer_outline.zip)

2021-11-13 16:14 UTC, patrykmichalik commented
I feel like the existing Solid Explorer icon better resembles the official design, so I’d suggest keeping this icon as is. On the other hand, I’d say XDA icon on the right is an improvement over the existing one. It may deviate from the official app icon, but it should be more legible.

2021-11-13 16:14 UTC, patrykmichalik approved these changes

2021-11-13 16:56 UTC, patrykmichalik commented
I would suggest nudging the XDA icon down so that it looks optically centered: [xda-icon-suggestion.zip](https://github.com/LawnchairLauncher/lawnicons/files/7532420/xda-icon-suggestion.zip). Because this PR deletes lines from `xda.svg`, I’m not able to use GitHub’s suggestion feature here.

2021-11-13 16:59 UTC, ninopiamonte commented
> I would suggest nudging the XDA icon down so that it looks optically centered: [`xda-icon-suggestion.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7532420/xda-icon-suggestion.zip). Because this PR deletes lines from `xda.svg`, I’m not able to use GitHub’s suggestion feature here.

Got it, thanks!

2021-11-13 17:35 UTC, ninopiamonte commented
Should close #73

2021-11-13 18:10 UTC, ninopiamonte commented
I forgot to optically align the Stellio icon. Will modify it tomorrow lol

2021-11-14 03:33 UTC, paphonb commented
For truecaller please link to `@drawable/dialer` instead of creating a new icon. Otherwise looks fine.

2021-11-14 08:58 UTC, patrykmichalik requested changes
Looking good! I suggest updating `grayscale_icon_map.xml` as per @paphonb’s suggestion and making the Sweech icon a bit smaller. The icon is more or less a square, and squares are optically larger than, for example, circles.

2021-11-14 08:58 UTC, patrykmichalik commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/truecaller" package="com.truecaller" name="Truecaller" />
```suggestion
    <icon drawable="@drawable/dialer" package="com.truecaller" name="Dialer" />
```

2021-11-14 08:58 UTC, patrykmichalik commented on app/src/main/res/drawable/sweech.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:fillColor="#FF000000"
      android:pathData="M3.072,5.4498l0,3.5712l5.9535,5.9535l4.3362,4.3362l-5.0571,-3.6144l-5.2326,5.2317l0,0.072l15.4071,-0.0009l2.4489,-2.4489l0,-3.5712l-5.9535,-5.9535l-4.3362,-4.3362l5.0571,3.6144l5.2326,-5.2317l0,-0.072l-15.4071,0.0009z"/>
</vector>
```

2021-11-14 08:58 UTC, patrykmichalik commented on svgs/sweech.svg
> +</svg>
```suggestion
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   id="Layer_1"
   data-name="Layer 1"
   viewBox="0 0 24 24"
   version="1.1"
   sodipodi:docname="sweech.svg"
   inkscape:version="1.1.1 (3bf5ae0d25, 2021-09-20)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs7" />
  <sodipodi:namedview
     id="namedview5"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     showgrid="false"
     inkscape:zoom="32.375"
     inkscape:cx="11.984556"
     inkscape:cy="12"
     inkscape:window-width="2560"
     inkscape:window-height="1015"
     inkscape:window-x="0"
     inkscape:window-y="32"
     inkscape:window-maximized="1"
     inkscape:current-layer="Layer_1" />
  <polygon
     points="2.08,4.722 2.08,8.69 8.695,15.305 13.513,20.123 7.894,16.107 2.08,21.92 2.08,22 19.199,21.999 21.92,19.278 21.92,15.31 15.305,8.695 10.487,3.877 16.106,7.893 21.92,2.08 21.92,2 4.801,2.001 "
     id="polygon2"
     transform="matrix(0.9,0,0,0.9,1.2,1.2)" />
</svg>
```

2021-11-14 09:54 UTC, patrykmichalik approved these changes

2021-11-14 09:56 UTC, merged

2021-11-14 09:56 UTC, patrykmichalik commented
Thanks, @ninopiamonte!