Update contacts icon
LawnchairLauncher/lawnicons pull request #628
Opened 2022-08-08 15:35 UTC by Chefski

Contacts icon was not meeting icon guidelines
#609 
**Before**
![image](https://user-images.githubusercontent.com/100310118/183455923-6c496f3b-5656-4f6a-8c8e-30366921e0d2.png)
**After**
![image](https://user-images.githubusercontent.com/100310118/183456514-ef43e00f-4d36-4f7c-ae94-8dcbafbc731a.png)

2022-08-14 15:50 UTC, jakito1 approved these changes

2022-08-20 08:41 UTC, SuperDragonXD requested changes
Thanks for the PR! Please rename `ic_contacts.xml` to `contacts.xml` to follow Lawnicons's naming convention.

2022-08-20 13:37 UTC, SuperDragonXD approved these changes

2022-08-20 13:37 UTC, merged

2022-08-20 13:37 UTC, SuperDragonXD commented
Thanks!