Add StreetComplete icon
LawnchairLauncher/lawnicons pull request #662
Opened 2022-09-15 00:30 UTC by ASTRELION

## Description

Added icon for [StreetComplete](https://github.com/streetcomplete/StreetComplete).

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* StreetComplete (`de.westnordost.streetcomplete`)

2022-09-15 10:22 UTC, Chefski requested changes
Icon looks good. It just needs to be sized up a bit to fit the content area as recommended in the guidelines (160px x 160px)

![image](https://user-images.githubusercontent.com/100310118/190379782-900d6862-47d0-4404-98ce-d5c7d3d7e63f.png)

2022-09-15 21:19 UTC, Chefski commented
The icon wasn't quite at its 160px x 160px border so I just made I minor tweak here that you could just swap out the file with: [streetcomplete.zip](https://github.com/LawnchairLauncher/lawnicons/files/9579123/streetcomplete.zip). Mind also updating the drawable file (`streetcomplete.xml`)? Other than that great job!

2022-09-16 09:17 UTC, Chefski approved these changes

2022-09-18 08:26 UTC, Goooler approved these changes

2022-09-18 08:26 UTC, merged