Add icon for Mastodon
LawnchairLauncher/lawnicons pull request #667
Opened 2022-09-16 06:53 UTC by ASTRELION

## Description

Added icon for [Mastodon](https://github.com/mastodon/mastodon-android).

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* Mastodon (`org.joinmastodon.android`)

2022-09-17 18:11 UTC, Chefski requested changes
Heya! Nice work on the icon unfortunately there seem to be 3 triangles which are beyond the view zone but are within the code. Mind removing them?

![image](https://user-images.githubusercontent.com/100310118/190870739-5f26ab8f-f4d5-4483-91d8-2c3ecd4bafe1.png)

2022-09-17 18:29 UTC, ASTRELION commented
Something small always seems to slip by, should be fixed :)

2022-09-17 19:09 UTC, Chefski approved these changes

2022-09-17 19:16 UTC, Chefski commented
> Something small always seems to slip by

YEAH! Its annoying when everything seems to be fine and then just a small thing jumps in

Anyways icon looks good now :)

2022-09-18 08:23 UTC, Goooler approved these changes

2022-09-18 08:23 UTC, merged