Adobe and YT Kids
LawnchairLauncher/lawnicons pull request #685
Opened 2022-09-22 19:13 UTC by naveenccmsd

## Description

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* Adobe (`com.adobe.reader`)
* YT Kids (`com.google.android.apps.youtube.kids`)

2022-09-22 20:16 UTC, Chefski requested changes
Hiya! Thanks for contributing. I've got some small tweaks to request:

**`youtube_kids.svg`**
- The icon is bigger than the 160x160px content area. Please make it slightly smaller.
- The icon has 2 shapes which are unnecessary and can be deleted (`path8754` and `path8758`can be deleted).
<img width="236"  src="https://user-images.githubusercontent.com/100310118/191840783-bfabae4a-fb74-463a-bef9-2696230ac2ad.png">

`adobe_logo.svg`
- The icon is smaller than the 160x160px content area
- I'd also just like to ask to make the width of the thick line 12px and the width of the thin line no smaller than 6px

2022-09-23 10:44 UTC, naveenccmsd commented
`youtube_kids.svg`
- The icon size reduced to fit into content area. 
- removed unnecessary paths

2022-09-23 14:59 UTC, ZhmieXD commented
Hi! You might want to link your radio apps to `@drawable/fm_radio` instead, I have added them and the PR for it (#611) is already merged ^^

2022-09-23 20:29 UTC, Chefski approved these changes

2022-09-24 02:25 UTC, merged