Add Box, Medium, OLX Polska, Overdrop, Overdrop Pro
LawnchairLauncher/lawnicons pull request #696
Opened 2022-09-25 06:06 UTC by KZacharski

## Description

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* Box (`com.box.android`)
* Medium (`com.medium.reader`)
* OLX Polska (`pl.tablica`)
* Overdrop (`widget.dd.com.overdrop.free`)

### Icons linked
* Overdrop Pro (linked `widget.dd.com.overdrop.pro` to `@drawable/overdrop`)

2022-09-25 20:08 UTC, Chefski requested changes
Hiya! Thanks for contributing. Could you just fix the OLX icon by change the width of the Lins to be 12px. For future or this fix, I recommend just using stroke with a width of 12px as it will avoid small issues like this. Cheers

2022-09-25 20:21 UTC, KZacharski commented
It was originally a 12px stroke but then I converted it to outlines, scaled it and forgot about it, thanks for reminding me

2022-09-25 20:28 UTC, Chefski approved these changes

2022-09-25 20:29 UTC, Chefski commented
> It was originally a 12px stroke but then I converted it to outlines, scaled it and forgot about it, thanks for reminding me

No problem. Looks good now!
@Goooler

2022-09-26 01:35 UTC, Goooler commented
@KZacharski Can you rebase? Seems I can't push to your branch.

2022-09-26 07:53 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/olx" package="pl.tablica" name="OLX Polska" />
e49dfc8ed59934f6ad4aea21f37d09e1522c87bd

2022-09-26 07:53 UTC, Goooler commented
https://github.com/LawnchairLauncher/lawnicons/actions/runs/3125960088/jobs/5070922244

CC @SuperDragonXD 

```
Traceback (most recent call last):
  File "/home/runner/work/lawnicons/lawnicons/send_notifications.py", line 55, in <module>
    commits = list(repository.iter_commits(commits_range))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/git/objects/commit.py", line 407, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list 02ebd9423634b73514d81cf64f29e24995bf63cf...b80d2c94[20](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3125960088/jobs/5070922244#step:6:21)9f3134a69177ee14036702b6ed9f4a --
  stderr: 'fatal: Invalid symmetric difference expression 02ebd94[23](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3125960088/jobs/5070922244#step:6:24)634b73514d81cf64f29e[24](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3125960088/jobs/5070922244#step:6:25)995bf63cf...b80d2c94209f3134a69177ee14036702b6ed9f4a
'
Error: Process completed with exit code 1.
```

2022-09-26 07:55 UTC, merged