Add icons for SchildiChat, BootBoi & NC-Photos
LawnchairLauncher/lawnicons pull request #769
Opened 2022-10-26 21:59 UTC by fischer-felix

## Description

Adds icons for:
- https://github.com/BootBoi/android-app
- https://github.com/SchildiChat/SchildiChat-android
- https://gitlab.com/nkming2/nc-photos

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information
### Icons added
* SchildiChat (`de.spiritcroc.riotx`)
* BootBoi (`com.elektropepi.bootboi`)
* Photos (for Nextcloud) (`com.nkming.nc_photos.gitlab`)

2022-10-26 23:25 UTC, Chefski requested changes
Hiya! Thanks for contributing! I've got some changed to request:

`bootboi.svg` is smaller than the 160x160px content area and has a hidden square which isn't being used in the icon. Could you size up the icon and remove the hidden square (just to keep the SVG minimal)?
<img width="613" alt="image" src="https://user-images.githubusercontent.com/100310118/198156974-b09c327d-eeba-44ff-86c5-c4e94ac042c7.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/100310118/198157010-36ac073b-5acd-4194-8301-26000330d0de.png">


<br>
<br>

`schildichat.svg` has strokes of 11.3 and opacity isn't at 100% for all lines. Could you change the stroke to 12px and ensure each line has 100% opacity?
<img width="582" alt="image" src="https://user-images.githubusercontent.com/100310118/198156357-2f2d343f-a2bc-4b0b-b9ad-3ca761e5d448.png">

2022-10-26 23:25 UTC, Chefski commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/nextcloud_notes" package="it.niedermann.owncloud.notes" name="Nextcloud Notes" />
This line is already added in line 604 / 606. Could you remove it?

2022-10-27 11:07 UTC, fischer-felix commented
Thanks for the heads-up, had forgotten to remove my reference from the bootboi icon.
Both things should be fixed now!

2022-10-27 19:10 UTC, Chefski approved these changes
Thanks for making the changes

2022-10-27 19:10 UTC, merged