add bandsintown
LawnchairLauncher/lawnicons pull request #790
Opened 2022-11-01 09:10 UTC by peterge1998

## Description

add bandsintown

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)

## Icons addition information
### Icons added
com.bandsintown

2022-11-01 09:10 UTC, peterge1998 commented
#766

2022-11-01 10:45 UTC, peterge1998 commented
K9-Mails Icon is fine? It's the second Icon I designed...
![image](https://user-images.githubusercontent.com/47355238/199216350-77c9e151-0de1-48e8-87fe-1c0be2e59d78.png)

2022-11-01 12:11 UTC, Chefski requested changes
Hey! Could you add the SVGs for the icons to the SVG folder?

2022-11-01 12:15 UTC, peterge1998 commented
> Hey! Could you add the SVGs for the icons to the SVG folder?

Done :)

2022-11-03 20:36 UTC, peterge1998 commented
This should be way better. Feel free to criticize :)
Thank you very much for your very helpful tips, here & in the issue!

2022-11-03 21:15 UTC, Chefski requested changes
One last tweak needed. The rectangle at the bottom has points that are no aligned horiaztontally. Could you align them and then it should be fine :)

![image](https://user-images.githubusercontent.com/100310118/199834015-1e163d93-2eec-45d6-8cf2-035f606bb20d.png)

2022-11-03 21:26 UTC, peterge1998 commented
Oh, that's because I started that shape in the top left corner and just closed it when i set the top right point. Can I do this with Inkscape too?

2022-11-03 22:08 UTC, Chefski commented
Use a guideline to align it on the same X axis

2022-11-04 07:33 UTC, peterge1998 commented
Okay, I still need to generate the XML with android studio, but I was able to do it with the Node tool :)

2022-11-05 19:57 UTC, peterge1998 commented
So, now its ready to merge @Chefski :)

2022-11-05 20:35 UTC, Chefski commented on app/src/main/res/xml/grayscale_icon_map.xml
> -    <icon drawable="@drawable/calendar" package="org.lineageos.etar" name="Calendar" />
Should this line be added back but linked to the Etar icon or is it an invalid package name?

2022-11-05 20:40 UTC, Chefski requested changes
New icons look fine. Could you just change `etar.svg` to have a content area size of 144x144px as its a square. After that I'll merge it and you can open new PRs when you add icons.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/100310118/200140294-7d4d296c-62c1-475f-b0b6-77f95024374d.png">

2022-11-05 21:01 UTC, peterge1998 commented
> New icons look fine. Could you just change `etar.svg` to have a content area size of 144x144px as its a square. After that I'll merge it and you can open new PRs when you add icons.
> 
> <img alt="image" width="744" src="https://user-images.githubusercontent.com/100310118/200140294-7d4d296c-62c1-475f-b0b6-77f95024374d.png">

Okay, if i did the math correctly it should now be fine!

2022-11-05 21:04 UTC, Chefski approved these changes
Thanks! :D

2022-11-05 21:35 UTC, daywalk3r666 commented
https://github.com/LawnchairLauncher/lawnchair/commit/aa251677483fde500a0f34fd31e761bdb44566c7

2022-11-05 22:05 UTC, Chefski commented
@daywalk3r666 thanks for bringing that up.

2022-11-05 22:08 UTC, merged