add 4 icons
LawnchairLauncher/lawnicons pull request #805
Opened 2022-11-06 17:12 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
```
    <icon drawable="@drawable/group_alarm" package="com.groupalarm.app" name="GroupAlarm" />
    <icon drawable="@drawable/home_assistant" package="io.homeassistant.companion.android.minimal" name="Home Assistant" />
    <icon drawable="@drawable/home_assistant" package="io.homeassistant.companion.android" name="Home Assistant" />
    <icon drawable="@drawable/teamnspeak" package="com.teamspeak.ts3client" name="TeamSpeak" />
    <icon drawable="@drawable/valetudo" package="cloud.valetudo.companion" name="Valetudo Companion" />
```

2022-11-06 17:55 UTC, daywalk3r666 commented
You made mistake. remane your xml to valetudo

2022-11-06 18:16 UTC, daywalk3r666 commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/teamnspeak" package="com.teamspeak.ts3client" name="TeamSpeak" />
You have a typo here

2022-11-07 16:01 UTC, Chefski requested changes
Hey! Got some small tweaks for 3 icons and 1 fix in the `grayscale_icon_map.xml`

Could you fix point on the G in `group_alarm.svg` to align with the other point from the other shape so that it doesn't cut in.
![image](https://user-images.githubusercontent.com/100310118/200354772-fb4ba7bd-8ace-4dee-8e50-5377336cc28b.png)

<br>

Could you make `rock_am_ring.svg` have a stroke of 12px or at least the circle and lines outside the circle?

<br>

Could you fix this alignments in `valetudo.svg` to be more smooth? Its a similar problem as in `group_alarm.svg`
![image](https://user-images.githubusercontent.com/100310118/200354604-4bc23e7d-c7de-426a-80d5-7fced9bf9ba2.png)

<br>

Also please change the line `<icon drawable="@drawable/rock_am_ring" package="com.mlk.rockamring" name="RAR & RIP" />` to `<icon drawable="@drawable/rock_am_ring" package="com.mlk.rockamring" name="RAR &amp; RIP" />`. 

I recommend grouping all the shapes and making the height, width or both 148px (Only applies when the stroke is centred for all shapes outside and if its not a square). It'll just make sure the shapes are at the borders of the content area size.

2022-11-07 18:41 UTC, peterge1998 commented
Okay, I did the changes you asked for @Chefski.
However, I can't create the new XML files, because android studio on my laptop does not show new > vector asset...
I don't know why, I am using the flatpak version on my desktop too...

2022-11-07 18:54 UTC, daywalk3r666 commented
https://inloop.github.io/svg2android/
you can use this instead of android studio

2022-11-07 20:05 UTC, Chefski commented
Also why didn't you set the XML name for `freenet.svg` to `freenet_mobilfunk.xml`?

2022-11-08 20:24 UTC, Chefski approved these changes
Thank you

2022-11-08 20:25 UTC, merged

2022-11-09 06:42 UTC, peterge1998 commented
> https://inloop.github.io/svg2android/ you can use this instead of android studio

I used it for the RAR icon, which looks scrambled in the latest debug build. I will fix it in my next PR (which shouldnt take that long :D)