Add 12 icons. My last pr for a completely redesigned app grid! (for now)
LawnchairLauncher/lawnicons pull request #823
Opened 2022-11-11 17:27 UTC by peterge1998

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark:  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
com.wizards.mtga
com.wizards.winter_orb
com.blizzard.wtcg.hearthstone
com.humble.SlayTheSpire
com.Afterburn.Railbound
de.human_resources
com.comdirect.phototan
com.github.premnirmal.tickerwidget
com.wireguard.android
com.commit451.gitlab
be.martinelli.miniflutt
com.ucdevs.jcross

Again some icons are scrambled like last time. Android studio cant do it sometimes with circles, exporing as inkscape svg...
These are fucked up:
phototan
human resources
railbound
stock ticker

2022-11-11 17:52 UTC, daywalk3r666 requested changes

2022-11-11 17:52 UTC, daywalk3r666 commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/stock_widget" package="com.github.premnirmal.tickerwidget" name="Stock Widget" />
<icon drawable="@drawable/stock_ticker" package="com.github.premnirmal.tickerwidget" name="Stock Widget" />

2022-11-12 04:28 UTC, peterge1998 commented
In my opinion the design of magic & companion turned out fcking awesome.
I hope hearthstone & wireguard are fine for you, i just wanted to keep the details of the original logos...

2022-11-12 04:30 UTC, peterge1998 commented
and this wont be my last pr, mydealz & covpass are still waiting ;)

2022-11-13 14:43 UTC, Chefski requested changes
Could you make miniflutt.svg have a stroke of 12px?

Hearthstone has sharp corners which don't necassirily match lawnicons style.

Strokes need to be rounded to 8px or 12px:
- wireguard.svg
- slay_the_spire.svg
- railbound.svg (can be 6px)
- nonogramm_katana.svg (hwoever it would also need a redesign as some gaps are too small)
- magic_companion.svg (also needs to be recentered)
- labcoat.svg

As for the icons that have been rendered wrong, I'd just ask to remove them or try to get them fixed

2022-11-14 08:03 UTC, peterge1998 commented
I have already updated hearthstone, wg, miniflutt and slay t s to 8px & round corners.

2022-11-14 18:40 UTC, Chefski requested changes
Don't really know how I feel about the heartstone icon. The corners are not rounded in the main shape in the middle and has lots of paths. You can either try improve on it or remove it from the PR and maybe add it in the future.

Also miniflutt has strokes that are not whole numbers. Could you fix that?

2022-11-15 02:00 UTC, peterge1998 commented
> Don't really know how I feel about the heartstone icon.

Nah, i would like to add it now. Can we agree on its current state?

> Also miniflutt has strokes that are not whole numbers. Could you fix that?

Now it should be 12

2022-11-15 02:12 UTC, peterge1998 commented
> * railbound.svg (can be 6px)

Done!

> * nonogramm_katana.svg (hwoever it would also need a redesign as some gaps are too small)

Which gaps do you mean? The squares (at 1 3 and 1 2)? 

> * magic_companion.svg (also needs to be recentered)

The C is aligned vertical to the page, which is correct in my opinion:
![image](https://user-images.githubusercontent.com/47355238/201808883-6996c95e-e5f3-4f84-abc7-e6dd9144125e.png)

> * labcoat.svg

2022-11-16 15:09 UTC, peterge1998 commented
👀

2022-11-16 20:22 UTC, Chefski requested changes
Here are the screenshots for the changes needed
![image](https://user-images.githubusercontent.com/100310118/202283575-c65317ad-06c7-4efe-9820-eba28200ecfa.png)

![image](https://user-images.githubusercontent.com/100310118/202285001-cadd0c06-0bfe-4912-b2c4-9580e7bfa04a.png)


Icons that new strokes with whole numbers:

- tipster
- lidl_plus

Icons needing resizing to 160x160:

- netto

2022-11-17 07:12 UTC, peterge1998 commented
Done :)
And I leave a small note here for my XML problem in android studio: If this occurs, go into Inkscape and convert the object not generating successful to a path (https://logosbynick.com/convert-text-to-a-path-in-inkscape/)

2022-11-17 21:32 UTC, Chefski approved these changes

2022-11-17 21:32 UTC, Chefski commented
Thanks

2022-11-17 21:32 UTC, merged