Calyxos apps
LawnchairLauncher/lawnicons pull request #824
Opened 2022-11-12 04:54 UTC by mwchiao

## Description
Adding new icons for a few CalyxOS apps and linking existing icons to some apps

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* Work Profile (`org.calyxos.bellis`)
* Firewall (`org.calyxos.datura`)
* Backup (`com.stevesoltys.seedvault`)

### Icons linked
* Calendar (linked `org.lineageos.etar` to `@drawable/calendar`)
* Weather (linked `org.secuso.privacyfriendlyweather` to `@drawable/weather`)
* Recorder (linked `org.calyxos.recorder` to `@drawable/recorder`)

2022-11-12 05:55 UTC, daywalk3r666 commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/calendar" package="org.lineageos.etar" name="Calendar" />
https://github.com/LawnchairLauncher/lawnchair/commit/aa251677483fde500a0f34fd31e761bdb44566c7

2022-11-12 09:08 UTC, Chefski requested changes
Hey! Thanks for contributing! Got small changes:

`seedvault.svg` and `datura.svg` have strokes with an opacity that is not 100% Could you fix that?
<img width="461" alt="image" src="https://user-images.githubusercontent.com/100310118/201467128-fa43ead9-d146-4f2c-bba6-d8ec6865b209.png">

Could you also remove the calendar link?

2022-11-12 17:03 UTC, mwchiao commented
Changes made. One of these days I'll get everything right on the first try xD

Since the calendar link is being removed, is the only solution to make a new icon for the Etar calendar?

2022-11-12 18:14 UTC, daywalk3r666 commented
With the next release of lawnchair launcher it will be themed

2022-11-13 14:25 UTC, Chefski approved these changes
Thanks

2022-11-13 14:25 UTC, merged