Add icon Wechat
LawnchairLauncher/lawnicons pull request #855
Opened 2022-11-26 14:47 UTC by Uni-Rider

## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons addition information

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

2022-11-26 16:09 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/wechat" package="com.tencent.mm" name="wechat" />
```suggestion
    <icon drawable="@drawable/wechat" package="com.tencent.mm" name="WeChat" />
```

2022-11-26 20:12 UTC, Chefski requested changes
Hey! The icon goes outside the 160x160 px content area size. Could you decrease the icon size so it fits right into it?

2022-11-26 20:34 UTC, Uni-Rider commented
> Hey! The icon goes outside the 160x160 px content area size. Could you decrease the icon size so it fits right into it?

The icon size has been decreased to 160 px

2022-11-26 20:35 UTC, Chefski requested changes
The outline now has a stroke of just over 11px instead of 12pox. Mind fixing it?

2022-11-26 20:54 UTC, Uni-Rider commented
> The outline now has a stroke of just over 11px instead of 12pox. Mind fixing it?

Can you please tell me how to adjust the stroke exactly to 12 px? I am a novice

2022-11-26 23:01 UTC, Chefski commented
Not sure how to tell you to be honest because you have and outside and inside line so you're currently using 7px. I'm not familiar with Inkscape either. But if you look at other icon they only have one path/line

2022-11-27 02:24 UTC, Uni-Rider commented
> Not sure how to tell you to be honest because you have and outside and inside line so you're currently using 7px. I'm not familiar with Inkscape either. But if you look at other icon they only have one path/line

I have changed the icon to single path, please check it. but the eyes seen from here are holes, if opened by IE, they are black dots, don't know why

2022-11-27 12:05 UTC, Chefski approved these changes
Thanks

2022-11-27 12:06 UTC, merged