Addes 3 icons, modified 1, corrected one mistake
LawnchairLauncher/lawnicons pull request #886
Opened 2022-12-07 13:23 UTC by Nido-nid

## Description

I added icons of more Apps, I recently started to use and wondered, that they weren't implemented already.
I also thought, that there already was a calendar icon, but I was wrong. So I added one as well, but I noticed, that the drawable was updated. So it was just the SVG missing, I guess.
And lastly i corrected a typo from my last pull request in the grayscale_icon_map.xml. I forgot an n in the package name for the SBB Mobile app, so it said ch.sbb.mobile.adroid.b2c. So the icon wasn't implemented correctly.

## Type of change
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Fixes
* SBB Mobile (`ch.sbb.mobile.adroid.b2c` -> `ch.sbb.mobile.android.b2c`)

### Icons added
* DJI Ronin (`com.dji.ronin`)
* Jitsi Meet (`org.jitsi.meet`)
* Voice (`de.ph1b.audiobook`)

### Icons updated
* /e/ OS Calendar (`foundation.e.calendar`)

2022-12-07 15:51 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/sbb_mobile" package="ch.sbb.mobile.android.b2c" name="SBB Mobile" />
Good catch! I've explicit the fix in 7405b8ddf34cdc99aee4971547c0fdc018698768.

2022-12-07 15:58 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/calendar" package="foundation.e.calendar" name="Calendar" />
Calendar icons had been handled by #750.

2022-12-07 16:01 UTC, Goooler requested changes

2022-12-07 16:01 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/calendar" package="foundation.e.calendar" name="Calendar" />
Calendar icons had been handled by #750, you should submit changes to Lawnchair like https://github.com/LawnchairLauncher/lawnchair/pull/3038.

2022-12-07 16:17 UTC, Chefski approved these changes
Hey! Icons look good. Next time try to keep the icon in strokes rather than converting to a shape. It just makes it easier to review.

As stated by @Goooler, Calendar icons are now in Lawnchair so I won't be reviewing it

2022-12-07 16:21 UTC, Goooler commented on app/src/main/res/xml/grayscale_icon_map.xml
> +    <icon drawable="@drawable/calendar" package="foundation.e.calendar" name="Calendar" />
Alright, I'm removing the calendar change now, you can send a new PR to Lawnchair.

2022-12-07 16:22 UTC, merged

2022-12-07 16:26 UTC, Nido-nid commented
> Hey! Icons look good. Next time try to keep the icon in strokes rather than converting to a shape. It just makes it easier to review.
> 
> As stated by @Goooler, Calendar icons are now in Lawnchair so I won't be reviewing it

Problem is, the rounded ends of the strokes aren't taken over. In the SVG, they're there, but on the drawable preview they are squared. Is this a mistake, and they get implemented correctly anyway?

2022-12-07 17:18 UTC, Chefski commented
> the rounded ends of the strokes aren't taken over. In the SVG, they're there, but on the drawable preview they are squared. Is this a mistake, and they get implemented correctly anyway?

You might have to show a screenshot whenever you see this again. It could be a problem when exporting as when I was reviewing these, the imported SVG was 1x1 in size so had to change to 192x192

2022-12-08 10:31 UTC, Nido-nid commented
> > the rounded ends of the strokes aren't taken over. In the SVG, they're there, but on the drawable preview they are squared. Is this a mistake, and they get implemented correctly anyway?
> 
> You might have to show a screenshot whenever you see this again. It could be a problem when exporting as when I was reviewing these, the imported SVG was 1x1 in size so had to change to 192x192

So for instance, this was my initial jitsi icon drawn with paths. Designed in Affinity Designer. Exported in SVG with 192x192 pixels.
![jitsi_path](https://user-images.githubusercontent.com/103198546/206423627-74bb1ef0-cb0b-42cf-a6d8-931162390fd9.svg)

But when converting it to a drawable, the rounded stroke-ends are squared. Could it be an issue with the program i use?
![Bildschirmfoto vom 2022-12-08 11-24-59](https://user-images.githubusercontent.com/103198546/206424042-dde1fae7-90cc-40d2-a214-c048abe163f2.png)

2022-12-08 11:57 UTC, Chefski commented
Not too sure why that happens... I suppose you can continue changing them to shapes or have two versions of the icon (one will remain in strokes and will be added to `svgs`, the other will be changed to a shape and used to create the drawable XML)